### ISSUE TITLE
Script uses first perl in path, rather than the system perl

### ISSUE THREAD

**Issue by cowens** [mobile-shell/mosh#100]
The perl script uses the shebang line of `#!/usr/bin/env perl` which causes it to use the first `perl` it finds in the path.  This is not safe, especially for people who work on `perl` (as they have multiple copies of development versions in their path).  This sort of software should be using the system version of `perl` commonly found at `/usr/bin/perl`.

**Comment by perlpunk** [comment]
I agree that it should be /usr/bin/perl on debian.
I have different perls on my machine for development, resulting in an error message because of a missing IO::Pty.
A system tool like mosh should use the system perl with which it was (hopefully) tested.
