### ISSUE TITLE
Incompatible with "bb" (libaa demo)

### ISSUE THREAD

**Issue by phmarek** [mobile-shell/mosh#1000]
When running "bb -driver stdout" (the libaa demo) via mosh, the output is garbled.
I'd expect this demo to work normally.

Setup is xterm -> mosh -> screen -> bb.

Thanks ;)

**Comment by cgull** [comment]
This works fine for me with XTerm 326 or iTerm2 3.2.1beta2 on a Mac, mosh 1.3.2, to screen and bb on Debian sid running on a local VM.  I even tried your net-impairment procedures on #999.

I'm beginning to wonder if there is something unusual/unique about your configuration-- perhaps some unusual configuration for screen?

**Comment by cgull** [comment]
Correction: I was running `bb`.  That works fine.  `bb -driver stdout` is completely broken in XTerm or iTerm2 (but it is with a bare ssh session too).

**Comment by phmarek** [comment]
Yeah, right. A plain "bb" works in xterm locally or via mosh remote -- sorry, I didn't check that "-driver stdout" is actually broken _everywhere_. My bad.
