### ISSUE TITLE
manual restart mosh server to mosh from new device 

### ISSUE THREAD

**Issue by longtth** [mobile-shell/mosh#1002]
I use mosh behind a company firewall, The firewall only allow me to using mosh to my aws server by port 60001, but after connect by a PC, when I try connect from 2nd PC, it throw the error: 
```
longnx-wsl@CPP00039344T:/mnt/c/Users/longnx$ mosh -ssh="ssh -i /mnt/c/Users/longnx/server-fpt-technojapan.pem" ubuntu@ec2-52-87-243-206.compute-1.amazonaws.com -p 60001
Failed binding to 172.31.84.137:60001
Error binding to IP 172.31.84.137: bind: Address already in use
Failed binding to 0.0.0.0:60001
Error binding to any interface: bind: Address already in use
Network exception: bind: Address already in use
Connection to ec2-52-87-243-206.compute-1.amazonaws.com closed.
/usr/bin/mosh: Did not find mosh server startup message.
```
I think this would be happened because of mosh-server still using 60001 port to listen from 1st PC. 
How could I manual restart the mosh-server to re-connect to using the 60001 port? 
Or if this error occurred because of other reason, so what is the reason and how to fix it?

**Comment by andersk** [comment]
If that’s really the only port you can use, you’ll need to stop (not restart) the old `mosh-server` process, either by sending it a termination signal (e.g. `pkill mosh-server`) or by causing its child process to exit.
