### ISSUE TITLE
Use existing mosh session as a form of "master persistent SSH connection"

### ISSUE THREAD

**Issue by monnier** [mobile-shell/mosh#1009]
Here's a typical scenario where I am mildly frustrated:

- I have my trusty mosh session to my beloved server running as always
- I need to copy a file from that beloved server
- I do `scp server:foo .` and SSH prompts for a password

I can circumvent the password, tho, e.g. by using `nc` in the mosh session to open up a temporary TCP connection on which to transfer the file, or by editing (in that mosh session) the `~/.ssh/authorized_keys` to add some local key that doesn't have a password, or ...

So the password really doesn't add much security since the mosh session already gives me access to the remote host.  But mosh doesn't let me re-use that connection conveniently to setup a new connection.

So wouldn't it be nice if we could use `mosh HOST CMD` to run CMD on HOST (just like ssh does) via an old TCP connection (so I can do `mosh server 'cd foo/bar; git diff' | patch -p1`, for example) or a `mocp`).  Or maybe just let SSH use the existing mosh connection as a kind of "persistent connection".

**Comment by andersk** [comment]
Your specific plan won’t work for a number of reasons, one of which is that Mosh does not use TCP and does not provide a reliable byte transport. You can already run `mosh server -- sh -c 'cd foo/bar; git diff'` today, but it’s likely to output only as much of the tail end of the diff as would fit on the screen, to save bandwidth. This is fundamental to the way Mosh works and won’t change any time soon.

However, SSH has an existing connection reuse mechanism, and both `mosh` (for the part of the initial login that uses `ssh`) and `scp` can take advantage of it. Look up the `ControlMaster` and `ControlPersist` options. It’s not perfect but I think you’ll find a configuration that makes you less frustrated.

**Comment by javabrett** [comment]
I think your best bet by far here is to sort-out some SSH key-management you are happy with, and use SSH for file-transfer.

**Comment by monnier** [comment]
There's a misunderstanding: I already know how to live without this feature.  I'm not asking for help.  This is just a suggestion for improvement.  I don't have the motivation to dig into the code and implement it, so I sent it here in case someone else likes the idea.  But apparently everyone else is happy using workarounds.

**Comment by javabrett** [comment]
> SSH's existing connection reuse (which I use, of course) only lasts for a limited time

Can you try setting `ssh_config` `ControlPersist` to a suitable value, or `yes` or `0` for indefinite control master persistence?

> I end up prompted for a password

You can try using an `ssh-agent` to avoid this.

**Comment by monnier** [comment]
[ Not sure why I keep answering.  ]
Regarding SSH's master-persistent thingy: think about what the "mo" in "mosh" stands for.
My suggestion is to do the opposite: make SSH use mosh as its persistent master.

**Comment by infinity0** [comment]
It's fundamentally hard to do this in the way that OP thinks it could be done. mosh works because the stream of terminal commands does *not* need to be sent with 100% integrity - if I hit a b c delete delete delete x, and x arrives first, the other packets can totally be dropped. This is why mosh can be so fast.

`scp` can't take advantage of this lack-of-strict-ordering, because it's not generally safe to skip bytes when copying files.

**Comment by monnier** [comment]
> It's fundamentally hard to do this in the way that OP thinks it could be
> done.

I already discussed the difficulty.  It's not hard.

> mosh works because the stream of terminal commands does *not* need to
> be sent with 100% integrity

Wrong: the stream of commands does have to be sent with 100% integrity
(in-order, with no loss, nor duplication).  It's only the "return
stream" (from the server back to the client) which can benefit from UDP.

> - if I hit a b c delete delete delete x, and x arrives first, the
> other packets can totally be dropped.

Not at all, because you might be currently running some ncurses
application where `a`, `b`, `DEL`, ... do not simply "insert themselves".
So they *definitely* need to be passed to the underlying tty in the
right order and without dropping anything.

It's the resulting *display* where things can be dropped (if the
resulting display after `x` is received, we don't need to know the
resulting display after `a` any longer).

> `scp` can't take advantage of this lack-of-strict-ordering, because it's not
> generally safe to skip bytes when copying files.

I'm not suggesting to do the file transfer over UDP.  Please re-read
what I wrote before jumping to conclusions.

**Comment by infinity0** [comment]
> Wrong: the stream of commands does have to be sent with 100% integrity

Apologies, your example is indeed the more likely situation and I should have said that instead. OTOH in principle with some more intelligence on the sender side, you could also skip the sends, but that would require application support in the general case so not really something we can expect mosh to do.

> I'm not suggesting to do the file transfer over UDP.  Please re-read what I wrote before jumping to conclusions.

Fair enough. Sometimes in life it's important to save time, assume things, then backtrack when you find out you're wrong. In this case re-reading your 4-line suggestion, it would basically be a polished version of `set -e; f=$(tempfile); ssh -M -S $f & pid=$!; mosh --ssh="ssh -S $f" "$@" || true; kill -INT $pid` which perhaps the maintainers here would be happy to accept and install as an "example" distributed with the program.

**Comment by monnier** [comment]
> In this case re-reading your 4-line suggestion, it would basically be
> a polished version of `set -e; f=$(tempfile); ssh -M -S $f & pid=$!;
> mosh --ssh="ssh -S $f" "$@" || true; kill -INT $pid` which perhaps the
> maintainers here would be happy to accept and install as an "example"
> distributed with the program.

I believe you're still confused: the above uses an `ssh` master server,
which uses a TCP socket and hence doesn't work in a *mobile* setting.

As I wrote already several times, I am *already* using ssh's
ControlMaster and what this feature request is about is to make `mosh`
provide a similar functionality since it would have the same advantage
over ssh's ControlMaster as a shell running inside `mosh` has over
a shell running inside `ssh` (i.e. it works even if the connection is
cut for a few days and later re-established but from a different IP).
