### ISSUE TITLE
Problems with Nano and Mac OSX Terminal

### ISSUE THREAD

**Issue by rissom** [mobile-shell/mosh#1012]
Hello, 
I use mosh to communicate to a Amazon Linux Lightsail instance. I am using the Mac Terminal app. When I delete things using the nano editor, with the backspace key, I sometimes get failures in the representation of the screen on my terminal. The cursor jumps randomly. If I use ssh directly, nano works as intended. Any ideas what the problem could be? 

Best Regards,

Thorsten

**Comment by da2x** [comment]
I've experienced the same thing when using Mosh with macOS Terminal and using nano over connections to various Linux distributions and FreeBSD.

**Comment by andersk** [comment]
What version of Mosh are you using (client and server)? This sounds similar to #539, fixed in 1.2.6.

**Comment by rissom** [comment]
Ah! That's probably it. The server (Amazon Linux) is running 1.2.4 . No idea how to tell Amazon to update their package. Will install it manually. Sorry, I should have checked that.

**Comment by rissom** [comment]
Always check server and client version number before opening an issue.
