### ISSUE TITLE
A client that uses explicit server-side port number encounters "address already in use" error during a reconnection attempt

### ISSUE THREAD

**Issue by HouzuoGuo** [mobile-shell/mosh#1015]
Hello!

Over here I have mosh version 1.3.2 running on both server and client. Due to firewall restrictions I have exactly one usable UDP port on the server for a mosh connection. It works quite well until an unexpected disconnect on the client side (e.g. system reboot), in which case the mosh server program remains running and still occupies the only usable UDP port. Subsequent connection attempt made to the same port fail with error "Error binding to IP 10.2.0.5: bind: Address already in use".

The only remedy appears to be SSH into the server and then kill the mosh-server program. Not very convenient.

Is there a better remedy to this issue? Thanks.

**Comment by andersk** [comment]
At present, Mosh requires one UDP port per session (see #295). Mosh has no way to tell the difference between a client that got rebooted and a client that was suspended and will be resumed later, so it cannot automatically garbage collect those sessions by default. However, there are options to make it do so after a certain time and/or on receipt of a certain signal (see #12, and the `mosh-server(1)` man page).

The easiest solution to your problem would be to open at least two ports (60001 and 60002), and use Mosh with `screen` or `tmux` in such a way that each new session automatically causes previous sessions to exit:

```sh
mosh HOST -- screen -dR mosh-session
mosh HOST -- tmux new -ADs mosh-session
```

(If `screen`/`tmux` is a direct child of `mosh-server` with no intermediate interactive shell, then `mosh-server` will exit when `screen`/`tmux` detaches.)

If you are really unable to open more than one port, then your solution is probably best. If you’re using `screen`/`tmux` as above, you could automate it by setting `--server` to a wrapper script like

```sh
#!/bin/sh
screen -d mosh-session
# or: tmux detach -s mosh-session
sleep 1
exec mosh-server "$@"
```

**Comment by HouzuoGuo** [comment]
Thanks for the hint @andersk, but what is this `mosh-session` executable? Is it a new feature from a version newer than 1.3.2?
