### ISSUE TITLE
[brew] mosh: remove transient dependency on python@2 via protobuf

### ISSUE THREAD

**Issue by javabrett** [mobile-shell/mosh#1016]
This issue is only a tracker/FYI/RFC for the following issue+PR I've created in `homebrew-core`:

- https://github.com/Homebrew/homebrew-core/issues/34345
- https://github.com/Homebrew/homebrew-core/pull/34346

Currently `brew install mosh` will drag `python@2` along with it, which AFAIK is unnecessary cruft, since `mosh` (client, or server) shouldn't have any Python dependencies.  It arrives on account of it being `recommended` in the `protobuf` recipe.

Anyway if there are any comments/disputes or reviews positive or negative for this they can probably best be made on the above issues or PR, and this issue can either remain open to help track those, or closed.

**Comment by rakkesh** [comment]
To comply with the on-going effort to remove options from all formulae, shouldn't we be using a `resource` block to include additional dependencies with options?

https://github.com/Homebrew/homebrew-core/issues/31510

**Comment by javabrett** [comment]
@rakkesh does that allow `protobuf` to be installed indirectly (not via `depends_on`), excluding `python@2`?  What are the benefits?

I'm hoping that my change won't require either package to be built-from-source i.e. they can still be installed from bottles, but I will check with the Brew team.

**Comment by javabrett** [comment]
@rakkesh spot-on, you'll see my issues were closed, based on the policy outlined in Homebrew/homebrew-core#31510.

So I expect this is a matter of the `protobuf` recipe stopping forcing Python as an additional/recommended/default dependency, perhaps creating `protobuf-python`.  And they should stop using the approaching-EOL Python 2.

I think I'll close this since there's not really anything Mosh-related to do here now.
