### ISSUE TITLE
custom port number and user@host

### ISSUE THREAD

**Issue by blub4747** [mobile-shell/mosh#1017]
Hi guys,

I want to know if I can logon to a linux server with mosh the same like with ssh.
which means in if I can use with normal ssh. eg 

> 
ssh user@example.server -p 23456(including a custom port number)

can I do same thing with mosh ? eg

> mosh user@example.server -p 23456 ?

or do I need to format it somehow different ?

Thx,blub4747

**Comment by eminence** [comment]
Yes, you can use a custom SSH port.  Please see the documentation at https://mosh.org/#usage and the `mosh` man page:

     mosh --ssh="ssh -p 2222" user@host

Mosh also accepts a `-p` argument directly, but this is for selecting the mosh UDP ports.

**Comment by blub4747** [comment]
Thank you for the support!
Is it also possible to add VNC SSH tunnel on top of the line above?
such as this example 

`ssh -L 5901:localhost:5901 -N -f -l vncuser IP_of_the_server`
https://community.time4vps.eu/discussion/120/how-to-connect-to-vnc-server-ussing-ssh-tunnel
