### ISSUE TITLE
How to install Mosh on DSM 6 (Synology)?

### ISSUE THREAD

**Issue by iFredOS** [mobile-shell/mosh#1025]
I tried to search for how to install Mosh on the Synology OS, but I cannot find package or instructions in the Wiki, to do it. I discovered Mosh project a few hours and very excited to use it / install it for the first time on my server. I want to kick out SSH! 🤓Help will be very appreciated. Thanks!

**Comment by javabrett** [comment]
I don't know anything about DSM, but it doesn't seem based on any (popular) upstream distro?  Does it have a good dev/compiler environment?  If so, you could try building from source.  You'll need to source dependencies of course.

**Comment by iFredOS** [comment]
Very good question. I can access my NAS by ssh. What do I need to compile the source? I want to try, with some guidance.

**Comment by eminence** [comment]
Can you tell us the output of `uname -a` and `lsb_release -a` ?   (The second command might not work, but that's OK)

**Comment by javabrett** [comment]
Have you seen http://www.courville.org/home/synology ? Rank very high searching for compiling Mosh on Synology.

**Comment by iFredOS** [comment]
> Have you seen http://www.courville.org/home/synology ? Rank very high searching for compiling Mosh on Synology.

Thanks! I didn't saw this link. I will try with the instructions and get back with an answer if it works.

**Comment by iFredOS** [comment]
Many instructions are not working because some folders don't exist and some library don't exist anymore. Very disappointing

**Comment by iFredOS** [comment]
> Can you tell us the output of `uname -a` and `lsb_release -a` ? (The second command might not work, but that's OK)

`uname -a`
`Linux iDiskStation 4.4.59+ #23824 SMP PREEMPT Tue Dec 25 18:27:56 CST 2018 x86_64 GNU/Linux synology_apollolake_918+`

`lsb_release -a`
`-sh: lsb_release: command not found`

**Comment by javabrett** [comment]
> Many instructions are not working because some folders don't exist and some library don't exist anymore.

I'm sure you have researched this pretty thoughroughly.  It might be worth leaving a couple of details here in case someone else comes along and can solve/document.

**Comment by grahams** [comment]
If you add the [SynoCommunity](https://synocommunity.com) package source repository to the Package Center, you can install the

[SynoCli Network Tools Package](https://synocommunity.com/package/synocli-net) which includes mosh amongst other common utilities.

**Comment by iFredOS** [comment]
> If you add the [SynoCommunity](https://synocommunity.com) package source repository to the Package Center, you can install the
> 
> [SynoCli Network Tools Package](https://synocommunity.com/package/synocli-net) which includes mosh amongst other common utilities.

Does it works now? I read somewhere it was not working. They added mosh to this package without testing.

**Comment by grahams** [comment]
I installed it and it appears to work on my x64 ds1817+.

**Comment by iFredOS** [comment]
> I installed it and it appears to work on my x64 ds1817+.

Okay. Then I'll try it. Thank you.

**Comment by drunkensouljah** [comment]
> Does it works now? I read somewhere it was not working. They added mosh to this package without testing.

I have the package installed on my DS216+ and it works fine.
I just have to run `mosh --server=/usr/local/bin/mosh-server diskstation`.
(it reads my ~/.ssh/config for the diskstation ssh config)
