### ISSUE TITLE
Mosh with only port 22 access?

### ISSUE THREAD

**Issue by vext01** [mobile-shell/mosh#1029]
Hi,

I'd like to use mosh, but I'm in a scenario where a corporate firewall blocks everything but port 22 inbound. Is there any way to use mosh in such a setting?

I suspect the answer is no, but I thought I'd ask.

Thanks

**Comment by eminence** [comment]
Hi,

You're correct.  Each mosh session requires its own UDP port, and you won't be able to get mosh to work unless this network traffic is allowed.

**Comment by keithw** [comment]
To be clear, you can still have *one* Mosh session going to that server at a time -- although you will probably have to log in as root so mosh-server can bind to UDP port 22.
