### ISSUE TITLE
Support for Windows

### ISSUE THREAD

**Issue by filips123** [mobile-shell/mosh#1030]
There should be support for native Windows binary.

**Comment by javabrett** [comment]
Possible dup #293, see also #989.

**Comment by filips123** [comment]
Yes but that issues aren't active. Is there any update?

Windows now supports OpenSSH and other programs natively so it should not be hard to support it.

**Comment by eminence** [comment]
There's no new status on this, though I should say that mosh works well under the relatively new Windows Subsystem for Linux (though this is only available on Windows 10).  I'm going to close this as a duplicate

**Comment by aress31** [comment]
+1

**Comment by SPDurkee** [comment]
There are now 2 terminals in the Windows Store that support Mosh natively:
https://www.microsoft.com/store/productId/9P2KRLMFXF9T
https://www.microsoft.com/store/productId/9NK1GDVPX09V

**Comment by Atry** [comment]
I think there are some distributions on Windows prividing the `mosh` package:

- https://packages.msys2.org/package/mosh
- https://cygwin.com/packages/summary/mosh.html
