### ISSUE TITLE
PKCS#11 (Cryptoki) support?

### ISSUE THREAD

**Issue by nickray** [mobile-shell/mosh#1031]
Hi,

I'm looking to extend our [FIDO2 USB key](https://github.com/solokeys/solo) with "personal HSM"-like qualities. Looking at OpenSSH, there is only support for RSA keys in PKCS11Provider, due to lack of resources it seems Ed25519 ([draft for release in PKCS#11 version 3](https://www.oasis-open.org/committees/document.php?document_id=62198&wg_abbrev=pkcs11)) will not happen anytime soon.

My question is whether there is any interest or even plans to support SSH keys from a PKCS#11 provider in mosh? As far as I understand, so far there is none? And if so, we would be interested particularly in support for Ed25519, as 4096 bit RSA keys are are quite bulky both in storage and implementation on a microcontroller.

I think 25519 would be a great fit for an innovative project like Mosh :) The dream is for road warriors to easily and safely connect from any laptop to any server.

**Comment by andersk** [comment]
`mosh` [delegates](https://github.com/mobile-shell/mosh/blob/mosh-1.3.2/scripts/mosh.pl#L400) the initial login, including everything related to authentication and public-key cryptography, to the `ssh` command. (This is why you don’t need to be running a separate Mosh daemon, only a normal SSH daemon, and why you can install and use `mosh` without special administrative privileges.) So `mosh` automatically supports whatever types of keys your `ssh` command supports, and there is no way to support additional types except by adding that support to `ssh`.

**Comment by nickray** [comment]
I see, thanks for clarifying!
