### ISSUE TITLE
Unable to connect to gpg-agent - IPC error

### ISSUE THREAD

**Issue by cbcoutinho** [mobile-shell/mosh#1034]
After logging onto a remote systems over ssh, I start up a `gpg-agent` to handle decrypting files and handling further ssh connections (using gpg authentication sub-keys). If I connect to the same remote using `mosh`, the gpg-agent is not able to start for some reason.

Expected behavior:
```shell
client$ ssh remote
remote$ gpg-connect-agent updatestartuptty /bye
gpg-connect-agent: no running gpg-agent - starting '/usr/bin/gpg-agent'
gpg-connect-agent: waiting for the agent to come up ... (5s)
gpg-connect-agent: connection to agent established
OK
```

Current behavior with mosh:

```shell
client$ mosh remote
remote$ gpg-connect-agent updatestartuptty /bye
gpg-connect-agent: no running gpg-agent - starting '/usr/bin/gpg-agent'
gpg-connect-agent: waiting for the agent to come up ... (5s)
gpg-connect-agent: waiting for the agent to come up ... (4s)
gpg-connect-agent: waiting for the agent to come up ... (3s)
gpg-connect-agent: waiting for the agent to come up ... (2s)
gpg-connect-agent: waiting for the agent to come up ... (1s)
gpg-connect-agent: can't connect to the agent: IPC connect call failed
gpg-connect-agent: error sending standard options: No agent running
```

I noticed a couple things that differ between the two systems that may lead to the cause of the problem, and maybe you have some idea of how to fix them:

1. Systems with `systemd` have changed where `gpg-agent` places its sockets, namely they are placed in the `/run/user/<uid>/gnupg` directory. Connecting to the remote over ssh shows that the sockets are placed in the proper place:

```shell
client$ ssh remote gpgconf --list-dir
sysconfdir:/etc/gnupg
bindir:/usr/bin
libexecdir:/usr/lib64
libdir:/usr/lib64/gnupg
datadir:/usr/share/gnupg
localedir:/usr/share/locale
socketdir:/run/user/<uid>/gnupg
dirmngr-socket:/run/user/<uid>/gnupg/S.dirmngr
agent-ssh-socket:/run/user/<uid>/gnupg/S.gpg-agent.ssh
agent-extra-socket:/run/user/<uid>/gnupg/S.gpg-agent.extra
agent-browser-socket:/run/user/<uid>/gnupg/S.gpg-agent.browser
agent-socket:/run/user/<uid>/gnupg/S.gpg-agent
homedir:/home/<user>/.gnupg
```

Those are not recognized over mosh for some reason:

```shell
client$ mosh remote
remote$ gpgconf --list-dir
sysconfdir:/etc/gnupg
bindir:/usr/bin
libexecdir:/usr/lib64
libdir:/usr/lib64/gnupg
datadir:/usr/share/gnupg
localedir:/usr/share/locale
socketdir:/home/<user>/.gnupg
dirmngr-socket:/home/<user>/.gnupg/S.dirmngr
agent-ssh-socket:/home/<user>/.gnupg/S.gpg-agent.ssh
agent-extra-socket:/home/<user>/.gnupg/S.gpg-agent.extra
agent-browser-socket:/home/<user>/.gnupg/S.gpg-agent.browser
agent-socket:/home/<user>/.gnupg/S.gpg-agent
homedir:/home/<user>/.gnupg
```

2. The SSH_TTY variable doesn't match the current psuedo-terminal:

```shell
client$ mosh remote
remote$ echo $SSH_TTY $(tty)
/dev/pts/0 /dev/pts/1
```

**Comment by cgull** [comment]
Mosh doesn't support SSH or GPG agent forwarding.  This is a topic of some debate in the Mosh community, but at least right now, no.  It only supports virtual terminal sessions.

`SSH_TTY` is wrong because you're not actually running SSH any longer, it's only used for startup and then `mosh-server` starts on another pty.

**Comment by cbcoutinho** [comment]
Ok great, thanks for the reply @cgull

Feel free to close this issue
