### ISSUE TITLE
Mosh Server Suddenly Exits when Starting Fish Shell (once again)

### ISSUE THREAD

**Issue by rapha8l** [mobile-shell/mosh#1037]
Hi,

I'm experimenting the same problem on Void linux version 1.3.2
as https://github.com/mobile-shell/mosh/issues/918

if I mosh from 1.3.2 to 1.3.2 and start fish 3.0.2 (Void on both), it disconnects
if I do it from OpenBSD version 1.3.2 or Debian version 1.2.6, and starts fish 3.0.2, it disconnects
if I connect from any of mosh version to an host and run fish version 2.*, then no problem
I don't know if it's a Mosh of a Fish problem (maybe I can open it on fish repo too)

Thanks

**Comment by ndowens** [comment]
Same here, seems this was a previous issue

**Comment by rapha8l** [comment]
The void update seems to have resolve the issue
Thanks
