### ISSUE TITLE
Cannot connect to host

### ISSUE THREAD

**Issue by gitgitgat** [mobile-shell/mosh#1042]
I have mosh installed in the server and client, I type mosh -p xxxx user@xxx.xxx.xx.xx but following error shows up:

`usr/local/bin/mosh: Could not connect to 210.16.120.32, last tried 210.16.120.32: IO::Socket::INET: connect: Connection refused ssh_exchange_identification: Connection closed by remote host /usr/local/bin/mosh: Did not find remote IP address (is SSH ProxyCommand disabled?).`

server in centOS 7.0 and connecting from osx Mojave

**Comment by gitgitgat** [comment]
And this happens from the Chrome app:

Server fingerprint unknown. Store and continue? (Yes/No): yes
Authentication types supported by server:
 - Public Key
```
Trying authentication type Public Key
No ssh key found.
ssh authentication failed: Access denied. Authentication that can continue: publickey,gssapi-keyex,gssapi-with-mic

SSH Login failed.

ssh user@xxx.xxx.xx.xx has no problems connecting.
```

**Comment by gitgitgat** [comment]
Now I am trying mosh installed in Ubuntu, but the following error shows up:

```
The locale requested by LC_CTYPE=UTF-8 isn't available here.
Running `locale-gen UTF-8' may be necessary.

mosh-server needs a UTF-8 native locale to run.

Unfortunately, the local environment ([no charset variables]) specifies
the character set "US-ASCII",

The client-supplied environment (LC_CTYPE=UTF-8) specifies
the character set "US-ASCII".

locale: Cannot set LC_CTYPE to default locale: No such file or directory
locale: Cannot set LC_ALL to default locale: No such file or directory
LANG=
LANGUAGE=
LC_CTYPE=UTF-8
LC_NUMERIC="POSIX"
LC_TIME="POSIX"
LC_COLLATE="POSIX"
LC_MONETARY="POSIX"
LC_MESSAGES="POSIX"
LC_PAPER="POSIX"
LC_NAME="POSIX"
LC_ADDRESS="POSIX"
LC_TELEPHONE="POSIX"
LC_MEASUREMENT="POSIX"
LC_IDENTIFICATION="POSIX"
LC_ALL=
Connection to xxx.xxx.xx.xx closed.
/usr/local/bin/mosh: Did not find mosh server startup message. (Have you installed mosh on your server?)

```

**Comment by gitgitgat** [comment]
export LC_ALL="en_US.UTF-8" has been working for that

**Comment by eminence** [comment]
Hi there.  The first errors you were showing looked like ssh-connection issues.  Did you get those sorted out?

The last error you showed was about the need for a UTF-8 locale.   Did you generated a UTF-8 locale on both your client and server machines?

**Comment by eminence** [comment]
No reply, so closing for now.  Please leave a comment here (or open a new issue) if you're still having problems.
