### ISSUE TITLE
client assert on FreeBSD

### ISSUE THREAD

**Issue by netchild** [mobile-shell/mosh#1045]
Hi,

coming from #1039, here the client-assert triggered on FreeBSD-13-current (in-development version of FreeBSD as of beginning of May). Please tell which kind of debugging you would like to have provided (e.g. syscall tracing, stack trace, ...).

```
% MOSH_KEY=mSyotVGryhhd6cjVhk527Q mosh-client -vvv 89.238.82.207 60001; date
mosh did not make a successful connection to 89.238.82.207:60001.
Please verify that UDP port 60001 is not firewalled and can reach the server.

(By default, mosh uses a UDP port between 60000 and 61000. The -p option
selects a specific UDP port number.)
[mosh is exiting.]
select: got poll (timeout 0)
                            Assertion failed: (false), function init_diff, file ./../statesync/user.h, line 92.
                                                                                                               [1]    17816 abort      MOSH_KEY=mSyotVGryhhd6cjVhk527Q mosh-client -vvv 89.238.82.207 60001
                                                                                      So. 19 Mai 2019 14:11:30 CEST
```

Bye,
Alexander.

**Comment by cgull** [comment]
It appears that you have two problems:  1) you can't connect, and 2) mosh-client crashes with that assert.  Is that correct?

Is the client using FreeBSD-CURRENT, or server, or both?

Does mosh-client always crash the same way with this server?  Is this problem reproducible with other servers?  If you have another -CURRENT machine, is it reproducible there?

Exactly what revision of FreeBSD-CURRENT are you running?  Snapshot, or source build?

kdump + ktrace -E would be somewhat useful to see in debugging this, I think.

My day job is FreeBSD-based and Mosh is one of my two main dev platforms, so I can install FreeBSD-CURRENT to take a look at this, if needed.

**Comment by cgull** [comment]
I think I'm interested in syscall tracing from both client and server here, actually.  I conjecture that your server-side issues are a server-side firewall issue, but traces will help explain what is going on.

**Comment by cgull** [comment]
Also, where does your Mosh build come from?  ports/pkg, or our Github source?

**Comment by netchild** [comment]
It could be that there are two problems...

Client and server are using the same revision (r347365) of -current. Both are source builds (build separately, one Intel, one AMD, CPUTYPE set to native in make.conf, CFLAGS=-O2, all other service (mysql, postfix, dovecot, nginx, ...) in jails on the hosts work fine.

I can reproduce this with this server. I don't have another server to test this against (there are several jails on both systems, the connection showed here is from host to host). If needed I can install a VM (will take some time) with the same rev. I haven't tried the other way around (NAT in front of one system, may take a while to get time to setup the UDP forwarding to test the other way around).

Mosh is build from ports.

Firewall: would be surprising, as I have "keep state" in the PF rule for the UDP ports for mosh. I also tried without firewall and a mosh client on the smartphone (no response from UDP port). So there's maybe a 3rd issue lurking somewhere.

I will see to get the kdump of client and server later today.

**Comment by cgull** [comment]
I now see an abort() on my -CURRENT install and on MacOS, but not Linux.  It only occurs when the `-v` flag is given to mosh-client.  Looking at it.

But it differs from yours: I'm not getting the same output as you (I'm not getting the select timeout and mosh-client aborts instantly), and I'm getting strange behavior from mosh-client, so I'd still appreciate ktrace/kdump to see what's different on your machine.  Does your client exit instantly, when this problem happens?

**Comment by netchild** [comment]
[mosh_client_kdump.txt](https://github.com/mobile-shell/mosh/files/3282827/mosh_client_kdump.txt)
[mosh_server_kdump.txt](https://github.com/mobile-shell/mosh/files/3282828/mosh_server_kdump.txt)

The ktrace was done with the firewall disabled. No packet arrived in "tcpdump -s 1500 udp port 60001".
The client dies instantly (as you will see from the timestamps in the trace).

**Comment by cgull** [comment]
I've been able to reproduce the abort you're getting.  Again, working on that, but to debug your connectivity problem, you can use `mosh-client` without `-v` for now.

I'm pretty sure you have a separate problem with `mosh-server`.  Does `ktrace` show it receiving the packets from the client?

**Comment by netchild** [comment]
[mosh_client_kdump_2.txt](https://github.com/mobile-shell/mosh/files/3284129/mosh_client_kdump_2.txt)
[mosh_server_kdump_2.txt](https://github.com/mobile-shell/mosh/files/3284130/mosh_server_kdump_2.txt)

kdump of client + server, firewall disabled, no "-v" on the client.
Output from mosh-server: 
> Crypto exception: Packet failed integrity check.

tcpdump output:
[mosh_tcpdump.txt](https://github.com/mobile-shell/mosh/files/3284139/mosh_tcpdump.txt)

**Comment by cgull** [comment]
The reason I had such difficulty reproducing the abort problem is that it's already fixed :)
(commits https://github.com/mobile-shell/mosh/commit/a40b67691aecfe9b31c3e8babf8e94d8d1a187a1#diff-e61e92f273166f575ca7b78e5b06ff9f, https://github.com/mobile-shell/mosh/commit/b11d524bb77d2e0f346bc0e64074b7c30c9b40a5#diff-e61e92f273166f575ca7b78e5b06ff9f)  I had done some general cleanup, and that's one of the things I cleaned up, and I forgot about it.

That's not yet in a Mosh release though.

Thanks for the traces.  The client and tcpdump traces both appear to be normal (though not from the same session, is that correct?)  The server trace is normal as far as it goes, but mosh-server forks a child, and the child's behavior is the interesting part here, and that wasn't traced. `ktrace -i` will capture that.

If you only got one `Crypto exception`, it's probably a random UDP packet being sent to the server's port, and being harmlessly discarded.  (It does tell us that `mosh-server` is receiving *something* on that port, though.)  Try doing `tcpdump` on your server while you `ktrace -i` on `mosh-server`, and compare the packets received in each.  If you want to attach the trace files to a comment, please attach the binary files next time, they're easier to review for this one, I think.

**Comment by netchild** [comment]
> Thanks for the traces. The client and tcpdump traces both appear to be normal (though not from the same session, is that correct?) The server trace is normal as far as it goes, but mosh-server forks a child, and the child's behavior is the interesting part here, and that wasn't traced. `ktrace -i` will capture that.

I had to re-run a trace on one side, and didn't bother to re-run the other side at the same time... Attached is now the ktrace -i (I mixed it up with -d on the runs before).

> If you only got one `Crypto exception`, it's probably a random UDP packet being sent to the server's port, and being harmlessly discarded. (It does tell us that `mosh-server` is receiving _something_ on that port, though.) Try doing `tcpdump` on your server while you `ktrace -i` on `mosh-server`, and compare the packets received in each. If you want to attach the trace files to a comment, please attach the binary files next time, they're easier to review for this one, I think.

I got 21 of those messages. They started when I started the client, and they stopped when the client stopped itself.

[mosh_server_side_3.zip](https://github.com/mobile-shell/mosh/files/3292232/mosh_server_side_3.zip)

I compared the first UDP packet, with what is listed in the kdump, all what is in the UDP packet is in the kdump.

**Comment by netchild** [comment]
Hi,
With a more recent version of FreeBSD-current and maybe a recompile of mosh with a more recent version of llvm: this works now.
Bye,
Alexander.
