### ISSUE TITLE
Website is down.

### ISSUE THREAD

**Issue by vext01** [mobile-shell/mosh#1046]
mosh.org is down with a HTTP 403.

![image](https://user-images.githubusercontent.com/604955/59353870-d3e2cb80-8d1b-11e9-97d0-854ca865e16d.png)

**Comment by eminence** [comment]
It looks OK to me now.  Are you still seeing this problem?

**Comment by cgull** [comment]
It's still down for me.  So is https://sipb.mit.edu.  This is probably an MIT web-hosting outage and will probably clear soon.

**Comment by vext01** [comment]
Hrm. I can hit if using lynx from another machine elsewhere.

**Comment by vext01** [comment]
Works for me now.

**Comment by eminence** [comment]
Ok, going to close the issue, under the assumption that it was a temporary network-wide outage that has since been fixed

**Comment by cgull** [comment]
mosh and sipb are both back up for me.
