### ISSUE TITLE
Optimal protobuf version for compilation

### ISSUE THREAD

**Issue by jtourig** [mobile-shell/mosh#1047]
When attempting to compile on a Fedora 29 remote machine to which I don't have sudo/package install privilege, configure proceeds fine with my compiled protobuf install but building fails.  With a recent clone of the current git, I get the error:
```
userinput.pb.h:9:10: fatal error: google/protobuf/stubs/common.h: No such file or directory
 #include <google/protobuf/stubs/common.h>
          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
```
This file, as far as I can see, does exist where it should.

With the mosh-1.3.2 release, I get:
```
In file included from userinput.pb.cc:4:
userinput.pb.h:17:2: error: #error This file was generated by an older version of protoc which is
 #error This file was generated by an older version of protoc which is
  ^~~~~                       
userinput.pb.h:18:2: error: #error incompatible with your Protocol Buffer headers. Please
 #error incompatible with your Protocol Buffer headers.  Please
  ^~~~~                       
userinput.pb.h:19:2: error: #error regenerate this file with a newer version of protoc.
 #error regenerate this file with a newer version of protoc. 
  ^~~~~                       
userinput.pb.cc:12:10: fatal error: google/protobuf/wire_format_lite_inl.h: No such file or directory
 #include <google/protobuf/wire_format_lite_inl.h>          
          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
```

This has occurred with several builds of protobuf, from 3.2.0 to 3.8.0, both 'cpp' and 'all' releases.

I have previously gotten mosh to compile on a different RHEL system, but clearly I am missing a compiler flag or something this time.  I have set my PKG_CONFIG_PATH appropriately (configure does not complain), it points to my pkgconfig/ dir containing the .pc files with the right info, and have also tried to set `protobuf_CFLAGS` and `protobuf_LIBS` manually.  Is there a preferred version of protocol buffers which works best with 1.3.2 or the current dev version, and/or any advice on the cause and solution?

This is a great tool which I enjoy using on the other system, thanks for any assistance.

**Comment by andersk** [comment]
Mosh works with a wide range of protobuf versions. Your problem is that you need to set `PATH` so that the first `protoc` binary in `PATH` matches the protobuf headers and libraries found by `pkg-config`. If you have `PKG_CONFIG_PATH=/foo/lib/pkgconfig:…`, you’ll also need `PATH=/foo/bin:…`.

**Comment by jtourig** [comment]
Thanks. I did a clean re-compilation, making the change to `PATH`, and am not getting the version error any more, but am still getting the missing `/google/protobuf/stubs/common.h` error.  When I inspect the actual build command with `make V=1`, I get:
`c++ -DHAVE_CONFIG_H -I. -I../..  /home/my_name/usr/local/include  -Wall -fno-strict-overflow -D_FORTIFY_SOURCE=2 -fstack-protector
-all -Wstack-protector --param ssp-buffer-size=1 -fPIE -fno-default-inline -pipe -Wno-error -g -O2 -MT userinput.pb.o -MD -MP -MF .
deps/userinput.pb.Tpo -c -o userinput.pb.o userinput.pb.cc`

So, my include dir is in there, but I thought it was odd it's missing the `-I` flag.  When I copy the command and run it in `mosh/src/protobufs` on its own, adding `-I` to my include path, it seems to work and yields the `userinput.pb.o` with error code 0.  I realize this is probably a janky autotools/automake issue on my system and not something mosh-specific, so sorry for treating y'all as tech support.
```
echo $protobuf_CFLAGS
/home/my_name/usr/local/include`
```
I don't want to manually do this for every object file, so if anyone has a recommendation....

**Comment by andersk** [comment]
That’s not a valid value for `protobuf_CFLAGS`; it’s supposed to include the `-I`. But instead of making that change, you should just unset `protobuf_CFLAGS` and `protobuf_LIBS` and try again. The right values should be detected by pkg-config.
