### ISSUE TITLE
mosh doesn't build with libc++ >=7.0 on case-insensitive filesystems

### ISSUE THREAD

**Issue by quentinmit** [mobile-shell/mosh#1051]
The Mosh build process writes a file called `VERSION` in its root directory. clang >= 7.0 has an include called `version`. On a case-insensitive filesystem these are the same name, so `VERSION` ends up getting parsed as an include file.

Possible fixes:
- Don't put the root directory in the include path (and move config.h/version.h into a subdirectory)
- Rename `VERSION` to something else (`VERSION.txt`?)
- Generate `version.h` directly and not generate `VERSION` at all
- File an upstream bug against `clang`, since this affects a bunch of packages that have `VERSION` files

**Comment by eminence** [comment]
Can you give a little more info about the system/platform you reproduced this on?   @cgull and I were not able to reproduce (on FreeBSD and Ubuntu, respectively.  Both of us were testing with ZFS in case-insensitive mode).  I tried clang-7 and clang-8, and @cgull tried clang 9.0.0.

**Comment by cgull** [comment]
I can't reproduce this on FreeBSD 12.0, package llvm-devel-9.0.d20190701, and Mosh on a case-insensitive ZFS filesystem.  And I don't see a file named `version` or `version.hpp` anywhere.  Can you describe your environment and the exact error you're getting?

**Comment by quentinmit** [comment]
Sure, here's the bug I got filed against me as a package maintainer:

https://trac.macports.org/ticket/58690#comment:10

and here's the build log:

https://trac.macports.org/attachment/ticket/58690/main.log

clang 7.0 includes the file at this path when built on Darwin in /opt/local::

`/opt/local/libexec/llvm-7.0/include/c++/v1/version`

I wouldn't have expected this to be OS-dependent. Are you maybe somehow testing clang-7/clang-8 with an earlier libc++? Technically the header is part of libc++ 7, not clang itself.

**Comment by quentinmit** [comment]
On IRC we figured out that FreeBSD uses an older libc++ with newer clang; it's actually the libc++ version that matters here. I also repro'd it myself with this MacPorts invocation:

```
sudo port -k -d -ns install mosh configure.compiler=macports-clang-8.0 build.post_args=V=1
```

(MacPorts defaults to using Apple's clang/libc++ on modern OS releases, which is why it doesn't happen unless you force clang 8.0.)

Here's the full build log: https://gist.github.com/quentinmit/e92599d204fa9baeadf9bc69a89d13bc

**Comment by quentinmit** [comment]
FYI I also filed an upstream llvm bug here: https://bugs.llvm.org/show_bug.cgi?id=42540

**Comment by cgull** [comment]
After looking at GCC documentation, I do believe Mosh is responsible for fixing this, on case-insensitive filesystems at least.  (GCC documentation isn't authoritative but I believe its documentation of how `-I` works is reflecting long-standing practice.)  And I can force the error by adding `#include <version>` to a Mosh source file.

So I somewhat fixed it in Mosh, pull request momentarily.
