### ISSUE TITLE
Terminal emulation different from ssh when running htop

### ISSUE THREAD

**Issue by dandv** [mobile-shell/mosh#1057]
Excuse the lame title, I'm far from an expert on terminal emulation :)

Here's what happens: when I run `htop` over a regular ssh connection and quit it, the screen goes blank and I'm returned to the prompt.

If I do the same over mosh, the screen isn't cleared:

![image](https://user-images.githubusercontent.com/33569/61594728-faf6ad80-aba3-11e9-8bdc-4d1f6db17ed3.png)

**Comment by andersk** [comment]
The missing feature here is alternate screen support in the emulated terminal. See #843.
