### ISSUE TITLE
Environment variables don't work

### ISSUE THREAD

**Issue by Omoeba** [mobile-shell/mosh#1063]
mosh is still killed by `pkill -SIGUSR1 mosh-server` on ubuntu 18.04 even when `running env | grep MOSH` returns `MOSH_SERVER_SIGNAL_TMOUT=100`.

**Comment by andersk** [comment]
Environment variables are per-process. Did you make sure the environment variable is set when the `mosh-server` process is started? You can see the environment variables of a process using:

`ps ewwp $(pgrep mosh-server)`

Getting the environment variable into the process is complicated by the fact that `mosh-server` is launched remotely using SSH, but one sure-fire way is

`mosh --server='env MOSH_SERVER_SIGNAL_TMOUT=100 mosh-server' user@host`

and if that works, you can then go figure out which dotfile you need to configure for the variable to be picked up in this execution path (perhaps `~/.ssh/environment`).

**Comment by Omoeba** [comment]
Putting the variable in ~/.ssh/environment worked. Does the signal timeout mean that a mosh-server process who hasn’t received an update in 100 seconds will terminate or it will wait to receive an update for 100 seconds before terminating?

**Comment by cgull** [comment]
If `MOSH_SERVER_SIGNAL_TMOUT=100`, then `mosh-server` will ignore `SIGUSR1` until 100 seconds have passed without receiving a client update.  After that, `SIGUSR1` will terminate mosh-server immediately.
