### ISSUE TITLE
Mosh over iterm(MacOS) to Linux not listing directory contents in color

### ISSUE THREAD

**Issue by sksd509** [mobile-shell/mosh#1065]
I am using iterm2/MacOs terminal to connect to Linux box over mosh. Currently, I have set **CLI_COLORS** and **TERM** properly set as the [link](https://superuser.com/questions/399594/color-scheme-not-applied-in-iterm2) says.

Also, this is not some issue with iterm/terminal client as I have tried SSH from iterm/terminal to the same Linux box and it works all fine( **ls** is listing contents in the ** coloured format** as seen in native terminal sitting in the Linux box)

**Comment by andersk** [comment]
Perhaps your Linux system is Ubuntu, which has a [confused `~/.bashrc` snippet](https://bugs.launchpad.net/ubuntu/+source/bash/+bug/103929) that checks for an incorrect `TERM` value. Just edit your `~/.bashrc` to fix the snippet or uncomment `#force_color_prompt=yes`. (Don’t try to change your `TERM` value as that will break other applications.)

**Comment by sksd509** [comment]
Having this in **~/.tmux.conf** >>
`set -g default-terminal "screen-256color"`
and, having this in my **~/.bashrc** >>
`export TERM=xterm-256color
alias tmux='tmux -2'`
worked for me!
NOTE : remember you have to start a new tmux session to see this in effect!
