### ISSUE TITLE
Passing TERM environment variable

### ISSUE THREAD

**Issue by grwlf** [mobile-shell/mosh#1069]
Hi. How to make mosh-server to set specific environment variables?

I'd like to automatically change TERM variable inside the console from `xterm` which I see now to `rxvt-unicode-256color` which I am using on client.

**Comment by andersk** [comment]
`mosh-server` intentionally sets `TERM`, since it is itself a terminal (like `screen` and `tmux`, which also set `TERM`). It would be wrong for it to pass through the outside value of `TERM`. See previous discussion at #446 and #728.
