### ISSUE TITLE
mosh-server 1.3.2 crashes on OSX 10.8.5

### ISSUE THREAD

**Issue by letaage** [mobile-shell/mosh#1071]
Hello,

I have been using mosh for quite a while on a Mac mini running OS X 10.8.5. I installed it  using macports and usually connect via my Android  mobile phone using JuiceSSH. Other than the occasional Mac firewall issue it has worked well.  

But recently mosh stopped working, I think it coincided with an upgrade of macports or an associated library but I am not sure. I am not a software person so bear with me!

The fault manifests itself as a  "Nothing received from the server on UDP port 60003" error message but I have disabled the firewall and the problem persists. I have tried connecting on the local host without luck and manually connecting - nothing is working.

I finally realised that mosh-server is crashing so I tracked down the crash log (attached below) and would appreciate if I can get some help working out what is causing the problem.

Cheers,
Tom

[mosh-server_2019-10-22-231533_slim.crash.log](https://github.com/mobile-shell/mosh/files/3755792/mosh-server_2019-10-22-231533_slim.crash.log)

**Comment by eminence** [comment]
Pasting the stack trace for convenience: 

```
Thread 0 Crashed:: Dispatch queue: com.apple.main-thread
0   libsystem_kernel.dylib        	0x00007fff8de9bd46 __kill + 10
1   libsystem_c.dylib             	0x00007fff95d2df83 abort + 177
2   libc++abi.dylib               	0x00007fff9344a9eb abort_message + 257
3   libc++abi.dylib               	0x00007fff9344839a default_terminate() + 28
4   libobjc.A.dylib               	0x00007fff8f169887 _objc_terminate() + 111
5   libc++abi.dylib               	0x00007fff934483c9 safe_handler_caller(void (*)()) + 8
6   libc++abi.dylib               	0x00007fff93448424 std::terminate() + 16
7   libc++abi.dylib               	0x00007fff9344958b __cxa_throw + 111
8   libprotobuf.21.dylib          	0x0000000108c2d443 google::protobuf::internal::LogMessage::Finish() + 127
9   libprotobuf.21.dylib          	0x0000000108c61c21 google::protobuf::internal::EpsCopyInputStream::DoneFallback(char const*, int) + 97
10  mosh-server                   	0x0000000108b9520b google::protobuf::internal::EpsCopyInputStream::DoneWithCheck(char const**, int) + 179
11  mosh-server                   	0x0000000108b943e4 TransportBuffers::Instruction::_InternalParse(char const*, google::protobuf::internal::ParseContext*) + 562
12  libprotobuf.21.dylib          	0x0000000108c60f37 bool google::protobuf::internal::MergePartialFromImpl<false>(google::protobuf::StringPiece, google::protobuf::MessageLite*) + 169
13  libprotobuf.21.dylib          	0x0000000108c61595 bool google::protobuf::MessageLite::ParseFrom<(google::protobuf::MessageLite::ParseFlags)1, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > >(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&) + 51
14  mosh-server                   	0x0000000108b787a2 Network::FragmentAssembly::get_assembly() + 232
15  mosh-server                   	0x0000000108b6e1ce Network::Transport<Terminal::Complete, Network::UserStream>::recv() + 110
16  mosh-server                   	0x0000000108b66ceb main + 3163
17  libdyld.dylib                 	0x00007fff92f617e1 start + 1
```

Looks protobuf related.  Are you still having this crash?   Can you see if macports has an updated package for protobufs?  I think the package will be called `protobuf-cpp`

**Comment by achernya** [comment]
I think this is an ABI issue we cannot reproduce. mosh as shipped by the official mosh pkg for macOS statically links libprotobuf. Try using either the official pkg or rebuilding mosh in macports.
