### ISSUE TITLE
Nothing received from server on UDP port 60001

### ISSUE THREAD

**Issue by ctsrc** [mobile-shell/mosh#1074]
Hi, I am having a strange issue with mosh.

In general, mosh has been working great across a wide range of computers that I have.

Today I installed mosh on a desktop computer of mine.

For testing, my laptop and my desktop are both connected via WiFi to the same access point.

## Computers and mosh versions involved

**Laptop**: MacBook Air 2018, running macOS Catalina 10.15.1

mosh version on laptop: mosh 1.3.2, installed with homebrew

**Desktop**: MSI Cubi, running KDE neon 5.17 User Edition (based on Ubuntu 18.04)

mosh version on desktop: mosh 1.3.2, installed with apt using the default repos of KDE neon

## Network

Both computers are connected to the same Access Point, which in turn is connected to a router by cable.

## Things that work

I am able to SSH from the laptop to the desktop.

```text
user@laptop ~ % ssh 203.0.113.220
```

I am able to SSH from the desktop to the laptop.

```text
user@desktop:~$ ssh 203.0.113.221
```

I am able to listen on UDP port 60001 on the desktop, and send a message to it from the laptop.

```text
user@desktop:~$ nc -w 0 -lu 60001
```

```text
user@laptop ~ % nc -w 0 -u 203.0.113.220 60001 <<EOF
hello
EOF
```

```text
hello
```

I am able to listen on UDP port 60001 on the laptop, and send a message to it from the desktop.

```text
user@laptop ~ % nc -w 0 -lu 60001
```

```text
user@desktop:~$ nc -w 0 -u 203.0.113.221 60001 <<EOF
hello
EOF
```

```text
hello
```

I am able to connect to the laptop with mosh from the desktop

```text
user@desktop:~$ mosh 203.0.113.221
```

## Problem

I am unable to connect to the desktop with mosh from the laptop

```text
user@laptop ~ % mosh 203.0.113.220
```

Shows the following message at the top of the terminal with a blue background:

```text
mosh: Nothing received from server on UDP port 60001. [To quit: Ctrl-^ .]
```

After about 15 seconds without contact, mosh times out and then it exits a few seconds after that with the following output:

```text
mosh did not make a successful connection to 203.0.113.220:60001.
Please verify that UDP port 60001 is not firewalled and can reach the server.

(By default, mosh uses a UDP port between 60000 and 61000. The -p option
selects a specific UDP port number.)
[mosh is exiting.]
```

**Comment by stephenlgpa** [comment]
I am having the same issue using Blink on an iPad Pro connecting to a remote linux vps. All worked fine until recently, and now I am receiving the messages detailed under "Problem" above. This occurs the same way with my firewall enabled or disabled...

**Comment by evetsso** [comment]
Does `--bind-server=any` on the client side fix the problem?

I was seeing similar behaviour here, and noticed that the mosh-server process is being spawned with `-s` (bind to the local interface from the SSH_CONNECTION environment variable), and this shows up in the mosh-server's environment:
```
SSH_CONNECTION=127.0.0.1 39796 127.0.0.1 22
```
which should mean that the server process is listening on the wrong interface.

`--bind-server=any` on the client works around the problem for me.

My environment is an up-to-date Arch Linux (on both client and server) with version `mosh 1.3.2 [build mosh-1.3.2-86-g0cc492d]` and openssh 8.1p1.

**Comment by ctsrc** [comment]
Hi @evetsso, I tried doing as you suggested but unfortunately `--bind-server=any` on the client side does not make any difference.

**Comment by borrible13th** [comment]
It seems to be a problem with the macOS Catalina firewall. For my MacBook Pro an entry for mosh-server is added in the firewall for allowing incoming connections, but it still doesn't connect via UDP port. And it doesn't matter how I add the entry there - via GUI or terminal. See [Blink Issue ](https://github.com/blinksh/blink/issues/11).

Connection can only be established if I disable the firewall.

Is there any solution found?

**Comment by cleeland** [comment]
I just switched from a laptop running mojave to a laptop running Big Sur, and I'm having the same issue with mosh. I'm suspecting it might be something to do with "improved" security settings on macos after mojave.

**Comment by anhdle14** [comment]
I tried to set /etc/pf.conf to allow UDP but that doesn't work either. Is anyone get Mosh working after Mac Big Sur?

**Comment by cleeland** [comment]
@anhdle14 I traced my issues with mosh down to using Pulse VPN client: when I would use pulse vpn, mosh would not work, but using it locally worked just fine.

I reported it to Juniper and never got a reply or acknowledgement, but at some point one of their updates cured the issue and mosh started working again.

**Comment by anhdle14** [comment]
Currently, I am using Tailscale, but from what you are saying it is because of some problems from the VPN side and not Mosh itself?

**Comment by cleeland** [comment]
I'm not familiar with tailscale, but from my experience, yes, it was not mosh.  I was able to use mosh to access other machines inside my own network, and I was able to use the same version of mosh to access machines across the VPN when running on macos mojave, but I was NOT able to use mosh to access machines across the VPN using macos catalina or big sur...until I installed some later Juniper update.

**Comment by anhdle14** [comment]
With Tailscale, I have contacted support but there is nothing from Tailscale side. However, the fix for me was simply playing around with the Firewall settings inside System Preferences. If you disable all firewalls you can connect without problems.

<img width="638" alt="System Preferences" src="https://user-images.githubusercontent.com/9645992/141674373-0901da7c-1f84-4fc1-8b3f-983a7e765a23.png">

**Comment by anhdle14** [comment]
```bash

fix-mosh () {
        local fw='/usr/libexec/ApplicationFirewall/socketfilterfw' 
        local mosh_sym="$(which mosh-server)" 
        local mosh_abs="$(greadlink -f $mosh_sym)" 
        sudo "$fw" --setglobalstate off
        sudo "$fw" --add "$mosh_sym"
        sudo "$fw" --unblockapp "$mosh_sym"
        sudo "$fw" --add "$mosh_abs"
        sudo "$fw" --unblockapp "$mosh_abs"
        sudo "$fw" --setglobalstate on
}
```

Disable firewall is not good and for macos fw they do not like symlink so the script is simply find the location of the source file and add that to the fw.

Just run it via SSH and exit back then run Mosh.

**Comment by arooni** [comment]
anyway to fix this without disabling the firewall on Mac OS Catalina?  Disabling the firewall does work but don't love to do that.

**Comment by anhdle14** [comment]
Maybe `launchctl`, you could also just make it persist in shell init.

**Comment by achernya** [comment]
Marking this as closed as it seems you have managed to get things to work.
