### ISSUE TITLE
mosh through pass, a font of airline|powerline isn't displayed on FreeBSD 12.1

### ISSUE THREAD

**Issue by kotashiratsuka** [mobile-shell/mosh#1075]
12.0R
<img width="507" alt="fb12" src="https://user-images.githubusercontent.com/1435951/68412618-e6c8d180-01cf-11ea-803c-61e20ecfa7de.PNG">

12.1R
<img width="522" alt="fb12 1" src="https://user-images.githubusercontent.com/1435951/68412625-e8929500-01cf-11ea-9117-aa1e46d2da17.PNG">

It was displayed correctly in 12.0.

12 and 12.1 were installed newly newly, and tried whether you recurred.

This phenomenon recurred by an upgrade to 12.1 and 12.1.

This problem doesn't form by 12.0R.

If it's in case of ssh, a problem doesn't occur.

**Comment by cromedome** [comment]
++ to this. I have noticed the same thing. When I ssh to my FreeBSD box, things look as intended, but when I connect via Mosh, I have similar display issues as indicated above.

I cannot speak to what versions of FreeBSD this started in, but I am running 12.1 STABLE at the present time.

**Comment by s-daveb** [comment]
This is happening to me too. Can't even see the powerline characters when i $ cat my .conf file in mosh.
Works perfectly fine in Linux and macOS.

**Comment by kotashiratsuka** [comment]
The problem was fixed in the recently released FreeBSD 13.0-RELEASE
