### ISSUE TITLE
mosh and auto-tmux don't love each other

### ISSUE THREAD

**Issue by stephane-archer** [mobile-shell/mosh#1076]
```
if command -v tmux 2>&1 > /dev/null && [ -z "$TMUX" ]; then
    tmux attach -t default || tmux new -s default
end
```
if I add this to my fish config file to start tmux automatically and then I try to connect with mosh I can see the tmux default session but I cannot type and interact with the application

**Comment by andersk** [comment]
Mosh needs to be able to use your shell noninteractively to start `mosh-server`, but if you configured your shell to automatically start an interactive command, it can’t do so. That configuration will break all kinds of other applications too. Don’t do that.

**Comment by stephane-archer** [comment]
How can I launch tmux automatically if it's an interactive session?

**Comment by eminence** [comment]
Try first checking if the shell is interactive.  I don't use fish, but a quick google suggests it looks something like:

```
if status --is-interactive
    if command -v tmux 2>&1 > /dev/null && [ -z "$TMUX" ]; then
        tmux attach -t default || tmux new -s default
    end
end
```

(You may also want to check to see if its a login shell, depending on your usecase)
