### ISSUE TITLE
[Question] Connect to remote mosh-server?

### ISSUE THREAD

**Issue by Merith-TK** [mobile-shell/mosh#1077]
So basically here i am, trying to SSH from my work. They have outgoing (out side of the network) SSH blocked. But i can use a VPN on my phone to get around this

If i run `mosh-server` on my phone, would i be able to connect to it from a client such as my laptop?

**Comment by dClauzel** [comment]
Yes, provided you also have a shell on your phone that mosh-server can spawn.
