### ISSUE TITLE
SIXEL graphics support

### ISSUE THREAD

**Issue by rongmu** [mobile-shell/mosh#1081]
SIXEL is an image format that allows high-quality image display in terminal.
For detailed information, check `libsixel` repo and Wikipedia:

- https://github.com/saitoha/libsixel
- https://en.wikipedia.org/wiki/Sixel

As shown in the comparison below, it seems that sixel graphics are supported by SSH but not mosh.
The terminal emulator tested with is [wsl-terminal](https://github.com/goreliu/wsl-terminal/) v0.8.13, which is based on [mintty](https://mintty.github.io/). On Linux, [mlterm](https://sourceforge.net/projects/mlterm/) also has sixel support out-of-the-box.

## SSH
![img2sixel-ssh](https://user-images.githubusercontent.com/1129506/69897760-9f2f0300-1393-11ea-88d2-7d221f1156f4.PNG)

## mosh
![img2sixel-mosh](https://user-images.githubusercontent.com/1129506/69897763-a81fd480-1393-11ea-96c5-374a85a7fecb.PNG)

**Comment by ebetica** [comment]
I can confirm this on xterm compiled with sixel support as well. Would be amazing to have this!

**Comment by achernya** [comment]
I'm afraid this feature request is extremely non-trivial. mosh's SSP (state synchronization protocol) would have to be substantially augmented to support large transfers of images. This is probably in the same amount of effort as port forwarding, or SSH agent support, in terms of the underlying features it requires.
