### ISSUE TITLE
MobaXterm Mosh client unable to connect to remote hosts with usage error...

### ISSUE THREAD

**Issue by tallship** [mobile-shell/mosh#1082]
When using MobaXterm's Mosh client on Windows 10/64 to connect to remote hosts I get the following, nondescript, usage error

```
/bin/moshsession usage:
  /bin/moshsession <server_name> <user_name> [<ssh_port_number> <locale> <Prediction_type> <mosh_server_command> <Mosh_ports_range> <Ssh_private_key>]
```

![moshfail2](https://user-images.githubusercontent.com/561994/70522240-9a85ef80-1af5-11ea-9fb5-e10b3ee648e5.png)

When attempting to connect to/from any UNIX host (Slackware, Debian 10, OpenBSD) from Bash or any other shell using my standard OpenSSh client with the following command line, I have no problem and everything works well:

```
mosh --ssh=\"ssh -p 50515\" -p 60050 username@hostname.sld.tld
```

Even trying to connect to a remote host from a UNIX VM within VirtualBox on my Windows workstation works as it should using the method above in Bash.

I've configured the advanced settings in the MobaXterm Mosh session manager to reflect the UDP port I want to connect to on the mosh-server as well as the (TCP) SSH port - in this case, 50515. It matters not whether I specify a UDP port to use when connecting to the mosh-server, or just leave it blank and accepting the default - I still cannot connect and receive the same usage message.

![mosh_fail](https://user-images.githubusercontent.com/561994/70522328-c3a68000-1af5-11ea-97a6-118e1c298179.png)

The only thing that  appears to make a difference is if I fill in the username field. If I leave it blank, I get the error above (as it appears in the screenie), if I fill in the username field, then nothing, it acts like it's waiting for a response from the server while it connects (like what you would receive during SSH session connection negotiations). It doesn't time out or anything.

My firewall ports for UDP 60000-61000 are open on my boxes that accept Mosh connections, etc., But I can't figure out why I can't connect via MobaXterm. Using MobaXterm to connect using SSH itself is no problem.

What am I doing wrong? Or what might I try to correct this issue?

**Comment by eminence** [comment]
`/bin/moshsession` is not a mosh script, so it must be from MobaXTerm.  Can you please ask the MobaXTerm team about this issue, as we cannot support these 3rd party programs.
