### ISSUE TITLE
is it possible to integration with https://github.com/jumpserver/jumpserver

### ISSUE THREAD

**Issue by hackrole** [mobile-shell/mosh#1083]
our company use jumpserver as a boston server.
but it was really slow while do some work in ssh,
I try to use mosh, but it seems need to install mosh in server , and I not certain if it can work with jumpserver, cause it is not a really ssh.

**Comment by achernya** [comment]
Unfortunately it seems https://github.com/jumpserver/jumpserver doesn't have any documentation I can find in a language I can read that explains how it works, so the following is entirely conjecture: I don't think it supports UDP pass-through, which would be required for mosh. Likely you'd need to file a feature request with the jumpserver folks.
