### ISSUE TITLE
Connects but no prompt

### ISSUE THREAD

**Issue by ndowens** [mobile-shell/mosh#1086]
I’ve tried to find why I connect fine but there is no shell prompt.  Locale is using en_US.UTF-8. If I connect using ssh I get a shell prompt

**Comment by eminence** [comment]
Do you see anything at all on your screen?  For both your server and your client, what version of mosh, what OS, and what terminal are you using?  And what's your shell on the server?

**Comment by ndowens** [comment]
Closing, as I just figured out what it was. It was a setting in elogind, KillUserProcess is on by default. Thanks for the quick response :)
