### ISSUE TITLE
Issues with 2FA

### ISSUE THREAD

**Issue by Yaff1e** [mobile-shell/mosh#1088]
I've just installed Mosh on my Ubuntu server. My SSH is set to use a key and also 2FA. When I try and connect to Mosh I get the 2FA prompt which accepts the code. I then get another 2FA prompt straight away. If I enter the (still current) code again it fails. I have to wait for the code to cycle before I enter the second code and then it works.

**Comment by eminence** [comment]
I don't understand what might be causing this.  Mosh only starts SSH once.   How is your 2FA configured?  What version of mosh are you using on the client?   Is it possible you have some wrapper scripts around `mosh` on the client that might be doing something unexpected?

**Comment by Yaff1e** [comment]
Apologies. I was using MobaXterm to access Mosh. I've just tried with Termius and JuiceSSH and I only get the one prompt so it appears to be an issue with MobaXterm.

**Comment by Yaff1e** [comment]
Just for completeness, I've since found out from their support that MobaXterm opens 2 SSH sessions. The first one is to autodetect the remote charset, the other is for the actual MOSH session. If you set the charset yourself then it only opens one session.
