### ISSUE TITLE
I want mosh-server to run all the time and use the same MOSH_KEY.

### ISSUE THREAD

**Issue by flying1574** [mobile-shell/mosh#1092]
I want mosh-server to run all the time and use the same MOSH_KEY. When I quit mosh-client, I do n’t want mosh-server to quit. What should I do? I want to use mosh like ssh

**Comment by eminence** [comment]
Hi.  This is not possible with mosh, as it's not possible to start a second mosh-client and have it connect to the first mosh-server.

Can you describe your use-case, and maybe we can come up with a solution?

**Comment by flying1574** [comment]
I am in Asia. I am using the American EC2 of AWS. Every time I connect, I have a special card. Later, I learned "mosh", I used it, indeed, it reduced the delay, but mosh server can't be used again after mosh client exits. If I want to use it again, I have to run mosh server again on EC2, which is very troublesome, so I want to log in with the same mosh_key as much as possible, and

**Comment by flying1574** [comment]
> 你好 对于mosh来说这是不可能的，因为不可能启动第二个mosh客户端并将其连接到第一个mosh服务器。
> 
> 您能否描述用例，也许我们可以提出解决方案？

I am in Asia. I am using the American EC2 of AWS. Every time I connect, I have a special card. Later, I learned "mosh", I used it, indeed, it reduced the delay, but mosh server can't be used again after mosh client exits. If I want to use it again, I have to run mosh server again on EC2, which is very troublesome, so I want to log in with the same mosh_key as much as possible, and I don't want to run mosh server every time, which is too inconvenient

**Comment by eminence** [comment]
Most people do not manually run mosh-server.  They just run `mosh user@server.com`.  The `mosh` script will automatically run mosh-server on the remote machine.  Is this not possible for you?

**Comment by flying1574** [comment]
> 大多数人不手动运行mosh-server。他们只是跑`mosh user@server.com`。该`mosh`脚本将自动在远程计算机上运行mosh-server。这对你来说不可能吗？

I don't know how to make it run automatically, and if you run mosh server again, it will regenerate mosh_key. Can you tell me the specific operation

**Comment by eminence** [comment]
The way to run `mosh-server` automatically is to use the "[mosh](https://github.com/mobile-shell/mosh/blob/master/scripts/mosh.pl)" command.  Have you tried it?  Is it giving you some errors?

**Comment by flying1574** [comment]
> `mosh-server`自动运行的方法是使用“ [mosh](https://github.com/mobile-shell/mosh/blob/master/scripts/mosh.pl) ”命令。你试过了吗？它给你一些错误吗？

How to make mosh server run automatically? I don't know mosh. I only knew it yesterday. Can you tell me the specific operation

**Comment by flying1574** [comment]
> `mosh-server`自动运行的方法是使用“ [mosh](https://github.com/mobile-shell/mosh/blob/master/scripts/mosh.pl) ”命令。你试过了吗？它给你一些错误吗？

May I have your contact information? Or email, I would like to contact you through other ways

**Comment by flying1574** [comment]
> The way to run `mosh-server` automatically is to use the "[mosh](https://github.com/mobile-shell/mosh/blob/master/scripts/mosh.pl)" command. Have you tried it? Is it giving you some errors?

Thank you. When I change a Ubuntu server and run "mosh Ubuntu @ IPAddress", it will work normally. Thank you

**Comment by eminence** [comment]
I think your question has been answered/solved, so I'm going to close this issue.  Let me know if you have additional questions.
