### ISSUE TITLE
mosh `w3mimageviewer` support

### ISSUE THREAD

**Issue by ryanerwin** [mobile-shell/mosh#1093]
When running `w3m xkcd.com` inside an Xterm, connected to SSH, inside Tmux, each link of the chain works fine and I can see the images from the xkcd page displayed in the terminal.

Unfortunately, when I use `mosh`, inside of a known working Xterm, I'm unable to get the images to display at all...

![image](https://user-images.githubusercontent.com/2156415/77999943-aa079d80-735d-11ea-83ed-bd9dd6600779.png)

There was previously a feature request #1081 related to `libsixel` but this does not seem to use libsixel as I don't see that linked to w3m or w3mimgagedisplay... Yet the Xterm Change Log does talk about introducing "ReGIS/Sixel modules" all the way back in May 2014, Patch 304, so however the graphics support works it does appear to be quite mature...

https://invisible-island.net/xterm/xterm.log.html

```
 ❯ ldd /usr/lib/w3m/w3mimgdisplay
	linux-vdso.so.1 (0x00007ffefa503000)
	libX11.so.6 => /lib/x86_64-linux-gnu/libX11.so.6 (0x00007f4661245000)
	libImlib2.so.1 => /lib/x86_64-linux-gnu/libImlib2.so.1 (0x00007f4660fe1000)
	libc.so.6 => /lib/x86_64-linux-gnu/libc.so.6 (0x00007f4660df0000)
	libxcb.so.1 => /lib/x86_64-linux-gnu/libxcb.so.1 (0x00007f4660dc7000)
	libdl.so.2 => /lib/x86_64-linux-gnu/libdl.so.2 (0x00007f4660dc1000)
	libfreetype.so.6 => /lib/x86_64-linux-gnu/libfreetype.so.6 (0x00007f4660d06000)
	libm.so.6 => /lib/x86_64-linux-gnu/libm.so.6 (0x00007f4660bb5000)
	libXext.so.6 => /lib/x86_64-linux-gnu/libXext.so.6 (0x00007f4660ba0000)
	libX11-xcb.so.1 => /lib/x86_64-linux-gnu/libX11-xcb.so.1 (0x00007f4660b9b000)
	libxcb-shm.so.0 => /lib/x86_64-linux-gnu/libxcb-shm.so.0 (0x00007f4660b96000)
	/lib64/ld-linux-x86-64.so.2 (0x00007f46613af000)
	libXau.so.6 => /lib/x86_64-linux-gnu/libXau.so.6 (0x00007f4660b90000)
	libXdmcp.so.6 => /lib/x86_64-linux-gnu/libXdmcp.so.6 (0x00007f4660b88000)
	libpng16.so.16 => /lib/x86_64-linux-gnu/libpng16.so.16 (0x00007f4660b4e000)
	libz.so.1 => /lib/x86_64-linux-gnu/libz.so.1 (0x00007f4660b32000)
	libbsd.so.0 => /lib/x86_64-linux-gnu/libbsd.so.0 (0x00007f4660b18000)
```

```
 ❯ ldd `which w3m`
	linux-vdso.so.1 (0x00007fffec3ae000)
	libm.so.6 => /lib/x86_64-linux-gnu/libm.so.6 (0x00007f5eb92fa000)
	libgc.so.1 => /lib/x86_64-linux-gnu/libgc.so.1 (0x00007f5eb9289000)
	libssl.so.1.1 => /lib/x86_64-linux-gnu/libssl.so.1.1 (0x00007f5eb91f7000)
	libcrypto.so.1.1 => /lib/x86_64-linux-gnu/libcrypto.so.1.1 (0x00007f5eb8f22000)
	libgpm.so.2 => /lib/x86_64-linux-gnu/libgpm.so.2 (0x00007f5eb8d1c000)
	libtinfo.so.6 => /lib/x86_64-linux-gnu/libtinfo.so.6 (0x00007f5eb8cec000)
	libc.so.6 => /lib/x86_64-linux-gnu/libc.so.6 (0x00007f5eb8af9000)
	/lib64/ld-linux-x86-64.so.2 (0x00007f5eb95dd000)
	libpthread.so.0 => /lib/x86_64-linux-gnu/libpthread.so.0 (0x00007f5eb8ad6000)
	libdl.so.2 => /lib/x86_64-linux-gnu/libdl.so.2 (0x00007f5eb8ad0000)
```

**Comment by cgull** [comment]
Mosh doesn't pass the entire stream of characters fed to the terminal, instead it sends what's necessary to display a screen of text at a given moment in time.  It doesn't support full xterm/VT100 functionality, let alone SIXEL/Regis.  Unless somebody makes quite a large effort to make Mosh support SIXEL/Regis, this is unlikely to ever work.  Sorry.
