### ISSUE TITLE
locale issues - tips to troubleshoot?

### ISSUE THREAD

**Issue by damnskippy** [mobile-shell/mosh#1096]
Using latest sources off the github repo.  Been fighting with locale errors without much luck after trying a whole bunch of things.  Seems it would be good if there's a cheat sheet to trouble shoot?  Some steps to troubleshoot would be helpful, check for a,b,c.  on the client and x,y,z on the server side.  Do this if you see this vs that, etc.  Or some type of a "fallback" to get things to work?  

Part of my problem is that I don't have sudo access on the server host, but I do have control on the client side.

Release version (1.3.2) works fine between the same client & server, probably because it's not much of stickler regarding locale.  I do want to use the latest sources as it supports truecolor.

Any suggestions?

**Comment by keithw** [comment]
Please paste the full error message you are getting and we can help you debug. And please let us know what platform (OS, etc.) you are using as the client and as the server. Honestly I don't think the Git version is any more strict about this than 1.3.2. But let's see the error messages and maybe we can help. (We put a lot of work into those error messages!)

**Comment by damnskippy** [comment]
Thanks very much for offering to help.

Client: wsl, Ubuntu 18.04
```
$ locale -a
C
C.UTF-8
en_US.utf8
POSIX
```
Server: Ubuntu 16.04
```
$ locale -a
C
C.UTF-8
en_US
en_US.iso88591
en_US.utf8
POSIX
```
Error message seen when connecting to remotehost below.  Unfortunately I don't have admin privileges on the remotehost, so I'm not able to modify any of the host settings.  Running this from the compiled sources directly (both `scripts `& `src/frontend `added to $PATH) - haven't done a make install yet until I can figure this out.

```
$ mosh --server=/homes/ds/mosh/wsl/mosh-server remotehost
The locale requested by LC_ALL=en_US.UTF-8 isn't available here.
Running `locale-gen en_US.UTF-8' may be necessary.

The locale requested by LC_ALL=en_US.UTF-8 isn't available here.
Running `locale-gen en_US.UTF-8' may be necessary.

mosh-server needs a UTF-8 native locale to run.

Unfortunately, the local environment (LC_ALL=en_US.UTF-8) specifies
the character set "US-ASCII",

The client-supplied environment (LC_ALL=en_US.UTF-8) specifies
the character set "US-ASCII".

LANG=en_US.UTF-8
LANGUAGE=en_US.UTF-8
LC_CTYPE="en_US.UTF-8"
LC_NUMERIC="en_US.UTF-8"
LC_TIME="en_US.UTF-8"
LC_COLLATE="en_US.UTF-8"
LC_MONETARY="en_US.UTF-8"
LC_MESSAGES="en_US.UTF-8"
LC_PAPER="en_US.UTF-8"
LC_NAME="en_US.UTF-8"
LC_ADDRESS="en_US.UTF-8"
LC_TELEPHONE="en_US.UTF-8"
LC_MEASUREMENT="en_US.UTF-8"
LC_IDENTIFICATION="en_US.UTF-8"
LC_ALL=en_US.UTF-8
Connection to remotehost closed.
/home/ds/mosh/scripts/mosh: Did not find mosh server startup message. (Have you installed mosh on your server?)

```
Somehow v1.3.2 installed via apt-get works like a charm between the same client and the server.  It's possible I'm doing something stupid that isn't apparent to me (yet).  I've tried playing with setting several of these LC_ variables in my env on both client/server, logging in/out, etc. to no avail.

**Comment by keithw** [comment]
Just to make sure I understand, are your client and server **both** running Windows (wsl)? You describe the server as "Ubuntu 16.04" but you're trying to run a mosh-server binary in the directory "/homes/ds/mosh/wsl/" ?

What is setting LC_ALL on your client? (Normally this is a brute-force instrument that shouldn't be anybody's default...) Does it work any differently if you unset LC_ALL, or set it to "en_US.utf8"?

We haven't changed much between 1.3.2 and master related to locale strictness, so I'm surprised it makes a difference. If you have time to bisect, we'd love to have a culprit commit!

**Comment by damnskippy** [comment]
Server is plain native Ubuntu 16.04.  Only the client is WSL.
LC_ALL is just me trying it to brute-force to get this to work.  Unsetting it (as it was to begin with) has the same result (doesn't work), so does setting it to "en_US.utf8".
I will try to bisect when I get a window to work on this (a bit spread too thin at the moment).

I cannot quite tell from the error message why it's not picking up the en_UTF8 from the locale.  It seems from the output of `locale -a` that both client and server support the char set.

**Comment by magikmw** [comment]
@damnskippy Hi, did you happen to work out this issue? Used to work great with Ubuntu 18.04 WSL image, but it's presenting the same character set errors on Ubuntu 20.04 WSL image.
