### ISSUE TITLE
mosh disconnects after network has been down for a long time

### ISSUE THREAD

**Issue by vegardsjo** [mobile-shell/mosh#1098]
I have a setup using two network adapters (net0, net1) connected to different networks, only one of them active at the same time.

mosh is connected to a server through net1. When bringing down net1 and switching to net0, the countdown timer is not show, and, after considerable time, it disconnects with the following output to the terminal:

```client_loop: send disconnect: Broken pipe```

 If I switch back to net1 within this timeout, the mosh session is still valid.

Is this correct behavior, and, if so, is it possible to extend this timeout indefinitely?

I'm running mosh version 1.3.2

**Comment by keithw** [comment]
That isn't a Mosh error message -- "client_loop: send disconnect: Broken pipe" is what you would get from OpenSSH's ssh client.

Are you sure you're using Mosh...? How are you connecting?

**Comment by vegardsjo** [comment]
You're absolutely right, and I feel stupid now :sweat_smile:. I was experimenting using ssh as an alias for mosh for a long time, and when I turned it off, I guess I forgot that it wasn't mosh anymore ...

**Comment by keithw** [comment]
:-) Glad you solved it!
