### ISSUE TITLE
Trying to mosh to server through mosh for chrome in windows but didn't find any luck please help

### ISSUE THREAD

**Issue by bhavnish07** [mobile-shell/mosh#1100]
mosh did not make a successful connection to 34.94.141.86:60004.

Please verify that UDP port 60004 is not firewalled and can reach the server.

(By default, mosh uses a UDP port between 60000 and 61000. The -p option

selects a specific UDP port number.)

[mosh is exiting.]

Mosh has exited.
Press "x" to close the window.

**Comment by eminence** [comment]
Hi.  Are there any firewalls between the client machine and the server machine?   If so, have you opened the necessary UDP ports?
