### ISSUE TITLE
Can't query "tmux ls" in inital mosh command?

### ISSUE THREAD

**Issue by ryanerwin** [mobile-shell/mosh#1102]
When I run `tmux ls` via ssh, I get the expected result:

```
 ❯ ssh example.com tmux ls
no server running on /tmp/tmux-1000/default
```

However, when I run the same command via mosh, I do not receive the expected output:
```
 ❯ mosh example.com tmux ls


[mosh is exiting.]
```

Note that this behaviour for `mosh example.com tmux ls` vs `ssh example.com tmux ls` is actually consistent across several versions of mosh that I tried, **INCLUDING** versions where the script below does actually work as expected, but I don't really understand what's happening in this situation well enough to describe it better.

Typically when I run mosh, I actually launch a remote script `tmux-attach-or-new.sh`:
```
#!/bin/bash
tmux attach -t $(tmux ls | grep -v attached | head -1 | cut -f1 -d:) || tmux
```

I think there may be a change in a recent version of mosh that prevents this script from working as it used to...

Client and server not working are both Ubuntu 20.04, tmux 3.0a, mosh v1.3.2.
Yet the script works `tmux-attach-or-new.sh` script works fine on Ubuntu 18.04 with tmux 2.6 and mosh v1.3.2

**Comment by renatofrota** [comment]
`mosh example.com --no-init tmux ls`

**Comment by ryanerwin** [comment]
Thank you @renatofrota , that did fix it for me!

For anyone else not familiar with this one:

```
       --no-init
              Do not send the smcup initialization string and rmcup deinitial‐
              ization string to the client's terminal. On many terminals  this
              disables alternate screen mode.
```

**Comment by eminence** [comment]
While using `--no-init` will work for scripts with small output (like `tmux ls`), I would like to remind everyone that this is not a general solution.  It will do something unexpected as soon as you run a command that produces multiple pages of output, or find yourself on a network with different network latencies.

If you want to run a non-interactive command on a remote system, you really ought to use `ssh`.

Regarding your `tmux-attach-or-new.sh` script, this looks fine to me, since you're running it on the remote system.   It's not clear to me why it wouldn't be working, or why `mosh --no-init` would have an impact on it.  Can you clarify how you're running this script?

**Comment by ryanerwin** [comment]
>  Can you clarify how you're running this script?

I always use mosh with tmux, so if I have a little mosh wrapper that will rename the current tmux tab if tmux is running. If tmux isn't running, then see if the remote side has a tmux to attach to, if not launch a new tmux on the remote side.

So basically I end up running:
```
/usr/bin/mosh --port 8000:8100 example.host ~/Dotfiles/bin/tmux-attach-or-new.sh
```

Content of `~/Dotfiles/bin/tmux-attach-or-new.sh`
```
#!/bin/bash

tmux attach -t $(tmux ls | grep -v attached | head -1 | cut -f1 -d:) || tmux
```

<details>
<summary>full mosh wrapper script</summary>

```
// if running on termux for android, use mosh.pl instead
if (( $+commands[termux-setup-storage])); then
  alias mosh_w_port='mosh.pl --port 8000:8100'
else
  alias mosh_w_port='/usr/bin/mosh --port 8000:8100'
fi
mosh() {
    if [ -n "$TMUX" ]; then
        tmux rename-window "$(echo $* | cut -d . -f 1,2)";
        mosh_w_port "$@";
        tmux set-window-option automatic-rename "on" 1>/dev/null;
    else
        # Since TMUX isn't running, let's launch it
        printf "\033kMOSH $(echo $* | cut -d . -f 1,2)\033\\"
        mosh_w_port "$@" --no-init ~/Dotfiles/bin/tmux-attach-or-new.sh;
    fi
}

```

</details>

The `--no-init` is a line that I added recently due to this ticket... Without that line the command just exits without launching the remote tmux:

```
 ❯ /usr/bin/mosh --port 8000:8100 example.host ~/Dotfiles/bin/tmux-attach-or-new.sh


[mosh is exiting.]

```

**Comment by eminence** [comment]
I'm afraid I cannot reproduce the issue.  I'm using mosh 1.3.2 on both client and server, and tmux 2.8 on the server.  Running `mosh example.host tmux-attach-or-new.sh` is working fine for me, without needed to use `--no-init`
