### ISSUE TITLE
Reboot awareness and automatic reconnection?

### ISSUE THREAD

**Issue by deed02392** [mobile-shell/mosh#1105]
Just did a `sudo reboot` and the session closed, made me think wouldn't it be nice if `mosh` could detect a system reboot and negotiate resuming the session under the same parameters once the server is back up?

**Comment by eminence** [comment]
I doubt mosh will ever have this feature.  It is tricky for many reasons (like how to detect a reboot, how to handle credentials, what to do about the internal crypto state), but not a lot of benefits.    

You could probably emulate this yourself with passwordless ssh-keys and a client-side script to automatically re-launch mosh when the client exits.
