### ISSUE TITLE
Vim exit still show file content after mosh installed

### ISSUE THREAD

**Issue by cshanbo** [mobile-shell/mosh#1106]
Hi Mosh team,
Thank you all for developing such a great tool.
Following steps is what I did:
- Install `mosh` on my remote server (Debian) and my laptop (Mac OS)
- Logging remote server via `mosh user_name@ip`
- vim a file and exit
   - the screen still shows the file content
- Uninstall `mosh` and re-login, the above vim issue fixed. 
Hope someone could help, thanks 

```
Distributor ID:	Debian
Description:	Debian GNU/Linux 9.12 (stretch)
Release:	9.12
Codename:	stretch
```

**Comment by keithw** [comment]
Mosh doesn't support the "alternate screen" part of the xterm terminal spec, so everything is just on the same screen. The screen isn't corrupted, it just doesn't maintain two screens and flip between them. This is unlikely to be changed anytime soon. (You don't have to uninstall Mosh to get the normal behavior, though -- you can always just use SSH if you want. Or you can use Mosh and then use tmux on the remote host.)
