### ISSUE TITLE
"Operation not permitted", adding SSH to Full Disk access in MacOS Mojave works but MOSH does not.

### ISSUE THREAD

**Issue by Kezzsim** [mobile-shell/mosh#1113]
I like to use MOSH to administer my home server remotely, and security is less of a concern because I have access locked down to only a handful of personal clients via ssh keys.

I intend to keep SIP turned on for my home system since it has other security benefits, but I need to give MOSH full disk access like I can for SSH. I've added every MOSH executable I could find to the permissions list like so:
<img width="423" alt="Screen Shot 2020-09-21 at 11 15 07 AM" src="https://user-images.githubusercontent.com/15878154/93785278-e5dc3b00-fbfb-11ea-9b50-6c33652f999e.png">

However, when I attempt to access something on the disk over MOSH, I still get denied:
`╰─ ls ~/Library/Messages
ls: Messages: Operation not permitted`

Versus over SSH where the operation just magically works:
```
$ ls ~/Library/Messages
Archive		chat.db		chat.db-wal	prewarm.db-shm
Attachments	chat.db-shm	prewarm.db	prewarm.db-wal
```

Any suggestions? As far as I know I've done everything right, I've even restarted the machine as a sanity check.
Is there a MOSH daemon somewhere else that should be in this list instead?

**Comment by zi0r** [comment]
Run Terminal.app and then ps auxw|grep mosh to verify you have the correct path(s) for the mosh-server you are running.

**Comment by zi0r** [comment]
Once you have the path, also try:
`sudo xattr -r -d com.apple.quarantine /path/to/mosh-server`

**Comment by Harwood** [comment]
You'll only need `mosh-server` added to Full Disk Access. If still unable to access `~/Library/Messages` it might be worth a try to add `mosh-server` under Developer Tools.
