### ISSUE TITLE
Nothing received from server problem.

### ISSUE THREAD

**Issue by 94JuHo** [mobile-shell/mosh#1114]
Hi,
I recently learned about Mosh, and I really want to use it. 
However, I have a problem. Because my server computer is at university, external access ports allow only two ports. 
So I was connecting to ssh on port 80, and I tried to connect using the Mosh -P option, but there was a 60001 port error. 
How can I solve this problem?
Thank you.

**Comment by 94JuHo** [comment]
I checked that the connection was normal when I executed the following command on my server.

```
mosh --ssh="ssh -p (ssh port)" name@serverIP
```

but, If I run the command through the blink app on the iPad, it shows a help phrase that says --ssh command cannot be used.
How can I fix it?

**Comment by 94JuHo** [comment]
I found a solution for myself.
The solutions are as follows.
The blink app basically reads the ~/.ssh/config file.

```
1. sudo gedit ~/.ssh/config
2. Input Port (Your ssh port, in my case 80)
3. In the blink app, mosh -P (your ssh port, in my case 80) name@serverIP
```
I hope my experience will help others as well.

**Comment by andersk** [comment]
Blink is a [separate project](https://github.com/blinksh/blink) with separate maintainers. Mosh does not have a `-P` option; that appears to be Blink-specific.

**Comment by 94JuHo** [comment]
> Blink is a [separate project](https://github.com/blinksh/blink) with separate maintainers. Mosh does not have a `-P` option; that appears to be Blink-specific.

yes, i know.
but, When I received the first error message, I thought it was a Mosh udp port problem
so I wrote an issue here.
Thank you for your response.
