### ISSUE TITLE
ubuntu -> mac, blink -> mac, mosh not working. just run zsh

### ISSUE THREAD

**Issue by XIYO** [mobile-shell/mosh#1117]
Hello. I am not good at English so I use a translator. Sorry.
I installed mosh on Mac Catalina using brew.
I installed mosh on ubuntu 20.04.

I also installed blink on iOS.

The first attempt connected mosh from mac to ubuntu.
Works fine.
mac -> ubuntu = sucess
> mosh --ssh="ssh -p 22" ubuntu@192.168.1.150
[or]
> mosh ubuntu@192.168.1.150

Second, I can't connect from Ubuntu to Mac.
ubuntu -> mac = fail
> mosh --ssh="ssh -p 22" mac@192.168.1.151

This code fails.
[error]
>zsh:1: command not found: mosh-server
Connection to 192.168.1.12 closed.
/usr/bin/mosh: Did not find mosh server startup message. (Have you installed mosh on your server?)

The reason it fails is that mosh-server is not in /usr/bin on Mac.
It must be specified forcibly.
So I modified the code a bit.
> mosh --ssh="ssh -p 22" --server="/usr/local/bin/mosh-server" mac@192.168.1.151
[or]
> mosh --ssh="ssh -p 22" --server="/usr/local/bin/mosh-server" --client="/usr/bin/mosh-client" mac@192.168.1.151

Both of these codes are accessible. But ZSH runs.

Finally, I tried connecting from BLINK.
[CODE]
> mosh -P 22 --server="/usr/local/bin/mosh-server" mac@192.168.1.151
Still not.

I have several questions.

1. Why isn't mosh installed in /usr/bin for mosh installed on Mac?
2. Typing whereis mosh on Mac doesn't return location. Still, how is the mosh command executed?
3. I ran into a locale problem on a Mac. Solved by using 
> export LC_ALL=ko_KR.UTF-8. 

But why doesn't Mac have locale? Is the default null?

**Comment by berot3** [comment]
Hi @XIYO I have the same problem. It says:

zsh:1: command not found: mosh-server
Could not start mosh-server.

What can I do?
