### ISSUE TITLE
mosh crashes with fqdn on ubuntu20.10

### ISSUE THREAD

**Issue by sterni1971** [mobile-shell/mosh#1120]
Hi!

strange bug

~ $ mosh foo.domain.name
malloc_consolidate(): unaligned fastbin chunk detected
/usr/bin/mosh: Did not find mosh server startup message. (Have you installed mosh on your server?)

BUT this works!
~ $ mosh foo 

I hunt the bug to the line 263

    if ( $sock = IO::Socket->new( Domain => $ai->{family},
                                  Family => $ai->{family},
                                  PeerHost => $addr_string,
                                  PeerPort => $port,
                                  Proto => 'tcp' )) {

but the parameters here don't change if I switch from hostname to fqdn ?????

**Comment by eminence** [comment]
Some good debugging hints, other info and a workaround is in #1138.  If it's the same issue, then this is an openssh [bug](https://www.mail-archive.com/openssh-bugs@mindrot.org/msg14937.html). -- Can you please check that issue for details.
