### ISSUE TITLE
Apple Silicon Arm Support

### ISSUE THREAD

**Issue by etmartinkazoo** [mobile-shell/mosh#1121]
Are there any plans to support Apple's M1 Arm processors?

**Comment by keithw** [comment]
Hmm, what would we have to do? My assumption is that HomeBrew (and MacPorts?) will continue to work without us having to do anything. With the change in policy at Travis-CI, I'm not sure we have a great way to auto-build on Mac anymore, unfortunately.

**Comment by etmartinkazoo** [comment]
@keithw - Unfortunately I'm not sure how you would go about making Mosh compatible for Arm/Apple Silicon. I am a Python developer so I don't know how much assistance I would be as I imagine Mosh is written in a lower level language like C or C++.

Apple has documentation for porting apps [here](https://developer.apple.com/documentation/xcode/porting_your_macos_apps_to_apple_silicon) which may be helpful.

**Comment by andersk** [comment]
The first question is, does it not work already? Mosh is written in a reasonably portable way and I would expect it to work as well as it does on macOS x86-64. Have you tried it?

**Comment by etmartinkazoo** [comment]
It can run with Apple's Rosetta Translation Environment but not natively on Arm/Apple Silicon.

<img width="544" alt="mosh-arm" src="https://user-images.githubusercontent.com/13721164/99480766-c1b08800-2926-11eb-9158-57879a9f7aec.png">

**Comment by andersk** [comment]
You’re looking at a specific x86-64 binary. Have you tried building Mosh from source?

**Comment by etmartinkazoo** [comment]
It is still not possible to build Protocol Buffers. I've opened an issue [here](https://github.com/protocolbuffers/protobuf/issues/8062). Once that is resolved it should be possible to build Mosh from source.

**Comment by andersk** [comment]
Your protobuf issue is, again, about a specific binary—this time a Linux binary, which will definitely not run on macOS. You’ll need to build protobuf from source too.

**Comment by coder543** [comment]
For what it's worth, I just tested `mosh` on an M1 MacBook Air. It worked perfectly fine. I simply did `brew install -s mosh` to install it. (And to be extra clear, my `brew` is not running inside Rosetta -- this is running natively.)
