### ISSUE TITLE
mosh does not work at all

### ISSUE THREAD

**Issue by dalisoft** [mobile-shell/mosh#1123]
Hi @mobile-shell/mosh developer team.

## Description

Thanks for such useful tool (i think), but it does not work.

## System

- macOS 10.15.7

## Reproduction

1. `brew install mosh` 
2. `mosh-server` in Terminal first tab
3. `mosh localhost` in Terminal second tab
4. Error

## Logs

```bash
❯ mosh 127.0.0.1
Password:
fish: Unknown command: mosh-server
fish: 
mosh-server 'new' '-c' '256' '-s' '-l' 'LC_CTYPE=UTF-8'
^
Connection to 127.0.0.1 closed.
/usr/local/bin/mosh: Did not find mosh server startup message. (Have you installed mosh on your server?)

~ took 2s 
❯ mosh dalisoft@127.0.0.1 --experimental-remote-ip=local
Password:
fish: Unknown command: mosh-server
fish: 
mosh-server 'new' '-c' '256' '-s' '-l' 'LC_CTYPE=UTF-8'
^
Connection to 127.0.0.1 closed.
/usr/local/bin/mosh: Did not find mosh server startup message. (Have you installed mosh on your server?)

~ took 2s 
❯ mosh dalisoft@127.0.0.1
Password:
fish: Unknown command: mosh-server
fish: 
mosh-server 'new' '-c' '256' '-s' '-l' 'LC_CTYPE=UTF-8'
^
Connection to 127.0.0.1 closed.
/usr/local/bin/mosh: Did not find mosh server startup message. (Have you installed mosh on your server?)

~ took 5s 
❯ 

```

## Additional information

Seems `mosh --local 127.0.0.1` like a working, but when tried to connect Linux, it errors, so tried to connect localhost, fails.

With SSH connects to localhost without any issue

**Comment by eminence** [comment]
Hi, I think there are two things going on here:

1.  Homebrew is probably installing `mosh-server` into `/usr/local/opt` or some other folder that's not in your path.  Can you find the full-path to `mosh-server` and then try running:

        mosh --server=/full/path/mosh-server 127.0.0.1


2. Under normal circumstances, you do not manually run `mosh-server` (which I think you are doing in step (2) of your reproduction steps).   The `mosh` script takes care of this for you.

**Comment by dalisoft** [comment]
@eminence 

Thanks for reply.

1. I'm tested and `mosh` in correct path (as described in docs at least)

```bash
~ 
❯ which mosh -a
/usr/local/bin/mosh

~ 
❯ 
```

2. I tried, after some fails, tried run `mosh-server` manually and it's did not help

**Comment by dalisoft** [comment]
@eminence 

`mosh --server=/usr/local/bin/mosh-server 127.0.0.1` does work but `mosh 127.0.0.1` not. Can i somehow make it work as default?

Thanks

**Comment by eminence** [comment]
Please double check your `$PATH`, in particular it may be set differently depending on if you have an interactive login or not.  For example, try this:

    ssh -n -tt 127.0.0.1 printenv PATH

Does this container `/usr/local/bin` ?

**Comment by dalisoft** [comment]
@eminence I ran command and got this result, it is correct result?

```bash
❯ ssh -n -tt 127.0.0.1 printenv PATH
Password:
/Users/dalisoft/lsp/bin:/Users/dalisoft/.cargo/bin:/Users/dalisoft/go/bin:/Users/dalisoft/.npm-global/bin:/sbin:/bin:/Users/dalisoft/Library/Android/sdk/platform-tools:/Users/dalisoft/Library/Android/sdk/tools/bin:/Users/dalisoft/Library/Android/sdk/tools:/Users/dalisoft/Library/Android/sdk/emulator:/Users/dalisoft/.cargo/bin:/Users/dalisoft/go/bin:/Users/dalisoft/.npm-global/bin:/usr/local/opt/openssl@1.1/bin:/usr/local/opt/fzf/bin:/usr/bin:/bin:/usr/sbin:/sbin
Connection to 127.0.0.1 closed.

~ via ⬢ v15.3.0 took 3s 
❯ 
```

**Comment by eminence** [comment]
No, that doesn't look correct, because I don't see `/usr/local/bin` in that $PATH (and you told me that your `mosh-server` binary is installed into `/usr/local/bin`)

**Comment by dalisoft** [comment]
@eminence Thanks, after adding `/usr/local/bin` to `PATH`, my issue was fixed. Thanks a lot
