### ISSUE TITLE
mosh-server exiting unexpectedly

### ISSUE THREAD

**Issue by ppattard** [mobile-shell/mosh#1131]
Hello,

I'm having a (new) weird issue with mosh on a fresh Manjaro install (based on Arch). I've been using mosh on this distrib for years without issue. But it seems something has changed in the distrib and I can't figure what. Mosh does not work at all when connecting to the machine, I get the classical error message "Nothing received from server on UDP port 60001" as if it was firewalled. But there is no firewall activated by default. Instead, I noticed that mosh-server is not running within the next 10s after the connection attempt.

I've tried several things unsuccessfully to debug the issue, and would need your help:
- Reproduced the issue on a fresh install in a VM, so problem is not linked to my install
- Tried from different source machines => same issue
- Tried to change shell as I use fish usually which is not very standard, but even the default zsh leads to the issue
- Tried to manually run "mosh-server new -v" and connect to it with mosh-client => this works fine
- Tried the local mode => this works as well
- Tried to run the exact same command to start the server that mosh script is running (mosh-server new -c 256 -s etc) => no crash observed
- I even tried to alter the mosh script to add a "&& sleep 60", and clearly it shows that the process dies when the SSH connection closes

Note that from time to time I get the motd displayed and shortly after the connection hangs.

Any clue how I could progress further in diagnosing the issue ?

Thanks.

**Comment by ppattard** [comment]
Actually it seems the issue is with openssh itself, not mosh. Right now even a command started with nohup and disowned gets killed upon ssh connection closure. I tested this to work with previous versions. Hence closing this ticket.

**Comment by andersk** [comment]
This may be the same as #730.

**Comment by ppattard** [comment]
> This may be the same as #730.

Hello, I don't know if it is the same issue or not (the ticket is opened since 2016, and I've been experiencing this issue with Arch only since a few days), but at least the solution proposed works perfectly fine !! So using an alias to "mosh --server 'systemd-run --scope --user mosh-server'". Thank you!!
