### ISSUE TITLE
Current master does not work between macos (client) and Ubuntu 16.04 (server)

### ISSUE THREAD

**Issue by themightyoarfish** [mobile-shell/mosh#1133]
On macOS, I ran `brew install --HEAD mosh`. On the server I compiled from source as per the website's instructions.

Trying to connect to server:
```
[libprotobuf FATAL google/protobuf/generated_message_util.cc:818] CHECK failed: (scc->visit_status.load(std::memory_order_relaxed)) == (SCCInfoBase::kRunning):
terminate called after throwing an instance of 'google::protobuf::FatalException'
  what():  CHECK failed: (scc->visit_status.load(std::memory_order_relaxed)) == (SCCInfoBase::kRunning):
Connection to my-server closed.
/usr/local/bin/mosh: Did not find mosh server startup message. (Have you installed mosh on your server?)
```
Protobuf version is 3.9.0

**Comment by keithw** [comment]
This is probably a problem with your homebrew installation of protobuf and
unrelated to mosh. Homebrew's handling of dependencies is pretty
lightweight and they tend to sometimes cause bugs that resemble this. It
appears to be a protobuf internal error. Please try reinstalling protobuf
(on the client) and then rebuilding mosh.

**Comment by themightyoarfish** [comment]
Protobuf I have installed from source anyway, maybe that is the issue, that homebrew compiles against its own version but at runtime resolves differently.

**Comment by themightyoarfish** [comment]
However, compiling manually (autogen, configure, make install) on both systems after removing brew protobuf (I can see it uses my install in `/usr/local/`) exhibits the same problem, so it must be something else.

**Comment by themightyoarfish** [comment]
Setting `CFLAGS` and `LDFLAGS` according to https://github.com/protocolbuffers/protobuf/blob/master/src/README.md#c-installation---unix does not change the outcome by the way.

**Comment by themightyoarfish** [comment]
It also happens when I use the brew binary install client (which also seems to be 1.3.2, so same version) with the source install server.

**Comment by themightyoarfish** [comment]
Solution: Manually compile on both systems and use these flags (not sure what of this is relevant, but this worked).

Mac:
```
./configure CXXFLAGS="$(pkg-config --cflags protobuf)"           LIBS="$(pkg-config --libs protobuf)" --disable-shared
```

Ubuntu 16.04:
```
./configure CXXFLAGS="$(pkg-config --cflags protobuf)"           LIBS="$(pkg-config --libs protobuf)" CXX=g++-9 --disable-shared
```
The default compiler lead to errors as `-std=c++11` is apparently not used by mosh, which is needed to support C++11 on older gcc. So ensure you have a current one installed.
