### ISSUE TITLE
Fatal assertion when exit on macos big sur

### ISSUE THREAD

**Issue by knightdf** [mobile-shell/mosh#1139]
When exiting mosh from remote server, a fatal error occur, although it seems having no bad effect:

```
Fatal assertion failure in function ~Socket at network.cc:650
Failed test: close( _fd ) == 0
[1]    7654 abort      mosh --ssh="ssh -i ~/.ssh/xxx" user@host
```

Mosh version:

```
> mosh -version
mosh 1.3.2 [build mosh 1.3.2]
Copyright 2012 Keith Winstein <mosh-devel@mit.edu>
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>.
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.
```

OS version:
`Big Sur 11.3.1`

**Comment by eminence** [comment]
Did this issue happen only once, or has it happened repeatedly?  If it only happened once, I don't think it's worth holding open this issue.

**Comment by knightdf** [comment]
> Did this issue happen only once, or has it happened repeatedly? If it only happened once, I don't think it's worth holding open this issue.

Happens every time, and not any more in Big sur v11.6.

**Comment by eminence** [comment]
Ok, thanks for the info!
