### ISSUE TITLE
display glitch with my zsh prompt

### ISSUE THREAD

**Issue by RonnyPfannschmidt** [mobile-shell/mosh#115]
mosh 1.1 from debian testing in gnome-terminal currently doesn't display my zsh prompt if its in the last line (selection with curser will force it to be rendered tho)

the issue doesnt appear with zsh directly in gnome-terminal

as basic config for the prompt in shell i use:

```
    autoload -Uz promptinit
    promptinit 
    prompt clint
```

**Comment by timofonic** [comment]
@keithw Sorry to ask about this old "bug". What's the current situation about this? Has gnome-terminal been fixed? Does MOSH support ISO-2022 locking shifts these days?

**Comment by keithw** [comment]
Yes, I believe VTE and gnome-terminal fixed this bug in 2012 or 2013.

Both Mosh and PuTTY continue to enforce strict ISO 10646 UTF-8 and do not allow ISO 2022 charset switches.

**Comment by timofonic** [comment]
@keithw I see. Both projects must have their reasons, but I see it as a problem as a mere user ;)

**Comment by keithw** [comment]
What ISO 2022-generating programs are you using in 2017? :-)
