### ISSUE TITLE
Connection hangs on RHEL 8.4 server

### ISSUE THREAD

**Issue by byron-hawkins** [mobile-shell/mosh#1152]
On a fresh install of Oracle Linux (based on RHEL 8.4), any attempt to connect with mosh over a direct ethernet connection shows two blank lines and nothing else.  I can start a `mosh-server` on the server, copy the `MOSH_KEY` to the client and then connect successfully using `mosh-client` on port 60001--everything about the session seems totally normal in this case. But attempting `mosh --port=60001` results in the same 2 blank lines. 

Diagnosing via `gdb`, the two server processes are stopped at `read()` and `select()`, while the client is at `wait()`.  The `perl` command remains active in the client's terminal title bar. With `--no-ssh-pty` the two blank lines are not generated on the connection attempt, but nothing else changes.

    [root@localhost ~]# cat /etc/redhat-release 
    Red Hat Enterprise Linux release 8.4 (Ootpa)
    [root@localhost ~]# uname -a
    Linux localhost.localdomain 5.4.17-2102.205.7.3.el8uek.x86_64 #2 SMP Fri Sep 17 17:54:52 PDT 2021 x86_64 x86_64 x86_64 GNU/Linux
    [root@localhost ~]# mosh --version
    mosh 1.3.2 [build mosh 1.3.2]

**Comment by keithw** [comment]
Hmm, does this problem happen on actual RHEL 8.4, or only on Oracle Linux? Does it happen with the EPEL package, or only building from source? Does it happen with the Mosh 1.3.2 release, or only tip-of-tree from the Git repository?

**Comment by eminence** [comment]
I think @njaard tracked this issue to an openssh bug and provided a nice fix for us in #1160, so closing this issue.
