### ISSUE TITLE
Terminal escape sequences not working with Chrome 94.0.4606.61

### ISSUE THREAD

**Issue by ppetr** [mobile-shell/mosh#1153]
Since past day or two `mosh` Chrome extension (v.0.5.6, mosh 1.3.2) stopped working with any `ncurses` program such as `mc` or `vim`.  The screen is just blank after running such a program, or contains garbled fragments of the expected output.

The only thing that I'm aware of that has changed recently is Chrome being updated to [94.0.4606.61](https://chromereleases.googleblog.com/2021/09/stable-channel-update-for-desktop_24.html).

Resetting preferences to defaults didn't help.

Please let me know if there is anything I can do to help with debugging the issue.

**Comment by andersk** [comment]
The Chrome extension is a [separate project](https://github.com/rpwoodbu/mosh-chrome) with different maintainers. You’ll need to ask there.

**Comment by ppetr** [comment]
I didn't know, thank you for the pointer.

**Comment by ppetr** [comment]
For reference, this is the bug I opened for the Chrome extension: https://github.com/rpwoodbu/mosh-chrome/issues/216
