### ISSUE TITLE
Nothing received from server on UDP port - One server works - an other one no

### ISSUE THREAD

**Issue by shakibamoshiri** [mobile-shell/mosh#1156]
Tested all the solutions #374 and did not work on two incidental servers. On one of them works , on other one no! 

In Both servers:  
 - static IP addresses
 - are Debian 10  
 - are from the same provider  
-  I have root access and just are managed by myself  

---

**What I have done to resolve the issue**  
 - reboot the server 
 -  iptable opening ports
 - test `nc`
 - using `-p` with a port
 - using `--family=all` and `--bind-server=any`
 - run the `/usr/bin/mosh-server new -i` with the server's IP

**Mosh**  on two servers
```bash
mosh -v
mosh 1.3.2 [build mosh 1.3.2]
Copyright 2012 Keith Winstein <mosh-devel@mit.edu>
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>.
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.
```

**Server 1** works file
```bash
PRETTY_NAME="Debian GNU/Linux 10 (buster)"
NAME="Debian GNU/Linux"
VERSION_ID="10"
VERSION="10 (buster)"
VERSION_CODENAME=buster
ID=debian
HOME_URL="https://www.debian.org/"
SUPPORT_URL="https://www.debian.org/support"
BUG_REPORT_URL="https://bugs.debian.org/"
```

![20211008_19o0106](https://user-images.githubusercontent.com/18571844/136583930-9524f9ed-522f-4a68-ae08-7087ed904a83.png)

**Server 2** Nothing received from server on UDP
```bash
PRETTY_NAME="Debian GNU/Linux 10 (buster)"
NAME="Debian GNU/Linux"
VERSION_ID="10"
VERSION="10 (buster)"
VERSION_CODENAME=buster
ID=debian
HOME_URL="https://www.debian.org/"
SUPPORT_URL="https://www.debian.org/support"
BUG_REPORT_URL="https://bugs.debian.org/"
```
![20211008_18o5311](https://user-images.githubusercontent.com/18571844/136582967-1e53af5d-fd2e-4f1d-a7bf-7d37cd3f6e8b.png)

**Client**
```bash
NAME="Ubuntu"
VERSION="18.04.5 LTS (Bionic Beaver)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 18.04.5 LTS"
VERSION_ID="18.04"
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
VERSION_CODENAME=bionic
UBUNTU_CODENAME=bionic
```

**Comment by achernya** [comment]
Please re-try with mosh 1.4.0 and let us know if you can still reproduce. I rather suspect this is a network configuration issue on one of your servers, though. Please provide the output of iptables-save, ip6tables-save, `ip addr show` `ip route` `ip -6 route` if you are able to reproduce.
