### ISSUE TITLE
can not see nerdfont glyph icons on shell prompt

### ISSUE THREAD

**Issue by jerome-diver** [mobile-shell/mosh#1157]
# What's happening ?
Can not see glyph shell prompt from nerdfont-complete on my ZSH (oh-my-zsh and powerlevel10k) shell prompt.

# Does it happen other place ?
No, with ```ssh``` command to connect, i can see these glyph fonts

# What is my system environment ?

## Local machine
Fedora-34 with mosh-1.3.2 inbstalled from dnf
locale system: fr_FR.UTF-8
shell: ZSH (oh-my-zsh and powerlevel10k)

## Remote machine
FreesBSD-12.2 with mosh-1.3.2 installed from pkg (no X system)
locale system: fr_FR.UTF-8
shell: ZSH (with ho-my-zsh and powerlevel10k)

# Show the difference
## ```mosh``` doesn't print glyph FreeBSD icon, on left
![mosh access glyph failed](https://user-images.githubusercontent.com/11176132/136883253-c17850b5-1059-408b-9ae6-80811f6874a8.png)

## ```ssh``` show FreeBSD glyph on left
![ssh icon glyph ok](https://user-images.githubusercontent.com/11176132/136883261-04f2ecef-9e69-4159-acf1-5aaabb088a7e.png)

**Comment by andersk** [comment]
This is the same issue as #351. Your C library’s `wcwidth` function has failed to tell Mosh how wide these private-use characters are. Mosh refuses to guess, because guessing wrong would leave it with no way of keeping the internal state on which its delta updates are based with the state of your actual terminal, resulting in persistent corruption of unrelated characters.

**Comment by jerome-diver** [comment]
Hi @andersk , and thank you for your answer.
 Did you red the (8 years ago) answer on this issue track number from @fulzy about this ?
==>
```
 Since the vim-powerline issue tracker has gone away, here are the details:
Old vim-powerline uses unassigned unicode area (e.g. U+2b80), but when mosh calls wcwidth() to determine its character width the function returns -1 (nonprintable) for unassigned ones, thus mosh removes it.
Some other scripts (e.g. oh-my-zsh agnoster theme) still uses old powerline characters. You have to update them to use with mosh. 
```
So i can not understand how i'm supposed to find a solution from there. Can you help me with that ?

**Comment by jerome-diver** [comment]
can you go to have a look, @andersk, to the #[1598](https://github.com/romkatv/powerlevel10k/issues/1598) posted issue that is talking about a unicode problem that mosh is not able to care about ?

**Comment by eminence** [comment]
It sounds like things are solved here, so closing
