### ISSUE TITLE
new pacman --sync --sysupgrade makes some progress indication mess

### ISSUE THREAD

**Issue by cypa** [mobile-shell/mosh#1161]
see screenshot please
![20211108_14h47m15s_grim](https://user-images.githubusercontent.com/807372/140720727-b85bbeb3-f4a0-4c87-ac89-73f66a48b4ee.png)

**Comment by achernya** [comment]
I'm not familiar with pacman's output enough to be able to tell what part of this screenshot is a "mess". Can you post a screenshot of what's expected versus what you actually see?  Also, can you reproduce with mosh 1.4.0? Please re-open this issue if so.
