### ISSUE TITLE
Mosh and cfs

### ISSUE THREAD

**Issue by niftyhacking** [mobile-shell/mosh#1162]
Someplace make a note under firewalls to correctly open ports that cfs closes.  

The cfs equivalent of.
  sudo ufw allow 60000:61000/udp 

Might do firewall checks before installing.

Also that ssh continues to be active and in some rare situations a telnet connection to fix things can be helpful. 
I tinker with “headless” machines behind a firewall and when connectivity gets tangled it gets “too interesting”.

Off to double check details of ubuntu, fedora, raspian, (raspberry pi boards).  
priority low for now. 

Good stuff,
Thank you.

Edit:
https://community.centminmod.com/threads/mosh-issue.5474/
https://www.digitalocean.com/community/questions/ufw-weirdness-on-ubuntu-20-04-droplet-i-don-t-understand-why-allowing-denying-tcp-22-affects-all-other-ports

Fail2ban has parallel issues.

**Comment by eminence** [comment]
I don't think there's anything actionable for us here, so I'm closing this.
