### ISSUE TITLE
Need clarification on MOSH support for save/restore cursor

### ISSUE THREAD

**Issue by scottchiefbaker** [mobile-shell/mosh#1164]
I'm the author of [Dool](https://github.com/scottchiefbaker/dool) which does not work correctly with `mosh`. After some digging it appears that the issue is that `dool` uses ANSI save/restore cursor position. That is `\033[s` and `\033[u` respectively. The only reference I can find to these ancient ANSI sequences and `mosh` is in this [unrelated bug](https://github.com/mobile-shell/mosh/issues/726#issuecomment-194569057) from 2016.

Before I go too far down a rabbit hole can I get clarification that `mosh` in 2021 does or does not support save/restore? Hoping to find something in writing or documentation that I can link if I fix the issue.

To recreate the bug in `dool` you can run `dool --more 3` under `mosh` and you'll see the lines draw incorrectly compared to vanilla SSH.

**Comment by keithw** [comment]
I think you are correct -- these escape sequences aren't part of the "xterm"/"xterm-256color" terminfo entries and aren't supported by Mosh.

**Comment by andersk** [comment]
In Python, you can use `curses.tigetstr("sc")` and `curses.tigetstr("rc")`. See also `infocmp xterm` and `man 5 terminfo`.

```console
$ cat test.py
import curses
import sys

curses.setupterm()
sys.stdout.buffer.write(
    b"abc" + curses.tigetstr("sc") + b"defg" + curses.tigetstr("rc") + b"HI\n"
)
$ python3 test.py
abcHIfg
```

**Comment by scottchiefbaker** [comment]
Interesting... your version using curses works in both `ssh` and `mosh`. This is a simplified version of the code from `dool` that does not work under `mosh` but **does** work under `ssh`.

```
import sys

ansi = {
    'save'   : '\033[s',
    'restore': '\033[u',
}

sys.stdout.write("abc" + ansi['save'] + "defg" + ansi['restore'] + "HI\n");
```

mosh output: `abcdefgHI`
ssh output: `abcHIfg`

**Comment by eminence** [comment]
The suggestion from @andersk is probably the best one.  On my terminals, save cursor is `\0337` and restore cursor is `\0338`, but you really should be getting these from the terminfo database.

**Comment by scottchiefbaker** [comment]
For my purposes, I think I will find another way to do things since save/restore doesn't seem well supported. Thank you for the confirmation and help testing.

**Comment by eminence** [comment]
Just to be clear, mosh *does* support DECSC and DECRC, and I think you could rely on those.  But I do agree your new approach is probably better.
