### ISSUE TITLE
Ignore RemoteCommand in ssh config

### ISSUE THREAD

**Issue by jordan-schneider** [mobile-shell/mosh#1175]
Per https://github.com/mobile-shell/mosh/issues/285#issuecomment-435290745 there's no way to get mosh to work with a RemoteCommand ssh config option. Given that, is there some way to tell mosh to ignore the option, instead of not working entirely?

**Comment by andersk** [comment]
It’s not Mosh’s option to ignore: it’s read by `ssh` from `~/.ssh/config` and used entirely within `ssh`, without Mosh ever seeing it.

We could pass `-o RemoteCommand=none` to `ssh`. The fact that this is possible is an undocumented property of OpenSSH, and it still won’t achieve what a user who configured `RemoteCommand` probably expects. But maybe it’d be reasonable if we first get a documentation patch into OpenSSH upstream (so we know they won’t change it).
