### ISSUE TITLE
Mosh not respecting port directive in ~/.ssh/config file. 

### ISSUE THREAD

**Issue by ioogithub** [mobile-shell/mosh#1176]
I have a simple alias in ~/.ssh/config:

```
Host remote
    HostName server.remote.com
    User 
    Port 15000
   IdentityFile ~/.ssh/id
```

I am trying to get mosh to parse this entry and connect to port 15000 with the command:
`mosh remote`

Here is the result:
```
mosh: Nothing received from server on UDP port 60001. [To quit: Ctrl-^ .]

mosh did not make a successful connection to x.x.x.x:60001.
Please verify that UDP port 60001 is not firewalled and can reach the server.

(By default, mosh uses a UDP port between 60000 and 61000. The -p option
selects a specific UDP port number.)
```

So interestingly, mosh did parse part of the file because it took the url and correctly translated it to the right IP address however it still tries to connect to UDP port on 60001 and this will not work.

According to https://mosh.org/#faq, mosh should respect the single port directive:

```
Q: How do I use a different SSH port (not 22)?
As of Mosh 1.2, you can pass arguments to ssh like so:
mosh remotehost --ssh="ssh -p 2222"
**Or configure a host alias in ~/.ssh/config with a Port directive. Mosh will respect that too.**
```

Rather mosh seems to ignore the port directive and tries to connect to UDP on 60001 anyway. This port is not an option.

To further troubleshoot, I can confirm that `ssh remote` connects successfully.
Also, `mosh remote -p 15000 ` does work correctly as well.

Version: mosh 1.3.2 [build mosh 1.3.2] on both client and server.

**Comment by msva** [comment]
this is not how mosh works

Moreover, it doesn't even read ssh config.

Moreover, it doesn't even use ssh to work. it only uses ssh (literally calls `ssh` program) to authenticate user and run mosh-server on remote side.

**Comment by eminence** [comment]
Yup, what `msva` said.  The `port` directive in a `~/.ssh/config` file controls what SSH port to use for the initial connection.  Mosh uses this initial connection to launch `mosh-server` on the remote machine.  The UDP port that `mosh-server` will listen on is controlled by the `-p` command line option.  There is no config file for mosh.
