### ISSUE TITLE
Update news section on mosh website

### ISSUE THREAD

**Issue by ShalokShalom** [mobile-shell/mosh#1177]
The news section on the homepage does suggest, that the project is not updated since 2017.

If you dont come to GitHub, you think the project is dead.

Maybe just say hello.

**Comment by hayd** [comment]
There also hasn't been a release/tag since 2017!

**Comment by paperbenni** [comment]
+1 on this one. It'd also be nice to have a list of things that still need to be done for a next release. With the current release nvim and tmux have major display issues, these have been fixed for a long time, just no distribution packages a version with the fixes. Is there a major rewrite or new features going on that take 5 years to get the stable enough for a release? Are there security concerns with the current git version?

**Comment by ShalokShalom** [comment]
It`s just laziness.

**Comment by RampedIndent** [comment]
Yea I almost skipped using this software because I looked at the website and saw it had any news in 5 years, I figured I should check the github since it does exactly what I need.

**Comment by ShalokShalom** [comment]
Just imagine how many potential contributors already skipped it actually. 

Just because the maintainer is unable to post a simple "we are still alive"

**Comment by elliott-sh** [comment]
il open a pr on the website github repo

**Comment by hayd** [comment]
should still be open...

**Comment by ShalokShalom** [comment]
Nobody cares, they just reopen and dont get to type 4 lines within years. 

Should tell you a lot about the QA here, just ditch it.

**Comment by paperbenni** [comment]
@ShalokShalom Wait if you have access to the repo, can't you just update the news section? I'm pretty sure you've spent about as much time on this issue as you would just commiting a news update
