### ISSUE TITLE
tmux still change tmux panel title

### ISSUE THREAD

**Issue by woodgear** [mobile-shell/mosh#1179]
after read https://github.com/mobile-shell/mosh/issues/477 and set env `MOSH_TITLE_NOPREFIX=true`. when i use `sshpass -p XXXX mosh root@xxx` it still change tmux panel title to root@hostname, replace mosh to ssh, it does not.
so I thought I should be some config I did not find out.
tmux: 3.0a
mosh: 1.3.2

**Comment by woodgear** [comment]
it seems `cd` change the tmux panel title either.

**Comment by woodgear** [comment]
![image](https://sm.ms/image/eK4JCwvXdnQmG5D) a gif as showcase.

**Comment by achernya** [comment]
Unfortunately the sm.ms link is expired, so I can't see what was contained there. However, it doesn't sound like this is a mosh issue, if `cd` also changed your tmux panel titles.
