### ISSUE TITLE
How to use mosh with git bash (windows) ?

### ISSUE THREAD

**Issue by Azureki** [mobile-shell/mosh#1183]
> [mosh.org](https://mosh.org/): You will need to run Mosh from a full-featured terminal program such as mintty 
> [mintty](https://mintty.github.io/): In Git-for-Windows, mintty is installed by default and invoked as "Git Bash". 

I found mosh here: https://github.com/mobile-shell/mosh/issues/293#issuecomment-885484861.

I can use mosh to connect remote linux with windows cmd. But in git, it shows `ERROR_INVALID_HANDLE`.

**Comment by eminence** [comment]
Hi.  I don't think we really support mosh in git bash.  The MinTTY terminal that comes with git-bash is fine, but I'm not sure about the rest of the environment.

> I can use mosh to connect remote linux with windows cmd.

I'm curious how you did this (what build of mosh are you running?)

Note that these days, I think the easiest way to run mosh on windows is via [WSL](https://docs.microsoft.com/en-us/windows/wsl/about)

**Comment by achernya** [comment]
It looks like most folks have moved away from cygwin and towards WSL which has "native" mosh.
