### ISSUE TITLE
Colors not displaying correctly for browsh

### ISSUE THREAD

**Issue by jonas-w** [mobile-shell/mosh#1185]
This is related to browsh but seems to be a mosh issue.

When i use browsh via mosh as "advertised" i get this rubbish output:
![image](https://user-images.githubusercontent.com/32615971/161666531-65ed8ee8-6bdb-43b0-af12-4ed22e875e55.png)

But if i use browsh via SSH it displays correctly:
![image](https://user-images.githubusercontent.com/32615971/161666623-c6eb80a6-70f2-4cf8-baf7-c32cbf48fbae.png)

I'm using Arch Linux with Sway and 
mosh 1.3.2 [build mosh-1.3.2-105-gdbe419d]

**Comment by Alumniminium** [comment]
https://www.brow.sh/docs/mosh/
did you compile it?

**Comment by jonas-w** [comment]
oh rtfm moment
