### ISSUE TITLE
Mosh attempt hangs without connecting

### ISSUE THREAD

**Issue by SyamGadde** [mobile-shell/mosh#1188]
Running on Fedora 31, mosh version 1.3.2, trying to connect to an RHEL8 server, same version of mosh.  Similar to #833 but don't know if the underlying cause is the same.  Essentially, after printing a few blank lines passed through from the child process that starts the server the parent process hangs on:

`close $pipe;`

at line 433 of /usr/bin/mosh.  The child process successfully connects to the server and the parent successfully receives the MOSH IP and MOSH_CONNECT strings, but hangs when attempting to close the pipe to the child.  Replacing -n with -f in `@sshopts` as suggested in another post fixes the problem.

**Comment by achernya** [comment]
Do you have anything interesting in your `.ssh/config`? I'm guessing that this is an issue with port-forwarding and `ssh` not terminating. Please re-try with mosh 1.4.0 and let us know if you can still reproduce this issue. `-f` helping seems to confirm this is the case.
