### ISSUE TITLE
Mosh crash: Aborting: _Unwind_RaiseException Mosh NaCl crashed

### ISSUE THREAD

**Issue by jittygitty** [mobile-shell/mosh#1192]
I see that message in chrome mosh client window but not sure if issue is mosh-client or mosh server. 
```
$ Aborting: 
_Unwind_RaiseException
 called (C++ exception handling is disabled)

** abort() called

Mosh NaCl crashed.
Press "x" to close the window.
```
cross-posted at:
https://github.com/rpwoodbu/mosh-chrome/issues/221
Someone more knowledgeable can close the issue in one place and/or redirect to the other.

**Comment by achernya** [comment]
This issue should only be open on the mosh-chrome repository
