### ISSUE TITLE
Error: bind: Address already in use

### ISSUE THREAD

**Issue by Sdator** [mobile-shell/mosh#1197]
The following is my server information and execution record

```text
CentOS Linux release 7.9.2009 (Core)
Linux version 3.10.0-1160.66.1.el7.x86_64 (mockbuild@kbuilder.bsys.centos.org) (gcc version 4.8.5 20150623 (Red Hat 4.8.5-44) (GCC) ) #1 SMP Wed May 18 16:02:34 UTC 2022

```

My mosh client and server version

```text
mosh 1.3.2 [build mosh 1.3.2]
Copyright 2012 Keith Winstein <mosh-devel@mit.edu>
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>.
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.
```

1. client > mosh -p 60001 MyVps
```text
mosh: Nothing received from server on UDP port 60001. [To quit: Ctrl-^ .]
```

2. server  > mosh-service

```text
MOSH CONNECT 60001 VTpO36b3c2JzoxSNWCHqnA

mosh-server (mosh 1.3.2) [build mosh 1.3.2]
Copyright 2012 Keith Winstein <mosh-devel@mit.edu>
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>.
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.

[mosh-server detached, pid = 24208]
```

server  > ps -aux | grep mosh
```text
root     24208  0.0  0.1 162284  1468 pts/0    S    05:15   0:00 mosh-server
root     24210  0.0  0.1 162288  1136 pts/1    Ss+  05:15   0:00 mosh-server
root     24221  0.0  0.0 112808   968 pts/0    S+   05:15   0:00 grep --color=auto mosh
```
>After I run the service manually, it will shut down automatically for an unknown reason after about a few dozen seconds.

server  > netstat -nulp | grep mosh
```text
udp        0      0 0.0.0.0:60001           0.0.0.0:*                           23551/mosh-server
```

server  > firewall-cmd --query-port=60001/udp
```text
You're performing an operation over default zone ('public'),
but your connections/interfaces are in zone 'docker' (see --get-active-zones)
You most likely need to use --zone=docker option.

yes
```

3. client > mosh -p 60001 MyVps

I tried to connect again and finally got the following message, my mosh is not working properly, ask for help.

```text
Failed binding to 10.0.0.6:60001
Error binding to IP 10.0.0.6: bind: Address already in use
Failed binding to 0.0.0.0:60001
Error binding to any interface: bind: Address already in use
Network exception: bind: Address already in use
Connection to xx.xxxx.xyz closed.
/usr/bin/mosh: Did not find mosh server startup message. (Have you installed mosh on your server?)
```

**Comment by eminence** [comment]
I'm a little confused about the exact commands that you ran, so let be cover some of the basics first:

* Each mosh session you have will use its own `mosh-server` process, and also its own dedicated UDP port.  
* Since you're running `mosh` with the `-p 60001` option, you'll only be able to use 1 simultaneous session, because the second session will try to bind to port 60001 and will fail with the error you are seeing ("Address already in use")
* The `mosh-server` process will wait 60 seconds to hear from the client.  If it hears nothing, it will automatically exit.  
* Running `mosh-server` manually can be useful for debugging, but it's never needed normally

The "Nothing received from server on UDP port 60001" message makes me think that your firewalls should be double-checked first

**Comment by Sdator** [comment]
> I'm a little confused about the exact commands that you ran, so let be cover some of the basics first:
> 
> * Each mosh session you have will use its own `mosh-server` process, and also its own dedicated UDP port.
> * Since you're running `mosh` with the `-p 60001` option, you'll only be able to use 1 simultaneous session, because the second session will try to bind to port 60001 and will fail with the error you are seeing ("Address already in use")
> * The `mosh-server` process will wait 60 seconds to hear from the client.  If it hears nothing, it will automatically exit.
> * Running `mosh-server` manually can be useful for debugging, but it's never needed normally
> 
> The "Nothing received from server on UDP port 60001" message makes me think that your firewalls should be double-checked first


First of all, thank you for your quick answer, as you can see, when I executed the `firewall-cmd-- query-port=60001/udp` command on the server, I returned `Connection to x.x.x.x 60001 port [udp/*] succeeded!` on the client side through the `nc-vnu ServerIP 60001` test port, so I can make sure that there is nothing wrong with my firewall settings.

I even uninstalled `firewall` and reinstalled `iptables-services`, and added `- An INPUT-p udp-- dport 60001-j ACCEPT` entry, the final result is the same as above, if you have a better way, please let me know, thank you!

In addition, in most of the tutorial examples I see on the network, very few people run the mosh service manually, but if I don't do it manually, I listen through the query port and there are no ports such as 60001, probably because I don't know the startup mechanism of mosh.
