### ISSUE TITLE
"Network is unreachable" error

### ISSUE THREAD

**Issue by CyberGhost047** [mobile-shell/mosh#1209]
Hello, I have a remote host that uses multiple IPs. The IP I am connecting from accepts all TCP and UDP traffic so that does not seem to be an issue. 

Can ssh normally both on my pc and termius mobile, however mosh gives me the message "Network is unreachable" despite me being connected via SSH. Looking at the processes the mosh server does start up. SSH is bound on port 31337 which I have specified on the mosh server command.

I did a similar configuration on a cheap VPS server with multiple ips and it works perfectly, so not exactly sure what my issue is here.

I am not sure what else I am able to do to get mosh working. Any help would be appreciated.

**Comment by eminence** [comment]
Could you please tell us the complete command that you're using to run mosh?

**Comment by CyberGhost047** [comment]
This is auto generated by termius once I input regular SSH details:
`mosh-server new -s -l LANG=en_GB.utf8 -p 31337`

**Comment by eminence** [comment]
The `-p` option to `mosh-server` controls the UDP port that `mosh-server` will listen on.  Since you said that SSH was bound to port 31337, this `-p` option is probably not what you intend.  I suspect that terminus isn't actually successfully connecting to your server (since it's probably using the default port 22, not port 31337)

**Comment by achernya** [comment]
I support @eminence's hypothesis. The routing configuration you shared seems to be fine, with things going out `enp1s0f0` by default.

**Comment by CyberGhost047** [comment]
The SSH port is defined in the configuration, and upon modifying the mosh server command to `mosh-server new -s -l LANG=en_GB.utf8`, I am still met with the error.

![image](https://user-images.githubusercontent.com/88786215/178533950-ddafe4fa-cd1e-40fe-9f91-e5debf3c5581.png)
![image](https://user-images.githubusercontent.com/88786215/178533990-0f54d590-a8f6-448a-b9ec-003887fe7754.png)

**Comment by keithw** [comment]
Hello -- I just want to be clear. It sounds like **Termius** is giving you the message, "Network is unreachable," and not a Mosh client?

Termius is not Mosh -- the company that makes it says it's an independent Mosh-compatible client and that it is unrelated to Mosh. The company promised us they would stop us using the "Mosh" name, but then they kept using our name anyway. I don't think your problems are with Mosh; you should consult the Termius authors.

If you can replicate the problem with Mosh (e.g., the mosh-client program, or a mobile app based on Mosh, including Blink or Termux), we can try to help you.

**Comment by CyberGhost047** [comment]
> Hello -- I just want to be clear. It sounds like **Termius** is giving you the message, "Network is unreachable," and not a Mosh client?
> 
> Termius is not Mosh -- the company that makes it says it's an independent Mosh-compatible client and that it is unrelated to Mosh. The company promised us they would stop us using the "Mosh" name, but then they kept using our name anyway. I don't think your problems are with Mosh; you should consult the Termius authors.
> 
> If you can replicate the problem with Mosh (e.g., the mosh-client program, or a mobile app based on Mosh, including Blink or Termux), we can try to help you.

In my original post, I have stated I managed to get mosh running on another host which I was able to connect via termius, However this server is a cheap host I use to test on. My production host is the one having errors so I believe it is more a host related error.

I have tried to connect to the host using JuiceSSH and receive a similar error

![image](https://user-images.githubusercontent.com/88786215/178546373-a3e0cc27-adcd-49f1-bcaf-17e4613eb8b5.png)
![image](https://user-images.githubusercontent.com/88786215/178547407-b309d25a-cdb4-41fc-b90a-2e344c75d042.png)

**Comment by eminence** [comment]
Have you been able to reproduce these problems with mosh directly?  (That is, without using JuiceSSH or Terminus)

**Comment by CyberGhost047** [comment]
I have tried to use mosh from one remote host to another using the following command: `mosh root@productionserver --ssh="ssh -p 31337"`

This does prompt for a password but then I am met with the message shown by that of JuiceSSH.

**Comment by eminence** [comment]
I'm not sure what of the above screenshots is from JuiceSSH.  Are you saying that you are seeing a "Nothing received from server on UDP port 60001" message?  Have you confirmed that your firewalls are configured properly?  You mentioned that your host is on OVH, so this means checking both the OVH firewall, plus the OS firewall.

**Comment by eminence** [comment]
Unfortunately you might have to dig out tcpdump or something similar to debug this.   There are some notes on our wiki: https://github.com/mobile-shell/mosh/wiki/Debugging-and-Theory

**Comment by feer9** [comment]
I had this exact same issue and solved it by using the same port both in the termius "port" parameter, and in the mosh command argument (also inside the termius config). 
I don't know if that's how it's supposed to be setted up, but it works
