### ISSUE TITLE
Mosh v1.4.0 release candidate available

### ISSUE THREAD

**Issue by andrew-aitchison** [mobile-shell/mosh#1219]
Apologies if you follow the Mosh mailing lists and have already seen this, but I thought that you would be interested to hear that there is a release candidate for the next version of Mosh:

As I have reduced colour vision the true color support is not important to me, but I am curious to see whether the non-prediction on large pastes has any performance benefits.

If you do release a new version of Juice SSH, I am still running Android 6.0 on my phone so if you can build a version that works that far back it would be great.

** I am not part of the Mosh team, just a Juice SSH user. **

----------------------------------------------------
Date: Sun, 7 Aug 2022 22:04:42 -0400
From: Andrew Chin <andrew@andrewchin.net> 
To: mosh-users@mit.edu, mosh-devel@mit.edu
Subject: [mosh-users] Mosh 1.4.0 release candidate 1 available for testing

Hi all,

The Mosh team is pleased to announce the first release candidate of the long awaited 1.4.0 release. This release has a mix of bug fixes and new features. This release is currently tagged as 1.3.2.95rc1, but this will become 1.4.0.

Here is a summary of what's new:

New features:
  * Support OSC 52 clipboard copy integration (Alex Cornejo)
  * Allow non-inserting prediction (--predict-overwrite) (John Hood)
  * Don't do prediction on large pastes into mosh-client (John Hood)
  * Add true color support (Kang Jianbin)
  * Add syslog logging of connections (Tom Judge)
  * If exec()ing the remote command fails, pause briefly (John Hood)

Bug fixes:
  * ignore unknown renditions (Keith Winstein)
  * Overlays were getting set to the wrong colors (John Hood)
  * Fix issue with incorrect true-color background erase colors (John Hood)
  * Use HAVE_UTEMPTER instead of HAVE_UPTEMPTER (Michael Jarvis) 
  * Apply latest consecutive resize, not earliest (Peter Edwards)
  * Use CLOCK_MONOTONIC_RAW when available (Harry Sintonen) 
  * Add tmux and alacritty to title_term_types (Naïm Favier)
  * Don't sometimes hang just after launching ssh (Kalle Samuels)

Internal changes:
  * Reformat printed strings in source (John Hood)
  * Code cleanups (John Hood, Anders Kaseorg, Benjamin Barenblat, Alex
Chernyakhovsky)
  * Always use non-blocking sockets for recvmsg() (John Hood)
  * Add Perl compile (John Hood)
  * Improvements to the test suite (John Hood)
  * Fixes to autoconf configure (Anders Kaseorg)
  * Cleanups to our crypto code (Benjamin Barenblat, Alex Chernyakhovsky)

Infrastructure changes:
  * Add support for OCLint static checker (John Hood)
  * Switch from Travis-CI to Github Actions (Wolfgang E. Sanyer, Alex
Chernyakhovsky)
  * Add code coverage and fuzzing infrastructure (Alex Chernyakhovsky)   

For a complete list of changes since 1.3.2:
<https://github.com/mobile-shell/mosh/compare/mosh-1.3.2...mosh-1.3.2.95rc1>

Source code is available in an official distribution tarball at:
https://github.com/mobile-shell/mosh/releases/download/mosh-1.3.2.95rc1/mosh-1.3.2.95rc1.tar.gz
(SHA256 5e05fc89e6f30a86b3f4ebe07bae04142d44fa9a86221c7d39e1b0a6f6136bd0)

There is also an unofficial macOS package build at:
https://github.com/mobile-shell/mosh/releases/download/mosh-1.3.2.95rc1/mosh-1.3.2.95rc1.pkg
(SHA256 44bdbeb570dac287c1926c38c85070dfcc9ce385435f44c935c1a5adb092c6e0)
and accompanying build report at:
https://github.com/mobile-shell/mosh/releases/download/mosh-1.3.2.95rc1/mosh-1.3.2.95rc1-osx-build-report.tbz

Notes to packagers:

Since this is only a release candidate, we recommend only making this
available in *experimental* channels.

We welcome any feedback (both positive and negative) before we release the final 1.4.0 release.  Testing of the macOS package would be especially useful, as well as systems not in our CI matrix (old RHEL, OpenBSD, Solaris, etc).

Please report any issues to Github or to our IRC channel at <irc://irc.libera.chat/mosh>

Sincerely,
-- The Mosh release team

**Comment by xtaran** [comment]
This is not an __ISSUE__.

**Comment by andrew-aitchison** [comment]
Sorry. This issue is in the wrong project. It should be in JuiceSSH.
