### ISSUE TITLE
Truncated output and other visual glitches

### ISSUE THREAD

**Issue by joshcangit** [mobile-shell/mosh#1223]
Hope this can be fixed.
I've used `mosh --no-init` with `tmux`.

Lines still get truncated if the output exceeds the terminal size.
The size is small on Termux on my phone so a lot gets cut off.
Using pagers like `less` can get around this but it still gets cut off after quitting.

I notice sometimes if the new lines suppose to go over the previous line, it instead goes to a new line.
I see this when doing `pacman -Syu`.
Strangely, carriage return works just fine.

Is this related to #909?

**Comment by achernya** [comment]
Can you clarify what you are expecting and what you see instead? Screenshots would be helpful.

**Comment by eminence** [comment]
It sounds like you are using Termux on your client (phone).  Do you also see problems when you use the standard mosh client?

**Comment by joshcangit** [comment]
Actually, using mosh as is won't show the text truncated because there's no scrollback.

**Comment by achernya** [comment]
Mosh emulates a terminal and only updates the visible area. Scroll back is "best effort" and in general should not be expected to work.
