### ISSUE TITLE
Chrome App to Progressive Web Apps

### ISSUE THREAD

**Issue by lathydxc** [mobile-shell/mosh#1225]
When launching Mosh on a Windows-machine with mosh installed as chrome-app it has started to popup with

![image](https://user-images.githubusercontent.com/58545949/193861366-98d883c8-d9f9-45df-a627-49f0e56063ed.png)

Learn-more points to https://support.google.com/chrome/thread/174381169?visit_id=638004940173080074-2900992435&p=chrome_app_deprecation&rd=1

Timeline for Chrome-apps:
July 2022: End support for Chrome Apps on Windows, Mac, and Linux.
January 2023: Chrome Apps will no longer be launchable on Windows, Mac, and Linux.
January 2025: End support for Chrome Apps on ChromeOS.

**Comment by achernya** [comment]
Mosh for chrome is not supported by the mosh team. I believe that is https://github.com/rpwoodbu/mosh-chrome. Since that's in a different organization, I cannot transfer this issue to them. Please reopen on that repository.
