### ISSUE TITLE
True Color does not work at top of tree (mosh-1.3.2.95rc2)

### ISSUE THREAD

**Issue by thecuriousone25** [mobile-shell/mosh#1229]
I just built from the source (top of tree  commit a08e682de6274685d636632240748f93311ac472 (mosh-1.3.2.95rc2)) and looks like true color does not work. True color on ssh for the same machine works.

- Wondering if true color is going to be supported (the commit history seem to indicate it would be)
- Is there anything special that needs to be done when building from source to add support for true color?

** Clarification **
- By does not work, I mean that nvim true color themes look all bad (like true color is not supported)
- To verify that true color is supported, I ran the below script in comments (from stackoverflow) to verify support. Its supposed to show rainbow colors if true color is supported. (Verified the script works with ssh and et (eternal terminal))

**Comment by achernya** [comment]
Can you please clarify what you mean when you ay "does not work"? We've had positive reports of it working with this version. Please post your terminal emulator, the output of `env` inside and outside mosh, as well as your operating system details.

**Comment by thecuriousone25** [comment]
The script I am using to verify true color support. Basically I run this after I use mosh to login to the remote machine

```
#!/bin/bash
# Based on: https://gist.github.com/XVilka/8346728 and https://unix.stackexchange.com/a/404415/395213

awk -v term_cols="${width:-$(tput cols || echo 80)}" -v term_lines="${height:-1}" 'BEGIN{
    s="/\\";
    total_cols=term_cols*term_lines;
    for (colnum = 0; colnum<total_cols; colnum++) {
        r = 255-(colnum*255/total_cols);
        g = (colnum*510/total_cols);
        b = (colnum*255/total_cols);
        if (g>255) g = 510-g;
        printf "\033[48;2;%d;%d;%dm", r,g,b;


        printf "\033[38;2;%d;%d;%dm", 255-r,255-g,255-b;
        printf "%s\033[0m", substr(s,colnum%2+1,1);
        if (colnum%term_cols==term_cols) printf "\n";
    }
    printf "\n";
}'
```

Attached is the output on env on the host  (macos) and remote machines (linux) [env.log](https://github.com/mobile-shell/mosh/files/9874795/env.log)

**Comment by achernya** [comment]
Can you print out `mosh --version` on both client and server? You need both to be updated to the latest version with truecolor support, otherwise it will not work (mosh runs a TTY emulator on both and keeps them in sync). I can reproduce the output you show with mosh 1.3.2.95rc2 on the client and 1.3.2 on the server.

**Comment by thecuriousone25** [comment]
Sure.. Here is the output. Both of them are the same versions.
`
Mosh Server: mosh 1.3.2.95rc2 [build mosh-1.3.2.95rc2]
Mosh Client: mosh 1.3.2.95rc2 [build mosh-1.3.2.95rc2]
`

**Comment by achernya** [comment]
Can you please post the full output including the hostnames (redacted is fine) with the shell paths? I cannot reproduce the behavior you describe with the new version.

**Comment by thecuriousone25** [comment]
Sure.. here it is.

```
xxx@client ~ % mosh --version
mosh 1.3.2.95rc2 [build mosh-1.3.2.95rc2]
Copyright 2012 Keith Winstein <mosh-devel@mit.edu>
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>.
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.

xxx@server ~$ mosh --version
mosh 1.3.2.95rc2 [build mosh-1.3.2.95rc2]
Copyright 2012 Keith Winstein <mosh-devel@mit.edu>
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>.
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.

```

**Comment by thecuriousone25** [comment]
Okay.. let me try to help.

I had true color working previously. I got it working based on some commit (a few months old commit) in main + the [patch](https://github.com/mobile-shell/mosh/commit/ac0492cb5a703ae979b5c923182671d2688b025a.patch) which is already part of the mosh release.

I will try to debug whats going on.

**Comment by huyz** [comment]
@thecuriousone25 How did you install mosh on your server? And what OS?

**Comment by thecuriousone25** [comment]
The mosh server is installed on Ubuntu 22 LTS. The client is on MacOS is on Monterey

**Comment by huyz** [comment]
I have the same setup. I didn't use source. I installed 1.4.0 using brew and Linuxbrew. What fixed it for me: I had to specify the `--mosh-server` absolute path on the client to make sure that the correct binary was used. (This was in addition to setting $PATH in my mosh client invocation. Not sure why I had to do both)
Anyway in my case, it was likely that the wrong mosh-server was being picked up because I have one from apt. I'm hoping that it's the same reason for you

**Comment by thecuriousone25** [comment]
It turned out that the mosh-server binary being picked up was different version. It was not obvious at first, because once I logged in, the mosh-server --version was the one from $PATH.

Tried `file /proc/<mosh-server PID>/exe` and it confirmed that the wrong `mosh-server` was being picked.

Thanks @huyz. Explicitly specifying the `--mosh-server` does the job too.
