### ISSUE TITLE
Don't clear screen on mosh connection

### ISSUE THREAD

**Issue by josharian** [mobile-shell/mosh#123]
Feature request: It'd be nice if the mosh client didn't clear the screen when establishing a connection, or if there was at least an option to disable that behavior. Frequently there's useful context up there I want to have available once I've connected.

Thanks for an awesome tool. :)

**Comment by cgull** [comment]
That script requires you to set LINES manually beforehand.  Better is this:
```
#!/bin/sh
for f in $(seq 1 $(tput li)); do echo; done
exec mosh-client $@
```
