### ISSUE TITLE
Using `mosh` with load balancer

### ISSUE THREAD

**Issue by abitrolly** [mobile-shell/mosh#1244]
To access host behind LoadBalancer, the LB needs to know how to route traffic to it. For SSH the LB can terminate the connection and use username as a host name to open a new encrypted connection to the host. But with `mosh` it doesn't work. So what are the options?

This is an issue for Gitpod https://github.com/gitpod-io/gitpod/issues/10440#issuecomment-1322432267

**Comment by achernya** [comment]
Unfortunately mosh requires an IP:port to function and is not vhostable/load-balanceable in this way. You need some mechanism to tunnel the mosh UDP via a bouncer service, or per port firewall rules and some sort of allocation service.

**Comment by abitrolly** [comment]
@achernya so what in your opinion these rules should be?

> You need some mechanism to tunnel the mosh UDP via a bouncer service

Can you give an example? I am not sure where the bouncer service should be and what should it do.

> or per port firewall rules and some sort of allocation service.

Is it possible to add some optional field to `mosh` protocol to tag traffic that is destined to the specific host behind the firewall? `IP:port` looks like L4 mapping, which seems complicated to maintain dynamically.

**Comment by achernya** [comment]
> Can you give an example? I am not sure where the bouncer service should be and what should it do.

Possibly [STUN](https://en.wikipedia.org/wiki/STUN) or [TURN](https://en.wikipedia.org/wiki/Traversal_Using_Relays_around_NAT), or possibly even [CONNECT-UDP](https://datatracker.ietf.org/doc/html/rfc9298).

> Is it possible to add some optional field to mosh protocol to tag traffic that is destined to the specific host behind the firewall?

No, this would constitute a privacy leak, and would be incompatible with all existing mosh implementations. If we were to make a protocol change, I'd be interested in doing something like [QUIC LB](https://datatracker.ietf.org/doc/draft-ietf-quic-load-balancers/), but that's an active area of research/development.
