### ISSUE TITLE
Kitty graphics protocol support

### ISSUE THREAD

**Issue by albertz** [mobile-shell/mosh#1248]
The protocol is described here: https://sw.kovidgoyal.net/kitty/graphics-protocol/

Related is SIXEL graphics support (#1081), however, the Kitty graphics protocol is more advanced.

There are also already some other terminals who adopted it, such as [Konsole](https://invent.kde.org/utilities/konsole/-/merge_requests/594), [wezterm](https://github.com/wez/wezterm/issues/986), [wayst](https://github.com/91861/wayst).

**Comment by achernya** [comment]
I'm afraid this feature request is extremely non-trivial. mosh's SSP (state synchronization protocol) would have to be substantially augmented to support large transfers of images. This is probably in the same amount of effort as port forwarding, or SSH agent support, in terms of the underlying features it requires.
