### ISSUE TITLE
Mosh Chrome app deprecated.

### ISSUE THREAD

**Issue by rokejulianlockhart** [mobile-shell/mosh#1249]
[The Chrome application for Mosh](https://chrome.google.com/webstore/detail/mosh/ooiklbnjmhbcgemelgfhaeaocllobloj?utm_source=chrome-app-launcher-info-dialog) [has been deprecated](https://user-images.githubusercontent.com/42837531/212517444-3d965924-04d3-4ab0-9034-bfdde26b64b6.png) per https://support.google.com/chrome/thread/174381169?visit_id=638093451802058341-2592637814&p=chrome_app_deprecation&rd=1.

This already means that it is incompatible with Microsoft Edge if the Microsoft account used contains an e-mail address that is different to the Google account used within the Chrome Web Store.

The timeline for the deprecation [is provided](https://support.google.com/chrome/thread/174381169?visit_id=638093451802058341-2592637814&p=chrome_app_deprecation&rd=1#:~:text=we've%20included%20the-,[timeline](https://support.google.com/chrome/thread/174381169?visit_id=638093451802058341-2592637814&p=chrome_app_deprecation&rd=1#:~:text=we've%20included%20the-,timeline,-for%20the%20phased),-for%20the%20phased):
> June 2022: Chrome Web Store will stop offering Chrome App installations for Windows, Mac, and Linux users.
July 2022: End support for Chrome Apps on Windows, Mac, and Linux.
March 2023: Chrome Apps will no longer be launchable on Windows, Mac, and Linux.
January 2025: End support for Chrome Apps on ChromeOS.

**Comment by achernya** [comment]
Unfortunately we don't maintain the mosh chrome app. Please file a bug on https://github.com/rpwoodbu/mosh-chrome

**Comment by rokejulianlockhart** [comment]
https://github.com/rpwoodbu/mosh-chrome/issues/223

**Comment by achernya** [comment]
mosh.org is https://github.com/mobile-shell/moshweb, our website. We can continue discussion on https://github.com/mobile-shell/moshweb/issues/70.
