### ISSUE TITLE
mosh-server doesn’t work after installing(deploying) vpn server

### ISSUE THREAD

**Issue by dev-onejun** [mobile-shell/mosh#1250]
Hi ! I am one of the enjoying users of mosh.
Thank you for this community at first.

The problem is, after deploying vpn server ([AlgoVPN exactly](https://github.com/trailofbits/algo)) on my computer,
my mosh-server which was work well does not work at all with the following output.

```
mosh: Nothing received from server on UDP port 60001
```

```
mosh did not make a successful connection to xxx.xxx.xxx.xxx:60001.
Please verify that UDP port 60001 is not firewalled and can reach the server.
```

Because I used well before, it is not a problem that I blocked the port 60000-61000/udp by the firewall.
Furthermore, when I set VPN, I opened the port 4160 and 51820 which is not duplicated with the mosh ports.

Please let me know what the problem that I can’t use mosh is … 😢

**Comment by achernya** [comment]
Unfortunately we need more information. It doesn't sound like this is a mosh issue, bit rather something about your VPN config. It seems AlgoVPN is wireguard based, which works fine as a transport for mosh in general.

**Comment by dev-onejun** [comment]
Thanks for your comment !!
As you clearly give a solution is not on here, I more eagerly search the opposite repos’ issue list and finally find it.

I solve the problem with the reference trailofbits/algo#14502 especially in [this comment](https://github.com/trailofbits/algo/issues/14502#issuecomment-1296199156).

As a result, I newly know that AlgoVPN intends to overwrite the firewall rules using `iptables`
which can conflict with the firewall tools such as `ufw` I used.

* You can get more information in the following links.
  * https://github.com/trailofbits/algo/blob/master/docs/deploy-to-ubuntu.md#local-installation
  * https://github.com/trailofbits/algo/blob/master/docs/firewalls.md

I had two machines that cannot be connected with mosh, one is in my home and the other is on gcp.

__And, the solution was different in each machine__

1. I just make the ufw disable with the following command.

``` bash
ufw disable
```

The one is solved with here.

2. make the proper firewall rules with `iptables`

``` bash
iptables -I INPUT -p udp -m udp —dport 60000:61000 -j ACCEPT
```

The other one is solved with here.
