### ISSUE TITLE
[Bug] mosh may display the contents of a disconnected connection

### ISSUE THREAD

**Issue by fansehep** [mobile-shell/mosh#1256]
Sometimes when i mosh my server. it will display some other ssh or mosh contexts. Seems a bug. but don't affect use.

**Comment by eminence** [comment]
Can you describe the situation in more detail: What are you seeing?  Is it something on screen for a short time, and then you see your new session?  Is it possible you're just seeing some scrollback in your local terminal before running mosh?

**Comment by fansehep** [comment]
ok 

system: Arch linux 6.1.7
server system: Arch Linux 6.1.7
mosh version: 1.4.0

![2023-02-11_13-02-1676094165](https://user-images.githubusercontent.com/75058860/218242611-c9061cac-cba6-48e9-a5f6-f9eb41e68a84.jpg)

 when i tap enter. 
 
![2023-02-11_13-02-1676094180](https://user-images.githubusercontent.com/75058860/218242675-49e012df-c7bd-4ca0-b689-b2977ad2e693.jpg)

before tap. I do nothing. but i did use man-pages recently.

it will not rollback.

**Comment by achernya** [comment]
This is almost certainly a bug in your terminal having to do with alternative screen mode. What terminal emulator is this?

**Comment by fansehep** [comment]
> This is almost certainly a bug in your terminal having to do with alternative screen mode. What terminal emulator is this?

Nope. I don't think the emulator error. I use Alacritty. I guess this is my ssh config error. I enable the ssh ```multiplex```. It may be connect other mosh server. I disable the option. The problem has been solved.
