### ISSUE TITLE
default url after ssh connected

### ISSUE THREAD

**Issue by daron4ever** [mobile-shell/mosh#1263]
Hi,

I've tried to change the path after connection however, it didn't work.
`mosh $REMOTE 'cd /my_folder; exec $SHELL -l'`

I was told that once the client is dead, you can't re-attach to the server session.
If I have the same ssh connections server with multiple tabs on the terminal and close one of the tabs.
The closed tab is still alive like the background running such as tmux?

**Comment by eminence** [comment]
In general, it is always better to explain how the thing you tried didn't work, instead of just saying "it didn't work"

The commands you gave mosh to run are not executables, but shell commands, so try this:

    mosh $REMOTE -- sh -c "cd /my_folder; exec $SHELL -l

**Comment by eminence** [comment]
I'm assuming your question is solved, so I'm going to close this issue.  Please let us know if you have additional questions.
