### ISSUE TITLE
mosh broadcast: textcast

### ISSUE THREAD

**Issue by poetaman** [mobile-shell/mosh#1265]
Given mosh is built on top of UDP, can it can leverage UDP's broadcast capability to broadcast a live terminal screencast ("textcast"). It could open up novel ways of using mosh, as a textcast requires way low bandwidth (e.g. 5KB/sec) compared to a video broadcast of terminal. The only requirement I see is users would need to use a TERM that has a ``smam``+``ramam`` terminfo capabilities. Perhaps mosh team can come up with a new recommended terminfo like "mosh-256color" that would be used by everyone dialing into such a textcast.

**Comment by achernya** [comment]
While this is an interesting idea, I don't think this feature belongs in mosh. Mosh heavily depends on AES-OCB for privacy and integrity and those modes are not amenable to being used in broadcast.

**Comment by eminence** [comment]
If anyone is interested in something like this, check out https://tmate.io/
