### ISSUE TITLE
mosh + neofetch gives unexpected behaviour

### ISSUE THREAD

**Issue by oregonpillow** [mobile-shell/mosh#1274]
I'm using [neofetch](https://github.com/dylanaraps/neofetch) in combination with[ oh-my-zsh](https://github.com/ohmyzsh/ohmyzsh), and it works except the rendering of the image when i use mosh. I don't particularly understand why this is happening.  When i use normal SSH, the image renders perfectly fine in my client terminal (iTerm2). 

Any suggestions or ideas what might be causing this?
Thanks!

---

**Normal SSH**
![normal SSH](https://github.com/mobile-shell/mosh/assets/53374403/33e31f2f-41ea-46c9-8205-426cf4262eac)

**Using Mosh** (image rendering broken, defaults to text art)
<img width="1510" alt="Screenshot 2023-05-26 at 13 19 37" src="https://github.com/mobile-shell/mosh/assets/53374403/d34393ed-c4c6-4e7d-a535-bbe2c3f4fbdf">

**Comment by achernya** [comment]
Mosh does not support either sixel or kitty graphics protocol. See #1081 and #1248 .

**Comment by oregonpillow** [comment]
Thanks @achernya I was already aware of this. However I'm using iTerm2 not sixel or kitty unless iTerm2 uses sixel in it's backend.

**Comment by achernya** [comment]
My mistake, I thought iterm2 used sixel but apparently it's a custom separate protocol: https://iterm2.com/documentation-images.html

The situation remains the same: mosh doesn't support any of these image protocol extensions and adding support for them is difficult as outlined in the referenced bugs.
