### ISSUE TITLE
non-ssh auth, VPN maybe

### ISSUE THREAD

**Issue by cypa** [mobile-shell/mosh#1275]
"Mosh leverages SSH to set up the connection and authenticate"
is it possible to leverage wireguard VPN, or ipsec, to set up the connection and authenticate mosh? anything else?

**Comment by eminence** [comment]
Note that you can always roll your own connection set-up if you want.  See the "How do I run the mosh client and server separately?" FAQ question on mosh.org

**Comment by cypa** [comment]
> It is not. Mosh requires being able to run processes on the destination machine, which VPN technologies do not allow.

is it a problem? could we start mosh-server on destination to listen for connection?

**Comment by achernya** [comment]
It is a problem, because mosh-server serves a single user and requires sharing the key it outputs.
