### ISSUE TITLE
Using zellij causes flickering and missing inputs

### ISSUE THREAD

**Issue by timhae** [mobile-shell/mosh#1277]
Thanks a lot for this great tool! Not sure if this is caused by [zellij](https://github.com/zellij-org/zellij) (tmux replacement) or mosh. I experience flickering and missing inputs when connecting to zellij through mosh. E.g. using `mosh server -- zellij` and then running `htop` causes flickering and missed inputs when pressing and holding the downwards button. With `ssh server`, running zellij and then within that htop, everything works as expected. Please let me know if you think this issue rather belongs to zellij. Thanks!

**Comment by achernya** [comment]
Hi @timhae, my intuition is you should start with the zellij team. To my knowledge mosh is pretty accurate in its support of different OSC sequences in its advertised $TERM.
