### ISSUE TITLE
Documentation about --bind-server=any

### ISSUE THREAD

**Issue by jsonmona** [mobile-shell/mosh#1279]
I have my server SSH behind a proxy. `haproxy` would listen on TCP 443 and disambiguate HTTPS and SSH, and relay SSH connections to local SSH server listening on port 10443. I've done this way because my school hates port 22, and port 443 is almost never blocked.

However, when I set it up this way, mosh-server mistakenly identifies 127.0.0.1 as the client IP and binds to localhost. I had to use `mosh myhost --bind-server=any` or `mosh-server ... -i 0.0.0.0` to circumvent it. I'd prefer both to be documented because some terminal apps on smartphones require configuring `mosh-server` invocation directly.

It would be nice if documentation could be improved to mention situations like this. I know `man mosh-server` has description about `-i` flag, but I had hard time figuring out *what* was wrong. Wiki mentions firewall issue, but nothing about binding.

**Comment by eminence** [comment]
As you say, both `--bind-server=any` and `-i` are already documented in the manual pages.  Is there something additional you'd like to see there?

Regarding the wiki, you're welcome to make any changes you want :)    Perhaps you could add some notes into the ["Debugging-and-Theory"](https://github.com/mobile-shell/mosh/wiki/Debugging-and-Theory) section about checking what IP the server binds to.   And maybe the ["Usage"](https://github.com/mobile-shell/mosh/wiki/Usage) page could have something that describes your case.

**Comment by jsonmona** [comment]
Yes, I'm aware they're in manual. But, you know, the manual isn't the first page you get by googling. In fact, I didn't know there was a manual until I typed `man mosh-server`!

I'll update wiki when I get back to home.
