### ISSUE TITLE
SSH Agent Forwarding

### ISSUE THREAD

**Issue by JackWolfard** [mobile-shell/mosh#1280]
5 years ago #120 was closed and marked as completed instructing users to utilize https://github.com/StanfordSNR/guardian-agent. However, that project is not maintained and cannot be used on modern laptops (StanfordSNR/guardian-agent/issues/36). What should users use now for SSH agent forwarding w/ Mosh?

**Comment by keithw** [comment]
guardian-agent is a separate project. Probably somebody (who knows Golang) should take it over and build it from source and distribute it via the normal channels (Debian/Homebrew/etc.) or GitHub releases.

**Comment by drewwells** [comment]
Guardian Agent wasn't very helpful to use, I preferred using SSH to do key operations. Another alternative is working on a way to authorize directly with 1password. It has a great suite of cli tools and may offer ways to bridge whatever technical gap mosh has with ssh-agent.

**Comment by achernya** [comment]
We have no plans to support SSH agent forwarding without [Reliable byte stream](https://github.com/mobile-shell/mosh/issues?q=is%3Aopen+is%3Aissue+label%3A%22Reliable+byte+stream%22) feature.

**Comment by muellert** [comment]
> We have no plans to support SSH agent forwarding without [Reliable byte stream](https://github.com/mobile-shell/mosh/issues?q=is%3Aopen+is%3Aissue+label%3A%22Reliable+byte+stream%22) feature.

I'm unfamiliar with this discussion, but what is "reliable byte stream", and what could be done to get it? Because w/o agent forwarding, pretty much all scenarios where you log into a jump host and then to other hosts from there, don't work with mosh, as having credentials on the jump host is out of the question.

**Comment by achernya** [comment]
Reliable byte stream is the protocol abstraction that is equivalent to ssh port forwarding. Agent forwarding is a special (mostly degenerate) case of port forwarding. We do not plan to support ssh agent forwarding through special case means.

Implementing a proper byte stream abstraction requires augmenting mosh with a full fledged UDP-based congestion control like QUIC.
