### ISSUE TITLE
Mosh, tmux, nvim rendering/redrawing issues

### ISSUE THREAD

**Issue by markolonius** [mobile-shell/mosh#1281]
When using mosh, tmux, nvim there are rendering issues that appear when switching tmux windows as seen in [this video](https://vimeo.com/846115113?share=copy)

This does not happen with ssh.  Seems to happen when using a linter or similar with nvim LSP that draws floating windows possibly? (such as when I install python-lsp-ruff or python-lsp-black).  I tried looking at similar issues however they are all years old and seem to have been issues fixed in subsequent releases.  Not sure if it is a tmux issue or mosh issue, however posting here since it only happens when using mosh.  I've tried plain default tmux confit and issue still persists.  I've attached my current [tmux config](https://github.com/mobile-shell/mosh/files/12075061/tmux_config.txt).

Using iTerm2 latest.
mosh 1.4.0
tmux 3.2a
TERM outside of tmux is xterm-256color, inside tmux both xterm-256color and tmux-256color give same rendering issue
LANG=en_US.UTF-8 is set everywhere
this is all in a docker container

**Comment by jay-ouellette** [comment]
I have this issue as well. Mosh is not redrawing the screen correctly after switching tmux sessions that are running nvim. When I use ssh instead of mosh and attach to the same tmux server, there are no drawing issue when switching tmux sessions.

MacOS 13.5.2
Alacritty 0.11.0
Mosh 1.4.0

Connected to

MacOS 13.4.1 via ethernet (on same switch)
Tmux 3.3a
Nvim v0.8.3

**Comment by julienmarie** [comment]
Same issue.

**Comment by vamsee007** [comment]
I have the same issue with Mosh + Tmux + NeoVim
 
The primary concern is Mosh doesn't support some  hieroglyphs and Nerd Fonts, due to which the redrawing/scrolling leaves some garbage characters on the screen.. 

** Try disabling the Dev Icons or any Nerd Font based icons in your Neovim config, this helped me to avoid those glitches**

However, SSH + Tmux + Neovim works fine as the character rendering is supported.

For more info
https://github.com/mobile-shell/mosh/issues/1041

**Comment by gilbertfrancois** [comment]
I can confirm this issue. Using mosh, tmux and nvim messes up the screen. When using ssh instead of mosh, the problem does not occur.

**Comment by kftang** [comment]
I have the same issue as well.

Using CentOS 7.9, mosh 1.4.0, tmux 3.3a, nvim 0.9.5

**Comment by mellery451** [comment]
+1  iterm2 --> mosh --> tmux 3.4 --> neovim 0.10 
..and the panes become unusable after just a few minutes with visual artifacts left all over the place. remove mosh from the chain (replace with ssh) and it's all good.

**Comment by iveney** [comment]
same - using Mosh it messed up the tmux pane. Even if not using mosh, using nvim will cause my whole screen to be green...

switching to ssh does not have this problem.

**Comment by OceanXS** [comment]
same issue -when using ***helix*** editor

**Comment by Drag0nFly** [comment]
Seeing this as well–

iTerm2 3.5.0 -> mosh 1.4.0 -> -> fish 3.7.1 -> alpine 2.26

Any time an email with a _high-ascii_ or _emoji_ is displayed, rendering is messed up. Also seeing a similar behaviour in the shell when escaping characters (i.e, mv long filename with spaces and adding \ in front of space, paranthesis, etc.) which causes the characters in the command line to be misplaced (display is not "in sync" with the actual commandline). This also occurs with MATE Terminal on Linux, so not iTerm2 specfic.

Really hoping this can be fixed, as it is quite a nuisance when one relies on mosh for remote sessions.

**Comment by keithw** [comment]
As has been explained in several other issues, Mosh just uses the libc wcwidth API to know the width of each character. At least until/unless Mosh decides to vendor this itself, you'll have to take this up with your libc vendors. (Apple unfortunately is pretty bad at keeping their Unicode support in macOS up-to-date, but if you're an Apple customer, better for them to hear it from you than from a third-party piece of software that just uses their API.)

**Comment by Drag0nFly** [comment]
Ok, thanks for the quick reply. It's also an issue with Linux/glibc unfortunately, so not Apple specific. It was just what I tested with from work.

**Comment by xyproto** [comment]
@keithw I do not think this is a width-related issue, because Orbiton has issues in connection with redrawing when running under mosh, and the problem can temporarily go away after refreshing/redrawing several times.

**Comment by heywoodlh** [comment]
This seems to also be an issue while using Zellij. Will be submitting a bug report to their GitHub repository and linking this thread for awareness.

**Comment by tidux** [comment]
> As has been explained in several other issues, Mosh just uses the libc wcwidth API to know the width of each character. At least until/unless Mosh decides to vendor this itself, you'll have to take this up with your libc vendors. (Apple unfortunately is pretty bad at keeping their Unicode support in macOS up-to-date, but if you're an Apple customer, better for them to hear it from you than from a third-party piece of software that just uses their API.)

This seems to be fixed on all recent glibc distros but still present in Apple libc:

```
[ Mac ] == mosh ==> [ GNU/Linux ] =>[tmux]=>[nvim] 
```
shows glitches, but
```
[ Mac ]==mosh==>[ 2nd GNU/Linux with newer glibc]=>[tmux]=>[nvim]
[ Mac ]== ssh ==>[ 2nd GNU/ Linux with newer glibc ]== mosh ==>[ GNU/Linux ]=>[tmux]=>[nvim]
```
do not.  Identical nvim configs, identical starting terminal on the Mac side.
