### ISSUE TITLE
Getting mosh work on Windows with truecolor (24-bit)

### ISSUE THREAD

**Issue by ppetr** [mobile-shell/mosh#1288]
I'm double-posting my SO question https://superuser.com/q/1803653/162491 here in case this happens to be a known bug/issue:

----

I'm trying to get mosh.org work on Windows with truecolor (24-bit) support. Mosh [includes truecolor support](https://github.com/mobile-shell/mosh/commit/6cfa4aef598146cfbde7f7a4a83438c3769a2835) since [version 1.4](https://github.com/mobile-shell/mosh/issues/961). However:

- There is no native Windows client.  The website https://mosh.org/#getting points to using a Chrome extension.
- The extension [is no longer supported](https://github.com/rpwoodbu/mosh-chrome/issues/223) and doesn't work with recent Chrome versions.
- Instead [it's suggested](https://github.com/rpwoodbu/mosh-chrome/issues/223#issuecomment-1268422280) to use the [Ssh Extension](https://chrome.google.com/webstore/detail/iodihamcpbpeioajjeobimgagajmlibd) which now includes Mosh. But **only version 1.3.2.**

----

Then I tried to compile Mosh 1.4 from source on [WSL](https://learn.microsoft.com/en-us/windows/wsl/). It compiled just fine:

```
% mosh --version
mosh 1.4.0 [build mosh-1.4.0-19-g1105d48]
```

I have `COLORTERM=truecolor` set. Truecolor support works locally within [Windows Terminal](https://apps.microsoft.com/store/detail/windows-terminal/9N0DX20HK701), tested with https://github.com/termstandard/colors.

[![enter image description here][1]][1]

I also have

```
% cat ~/.ssh/config
SendEnv             COLORTERM
```

so that the variable propagates to the remote system.

When connecting via ssh, truecolor support works. But when connecting via mosh 1.4 (and also 1.3.2), truecolor still doesn't work.

[![enter image description here][2]][2]

Any ideas how to debug the problem further?

  [1]: https://i.stack.imgur.com/Jzitn.png
  [2]: https://i.stack.imgur.com/L7sVk.png

**Comment by achernya** [comment]
What version of mosh is on your server? Both client and server need to be updated to 1.4.0 or newer.

**Comment by ppetr** [comment]
Ah, I didn't realize that, that's for sure the problem. Thanks!

**Comment by ppetr** [comment]
Works 👍
