### ISSUE TITLE
[REQ] Better way of handling locale

### ISSUE THREAD

**Issue by xxxserxxx** [mobile-shell/mosh#1329]
I would like a better way of handling locale issues in mosh; in particular, I'd like mosh to respect the settings in `~/.ssh/config`. There are a couple of related tickets; the closest is #793, which is locked and in which the last comment is "please open a new ticket" for further discussion.

I have an unusal locale set-up: it's a custom environment based on  `en_US.UTF-8`, except with a sane (ISO 8601) timestamp. This is _only_ configured on my desktop, and it obviously causes trouble with ssh-ing into servers. Therefore, I have `SendEnv -LANG -LC_*` set in `~/.ssh/config`, which works fine. However, mosh ignores this setting and tries to send the locale environment variables anyway.

Anti-solutions are:

1. Configuring the server to have my custom locale: first, this is not always within the user's power; and second, I don't _want_ my servers to have my custom locale, to avoid potentially affecting services.
2. Using vanilla `en_US.UTF-8` instead of my custom locale as my system setting. In some programs (e.g., [sc-im](https://github.com/andmarti1424/sc-im)), the only control over the date format is the locale. And, frankly, users should be able to muck around with their desktop locales to get the formatting they want.
3. Using an English locale that already has a sane `LC_TIME` like `en_CA`. This fails if the server hasn't been configured for that locale, and (again) doing so may be neither in the control nor desire of the user. Many distributions pare down the default configured locales to a single locale selected by the user during install.

The work-around I'm using is a wrapper alias around `mosh` that resets the locale environment variables to base `en_US.UTF-8` before calling mosh, but is a hacky solution. It would be a better user experience if mosh respected the settings in `~/.ssh/config`, which provides reasonably fine-grained control over how environment variables are handled; this would allow, for instance, passing on my frankenstein locale to servers I've configured to support it, while stripping the locale back to vanilla for ones that don't.

**Comment by andersk** [comment]
By default, the Mosh server already leaves in place the locale variables passed (or not) via `ssh`, respecting `~/.ssh/config`. If the variables from `ssh` were insufficient to get it a working UTF-8 locale, *then* it falls to using the extra locale variables passed directly from the Mosh client.

What is the output of `ssh -n -tt YOURSERVER locale`?

https://github.com/mobile-shell/mosh/blob/1105d481bb9143dad43adf768f58da7b029fd39c/src/frontend/mosh-server.cc#L336-L372

**Comment by xxxserxxx** [comment]
That's interesting, because:

1. Without the `SendEnv -LANG -LC` I get the locale errors with ssh
2. **With** the `SendEnv` line, I can ssh into the server _without_ getting the errors
3. I always get the errors with mosh, regardless of whether I have the `SendEnv` line in `~/.ssh/config`

The "ssh locale" command gives me:

```
LANG=
LC_CTYPE="POSIX"
LC_NUMERIC="POSIX"
LC_TIME="POSIX"
LC_COLLATE="POSIX"
LC_MONETARY="POSIX"
LC_MESSAGES="POSIX"
LC_PAPER="POSIX"
LC_NAME="POSIX"
LC_ADDRESS="POSIX"
LC_TELEPHONE="POSIX"
LC_MEASUREMENT="POSIX"
LC_IDENTIFICATION="POSIX"
LC_ALL=
```

So, this must be related to the comment I've seen that mosh -- unlike ssh -- _requires_ at UTF-8 locale setting, and my configuration is just telling the ssh client to not send anything to the server, whereby it defaults to whatever on the server. Is that right?

**Comment by andersk** [comment]
That’s right, Mosh requires a UTF-8 locale, so that it can correctly understand and optimize the terminal command sequences that flow through it. It’s up to you whether to configure the locale by passing it through SSH or Mosh or by configuring your server’s system locale (e.g. using [`localectl`](https://www.freedesktop.org/software/systemd/man/latest/localectl.html) on a systemd-based OS).
