### ISSUE TITLE
Poor terminal optimisation with scrolling regions

### ISSUE THREAD

**Issue by peterjeremy** [mobile-shell/mosh#135]
I have been comparing mosh with ssh when running weechat-curses (an IRC etc client) and have found that mosh generates far more network traffic.  As an example, the following update (written by weechat-curses) causes mosh to send about 1550 bytes in 3 packets, whilst SSH sends about 48 bytes.  Normal scrolling doesn't have this problem so it's presumably related to the use of scrolling regions

       0x0000 1b5b 373b 3431 721b 5b34 313b 3148 0a1b  |.[7;41r.[41;1H..|
       0x0010 5b31 3b34 3372 1b5b 3431 3b31 481b 5b33  |[1;43r.[41;1H.[3|
       0x0020 326d 5b1b 5b33 396d 3135 1b5b 3333 6d3a  |2m[.[39m15.[33m:|
       0x0030 1b5b 3339 6d31 391b 5b33 336d 3a1b 5b33  |.[39m19.[33m:.[3|
       0x0040 396d 3137 201b 5b33 326d 1b5b 316d 401b  |9m17 .[32m.[1m@.|
       0x0050 5b33 396d 7065 7465 721b 5b6d 1b5b 3332  |[39mpeter.[m.[32|
       0x0060 6d5d 1b5b 3339 6d20 4973 6e27 7420 7468  |m].[39m Isn't th|
       0x0070 6174 204e 4545 4d41 2028 6f72 2077 6861  |at NEEMA (or wha|
       0x0080 7465 7665 7220 6974 2773 2063 616c 6c65  |tever it's calle|
       0x0090 6429 3f1b 5b34 333b 3133 481b 5b6d       |d)?.[43;13H.[m|

**Comment by cgull** [comment]
Closing, I've committed code that fixes or at least changes this.  Please open a new issue if you still have performance issues.
