### ISSUE TITLE
Bug when changing port OSX?

### ISSUE THREAD

**Issue by Pezmc** [mobile-shell/mosh#138]
I am trying to change the port to 92, this doesn't seem to work on my Mac?

"pezcuckowmbp:~ pezcuckow$ mosh --port=92 umgs@brave
/usr/bin/mosh: connect to host 130.88.**.** port 22: Connection refused
pezcuckowmbp:~ pezcuckow$ mosh -p 92 umgs@brave
/usr/bin/mosh: connect to host 130.88.**.** port 22: Connection refused
ssh_exchange_identification: Connection closed by remote host
/usr/bin/mosh: Did not find mosh server startup message.
pezcuckowmbp:~ pezcuckow$ mosh -p92 umgs@brave
Unknown option: p92"

**Comment by mkozjak** [comment]
This still isn't in mainline?
