### ISSUE TITLE
Scrollback and shift-PageUp/PageDown

### ISSUE THREAD

**Issue by phmarek** [mobile-shell/mosh#145]
In many terminal emulators shift+PageUp/PageDown allow to look back at the scrollback buffer; or, when a full-screen program is running (vim, screen), they are inhibited.

mosh does neither - scrolling back shows "bad" output (ie. simply cut off), and works in a ncurses program too (like vim).

So the easy way out would be to inhibit these keys; the "better" way might be to store some "historical" data (ie. the scrollback buffer), this might be fairly easy because of the delta sending (I'm hoping).

Having a configurable scrollback-buffer might then allow to see repeated data, ie. an (mostly) identical "ls -la"  output - and that could be delta-encoded again, saving bandwidth.

Thanks a lot!

**Comment by nmz787** [comment]
so how do I scroll back in stdout history???
