### ISSUE TITLE
Logging into Linerva from OS X with a password somehow gets me the wrong tokens

### ISSUE THREAD

**Issue by xavidotron** [mobile-shell/mosh#149]
dhcp-172-31-205-227:~ xavid$ mosh linux.mit.edu --server='athrun mosh_project mosh-server'
Password: 

\
\
WARNING: You have no valid AFS tokens.
See http://debathena.mit.edu/ssh

bash: /afs/athena.mit.edu/user/x/a/xavid/.bash_login: Permission denied
xavid@dr-wily:~$ tokens

Tokens held by the Cache Manager:

User's (AFS ID 35127000) tokens for afs@csail.mit.edu [Expires Apr 11 23:44]
   --End of list--
xavid@dr-wily:~$ klist
Ticket cache: FILE:/tmp/krb5cc-mosh_41327_nctdvQ
Default principal: xavid@ATHENA.MIT.EDU

Valid starting     Expires            Service principal
04/11/12 11:43:58  04/12/12 08:58:58  krbtgt/ATHENA.MIT.EDU@ATHENA.MIT.EDU
        renew until 04/12/12 11:43:58
04/11/12 11:43:58  04/12/12 08:58:58  afs/athena.mit.edu@ATHENA.MIT.EDU
        renew until 04/12/12 11:43:58
04/11/12 11:43:59  04/12/12 08:58:58  afs/sipb.mit.edu@ATHENA.MIT.EDU
        renew until 04/12/12 11:43:58
04/11/12 11:44:01  04/12/12 08:58:58  krbtgt/CSAIL.MIT.EDU@ATHENA.MIT.EDU
        renew until 04/12/12 11:43:58
04/11/12 11:44:01  04/11/12 23:44:01  afs@CSAIL.MIT.EDU
        renew until 04/11/12 11:44:01
xavid@dr-wily:~$ 

I don't know if this is something with mosh, or with linerva, or something weird about my setup I missed.  I see the same behavior on athena.dialup.mit.edu.  In both cases, logging in over ssh with no tickets using a password works.

**Comment by achernya** [comment]
Linerva has been turned down.
