### ISSUE TITLE
rxvt-unicode control-arrowkeys incompatible with mosh

### ISSUE THREAD

**Issue by keithw** [mobile-shell/mosh#161]
For control-arrowkey, xterm and gnome-terminal (and I think Terminal.app) send ^[[1;5D

But rxvt-unicode sends ^[Od .

Unfortunately this confuses mosh (which puts the user in application-mode cursor keys and translates them to ANSI if necessary, which requires no lookahead). See terminaluserinput.cpp

Solution 1: More lookahead to correctly translate rxvt-unicode cursor keys (we have to see what the byte is AFTER ^[O, aka SS3, to know whether it needs to be translated to ANSI mode). I don't want to do more lookahead though, because it means delaying when a byte gets sent to the server in some cases, and it's easier to just never do this.

Solution 2: Stop translating cursor keys, and just propagate the application's choice of cursor key mode all the way to the outer terminal, and maintain it as part of the synchronized state. This has some appeal, but I'm not sure what the difficulties will be without trying it.

Solution 3: Declare it a bug in rxvt-unicode.

Thanks to Meelap for identifying this.

**Comment by anarcat** [comment]
for the record, i do not believe this is fixed at all. but this seems to be tracked in #178...

**Comment by tsmithe** [comment]
If this is indeed tracked in #178, then the work-around suggested there does not seem to work for me. I also do not believe that this is fixed.
