### ISSUE TITLE
mosh client is unkillable while trying to connect

### ISSUE THREAD

**Issue by phik** [mobile-shell/mosh#174]
In the 30-second-or-so interval between starting the client:

> $ mosh server

and it showing the blue connection bar:

> mosh: Connecting... (9 s without contact.) [To quit: Ctrl-^ .]

it doesn't honour C-c or C-z or C-^ . or ~., which makes it effectively unkillable except from another shell.

Makes debugging connection issues somewhat irritating.

**Comment by eminence** [comment]
This issue is no longer reproducible in the latest mosh (1.3)
