### ISSUE TITLE
Mosh doesn't show motd

### ISSUE THREAD

**Issue by jamgregory** [mobile-shell/mosh#190]
Sorry if this issue has been brought up before (I couldn't find it if it was) but mosh doesn't appear to show the message of the day (/etc/motd) when starting. Is there some way to enable this, either server-side or client-side?

**Comment by mcginty** [comment]
For the record, this doesn't work in Ubuntu 16.04.1 LTS. MOTD is stored in /etc/update-motd.d, and IIRC there's a PAM module that runs the MOTD (a la `run-parts /etc/update-motd.d`).

**Comment by mhalano** [comment]
I can confirm the MOTD doesn't work on Ubuntu 16.04.1 LTS. But if you create manually a file /etc/motd the works.

**Comment by mhalano** [comment]
@mcginty I found this page: https://www.devinhoward.ca/ideas/2015/nov/make-mosh-print-message-day-ubuntu-1404 which has a interesting workaround:
sudo ln -s /var/run/motd.dynamic /etc/motd
And all works great.
Now I'm trying to do MOTD work with Byobu. :)

**Comment by jshap70** [comment]
@mhalano 's work around brings back up the problem of having it print twice when you use a different login method.

**Comment by cgull** [comment]
I recently added code to Mosh to print both `/etc/motd` and `/var/run/motd.dynamic`, which will also print twice with @mhalano's slightly hackish workaround.  That's available in version 1.3.2 and later.

**Comment by mhalano** [comment]
I tested now (better late than never, ugh?) on a fresh machine with Ubuntu 17.10, I connecte from the same machine and from other machine and and both work like a charm.
