### ISSUE TITLE
Mac OS X mach bootstrap context (or something) is wrong

### ISSUE THREAD

**Issue by saurik** [mobile-shell/mosh#223]
In #218, @jcftang reported an issue using "w" from a mosh session connected to a Mac OS X 10.6.8 server. This issue is not equivalent to the race condition documented in #221: the workaround I presented there did not solve this issue (although you might need that workaround for fixes for this issue to be effective; untested).

The specific symptom (which I was easily able to reproduce) is an error report about the "DNS configuration info service", and the code that is failing is going to look like the function `_dns_configuration_server_port` from configd in [dnsinfo_private.c](http://www.opensource.apple.com/source/configd/configd-395.6/dnsinfo/dnsinfo_private.c) (and may actually be exactly that code: that code may be part of a static library or common stub generation).

This bug does seem to be fixed (on my system with my reproduction: this is is as yet unconfirmed by @jcftang) by the code I submitted as part of pull request #219 that uses /bin/login to portably and correctly handle spawning the login shell.

```
$ w
could not lookup DNS configuration info service: (ipc/send) invalid destination port
15:56  up 9 days, 56 mins, 8 users, load averages: 0.95 1.00 0.87
USER     TTY      FROM              LOGIN@  IDLE WHAT
...
```

**Comment by eminence** [comment]
Recommend closing this in favor of #249 which seems to have more discussion/details.

**Comment by cgull** [comment]
Closing as obsolete, please comment on #249 if you are having issues with this.
