### ISSUE TITLE
installation through fink

### ISSUE THREAD

**Issue by jbaraban** [mobile-shell/mosh#227]
It'd be great if mosh was available for installation through fink on OS X.  I've written a draft of a .info file, which works to install mosh on my system (10.6.8, Fink version 0.32.6).  It is almost certainly not up to snuff for general distribution use yet.  The compilation complains about the lack of utempter, but the final product works in my extremely limited testing.

Package: mosh
Version: 1.1.3
Revision: 1
Depends: protobuf-c 
BuildDepends: boost1.41.cmake
Source: https://github.com/downloads/keithw/%n/%n-%v.tar.gz
Source-MD5: de507695b6f67523bc81596f97220a9a
License: GPL
Homepage: http://mosh.mit.edu
Maintainer:  ?
Description: Mobile shell
DescDetail: <<
Remote terminal application that allows roaming, supports intermittent 
connectivity, and provides intelligent local echo and line editing of 
user keystrokes.
<<

Thanks for a great program.  -Josh

**Comment by achernya** [comment]
According to the fink homepage, they do not support modern macOS (11 or 12).
