### ISSUE TITLE
brew installed, bash: mosh-server: command not found...

### ISSUE THREAD

**Issue by yixizhang** [mobile-shell/mosh#237]
installed the latest version, 1.1.3, tried to run mosh username@server-path, and entered the password, keep receiving the error message: bash: mosh-server: command not found... but checked and pretty sure that mosh-server and mosh-client were installed in the same directory, /usr/local/bin as well.

**Comment by h3rb** [comment]
Same problem here, I can ssh into the Mac and type mosh-server and everything looks as iamchanghyunpark describes.  Then when I ssh in using Mosh-Client for Google Chrome, I get 

Bad response when running mosh-server: 'bash: mosh-server: command not found

**Comment by andersk** [comment]
Since this closed issue seems to be a popular place to go for people with similar symptoms: if you are seeing a message like `mosh-server: command not found`, you need to make sure that

1. The `mosh-server` command is **installed on the server**,
2. The `mosh-server` command is **in your server’s PATH**, and
3. The `mosh-server` command is _still_ in your server’s PATH if you **run it directly from the SSH command line**. Try these commands:

```
ssh HOSTNAME 'mosh-server --help'
````

or

```
ssh HOSTNAME 'echo $PATH'
```

It seems that some systems satisfy (2) but not (3), perhaps because PATH is not being set in the right dotfiles. (I wouldn’t blame you—which dotfiles are executed where can be a confusing system-dependent mess.)

If you don’t want to fix your dotfiles, you can work around this by passing the `--server` option: `mosh --server=/full/path/to/mosh-server HOSTNAME`.

**Comment by Manouchehri** [comment]
# Problem
```sh
dave@mbp ~ % mosh m1@mac.315.intra.google.com
zsh:1: command not found: mosh-server
Connection to 142.250.64.141 closed.
/opt/homebrew/bin/mosh: Did not find mosh server startup message. (Have you installed mosh on your server?)
```

# Solution
```sh
mosh --server=/opt/homebrew/bin/mosh-server m1@mac.315.intra.google.com
```

# Setup
This assumes you've previously install brew and mosh on your M1:
```sh
/bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
brew install mosh
```

**Comment by joevandyk** [comment]
The best answer:

Create or edit your `~/.zshenv` file and add the following:
```
PATH=/opt/homebrew/bin/:$PATH
```

`.zshenv` is read for non-interactive shells.  https://unix.stackexchange.com/questions/71253/what-should-shouldnt-go-in-zshenv-zshrc-zlogin-zprofile-zlogout has more.

**Comment by gregpalaci** [comment]
> The best answer for macOS:
> 
> Create or edit your `~/.zshenv` file and add the following:
> 
> ```
> PATH=/opt/homebrew/bin/:$PATH
> ```
> 
> `.zshenv` is read for non-interactive shells. https://unix.stackexchange.com/questions/71253/what-should-shouldnt-go-in-zshenv-zshrc-zlogin-zprofile-zlogout has more.

This is it, not a way to automate with brew install?

**Comment by cmjdmiller** [comment]
> The best answer for macOS:
> 
> Create or edit your `~/.zshenv` file and add the following:
> 
> ```
> PATH=/opt/homebrew/bin/:$PATH
> ```
> 
> `.zshenv` is read for non-interactive shells. https://unix.stackexchange.com/questions/71253/what-should-shouldnt-go-in-zshenv-zshrc-zlogin-zprofile-zlogout has more.

This fixed it for me..
I reinstalled mosh using Brew to make sure I had a fresh install that didn't help.
I ensured my PATH was updated with the location I verified via which mosh-server / which mosh.
It was still part of my path when logged in via SSH.
I was able to manually connect mosh when specifying the --server switch to the right location so I knew it was installed properly.
Then I created the .zshenv file and edited with VIM adding the line you supplied and now I can mosh to the machine without issues.

**Comment by jswhisperer** [comment]
@cmjdmiller glad it helped if you wanna maybe a thumbs or something? I usually look for the most +1s or thumbs when doom scrolling issues haha but totally up to you.

**Comment by achernya** [comment]
Folks, can we please take the homebrew-specific discussion elsewhere? This is a closed issue (for over a decade!), and it appears that discussion has veered off into something that has more to do with homebrew's packaging choices for mosh (of which we are not the maintainers!) than mosh itself.
