### ISSUE TITLE
mosh script interacts badly with ControlMaster

### ISSUE THREAD

**Issue by ebroder** [mobile-shell/mosh#24]
I'm not sure exactly what's going on, but I use ControlMaster to avoid establishing multiple connections to a server. If I have an open ssh connection to a server (and therefore an active ControlMaster socket), starting mosh fails:

```
evan@warwick:~$ ssh -N broder@spock.tribbl.es

evan@warwick:~$ ls .ssh
authorized_keys                    id_dsa      known_hosts
authorized_keys2                   id_dsa.pub  known_hosts.old
config                             id_rsa
control-broder@spock.tribbl.es:22  id_rsa.pub
evan@warwick:~$ mosh broder@spock.tribbl.es
/usr/bin/mosh: Did not find mosh server startup message.
```

The relevant portion of .ssh/config is:

```
Host *
    ControlPath ~/.ssh/control-%r@%h:%p
    ControlMaster auto
    ControlPersist 1
```

**Comment by ScoreUnder** [comment]
>This fix annoys me a lot

You're not the only one. I have a workaround though:

```bash
#!/bin/sh
die() { printf %s\\n "$*" >&2; exit 1; }

# Start mosh on the server, retrieve its IP from ipinfo.io
# Feel free to replace with a better method of finding the IP
info=$(ssh "$@" <<\END_SSH
    . /etc/locale.conf >&2;
    export LANG
    env -u SHLVL mosh-server || exit
    echo '=cut='
    curl -sS ipinfo.io | jq -r .ip
END_SSH
) || die 'SSH reported failure, giving up.'

# Ensure these variables are not already filled (in the environment)
# Because we check their contents later
mosh_port=
MOSH_KEY=

while read -r mosh connect port key; do
    # Don't allow curl/jq output to bleed into mosh output parsing
    [ "$mosh" = '=cut=' ] && break

    if [ "$mosh $connect" = "MOSH CONNECT" ]; then
        mosh_port=$port
        MOSH_KEY=$key
        break
    fi
done <<EOF
$info
EOF

if [ "$mosh $connect" != "MOSH CONNECT" ] || [ -z "$mosh_port" ] || [ -z "$MOSH_KEY" ]; then
    die 'Did not find mosh server banner'
fi

lf='
'
# IP should be the very last line, so delete everything up-to-and-including the final LF
ip=${info##*"$lf"}

# Only really need to check for "-" which could be used to pass switches to mosh-client
# Anything else mosh-client will reject as a bad IP
[ "${ip#-}" = "$ip" ] || die 'Malformed IP from ipinfo.io'
# If jq didn't output anything, the last line will be our '=cut='
[ "$ip" = '=cut=' ] && die 'No IP from ipinfo.io'

export MOSH_KEY
exec mosh-client "$ip" "$mosh_port"
```
Judge for yourself how much of a hack that is.
I've tried my best to keep it secure in the sense that a MITM between the server and ipinfo.io shouldn't cause any security issues, but of course they can still cause a denial of service because the script might no longer work.

**Comment by lilydjwg** [comment]
@ScoreUnder Thanks! :+1: Your script works well and doesn't need a JSON parser actually. Just `curl ipinfo.io/ip` and you'll get it :-)

**Comment by ScoreUnder** [comment]
Thanks for the catch, I've now updated the post above to reflect that. It's always nice to be able to remove unnecessary dependencies :smile:

**Comment by jettero** [comment]
This was closed in 2012?

I just found that -S none in the mosh client script. *sigh* There's got to be a better way to do that.

**Comment by cgull** [comment]
Actually, now that we have `--experimental-remote-ip=local` and `--experimental-remote-ip=remote`, we could remove `-S none` for those options.

(Compromises, compromises.  There's no perfect solution to finding the remote IP.)

**Comment by cgull** [comment]
Oops, I commented before looking at the code-- which already does exactly that.  Try those options.

**Comment by jettero** [comment]
Oh, interesting. In my mosh-client "bin" there's a hardcoded -S none ... you're saying if I update there's commandline args that disable it I think. Checking.

**Comment by lilydjwg** [comment]
Sadly `--experimental-remote-ip` doesn't work for me in some cases. With `remote`, it gets the intranet IP; with `local`, it doesn't pick up my settings in ssh config.

**Comment by jettero** [comment]
What about some of these environment variables?

ssh to outside IP of a host, then issue `set | grep ^SSH_`:
````
SSH_AUTH_SOCK=/tmp/ssh-xxxxxx/agent.2471
SSH_CLIENT='75.x.x.x 41434 22'
SSH_CONNECTION='75.x.x.x 41434 10.x.x.x 22'
SSH_TTY=/dev/pts/10
```

ssh to inside IP (through VPN) of the same host `set | grep ^SSH_`:
```
SSH_AUTH_SOCK=/tmp/ssh-xxxxx/agent.28706
SSH_CLIENT='10.x.x.x 45992 22'
SSH_CONNECTION='10.x.x.x 45992 10.x.x.x 22'
SSH_TTY=/dev/pts/10
```

**Comment by lilydjwg** [comment]
@jettero In my case the server is behind a NAT with port-forwarding settings. The server itself doesn't know its outside IP. If `--experimental-remote-ip=local` could pick up my ssh_config settings it would work well for my case.

I know this option resolves the hostname itself and passes IP to ssh in case the hostname resolves to a different IP. My hostname won't do that however, and I think everyone should ensure the hostname they're sshing into doesn't change back and forth frequently.

**Comment by jettero** [comment]
Yeah, mine seems to know. If I ssh to it on the outside IP, even through the nat, the env vars show the pub IP and the inside IP both. See the first block.

**Comment by ssb22** [comment]
I have an account on an SSH server run by an institution which stores users' home directories on a Windows filestore and sets their Linux SSH server to mount them via CIFS.  Unfortunately this CIFS arrangement is such that the SSH server requires a user's password before it can access that user's home directory, therefore `.ssh/authorized_keys` is not an option and a password must be typed.  So I set a `ControlMaster` to avoid having to re-type my password into every single `ssh` and `scp` command.  The `-S none` fix means I do have to retype my password when running `mosh`.  But thankfully, adding `--experimental-remote-ip=remote` to my `mosh` alias works for me because the server knows its outside IP.
