### ISSUE TITLE
Enable non-TTY usage.

### ISSUE THREAD

**Issue by jimsynz** [mobile-shell/mosh#242]
We've been using protocols like tornado to speed up transfers over our local research network and Internet2 as TCP is not well suited to high-bandwidth high-latency links. It would be great to be able to use mosh as the backend to rsync by setting `RSYNC_RSH=mosh`.

When I doing this I get the following error: 

```
Given filehandle is not a tty in clone_winsize_from, called at /usr/local/bin/mosh line 164
rsync: connection unexpectedly closed (0 bytes received so far) [receiver]
rsync error: unexplained error (code 102) at /SourceCache/rsync/rsync-42/rsync/io.c(452) [receiver=2.6.9]
```

**Comment by shivawu** [comment]
Already closed, but +1 for this.
Even the latency will not be better, using mosh is usually not about that. It's about the ability to auto-reconnect and recover the connection compared to SSH. :-)
