### ISSUE TITLE
mosh-server on OS X sometimes lacks a Mach context

### ISSUE THREAD

**Issue by kmcallister** [mobile-shell/mosh#249]
Summarizing from #221:

> if sshd shuts down before the login shell starts up... then the resulting shell is pretty much entirely broken: you can't even figure out your own username (whoami returns numbers and bash simply prints "I have no name!"), much less talk to complex Mach services such as launchd.

See also #223.

**Comment by cgull** [comment]
Recently seen and probably relevant: https://github.com/ChrisJohnsen/tmux-MacOSX-pasteboard

(tl;dr: undocumented, unstable Apple APIs)

**Comment by quentinmit** [comment]
mosh does not use `daemon(3)` so it sounds like mosh-server could just call `_vprocmgr_detach_from_console`. It sucks that it's a private API, but given that Apple patches screen, it seems like it ought to be fairly stable. Nice find!

**Comment by cgull** [comment]
Looking back at #221, I think I'd be happier making the parent wait for the forkpty child, if that solves the problem-- that's simpler, completely portable, and offers us opportunities to report errors that we can't report right now.

Why is this failure seemingly rare?  I use mosh-server on OS X a fair bit and I've never encountered this problem, and there've been no me-toos here in 2.5 years.

**Comment by cgull** [comment]
I'm closing this and #223 as obsolete, OS X 10.6.8 is quite old and hasn't received any updates in over a year.  But if you're still pained by this problem, please reopen this issue or comment here, and we'll look at it.
