### ISSUE TITLE
Supporting midnight commander hidden terminal output

### ISSUE THREAD

**Issue by asergeyev** [mobile-shell/mosh#260]
An ancient (but useful) program "midnight commander" (mc) and it's editor (mcedit) have ability to keep terminal output hidden and until you hit Ctrl+O ... 

I know it's not commonly used and rather to not affect anyone else of current mosh users but it would be nice to see why this happens.  I tried in text console, in xterm and gnome-terminal, everyone have same thing, hidden output is not redrawn when you hide mc stuff.

**Comment by al-zatv** [comment]
ha, 7 years pass,and everybody around me still using mc.
