### ISSUE TITLE
Issue with iterm2 login command under Mac OS X

### ISSUE THREAD

**Issue by lxyu** [mobile-shell/mosh#281]
I'm using iterm2 under Mac OS X 10.7.4

I always change the `Profiles -> General -> Command` setting from `login shell` to a login command with a key binding for a quick login.

For example bind `Ctrl + P` to a machine1 profile with this command:

```
ssh machine1
```

But if I replace it with

```
mosh machine1
```

iterm2 will closes right away with this displayed:

```
## exec failed ##
argpath=mosh error=No such file or directory
```

Any ideas on how to solve this problem?

**Comment by Huang-Libo** [comment]
This works for me
`sh -c "export LANG=\"en_US.UTF-8\"; /usr/local/bin/mosh user@example.com"`
