### ISSUE TITLE
"Connecting.." with no error when no permissions to /dev/ptmx

### ISSUE THREAD

**Issue by andre-d** [mobile-shell/mosh#298]
I did not have permissions to /dev/ptmx and could not figure out why mosh would not work (Infinite count-up Connecting... screen).  I figured it out once I tried to run screen and it told me "No more available PTYs" or something to that regard.  Mosh should likely error out there similar to screen does instead of connecting indefinitely.

**Comment by achernya** [comment]
mosh >1.2 has been released for over a decade, which added the timeout. I don't think there's anything else to be done here.
