### ISSUE TITLE
Make mosh-server exit if no connection started in 60 seconds

### ISSUE THREAD

**Issue by keithw** [mobile-shell/mosh#30]
The mosh-server should quit gracefully if there has been no connection established after 60 seconds. This will lead to fewer mosh-servers lingering around.

**Comment by zylian1** [comment]
Hi,
Is there any option to disable this feature? Like if I don't want to run SSH on my server, so I can just have mosh-server waiting indefinitely for a connection from mosh-client?

**Comment by The-Compiler** [comment]
No - mosh uses ssh for authentication, i.e. this way there are a lot of problems mosh doesn't need to solve itself.

You could build something which does authentication based on something else, spawns mosh-server and gets the key to you securely somehow, but you can't run mosh-server as a daemon.

**Comment by zylian1** [comment]
Think I'll use TeamViewer, easiest solution.
