### ISSUE TITLE
cxxwrapper patch-3: servname not supported for ai_socktype

### ISSUE THREAD

**Issue by rurban** [mobile-shell/mosh#303]
http://mailman.mit.edu/pipermail/mosh-devel/2012-July/000271.html

On cygwin with pianucci's patch-3 branch:

 $ mosh --ssh='ssh -p 222' florian@the-compiler.org
   mosh: Could not resolve hostname the-compiler.org: getaddrinfo:
   servname not supported for ai_socktype

**Comment by eminence** [comment]
This a bug report on a pretty ancient version of mosh, going to assume this issue is no longer reproducible.
