### ISSUE TITLE
-fPIE / -pie is broken on Android, Maemo on ARM

### ISSUE THREAD

**Issue by kmcallister** [mobile-shell/mosh#309]
> &lt;kmc&gt; can you paste the config.log output somewhere?  it should auto-detect which flags work
> &lt;ddrown&gt; android/arm is cross-compiling, so the flags "work" the binary just segfaults on startup
> &lt;kmc&gt; oh, awkward
> &lt;kmc&gt; well, maybe i should add a --disable-pie flag

**Comment by eminence** [comment]
Without more actionable information, I'm going to close this.  We can re-open it if there is something to discuss.
