### ISSUE TITLE
Fails and asks about ProxyCommand - I don't use ProxyCommand

### ISSUE THREAD

**Issue by lizsugar** [mobile-shell/mosh#311]
I have three machines:
- alademan (a VPS)
- ophiuchus
- taco

The ~/.ssh/config and /etc/ssh/sshd_config files are _identical_ on all three of the machines.  They are all running the same version of mosh and all have the latest update for OpenSSH.

There are **zero** mentions of ProxyCommand in any of the configuration files.  

I've installed mosh 1.2.2-1 from the Arch community repo as well as the latest git pull and I get this issue on only one of my three machines:

```
ophiuchus ~ > mosh localhost
MOSH IP 127.0.0.1
satoshi@localhost's password: 

/usr/bin/mosh: Did not find remote IP address (is SSH ProxyCommand disabled?).
ophiuchus ~ > mosh taco
MOSH IP 192.168.1.22

/usr/bin/mosh: Did not find remote IP address (is SSH ProxyCommand disabled?).
ophiuchus ~ > 
```

The following connections **do work**:
- taco -> alademan
- taco -> taco ('cause why not)
- taco -> ophiuchus
- alademan -> alademan
- alademan -> taco (taco is the only machine visible from outside my local network)

The following connections **do not work**:
- ophiuchus -> alademan
- ophiuchus -> taco
- ophiuchus -> ophiuchus

Again, each machine has _identical_ configurations for SSH, none of which mention ProxyCommand anywhere.  The fact that moshing to localhost fails on ophiuchus indicates to me that something else is at play here and that the ProxyCommand message is a red herring.

I wish I could provide more detailed information about what is going on, but I do not see a --verbose option.

**Comment by mkozjak** [comment]
Removing ```^``` didn't fix it here. OS X 10.11 connecting to Arch Linux with mosh 1.2.5.

**Comment by serious-angel** [comment]
Dear, that was some kind of a case! Even stracing did not indicate the issue, and a solution required a step-by-step debugging for the both network and file-system environments.

Apparently, the issue was a set `RemoteCommand` for the host in `~/.ssh/config`.

It makes sense, since Mosh executes the Mosh server remotely within the SSH session, yet dear it's not obvious considering the error message...

# Example

```sh
user@local$ cat ~/.ssh/config;
Host some-example
    Hostname some.example.com
    Port 2221
    User remote
    IdentityFile /home/user/.ssh/keys/some-example.pk
    RequestTTY yes
    RemoteForward 0.0.0.0:1234 127.0.0.1:4321
    RemoteCommand /bin/tmux new -As 0 || /bin/bash;

Host some-example-mosh
    Hostname some.example.com
    Port 2221
    User remote
    IdentityFile /home/user/.ssh/keys/some-example.pk
    RequestTTY yes
    RemoteForward 0.0.0.0:1234 127.0.0.1:4321
    # RemoteCommand /bin/tmux new -As 0 || /bin/bash;

user@local$ mosh some-example;
Cannot execute command-line and remote command.
/usr/bin/mosh: Did not find remote IP address (is SSH ProxyCommand disabled?).

user@local$ mosh some-example-mosh;
remote@example$ 
```
