### ISSUE TITLE
Android port

### ISSUE THREAD

**Issue by keithw** [mobile-shell/mosh#32]
It would be wonderful to have persistent remote-terminal sessions from an Android device. Theoretically the Mosh code should be compilable on Android and should be runnable from an existing GUI terminal emulator without needing to jailbreak.

**Comment by Neo-Oli** [comment]
[Termux ](https://termux.com/) now has both a mosh-client and a mosh-server which can be installed with `apt install mosh`

**Comment by timoc** [comment]
+1 Termux should be added alongside Juicessh on the main page. 
tps://play.google.com/store/apps/details?id=com.termux

**Comment by achernya** [comment]
It looks like this was completed in https://github.com/mobile-shell/moshweb/pull/39
