### ISSUE TITLE
Package GNU/Linux + mosh + irssi to run on EC2

### ISSUE THREAD

**Issue by kmcallister** [mobile-shell/mosh#320]
It would be cool to publish an EC2 [AMI](https://aws.amazon.com/amis/) providing GNU/Linux + mosh + irssi as a mobile IRC solution.  It would almost certainly fit within a free micro instance.

**Comment by cgull** [comment]
Agreed.  Off the top of my head, FreeBSD AMIs, which can then also install recent versions of Mosh from their default package repos, are also available.
