### ISSUE TITLE
Delayed or shared binding of UDP ports

### ISSUE THREAD

**Issue by kmcallister** [mobile-shell/mosh#324]
If your server only has one UDP port open, and you have an abandoned `mosh-server` running, then you can't use

```
mosh -p 12345 host -- screen -dR
```

because the new `mosh-server` will want to bind to that UDP port before the old one has given it up.  Perhaps `mosh-server` should retry binding to the port after executing the command.  Or it could not ask for exclusive use of the port (I believe this should be possible with UDP).

**Comment by achernya** [comment]
I'm closing this in favor of #12. I don't think we're going to implement the specific workaround suggested here.
