### ISSUE TITLE
tmux+mosh frequently causes the last line of output to disappear

### ISSUE THREAD

**Issue by epitron** [mobile-shell/mosh#325]
Here are a couple screenshots of the problem: http://imgur.com/a/QP4Hb

This happens in gnome-terminal as well as xfce4-terminal, as well as the tmux installed on a number of other servers (ubuntu, debian, and fedora).

Any idea where I could start investigating the cause? I have a hunch that it's happening because my prompt is prefixed with an invisible blob of terminal codes to set the terminal title to the current path. See here: https://github.com/epitron/scripts/blob/master/red

**Comment by zywx** [comment]
Hey I still have this issue. Any chance I’m doing something wrong?

Tmux 2.a
Ubuntu 16.04
mosh-server 1.2
