### ISSUE TITLE
Mosh breaks F1-F4 keys for byobu-tmux

### ISSUE THREAD

**Issue by aaronkurtz** [mobile-shell/mosh#326]
https://bugs.launchpad.net/ubuntu/+source/byobu/+bug/1029030 has a nice set of steps to reproduce, but to be short, when I connect with mosh and run byobu-tmux the F1-F4 keys aren't recognized, although Shift-F1 etc. are recognized.

They are recognized if I'm running less on a file, however.

byobu 5.17-0ubuntu1
mosh 1.1.3-1
Also tried mosh 1.2.2

**Comment by blueyed** [comment]
Just for the record: this is a duplicate of #178 (mentioned before, but for anyone coming here).

**Comment by gabri94** [comment]
Any fix? I have rxvt and I can't use f-keys
