### ISSUE TITLE
Unset $DISPLAY when running under mosh

### ISSUE THREAD

**Issue by grep0** [mobile-shell/mosh#334]
mosh does not support X11 forwarding, but it is still keeping $DISPLAY env. It breaks the programs that work differently depending on X11 presence.

If would be great to unset $DISPLAY in a shell under mosh.

**Comment by achernya** [comment]
It seems that having mosh be in the business of deciding which environment variables should (not) be passed in is extra complexity. For local environments that need this behavior we suggest writing a small wrapper script that replaces mosh-server, unsets the appropriate variables, and then exec's the real mosh-server binary.
