### ISSUE TITLE
Buffer input while establishing connection

### ISSUE THREAD

**Issue by dnnr** [mobile-shell/mosh#340]
With ssh, I'm used to being able to just start typing my first command right after executing ssh. Establishing the connection usually takes a few seconds, but all keys pressed inbetween will end up on the remote prompt as expected. Mosh, on the other hand, drops those inputs.

It would be great if mosh would allow typing right away just as ssh does.

**Comment by achernya** [comment]
In theory, we'd be able to do this by having the ssh process have stdin connected to /dev/null. That way the kernel would buffer your input and it would be available for mosh-client to consume.

However, this has the downside that it would break ssh interactive (i.e., password) authentication, which is a very common use case. I don't think we can support this feature request without either reimplementing the ssh client ourselves, or patches to ssh.

**Comment by dnnr** [comment]
That's sadly a good point. Thanks for taking the time to explain!
