### ISSUE TITLE
lingering mosh-server processes

### ISSUE THREAD

**Issue by eminence** [mobile-shell/mosh#345]
When the mosh-client doesn't exit cleanly, its corresponding mosh-server process continues to run (apparently forever), since it has no way to distinguish a dead-client from a client that is simply offline.  Over time, stale mosh-server processes can build up.

This feature request is asking for a way to have mosh-server processes terminate themselves if they have not seen any incoming data for a user-configurable duration of time.  In my case, a week might a reasonable duration.

**Comment by cgull** [comment]
I fixed this specific request some time ago in #690.
