### ISSUE TITLE
Stale list of detached mosh processes

### ISSUE THREAD

**Issue by aaronsw** [mobile-shell/mosh#346]
I just upgraded to mosh 1.2.3 and got this new warning:

```
Mosh: You have 3 detached Mosh sessions on this server, with PIDs:
- mosh [2813]
- mosh [1370]
- mosh [16267]
```

I killed all those processes, logged out, and reconnected, but I still get the warning. There are no such processes.

```
$ kill 2813
kill: No such process
```

**Comment by perguth** [comment]
`pgrep -u "$USER" mosh-server | tr ' ' '\n' | grep -v "$PPID" | xargs kill 2> /dev/null`
