### ISSUE TITLE
server-specific configuration settings?

### ISSUE THREAD

**Issue by kyleniemeyer** [mobile-shell/mosh#347]
Is there any way to set configuration settings for each server, to avoid remembering/entering them every time?

For instance, on one server I don't have root access so I installed mosh into my home folder. To connect from my local machine, I have to enter `mosh --server="LD_LIBRARY_PATH=/home/user/lib /home/user/bin/mosh-server" host`

Can I set up a configuration file (like .ssh/config) to avoid doing this every time? And possibly other settings for different servers, like specific port numbers?

**Comment by electblake** [comment]
I went the wrapped route, and I created a function for my zsh shell (I use oh-my-zsh with spaceship-prompt, but should work with vanilla oh-my-zsh setup as well)

https://gist.github.com/electblake/e150f3dc45ee0452ef3fe21fd34221e2
- Requires zsh and oh-my-zsh
