### ISSUE TITLE
mosh-server on Raspberry Pi: ~50% cpu load

### ISSUE THREAD

**Issue by phmarek** [mobile-shell/mosh#372]
See also #297; "top" with 1 sec interval causes mosh-server to eat nearly half of the CPU.

"-pg" profile available.

**Comment by vielmetti** [comment]
Ran across this issue and wanted to report current (March 2015) timings:

```

  PID USER      PR  NI  VIRT  RES  SHR S %CPU %MEM     TIME+ COMMAND                        
 5392 pi        20   0 14880 3448 1280 S  7.2  0.8   0:12.69 mosh-server        
```

7.2% of CPU seems a little high but is by no means outlandish, this is running top on a Pi.

**Comment by gordon-morehouse** [comment]
I'm seeing 5-18% with a steady state around 12.5% on my Pi, which isn't overclocked to the max (I think I have it at 900MHz core clock, not 1GHz).

This is mosh 1.2.3-1 on Raspbian; I've had no noticeable problems with mosh-server and CPU usage on a Pi supporting a few users.

**Comment by cgull** [comment]
It occurs to me that Raspbian has probably seen performance improvements since 2012, and that might explain the different results people are getting.

That said, my changes in #531 will get you about an order of magnitude better performance.

**Comment by cgull** [comment]
Closing, please open a new issue if you still have performance issues.
