### ISSUE TITLE
Nothing received from server on UDP port 60001

### ISSUE THREAD

**Issue by gabrielecirulli** [mobile-shell/mosh#374]
Hi, I have a server running Ubuntu 12.04 64bit and I compiled mosh on it, now I'm trying to connect to it from OS X (I used the pkg installer) but I get the following error:

`Nothing received from server on UDP port 60001`

I also ran iptables to allow traffic on port 60001 but to no avail. Could you please help me troubleshoot this problem?

**Comment by 00001** [comment]
I still have this issue with 1.2.4a on Ubuntu 14.04, on a remote machine behind NAT.

Using chrome extension on W7 to connect.

**Comment by ovizii** [comment]
When you guys are talking about port forwarding you mean on the server, right?

**Comment by xinan** [comment]
@keithw I have this issue with mosh 1.2.5 on my digital ocean instance. I allowed mosh in ufw settings. However, it still fails to connect to 60001, but it can connect to 60002 onwards. With the `nc` command, I can see the text that I type on 60002 onwards, but nothing appears for port 60001. I am so confused.

**Comment by MasonMoreland** [comment]
I'm still having an issue connecting through a NAT on my router. If I connect locally, I get in no problem. It's only when I go through the NAT that I fail to get mosh to come up, but ssh works fine.

**Comment by NotAFile** [comment]
I had similar issues using it over a VPN (wireguard). It turns out the issue was the providers CGNAT. Nothing I can do, it seems.

**Comment by adam-dziedzic** [comment]
This worked for me: sudo iptables -I INPUT 1 -p udp --dport 60000:61000 -j ACCEPT 
(mosh 1.2.5)

**Comment by eminence** [comment]
@k-five would you please open a new issue for your problem (or find us on IRC)? It's slightly disruptive to bring new activity to an issue that's been closed for years
