### ISSUE TITLE
Error when LC_COLLATE not available on remote

### ISSUE THREAD

**Issue by felixonmars** [mobile-shell/mosh#386]
I'm getting this error when LC_COLLATE set to zh_CN.utf8 which is not present on remote machine. Both are running mosh 1.2.3.

unset LC_COLLATE could solve it, but I'm wondering if there is a way to just ignore the not applicable param and continue connecting anyway, as this is not indeed a lack of "UTF-8 native locale" as the error message says.

Full output:

```
The locale requested by LANG=en_US.utf8 isn't available here.
Running `locale-gen en_US.utf8' may be necessary.

mosh-server needs a UTF-8 native locale to run.

Unfortunately, the local environment ([no charset variables]) specifies
the character set "US-ASCII",

The client-supplied environment (LANG=en_US.utf8) specifies
the character set "US-ASCII".

locale: Cannot set LC_ALL to default locale: No such file or directory
LANG=en_US.utf8
LC_CTYPE="en_US.utf8"
LC_NUMERIC="en_US.utf8"
LC_TIME="en_US.utf8"
LC_COLLATE=zh_CN.utf8
LC_MONETARY="en_US.utf8"
LC_MESSAGES="en_US.utf8"
LC_PAPER="en_US.utf8"
LC_NAME="en_US.utf8"
LC_ADDRESS="en_US.utf8"
LC_TELEPHONE="en_US.utf8"
LC_MEASUREMENT="en_US.utf8"
LC_IDENTIFICATION="en_US.utf8"
LC_ALL=
```

**Comment by achernya** [comment]
This support request is nearly 10 years old, so I don't think we can do anything here. However, the issue here is that the requested locale (en_US.utf8) is not present on the target machine. The printed error message about local-gen is correct -- mosh requires the requested locale to be present on the machine.
