### ISSUE TITLE
syslog support

### ISSUE THREAD

**Issue by m0yellow** [mobile-shell/mosh#387]
Hello, I'm using mosh regularly as remote shell, but having it available for a long time I would need syslog support for audit purposes.

I looked at #217 , but this requires to manipulate the mosh-server call, but I want to have it configured on the server to report IP changes, or open sessions that have lots of output waiting.

As mosh doesn't register PTYs in my environment (linux 3.1.10 and 2.6.37.6), when giving access to users via mosh, I have a hard time keeping an eye on usage stats. Only security limits apply then.

So my feature request is to behave more like a traditional shell in sense of presence and logging on the server side.

Our server environment is (opensuse) linux, IPv4/IPv6 dual stack, clients are linux and mostly OS X in RFC1918 (old) or NAT64 (new) setups. We plan to have all support personal prefer mosh over ssh, as it would solve issues with roaming from UMTS (not our net) to WLAN (our net). (this was an obvious hint on the discussion of #81 ).

**Comment by achernya** [comment]
More modern versions of libutempter should produce syslog entries.
