### ISSUE TITLE
PKG Removal on Mac OS X

### ISSUE THREAD

**Issue by andyleejordan** [mobile-shell/mosh#396]
There is no clear/apparent way to cleanly remove Mosh from Mac OS X when installed via the PKG file.

I'd like to know how to fully remove it (so I can install it using Homebrew).

Thanks,

Andrew Schwartzmeyer

**Comment by godzillante** [comment]
Update: the actual path is now
/usr/local/bin/mosh*
/usr/local/share/man/man1/mosh*

(tested on OSX 10.10.4)
