### ISSUE TITLE
MinGW support

### ISSUE THREAD

**Issue by V-E-O** [mobile-shell/mosh#410]
Hi,

I tried Cygwin version of Mosh, it reacts slow in mintty.
Hope some port on MinGW that make it running well on windows.
Thanks.

**Comment by cgull** [comment]
Mosh is now available on both Cygwin and MSYS2, at least.  It's also available for Mosh-for-Chrome, see https://mosh.org for details.

What was your original problem with Mosh being "slow" on Cygwin?  Can you describe it further?  I know of an issue with Cygwin `select()` that can cause typing echo to be slightly laggy, your issue might or might not have been that.
