### ISSUE TITLE
Mosh client passes xterm-color to server as xterm

### ISSUE THREAD

**Issue by TomFrost** [mobile-shell/mosh#446]
Max OS X 10.8.3 (mosh 1.2.4 from zsh) connecting to Ubuntu 12.04 (mosh 1.2.4 on bash):

```
tf@local$ echo $TERM
xterm-color

tf@local$ mosh tf@remote
[snip connection output]

tf@remote$ echo $TERM
xterm
```

However, if I change it from xterm-color...

```
tf@local$ TERM=xterm-256color mosh tf@remote
[snip connection output]

tf@remote$ echo $TERM
xterm-256color
```

I can't seem to get `xterm-color` to pass without it being forced to plain `xterm`.

**Edit:** Note that, connecting between the same machines using standard ssh, I see xterm-color on the remote end.

**Comment by timofonic** [comment]
Is this problem solved these days? 

I'm scared about deploying MOSH and have these kind of issues, despite the potential advantages as a persistent shell over the network and a somewhat screen/tmux all-in-one plus other advantages.

**Comment by keithw** [comment]
Situation hasn't changed -- Mosh behaves like screen and tmux.
