### ISSUE TITLE
Cannot run mosh in Cygwin through a Windows shortcut

### ISSUE THREAD

**Issue by lkangas** [mobile-shell/mosh#448]
In cygwin, using mintty, both of these commands work as they should:

```
ssh kapsi
mosh kapsi
```

where `kapsi` is defined in `~/.ssh/config` with a username and hostname.

I'm trying to create a windows shortcut to mintty which would run mosh kapsi directly. For ssh, it works when setting Target as:
`D:\cygwin\bin\mintty.exe -i /Cygwin-Terminal.ico -e /bin/ssh kapsi`

Trying with mosh,
`D:\cygwin\bin\mintty.exe -i /Cygwin-Terminal.ico -e /usr/bin/mosh kapsi`
fails with 

```
/bin/sh: mosh-client: command not found
/usr/bin/mosh: Can't count colors: 0
```

Trying
`D:\cygwin\bin\mintty.exe -i /Cygwin-Terminal.ico -e /usr/bin/mosh --client=/usr/bin/mosh-client kapsi`
results in

```
Cannot exec ssh: 2
/usr/bin/mosh: Did not find remote IP address (is SSH ProxyCommand disabled?).
```

Replacing `kapsi` with `username@hostname.fi` in the above examples produce identical results. Also when entering above Targets as such into the Run dialog.

**Comment by ranyyy** [comment]
Thanks @lkangas :)
