### ISSUE TITLE
Incorrect background color after exiting Midnight Commander

### ISSUE THREAD

**Issue by aik099** [mobile-shell/mosh#454]
I'm on OSX 10.8.4 and have a Terminal color scheme applied with non-black background. Here is how it looks right after login:

![mosh_right_after_login](https://f.cloud.github.com/assets/1277526/981311/1615b56a-075a-11e3-9f81-03c4c0632f34.png)

Then I run Midnight Commander by typing "mc" + ENTER and immediately exit from it using F10 + ENTER. After that screen should revert to it's original state, but Mosh thinks that it should fill place, where Midnight Commander was displayed with black, instead of keeping it transparent and let Terminal.app do color things:

![mosh_after_exiting_mc](https://f.cloud.github.com/assets/1277526/981316/54610252-075a-11e3-8297-e09ca618eb10.png)

**Comment by cgull** [comment]
I just tested this with current Mosh and OS X 10.12.3's `Terminal.app` and `mc` from Homebrew.  This seems to work fine for me with a white background.  Please reopen if you're still seeing this.

**Comment by aik099** [comment]
@cgull , does it work if you change background color to other than white?

**Comment by cgull** [comment]
I copied a profile, set its background color to an obnoxious magenta, and opacity to 50%.  That seems to work fine.

What value is `TERM` in your Terminal window?  Do you have any color customizations applied in `mc`?

**Comment by aik099** [comment]
I'm using Solarized Dark profile. Actually I've stopped using Mosh 3 years ago because of that bug.
