### ISSUE TITLE
Passing mosh options from other programs (eg sshfs) à la SSH

### ISSUE THREAD

**Issue by saizai** [mobile-shell/mosh#462]
I have mosh installed in user directory on my server. I want to run sshfs on my laptop through mosh.

To run mosh, I need to do this:

```
mosh --server=LD_LIBRARY_PATH=/some/home/lib /some/home/bin/mosh-server me@host
```

sshfs has the ability to pass options in SSH style like this:

```
sshfs me@host:/ -oIdentityFile=/home/me/.ssh/id_rsa,Ciphers=aes256-ctr
```

AFAICT it relies on the availability of SSH -o options; ssh man page segment:

```
     -o option
             Can be used to give options in the format used in the configuration file.  This is useful for specifying options for which there is no separate command-line
             flag.  For full details of the options listed below, and their possible values, see ssh_config(5).

                   AddressFamily
                   BatchMode
                   BindAddress
                   ChallengeResponseAuthentication
```

Could we add the same -o format variant for all mosh options, so they can be passed from other programs that expect ssh (like sshfs)?

**Comment by chadwickboggs** [comment]
The combination of mosh's features and sshfs' features often are sought as it enables true client mobility at the correct level, whereas tmux is at the application level, to high.

**Comment by visiover** [comment]
+1
