### ISSUE TITLE
mosh on Openwrt with dropbear server.

### ISSUE THREAD

**Issue by cmtsij** [mobile-shell/mosh#464]
Because OpenWrt lack locale command, 
I patch mosh source code  to let it's always be true when check utf-8 support:

```
--- a/src/util/locale_utils.cc
+++ b/src/util/locale_utils.cc
@@ -86,10 +86,10 @@ const char *locale_charset( void )

 bool is_utf8_locale( void ) {
   /* Verify locale calls for UTF-8 */
-  if ( strcmp( locale_charset(), "UTF-8" ) != 0 &&
-       strcmp( locale_charset(), "utf-8" ) != 0 ) {
-    return 0;
-  }
+  //if ( strcmp( locale_charset(), "UTF-8" ) != 0 &&
+  //    strcmp( locale_charset(), "utf-8" ) != 0 ) {
+  // return 0;
+  //}
   return 1;
 }
```

If I manually start mosh-server on Openwrt first.
And I use "MOSH_KEY=xxxxx mosh-client ip port" On client side (Linux Mint Maya). 
It connect successfully without any problem.
I'm not familiar with perl, so i can't debug "mosh" command by myself.

Here is my full ssh log:
 # mosh --ssh="ssh -vvv" --client=/tmp/mosh/root/bin/mosh-client --server='/usr/bin/mosh-server' 192.168.1.1
penSSH_5.9p1 Debian-5ubuntu1.1, OpenSSL 1.0.1 14 Mar 2012
debug1: Reading configuration data /home/cti/.ssh/config
debug1: /home/cti/.ssh/config line 6: Applying options for 192.168.1.1
debug1: Reading configuration data /etc/ssh/ssh_config
debug1: /etc/ssh/ssh_config line 19: Applying options for *
debug2: ssh_connect: needpriv 0
debug1: Executing proxy command: exec './mosh' --fake-proxy -- 192.168.1.1 33
debug1: permanently_drop_suid: 1000
debug3: Incorrect RSA1 identifier
debug3: Could not load "/home/cti/.ssh/id_rsa" as a RSA1 public key
debug1: identity file /home/cti/.ssh/id_rsa type 1
debug1: Checking blacklist file /usr/share/ssh/blacklist.RSA-2048
debug1: Checking blacklist file /etc/ssh/blacklist.RSA-2048
debug1: identity file /home/cti/.ssh/id_rsa-cert type -1
debug1: identity file /home/cti/.ssh/id_dsa type -1
debug1: identity file /home/cti/.ssh/id_dsa-cert type -1
debug1: identity file /home/cti/.ssh/id_ecdsa type -1
debug1: identity file /home/cti/.ssh/id_ecdsa-cert type -1
debug1: Remote protocol version 2.0, remote software version dropbear_2011.54
debug1: no match: dropbear_2011.54
debug1: Enabling compatibility mode for protocol 2.0
debug1: Local version string SSH-2.0-OpenSSH_5.9p1 Debian-5ubuntu1.1
debug2: fd 5 setting O_NONBLOCK
debug2: fd 4 setting O_NONBLOCK
debug3: put_host_port: [192.168.1.1]:33
debug3: load_hostkeys: loading entries for host "[192.168.1.1]:33" from file "/home/cti/.ssh/known_hosts"
debug3: load_hostkeys: loaded 0 keys
debug1: SSH2_MSG_KEXINIT sent
debug1: SSH2_MSG_KEXINIT received
debug2: kex_parse_kexinit: ecdh-sha2-nistp256,ecdh-sha2-nistp384,ecdh-sha2-nistp521,diffie-hellman-group-exchange-sha256,diffie-hellman-group-exchange-sha1,diffie-hellman-group14-sha1,diffie-hellman-group1-sha1
debug2: kex_parse_kexinit: ecdsa-sha2-nistp256-cert-v01@openssh.com,ecdsa-sha2-nistp384-cert-v01@openssh.com,ecdsa-sha2-nistp521-cert-v01@openssh.com,ssh-rsa-cert-v01@openssh.com,ssh-dss-cert-v01@openssh.com,ssh-rsa-cert-v00@openssh.com,ssh-dss-cert-v00@openssh.com,ecdsa-sha2-nistp256,ecdsa-sha2-nistp384,ecdsa-sha2-nistp521,ssh-rsa,ssh-dss
debug2: kex_parse_kexinit: aes128-ctr,aes192-ctr,aes256-ctr,arcfour256,arcfour128,aes128-cbc,3des-cbc,blowfish-cbc,cast128-cbc,aes192-cbc,aes256-cbc,arcfour,rijndael-cbc@lysator.liu.se
debug2: kex_parse_kexinit: aes128-ctr,aes192-ctr,aes256-ctr,arcfour256,arcfour128,aes128-cbc,3des-cbc,blowfish-cbc,cast128-cbc,aes192-cbc,aes256-cbc,arcfour,rijndael-cbc@lysator.liu.se
debug2: kex_parse_kexinit: hmac-md5,hmac-sha1,umac-64@openssh.com,hmac-sha2-256,hmac-sha2-256-96,hmac-sha2-512,hmac-sha2-512-96,hmac-ripemd160,hmac-ripemd160@openssh.com,hmac-sha1-96,hmac-md5-96
debug2: kex_parse_kexinit: hmac-md5,hmac-sha1,umac-64@openssh.com,hmac-sha2-256,hmac-sha2-256-96,hmac-sha2-512,hmac-sha2-512-96,hmac-ripemd160,hmac-ripemd160@openssh.com,hmac-sha1-96,hmac-md5-96
debug2: kex_parse_kexinit: none,zlib@openssh.com,zlib
debug2: kex_parse_kexinit: none,zlib@openssh.com,zlib
debug2: kex_parse_kexinit: 
debug2: kex_parse_kexinit: 
debug2: kex_parse_kexinit: first_kex_follows 0 
debug2: kex_parse_kexinit: reserved 0 
debug2: kex_parse_kexinit: diffie-hellman-group1-sha1,diffie-hellman-group14-sha1
debug2: kex_parse_kexinit: ssh-rsa,ssh-dss
debug2: kex_parse_kexinit: aes128-ctr,3des-ctr,aes256-ctr,aes128-cbc,3des-cbc,aes256-cbc
debug2: kex_parse_kexinit: aes128-ctr,3des-ctr,aes256-ctr,aes128-cbc,3des-cbc,aes256-cbc
debug2: kex_parse_kexinit: hmac-sha1,hmac-md5
debug2: kex_parse_kexinit: hmac-sha1,hmac-md5
debug2: kex_parse_kexinit: none
debug2: kex_parse_kexinit: none
debug2: kex_parse_kexinit: 
debug2: kex_parse_kexinit: 
debug2: kex_parse_kexinit: first_kex_follows 0 
debug2: kex_parse_kexinit: reserved 0 
debug2: mac_setup: found hmac-md5
debug1: kex: server->client aes128-ctr hmac-md5 none
debug2: mac_setup: found hmac-md5
debug1: kex: client->server aes128-ctr hmac-md5 none
debug2: dh_gen_key: priv key bits set: 128/256
debug2: bits set: 1005/2048
debug1: sending SSH2_MSG_KEXDH_INIT
debug1: expecting SSH2_MSG_KEXDH_REPLY
debug1: Server host key: RSA 62:e1:7f:81:eb:44:b7:da:8b:e4:4b:61:74:5c:52:b9
debug3: put_host_port: [192.168.1.1]:33
debug3: load_hostkeys: loading entries for host "[192.168.1.1]:33" from file "/home/cti/.ssh/known_hosts"
debug3: load_hostkeys: loaded 0 keys
debug1: checking without port identifier
debug3: load_hostkeys: loading entries for host "192.168.1.1" from file "/home/cti/.ssh/known_hosts"
debug3: load_hostkeys: found key type RSA in file /home/cti/.ssh/known_hosts:36
debug3: load_hostkeys: loaded 1 keys
debug1: Host '192.168.1.1' is known and matches the RSA host key.
debug1: Found key in /home/cti/.ssh/known_hosts:36
debug1: found matching key w/out port
debug2: bits set: 1000/2048
debug1: ssh_rsa_verify: signature correct
debug2: kex_derive_keys
debug2: set_newkeys: mode 1
debug1: SSH2_MSG_NEWKEYS sent
debug1: expecting SSH2_MSG_NEWKEYS
debug2: set_newkeys: mode 0
debug1: SSH2_MSG_NEWKEYS received
debug1: Roaming not allowed by server
debug1: SSH2_MSG_SERVICE_REQUEST sent
debug2: service_accept: ssh-userauth
debug1: SSH2_MSG_SERVICE_ACCEPT received
debug2: key: /home/cti/.ssh/id_rsa (0x7f6d29e3f750)
debug2: key: /home/cti/.ssh/id_dsa ((nil))
debug2: key: /home/cti/.ssh/id_ecdsa ((nil))
debug1: Authentications that can continue: publickey,password
debug3: start over, passed a different list publickey,password
debug3: preferred gssapi-keyex,gssapi-with-mic,publickey,keyboard-interactive,password
debug3: authmethod_lookup publickey
debug3: remaining preferred: keyboard-interactive,password
debug3: authmethod_is_enabled publickey
debug1: Next authentication method: publickey
debug1: Offering RSA public key: /home/cti/.ssh/id_rsa
debug3: send_pubkey_test
debug2: we sent a publickey packet, wait for reply
debug1: Server accepts key: pkalg ssh-rsa blen 279
debug2: input_userauth_pk_ok: fp 5d:49:eb:32:09:68:2c:0f:63:b6:8a:a0:f2:2e:44:d5
debug3: sign_and_send_pubkey: RSA 5d:49:eb:32:09:68:2c:0f:63:b6:8a:a0:f2:2e:44:d5
debug1: Authentication succeeded (publickey).
Authenticated to 192.168.1.1 (via proxy).
debug2: fd 3 setting O_NONBLOCK
debug2: fd 6 setting O_NONBLOCK
debug3: fd 7 is O_NONBLOCK
debug1: channel 0: new [client-session]
debug3: ssh_session2_open: channel_new: 0
debug2: channel 0: send open
debug1: Entering interactive session.
debug2: callback start
debug2: client_session2_setup: id 0
debug2: channel 0: request pty-req confirm 1
debug1: Sending environment.
debug3: Ignored env USER
debug3: Ignored env SSH_AGENT_PID
debug3: Ignored env SHLVL
debug3: Ignored env OLDPWD
debug3: Ignored env HOME
debug3: Ignored env MDM_LANG
debug3: Ignored env XDG_SESSION_COOKIE
debug3: Ignored env DESKTOP_SESSION
debug3: Ignored env MATECORBA_SOCKETDIR
debug3: Ignored env DBUS_SESSION_BUS_ADDRESS
debug3: Ignored env COLORTERM
debug3: Ignored env MDMSESSION
debug3: Ignored env MANDATORY_PATH
debug3: Ignored env LOGNAME
debug3: Ignored env GTK_IM_MODULE
debug3: Ignored env WINDOWID
debug3: Ignored env _
debug3: Ignored env DEFAULTS_PATH
debug3: Ignored env TERM
debug3: Ignored env USERNAME
debug3: Ignored env WINDOWPATH
debug3: Ignored env PATH
debug3: Ignored env SESSION_MANAGER
debug3: Ignored env DISPLAY
debug1: Sending env LANG = en_US.UTF-8
debug2: channel 0: request env confirm 0
debug3: Ignored env XMODIFIERS
debug3: Ignored env XAUTHORITY
debug3: Ignored env SSH_AUTH_SOCK
debug3: Ignored env SHELL
debug3: Ignored env MATE_KEYRING_CONTROL
debug3: Ignored env GPG_AGENT_INFO
debug3: Ignored env QT_IM_MODULE
debug3: Ignored env PWD
debug3: Ignored env XDG_CONFIG_DIRS
debug3: Ignored env XDG_DATA_DIRS
debug3: Ignored env MDM_XSERVER_LOCATION
debug3: Ignored env MATE_DESKTOP_SESSION_ID
debug1: Sending command: /usr/bin/mosh-server 'new' '-c' '8' '-s' '-l' 'LANG=en_US.UTF-8'
debug2: channel 0: request exec confirm 1
debug2: callback done
debug2: channel 0: open confirm rwindow 24576 rmax 32768
debug2: channel 0: read<=0 rfd 3 len 0
**debug2: channel 0: read failed**
debug2: channel 0: close_read
debug2: channel 0: input open -> drain
debug2: channel 0: ibuf empty
debug2: channel 0: send eof
debug2: channel 0: input drain -> closed
debug2: channel_input_status_confirm: type 99 id 0
debug2: PTY allocation request accepted on channel 0
debug2: channel_input_status_confirm: type 99 id 0
debug2: exec request accepted on channel 0
debug2: channel 0: rcvd eof
debug2: channel 0: output open -> drain
debug2: channel 0: obuf empty
debug2: channel 0: close_write
debug2: channel 0: output drain -> closed
debug1: client_input_channel_req: channel 0 rtype exit-status reply 0
debug2: channel 0: rcvd close
debug3: channel 0: will not send data after close
debug2: channel 0: almost dead
debug2: channel 0: gc: notify user
debug2: channel 0: gc: user detached
debug2: channel 0: send close
debug2: channel 0: is dead
debug2: channel 0: garbage collecting
debug1: channel 0: free: client-session, nchannels 1
debug3: channel 0: status: The following connections are open:
  #0 client-session (t4 r0 i3/0 o3/0 fd -1/-1 cc -1)

debug1: fd 1 clearing O_NONBLOCK
debug3: fd 2 is not O_NONBLOCK
Connection to 192.168.1.1 closed.
Transferred: sent 3208, received 1448 bytes, in 0.1 seconds
Bytes per second: sent 29930.9, received 13510.0
debug1: Exit status 0
./mosh: Did not find mosh server startup message

**Comment by achernya** [comment]
Closing in favor of #819
