### ISSUE TITLE
mosh slower than ssh on fast link with multiple vim windows

### ISSUE THREAD

**Issue by klement** [mobile-shell/mosh#468]
I am noticing some pain when using mosh with vim split in 2 windows. When I scroll in the larger of the windows, it's very slow, it moves line by line and takes ages to scroll. Also, when I let go of the key, it keeps scrolling for a while. With ssh, it is laggy, but much faster, initially, first 2-5 lines, it's as slow as mosh, then it speeds up and scrolls decently taking some time to stop scrolling when I let go of the key. I understand the lag at the end of scrolling in both cases, but I am surprised that ssh is faster in this case. The vim is inside screen and it's on a fast link. Messing with --prediction doesn't seem to affect this at all.

**Comment by cgull** [comment]
Closing, I've committed code that should fix this.  Please open a new issue if you still have performance issues.
