### ISSUE TITLE
Mosh should disconnect when remote is rebooted

### ISSUE THREAD

**Issue by uzytkownik** [mobile-shell/mosh#480]
When I use ssh and reboot remote a message displaying that remote is rebooted is displayed and ssh session is terminated. mosh needs to be terminated manually.

It would be nice to send the disconnection signal to client when server is being terminated.

**Comment by eminence** [comment]
I just tested this on a fresh install of Debian 9 (aka Debian Stretch), which defaults to using systemd these days, as well as my gentoo machine.  In both cases, the mosh-client exited cleanly, with no need to manually terminate anything.  So now that this appears fixed, I'm going to close this issue.

**Comment by cgull** [comment]
I have made a couple of changes over time that should cause `mosh-server` to more robustly terminate the client on a server shutdown in some cases.  If you are still having problems here, and your SSH sessions do terminate promptly and cleanly, please comment here.

(There are still occasionally systems that bring down their network connectivity before user sessions are closed.  That is a different problem which should be addressed at the OS/configuration level.)
