### ISSUE TITLE
mosh slow at rendering vim windows with 256-color colorschemes

### ISSUE THREAD

**Issue by dorserg** [mobile-shell/mosh#487]
My set up is mosh -> screen -> vim session.

I recently switched from default 8-color colorscheme to a 256-color one (e.g. https://github.com/tomasr/molokai or http://www.vim.org/scripts/script.php?script_id=415), and noticed that rendering of a window Vim is in became pretty slow -- a couple lines at a time, taking about a second to render the full window (this is on a big monitor). This happens either when I switch from one screen window to the one Vim is in, or when I jump to a remote part of the file within Vim itself, causing it to show/render completely new lines of code (e.g. jump from the beginning of the file to line 500).

It seems related to 256 colors because if you either
1) force Vim to only use 8 colors (`:set t_Co=8` at the beginning of your `.vimrc` before the colorscheme is applied), or
2) use default colorscheme (which only uses 8 colors),
rendering becomes fast.

One other thing to note is, if you substitute mosh with ssh (i.e. ssh -> screen -> vim), it renders both 8- and 256-color colorschemes fast.

Would be great if you could look into this. Thanks!

**Comment by cgull** [comment]
Closing, I've committed code that should fix this.  Please open a new issue if you still have performance issues.
