### ISSUE TITLE
Unicode line drawing characters shown incorrectly for me

### ISSUE THREAD

**Issue by kergoth** [mobile-shell/mosh#493]
It's entirely possible it's somehow user error, if so I'd love to discover what it is. I'm running mosh master on both ends, NCURSES_NO_UTF8_ACS is set to 1 after connecting, and the line drawing characters used by dvtm are displayed as q, x, and w, rather than what they should be. Standard ssh works fine.

**Comment by cypa** [comment]
got TERM values are same on local and mosh shells and NCURSES_NO_UTF8_ACS=1 and locale are set ... still no correct line drawing characters, while via ssh with same environment line are OK

**Comment by trysten** [comment]
Some combination of the proper setting for `TERM` and `NCURSES_NO_UTF8_ACS` seems to be the correct solution. But I found one program that doesn't draw correctly even with the proper setting: [nmon](https://nmon.sourceforge.io/pmwiki.php). 

If we wanted to fix this, one might see how nmon initializes curses. Maybe it is failing to respect the `NCURSES_NO_UTF8_ACS` setting? But it does work over SSH, so nmon qualifies to be on some kind of 'has-issues' list of software.
