### ISSUE TITLE
mosh sometimes generates spurious "You have a detached Mosh session on this server" when multiple sessions are established at once

### ISSUE THREAD

**Issue by codemage** [mobile-shell/mosh#504]
I just set up a window manager alias that spawns 3-4 mosh sessions in separate xterm windows all at about the same time, across a link with a 150ms ping or so.

I am finding that mosh consistently produces "detached Mosh session" on one or two of these connections for the others -- killing the PID's from any of the messages once everything is settled shuts down one of the active sessions.

It's just spam now that I know what's goign on, but it would be nice if mosh could distinguish the "server just started, client hasn't connected yet" state with some reasonable timeout and suppress messages about those sessions being "detached."

**Comment by isonno** [comment]
May or may not be related: I frequently see `detected Mosh session` messages that appear to be bogus:
```
    Mosh: You have a detached Mosh session on this server (mosh [15630]).  
    jp@eyeball ~ $ kill -KILL 15630
    -bash: kill: (15630) - No such process
    jp@eyeball ~ $
```

**Comment by keithw** [comment]
What version of mosh-server are you using on the server?

**Comment by keithw** [comment]
Also, why run `kill -KILL`? There is no way a process can clean up after itself (including cleaning up a `utmp` entry) when you send it the KILL signal! Normal kill is sufficient.
