### ISSUE TITLE
ForceCommand should present the user with a prompt during bootstrap if it asks for input

### ISSUE THREAD

**Issue by skottler** [mobile-shell/mosh#506]
`ForceCommand` in `/etc/ssh/sshd_config` is often used by two-factor authentication systems to prompt the user for input (like a token that's pushed to their mobile) before giving a shell. It'd be nice if mosh supported presenting that prompt to use when standing up `mosh-server` over the initial SSH connection.

**Comment by achernya** [comment]
Unfortunately I don't think we have the resources to support a proprietary two-factor authentication system (ab)using ForceCommand.
