### ISSUE TITLE
ssh error messages appear out of order

### ISSUE THREAD

**Issue by ahroach** [mobile-shell/mosh#52]
Some error messages from the initial ssh connection appear after the password prompt is reprinted. For example, when inputting an incorrect password:

aroach@champignon:~$ mosh champignon
aroach@champignon's password: 
aroach@champignon's password: Permission denied, please try again.

**Comment by achernya** [comment]
This was filed nearly 10 years ago, and we've had lots of changes to the mosh startup script since. It's unclear to me this issue still exists. Please reopen if you can reproduce with mosh 1.4.0
