### ISSUE TITLE
Store 'client ID' on server

### ISSUE THREAD

**Issue by Habbie** [mobile-shell/mosh#533]
Right now, when I log in I see something like:

```
Mosh: You have a detached Mosh session on this server (mosh [8893]).
```

sometimes, I have two or three entries. Some of those sessions may be dead (laptop crashed, JuiceSSH on Android crashed, etc.). Some kind of client identifier (like the client machine's hostname or device name) might aid in deciding what sessions to kill.

**Comment by cgull** [comment]
This is far from a complete solution, but on systems where mosh uses `utempter`, `last` will get you this information, at least until wtmp is rotated or truncated.
