### ISSUE TITLE
mosh does not work when the login shell is screen

### ISSUE THREAD

**Issue by amit** [mobile-shell/mosh#535]
When the login shell on the remote account is set to '/usr/bin/screen' mosh is unable to connect. It issues the following error message:

Unable to open "mosh-server 'new' '-s' '-c' '8' '-l' 'LANG=en_US.UTF-8' '-l' 'LANGUAGE=en_US:en' '-l' 'LC_CTYPE=en_US.UTF-8' '-l' 'LC_NUMERIC=en_US.UTF-8' '-l' 'LC_TIME=en_US.UTF-8' '-l' 'LC_MONETARY=en_US.UTF-8' '-l' 'LC_PAPER=en_US.UTF-8' '-l' 'LC_NAME=en_US.UTF-8' '-l' 'LC_ADDRESS=en_US.UTF-8' '-l' 'LC_TELEPHONE=en_US.UTF-8' '-l' 'LC_MEASUREMENT=en_US.UTF-8' '-l' 'LC_IDENTIFICATION=en_US.UTF-8'".

ssh'ing to that host works fine and changing the login shell back to regular shells (zsh/bash) works  fine.

**Comment by cgull** [comment]
Using mosh that way generally doesn't make sense.  On login, you're starting `screen`, which starts a session with a new pty.  `mosh-server` then starts running in that session (or doesn't, in your case), and opens its own new session on another pty, which is separate from the sessions in `screen`.  Also, screen doesn't (and cannot) promise to deliver `mosh-server`'s startup messages back to your client, and is at least theoretically unreliable for starting mosh sessions.  The thing you want to do is start `mosh-server` with a normal login shell, and start `screen` in its session.  You can do this easily enough with `mosh user@host screen -<your-favorite-screen-options>` (and also in ssh), and this also allows non-interactive ssh sessions to work properly.

But if you need to use mosh this way for some reason, I suspect that your `mosh-server` binary is not on your system's default `PATH`, and using the `--server` option with an absolute path to `mosh-server` will fix your problem.
