### ISSUE TITLE
option to kill stuck mosh-server processes

### ISSUE THREAD

**Issue by ibukanov** [mobile-shell/mosh#538]
Currently if the client does not terminate the connection properly, mosh-server process on the remote side hangs forever. It would be nice if mosh supported an option to kill such processes when a new client connects to the remote server.

As a workaround for that I use a shell script that kills all mosh-server instances before executing mosh-server and then use mosh's server option to point to this script. But this is not ideal as sometimes I do want to have 2 or more mosh sessions from the same or different machines. A proper solution would keep track on the client of all sessions that were not properly terminated and pass those to the server for the cleanup.

**Comment by cgull** [comment]
@PriceChild's solution is a common and simple way to handle this, #690 provides server timeouts.  @ibukanov, do the combination of these and simple scripting meet your needs?
