### ISSUE TITLE
Mosh fails to support back tab (\e[Z)

### ISSUE THREAD

**Issue by andersk** [mobile-shell/mosh#539]
The terminfo for `xterm` advertises support for back tab (`cbt=\E[Z, kcbt=\E[Z`), but Mosh doesn’t support it. Outside Mosh:
```
$ printf 'hello, wurld\e[Zo\n'
hello, world
```
Inside Mosh:
```
$ printf 'hello, wurld\e[Zo\n'
hello, wurldo
```

This results in display corruption; I observed it while pressing backspace in nano 2.3.1 on CentOS 7.

**Comment by philip-wernersbach** [comment]
Confirmed with CentOS 6.7. This makes "nano" pretty much unusable over mosh.
