### ISSUE TITLE
ubuntu install not working.

### ISSUE THREAD

**Issue by lambdaq** [mobile-shell/mosh#567]
I found the instructions on http://mosh.mit.edu is kinda wrong for Ubuntu (at least for me on 14.04 LTS)

The line in question is 

```
$ sudo apt-get install python-software-properties
```

Which should be 

```
$ sudo apt-get install software-properties-common
```

instead.  Other wise there won't be a command called `/usr/bin/add-apt-repository`

**Comment by eminence** [comment]
This was fixed forever ago in the moshweb repo.  Close this issue!
