### ISSUE TITLE
Did not find mosh server startup message

### ISSUE THREAD

**Issue by NavinF** [mobile-shell/mosh#568]
Title says it all:
```
localhost:~ navin$ mosh --server=/home/root/mosh-server-runner root@192.168.1.21
Connection to 192.168.1.21 closed.
/usr/local/bin/mosh: Did not find mosh server startup message.
```
I added --ssh="ssh -vv" to the command and it seems to fail when it tries to run the server:
```
debug1: Sending command: /home/root/mosh-server-runner 'new' '-s' '-c' '256' '-l' 'LANG=en_US.UTF-8'
debug2: channel 0: request exec confirm 1
debug2: callback done
debug2: channel 0: open confirm rwindow 24576 rmax 32768
debug2: channel 0: read<=0 rfd 3 len 0
debug2: channel 0: read failed
debug2: channel 0: close_read
debug2: channel 0: input open -> drain
debug2: channel 0: ibuf empty
debug2: channel 0: send eof
debug2: channel 0: input drain -> closed
debug2: channel_input_status_confirm: type 99 id 0
debug2: PTY allocation request accepted on channel 0
debug2: channel_input_status_confirm: type 99 id 0
debug2: exec request accepted on channel 0
debug2: channel 0: rcvd eof
debug2: channel 0: output open -> drain
debug2: channel 0: obuf empty
debug2: channel 0: close_write
debug2: channel 0: output drain -> closed
debug1: client_input_channel_req: channel 0 rtype exit-status reply 0
debug2: channel 0: rcvd close
debug2: channel 0: almost dead
debug2: channel 0: gc: notify user
debug2: channel 0: gc: user detached
debug2: channel 0: send close
debug2: channel 0: is dead
debug2: channel 0: garbage collecting
debug1: channel 0: free: client-session, nchannels 1
debug1: fd 1 clearing O_NONBLOCK
Connection to 192.168.1.21 closed.
Transferred: sent 4312, received 1856 bytes, in 0.1 seconds
Bytes per second: sent 36649.2, received 15774.8
debug1: Exit status 0
/usr/local/bin/mosh: Did not find mosh server startup message.
```
Now if I try to run the server manually, it seems to work...
```
localhost:~ navin$ ssh root@192.168.1.21 <<"END"
> /home/root/mosh-server-runner 'new' '-s' '-c' '256' '-l' 'LANG=en_US.UTF-8'
> END
Pseudo-terminal will not be allocated because stdin is not a terminal.
Server started without pseudo-terminal. Opening 80x24 terminal.

MOSH CONNECT 60001 ZQHJY74kxf08U1Me/m6/jQ
```
Just for reference, mosh-server-runner is a wrapper for mosh-server and here are its contents:
```
export PATH=/usr/local/bin/:$PATH
LD_LIBRARY_PATH=/usr/local/lib:$LD_LIBRARY_PATH
export LD_LIBRARY_PATH
export LANG=en_US.UTF-8
mosh-server "$@"
```

What am I missing?

**Comment by andersk** [comment]
Is there something funny in your dotfiles (`~/.bashrc`, `~/.bash_profile`, `~/.bash_login`, `~/.profile`, `~/.ssh/rc`, etc.)?

**Comment by kesavkolla** [comment]
I just did a fresh install of mosh on my ubuntu server and mac.  I'm trying to connect ubuntu server from mac and I get the same error message `Did not find mosh server startup message.` after couple of minutes.

I ran with debug mode and here is the output

```
bash-4.3$ mosh dbmanuals --ssh="ssh -vv"
OpenSSH_6.2p2, OSSLShim 0.9.8r 8 Dec 2011
debug1: Reading configuration data /Users/kesav/.ssh/config
debug1: /Users/kesav/.ssh/config line 39: Applying options for dbmanuals
debug1: Reading configuration data /etc/ssh_config
debug1: /etc/ssh_config line 20: Applying options for *
debug2: ssh_connect: needpriv 0
debug1: Executing proxy command: exec '/usr/local/bin/mosh' '--family=inet' --fake-proxy -- db.manuals-store.com 2022
debug1: identity file /Users/kesav/.ssh/id_rsa type 1
debug1: permanently_drop_suid: 501
debug1: identity file /Users/kesav/.ssh/id_rsa-cert type -1
debug1: identity file /Users/kesav/.ssh/id_dsa type -1
debug1: identity file /Users/kesav/.ssh/id_dsa-cert type -1
debug1: Enabling compatibility mode for protocol 2.0
debug1: Local version string SSH-2.0-OpenSSH_6.2
debug1: ssh_exchange_identification: \033[31m$fish_theme usage has been deprecated. Please see https://asciinema.org/a/20802.

debug1: ssh_exchange_identification: \033[30m\033(B\033[mSSH-2.0-OpenSSH_6.6.1p1 Ubuntu-2ubuntu2.3


debug1: ssh_exchange_identification:
debug1: ssh_exchange_identification: ss,ecdsa-sha2-nistp256
debug1: ssh_exchange_identification: u.se
debug1: ssh_exchange_identification: tm@openssh.com,hmac-sha1-etm@openssh.com,umac-64-etm@openssh.com,umac-128-etm@openssh.com,hmac-sha2-256-etm@openssh.com,hmac-sha2-512-etm@openssh.com,hmac-ripemd160-etm@openssh.com,hmac-sha1-96-etm@openssh.com,hmac-md5-96-etm@openssh.com,hmac-md5,hmac-sha
debug1: ssh_exchange_identification: 1,umac-64@openssh.com,umac-128@openssh.com,hmac-sha2-256,hmac-sha2-512,hmac-ripemd160,hmac-ripemd160@openssh.com,hmac-sha1-96,hmac-md5-96
debug1: ssh_exchange_identification: etm@openssh.com,hmac-sha2-512-etm@openssh.com,hmac-ripemd160-etm@openssh.com,hmac-sha1-96-etm@openssh.com,hmac-md5-96-etm@openssh.com,hmac-md5,hmac-sha1,umac-64@openssh.com,umac-128@openssh.com,hmac-sha2-256,hmac-sha2-512,hmac-ripemd160,hmac-ripemd160@ope
ssh_exchange_identification: Connection closed by remote host
/usr/local/bin/mosh: Did not find mosh server startup message.
```

**Comment by eminence** [comment]
This part looks funny and suspicious:

```
fish_theme usage has been deprecated. Please see https://asciinema.org/a/20802.
```

I'm not sure what this is, but I'm guessing it's related to the `fish` shell.  Perhaps start by trying to quell this message?

**Comment by kesavkolla** [comment]
Don't know why that message is coming.  I'm using bash shell on mac.

`bash-4.3`

**Comment by eminence** [comment]
What are you using on the ubuntu server?

**Comment by kesavkolla** [comment]
Shell on Ubuntu server is bash

**Comment by eminence** [comment]
Does `~/.config/fish/config.fish` exist on either your client or your server?

**Comment by cgull** [comment]
It's extremely odd to see a login message about Fish (which you'd expect to be sent to the login's tty) before the SSH session has even *started*, and before there's any login tty.

My best guess is that you are proxying your SSH session through another machine, and the Fish login message is coming from *that* machine.  If so, you need to fix that machine to not print messages on non-interactive logins.

Additionally, if you're needing to proxy your SSH session, you may not have the UDP connectivity needed for Mosh anyway.

**Comment by cgull** [comment]
There's also a minor issue for Mosh here:  For the initial connect, Mosh runs a non-interactive SSH session, but for historical reasons, it uses a tty.  That's no longer necessary.  This issue is probably due to a badly-written shell login/profile script, and this is something that comes up somewhat frequently.  I think we might see it less often if we didn't use a tty-- the two main usages of SSH are interactive logins, or non-interactive, non-tty remote commands, and we're using a bit of a corner case here.

**Comment by kesavkolla** [comment]
I do have `~/.config/fish/config.fish` on my mac.  I have a fish shell installed on mac.

I don't use any proxy for my ssh session.  I'm straight connecting to ubuntu server.

**Comment by eminence** [comment]
Can you remove `~/.config/fish/config.fish` temporarily and try again?   The goal here is to remove as many variables as possible.

**Comment by cgull** [comment]
Oh, how I forget.  This could be essentially the same basic problem as #663.  SSH uses the user's $SHELL to run our fake proxy, and if that shell (or its profile/rc files) generate output on stdout, they would be dumped into the SSH protocol stream.

@kesavkolla, if you can fix or disable your `fish` config, or temporarily switch to another login shell and open a new terminal, that will help show if the problem is in this area.

**Comment by kesavkolla** [comment]
Ok my issue got resolved.  I had oh-my-fish installed on my mac and it has an echo message which is coming even when I tried mosh from bash shell.  I commented that message and everything works well.

**Comment by cgull** [comment]
Good to hear, thanks for letting us know it's resolved.

**Comment by cgull** [comment]
Commit 09bdc7caaee4473b4f1087b1e58058b3ea383655 probably fixes this from the Mosh side.

**Comment by jleaders** [comment]
I'm having this issue as well with an OSX client (I tried commenting out the SetLang) and an Ubuntu server. Do you think it may because my Ubuntu default shell is tcsh?

**Comment by arunpatro** [comment]
/usr/local/bin was in the path on the server side but I still got the error message along with some LC_TYPE and LC_ALL. 

Adding the following to ~/.bashrc resolved the issue for me, as I didn't have sudo access. 

```
export LC_ALL=en_US.UTF-8
export LANG=en_US.UTF-8
```
