### ISSUE TITLE
Local echo + tmux horizontal panes

### ISSUE THREAD

**Issue by elbaro** [mobile-shell/mosh#574]
When I have a tmux running two panes like this:

```
Pane1     | Pane2
prompt>   | prompt>
```

If I type 'hello' in the left pane's prompt, the panel separator `|` and the right panes' `prompt>` is shifted to the right by the same amount.

```
Pane1     | Pane2
prompt>hello   | prompt>
```

Though this is refreshed after a second, is this natural for a predictive local echo? can we make an exception for certain situations like tmux or screen?

**Comment by cgull** [comment]
Have a look at #622.

**Comment by achernya** [comment]
There's no good way to support this as we cannot reliably detect if the application is in insert mode, or overwrite mode. The default for readline is insert mode, which is why you end up with things shifting to the right.
