### ISSUE TITLE
Build mosh in docker?

### ISSUE THREAD

**Issue by vielmetti** [mobile-shell/mosh#595]
You wouldn't normally need to build a mosh client or server inside a docker container, but just in case someone has a Dockerfile that builds mosh, I'm interested. Particularly if all of the dependencies are spelled out.....

This is a start https://registry.hub.docker.com/u/ddrown/mosh-build/dockerfile/ from @ddrown last summer.

**Comment by keithw** [comment]
My temptation would just be to get the source dpkg and build that -- that is batteries-included with dependencies and regression tests and everything (in debian/control). Would that work for you? https://packages.debian.org/sid/mosh

**Comment by vielmetti** [comment]
This gist has a 'salt' SLS file for Ubuntu that pulls down all of the packages necessary so that if you download and build mosh from sources that you get through the "configure" process

https://gist.github.com/767d0c329268d55e02d8

This corresponds to collecting up the following Ubuntu dependencies on a Ubuntu 14.04 system.

libncursesw5-dev, libprotobuf-dev, libssl-dev, libutempter-dev, openssl, pkg-config, protobuf-compiler, zlib-bin, zlib1g-dev, zlibc.

This might not actually be a minimal subset of dependencies but it does cause a clean build.

**Comment by cgull** [comment]
```shell
apt-get build-dep mosh
```
already does what you want, I think.
