### ISSUE TITLE
mosh-server behind NAT

### ISSUE THREAD

**Issue by LucaSimonelli** [mobile-shell/mosh#602]
It seems that currently the mosh perl script doesn't provide an option to execute the mosh-server and the mosh-client on two different port numbers. That doesn't make things easy when connecting to a machine that is behind NAT and the mosh-server UDP port is mapped to a different UDP port number on the public IP address.

The tweak I did to the code, after adding a port_nat parameter, summarizes to:

```
+  if (defined $port_nat) {
+    $port = $port_nat
+  }
    exec {$client} ("$client @cmdline |", $ip, $port);
```

I'd like to fork and make a pull request unless there are major reasons on why that option shouldn't be supported.

**Comment by achernya** [comment]
I think the behavior you want can be accomplished with manually passing arguments to mosh-client and mosh-server. That way you can have the two ports differ as you desire. The specific "--port_nat" option is sufficiently exotic that I don't think it is worth implementing first-class support for in the mosh perl script.
