### ISSUE TITLE
Mosh 1.2.4.95 doesn't recognize pure IPv6 addresses on the commandline

### ISSUE THREAD

**Issue by xtaran** [mobile-shell/mosh#629]
```
→ mosh  2001:db8::4
/usr/bin/mosh: Could not connect to 2001:db8::4: Address family for hostname not supported
ssh_exchange_identification: Connection closed by remote host
/usr/bin/mosh: Did not find remote IP address (is SSH ProxyCommand disabled?).
```
Works fine if I explicitly use the option `-6`:

```
→ mosh -6 2001:db8::4
The authenticity of host '2001:db8::4 (<no hostip for proxy command>)' can't be established.
ECDSA key fingerprint is 95:94:93:[…]
Are you sure you want to continue connecting (yes/no)? ^C
```

**Comment by cgull** [comment]
The code's working as designed, but the fact that you have to specify `-6` to use IPv6 at all isn't documented well, and this is a UI issue.

When mosh is presented with a numeric IPv4 or IPv6 address, or a hostname that resolves to only an A or AAAA record, it could easily infer which family to use.  Then we'd only need to use `-4` or `-6` on dual-stack hostnames.

**Comment by cgull** [comment]
Also, if that determination fails, then we can give the user a nice specific error message about our inability to roam between v4 and v6 server addresses.  So I think this is worth doing for 1.2.5.

**Comment by cgull** [comment]
Wait, I'm forgetting about the problem of neither mosh nor fake proxy getting the hostname in the first place.  More complicated.  Bah.

**Comment by xtaran** [comment]
Hi,

On Wed, Jun 10, 2015 at 12:54:28PM -0700, cgull wrote:
> The code's working as designed, but the fact that you have to
> specify `-6` to use IPv6 at all isn't documented well, and this is a
> UI issue.

Oh, ok. That was unexpected indeed.

The man page currently states:

       --family=FAMILY

              Force the use of a particular address family, which
	      defaults to `inet' (IPv4), and can also be `inet6'
              (IPv6; requires IO::Socket::IP or IO::Socket::INET6).

Without the knowledge above, I interpreted "which defaults to `inet'
(IPv4)" as "which defaults to `inet' (IPv4) if a host has both, A and
AAAA records".

But yes, it also can be read as "which defaults to `inet' (IPv4) even
if an IPv6 address is given or a host only has an AAAA record".

If the detection can't be improved for 1.2.5, IMHO at least the man
page should be clarified, maybe as follows:

       --family=FAMILY

              Force the use of a particular address family.

              Defaults to `inet' (IPv4) in all cases -- even if a host
	      only has an AAAA DNS record or an IPv6 address is given;
	      no auto detection is implemented so far.

	      Use `inet6' (IPv6; requires IO::Socket::IP or
	      IO::Socket::INET6) if you want mosh to use IPv6.

Thanks for considering!

		Kind regards, Axel

**Comment by xtaran** [comment]
Meh. Github's e-mail parsing seems broken with regards to indentation.

**Comment by andersk** [comment]
`mosh --fake-proxy` does get the actual hostname.

**Comment by cgull** [comment]
This fell in a crack for 1.2.5, but I think it's moderately important to try and improve sooner rather than later.

**Comment by ctrlcctrlv** [comment]
Ran into this issue today, luckily my man page had `6` and `--family`.

What's most annoying is the hostname bug, it should at least resolve the hostname and choose the net accordingly, I mean there only are two (INET and INET6) ;)
