### ISSUE TITLE
Fix signal handler

### ISSUE THREAD

**Issue by elfring** [mobile-shell/mosh#634]
[The variable "got_signal"](https://github.com/keithw/mosh/blob/c58642dd63b8d359a44bdf1197df7b8405e25d94/src/util/select.h#L207) should [use the data type "sig_atomic_t"](https://www.securecoding.cert.org/confluence/display/c/SIG31-C.+Do+not+access+shared+objects+in+signal+handlers).
I guess that a different program design will be needed for your function "[handle_signal](https://github.com/keithw/mosh/blob/f3073bbe5dafb892ce0c1c93dd246233eaa73309/src/util/select.cc#L39)".

**Comment by eminence** [comment]
To quote the GNU libc manual:

> In practice, you can assume that int is atomic. You can also assume that pointer types are atomic; that is very convenient. Both of these assumptions are true on all of the machines that the GNU C Library supports and on all POSIX systems we know of.

While `sig_atomic_t` would be more correct, there's been no known reports of problems with this code, so I'm going to close this issue under the "if it ain't broke, don't fix it" rule :)

**Comment by elfring** [comment]
* Do you care if the access to an array element of a class attribute is still [atomic](http://en.cppreference.com/w/c/language/atomic "atomic types")?
* Can it be needed to mark the corresponding data type as [volatile](http://en.cppreference.com/w/c/language/volatile "volatile type qualifier")?

**Comment by andersk** [comment]
This seems like a legitimate issue that might as well be fixed, even if it’s incredibly unlikely there are any real systems it can affect.

**Comment by elfring** [comment]
Please take another look at [corresponding software design aspects](http://www.informit.com/articles/article.aspx?p=2204014 "Article “Accessing shared atomic objects from within a signal handler in C” by Robert C. Seacord (2014-04-24)").

**Comment by andersk** [comment]
@elfring There’s no need for condescension. If you think we have a specific disagreement, state it.
