### ISSUE TITLE
Better return code after exception handling

### ISSUE THREAD

**Issue by elfring** [mobile-shell/mosh#635]
I would prefer that [a non-zero value](https://en.wikipedia.org/wiki/Exit_status) will be returned by [your program](https://github.com/keithw/mosh/blob/543f346ac761f3093d1efb1f359f179a1d9bb078/src/frontend/mosh-client.cc#L166) after an exception was caught.

**Comment by cgull** [comment]
This was fixed some time back in 5959342ac76e04792920b5cccffd67a840b2193d.
