### ISSUE TITLE
Remove unnecessary null pointer checks

### ISSUE THREAD

**Issue by elfring** [mobile-shell/mosh#636]
[An extra null pointer check is not needed](https://isocpp.org/wiki/faq/freestore-mgmt#delete-handles-null) in a function like "[~STMClient](https://github.com/keithw/mosh/blob/543f346ac761f3093d1efb1f359f179a1d9bb078/src/frontend/stmclient.h#L123)".

**Comment by eminence** [comment]
8f68400c13b44a4e819d703c2be2bf3dd6198fa5 probably closes this issue.  CC @cgull

**Comment by cgull** [comment]
Yup, I don't see any instances of that code smell any more.
