### ISSUE TITLE
Mosh with uclibc

### ISSUE THREAD

**Issue by WillItWork** [mobile-shell/mosh#639]
I'm working with a uclibc environment, where everything is (built-in) en_US.UTF-8. I know it defaults to C, but it's been built for Unicode.

However, `LC_TYPE` doesn't work, because it's a glib thing. The locale is still supported, and is native.

Is there any way to force mosh to ignore, or not detect?

**Comment by andersk** [comment]
Mosh detects Unicode support via `nl_langinfo(CODESET)` ([here’s the code](https://github.com/keithw/mosh/blob/mosh-1.2.4/src/util/locale_utils.cc#L73-94)). What does `nl_langinfo(CODESET)` return for you?

**Comment by WillItWork** [comment]
Closing ticket because uclibc is unsupported and I have moved on. Sorry to waste your time.
