### ISSUE TITLE
Please place 1.2.5 OS X packages as GitHub releases

### ISSUE THREAD

**Issue by nmcspadden** [mobile-shell/mosh#654]
We have an automated mechanism that downloads new releases from this Github repo.  It's been working great so far, but your OS X packages are added separately, not as Github releases, and so our mechanism didn't see them.  It would make me quite happy if you provided them as releases instead of custom links.  Thanks! :)

**Comment by keithw** [comment]
Hello, thanks for letting me know. Who is "we"? I think (as we say at http://mosh.mit.edu) we would prefer that users get mosh from some mechanism with updates (e.g. Fedora, Ubuntu, MacPorts, Homebrew) if possible.

If there's an automated system that is downloading the OS X binary .pkg files, can you tell us more about it?

**Comment by nmcspadden** [comment]
Sorry, when I say "we", I mean via [AutoPkg](https://github.com/autopkg/autopkg).  I've written a recipe (which is not currently open sourced, but will be shortly) that automatically looks at [GitHubReleases](https://github.com/autopkg/autopkg/wiki/Processor-GitHubReleasesInfoProvider) for URLs and then downloads the appropriate one with some regex.

Basically, what I'd like for this recipe is for a dedicated URL that will always grab the latest OS X package.  If you've got a URL such as "http://mosh.mit.edu/osx-latest.pkg", that'd make my life even easier! But GitHub releases also work, because they can be parsed for URLs to find the specific package.

Alternatively, if you strongly prefer users on OS X get it via MacPorts or Homebrew, I'll stop using this method and rely on one of those instead - but this way is easier, honestly, because it's also automatic and we have an internal software installation service that can continually deploy updates.

**Comment by cgull** [comment]
Our current OS X standalone/universal .pkg builds are rather manual and ad-hoc, and I don't think they have the maturity of other package builds (even Macports/Homebrew builds).  We also haven't got any formal/automated process for making those packages available.  So I'm hesitant about recommending anything as a target for automation.

I don't have a *strong* preference for using package managers.  The reason I suggest using one if available is partly about avoiding install conflicts between package-manager installs and OS X installs for less-clueful users, now that the OS X package has to install into /usr/local for Rootless Mode.  It's not a strong preference.  If you're sophisticated enough to be doing managed installs with AutoPkg (looks nifty!), do whatever you want.

Could the GitHubReleases provider and/or your recipe use URLs in the GitHub release notes that point to packages at mosh.mit.edu?

**Comment by nmcspadden** [comment]
Sure, I could write a custom processor to scrape those URLs from the
release notes, if you didn't want to provide the package as a release.

Part of the goal of this process was to provide a one-click install for our
users depending on mosh with IPv6 support.  Previously, mosh had to be
compiled in a specific way for IPv6 support, and that process was pretty
dramatic for some of our end users.  The release of 1.2.4.95rc2 was super
easy to process via AutoPkg, because it was a github release.

Obtaining future releases of mosh are going to depend on me regexing
https://mosh.mit.edu/mosh-XXXX.pkg and hoping the version format never
changes.  It's just a bit more fragile and more prone to breakage should
you ever change how versions are handled.

Thanks for engaging me on this topic, I appreciate the response.

On Fri, Jul 24, 2015 at 11:51 AM, cgull <notifications@github.com> wrote:

> Our current OS X standalone/universal .pkg builds are rather manual and
> ad-hoc, and I don't think they have the maturity of other package builds
> (even Macports/Homebrew builds). We also haven't got any formal/automated
> process for making those packages available. So I'm hesitant about
> recommending anything as a target for automation.
>
> I don't have a *strong* preference for using package managers. The reason
> I suggest using one if available is partly about avoiding install conflicts
> between package-manager installs and OS X installs for less-clueful users,
> now that the OS X package has to install into /usr/local for Rootless Mode.
> It's not a strong preference. If you're sophisticated enough to be doing
> managed installs with AutoPkg (looks nifty!), do whatever you want.
>
> Could the GitHubReleases provider and/or your recipe use URLs in the
> GitHub release notes that point to packages at mosh.mit.edu?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/keithw/mosh/issues/654#issuecomment-124626145>.
>



-- 
--
Nick McSpadden
nmcspadden@gmail.com
