### ISSUE TITLE
Add tests for terminal emulation

### ISSUE THREAD

**Issue by keithw** [mobile-shell/mosh#656]
Here are all of my bugs that I filed against hterm:

https://code.google.com/p/chromium/issues/list?can=1&q=winstein%40gmail.com&colspec=ID+Pri+M+Stars+ReleaseBlock+Cr+Status+Owner+Summary+OS+Modified&cells=tiles

I believe Mosh currently is free of these bugs (and was then) and would be nice to keep it that way.

**Comment by achernya** [comment]
From Keith on IRC:

"achernya: I think since that issue was posted, cgull created a bunch of termemu tests in Mosh, so I'm not sure more action is needed."
