### ISSUE TITLE
On systems without IPv4 address mapping, mosh-server doesn't receive IPv4 by default

### ISSUE THREAD

**Issue by beam** [mobile-shell/mosh#657]
Hello, after upgrade to 1.2.5 i have problem run mosh server without -s param, 
there is **setsockopt( IP_RECVTOS ): Invalid argument** error.

```
root@freebsd:~ # uname -a
FreeBSD freebsd 10.1-RELEASE-p16 FreeBSD 10.1-RELEASE-p16 #0: Tue Jul 28 12:04:19 UTC 2015     root@amd64-builder.daemonology.net:/usr/obj/usr/src/sys/GENERIC  amd64
r
root@freebsd:~ # mosh-server new
setsockopt( IP_RECVTOS ): Invalid argument

MOSH CONNECT 60001 PIuj3A9fIsVi326kdX8RJQ

mosh-server (mosh 1.2.5) [build mosh 1.2.5]
Copyright 2012 Keith Winstein <mosh-devel@mit.edu>
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>.
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.

[mosh-server detached, pid = 98607]

Warning: termios IUTF8 flag not defined.
Character-erase of multibyte character sequence
probably does not work properly on this platform.
root@freebsd:~ # sockstat -4 | grep mosh
root@freebsd:~ # 
root@freebsd:~ # mosh-server new -s

MOSH CONNECT 60001 ZVmC9FR4bSb16I7XAW2aKw

mosh-server (mosh 1.2.5) [build mosh 1.2.5]
Copyright 2012 Keith Winstein <mosh-devel@mit.edu>
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>.
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.

[mosh-server detached, pid = 11680]

Warning: termios IUTF8 flag not defined.
Character-erase of multibyte character sequence
probably does not work properly on this platform.
root@freebsd:~ # sockstat -4 | grep mosh
root     mosh-serve 11680 4  udp4   192.168.0.162:60001   *:*
root@freebsd:~ # 
```

after downgrade to 1.2.4 it works again

```
root@freebsd:~ # mosh-server new

MOSH CONNECT 60001 Me/iTk6y4osUhZQp57M5TQ

mosh-server (mosh 1.2.4)
Copyright 2012 Keith Winstein <mosh-devel@mit.edu>
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>.
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.

[mosh-server detached, pid = 9241]

Warning: termios IUTF8 flag not defined.
Character-erase of multibyte character sequence
probably does not work properly on this platform.
root@freebsd:~ # sockstat -4 | grep mosh
root     mosh-serve 9241  4  udp4   *:60001               *:*
root@freebsd:~ # 
```

**Comment by keithw** [comment]
Hello,

Does this actually stop mosh-server from working, or is it just a nonfatal warning message?

**Comment by beam** [comment]
It doesn't open UDP on *:60001 for listening. So without -s mosh server
doesn't work.
Dne 2. 8. 2015 20:25 napsal uživatel "Keith Winstein" <
notifications@github.com>:

**Comment by cgull** [comment]
That's all odd, because I do a fair bit of my development on FreeBSD, and it works well on a variety of FreeBSD releases.

That said, I was able to reproduce your problem on a 10.1 machine (not mine) that is running jails and has badly configured network (it cannot reach itself on any of its addresses).  When I look at sockstat, I see that mosh-server has bound to udp6 *:60001.

Can you look at that, and if possible, show us your /etc/rc.conf, /etc/sysctl.conf, and jail configurations?

**Comment by beam** [comment]
I made for testing clean virtual machine in VirtualBox. No jails, no IPv6, just installed.
On IPv4, it doesn't work (as you see down, compared to 1.2.4)
```
root@freebsd:/home/beam # ifconfig -a
em0: flags=8843<UP,BROADCAST,RUNNING,SIMPLEX,MULTICAST> metric 0 mtu 1500
        options=9b<RXCSUM,TXCSUM,VLAN_MTU,VLAN_HWTAGGING,VLAN_HWCSUM>
        ether 08:00:27:e8:43:ba
        inet 192.168.0.162 netmask 0xffffff00 broadcast 192.168.0.255
        nd6 options=29<PERFORMNUD,IFDISABLED,AUTO_LINKLOCAL>
        media: Ethernet autoselect (1000baseT <full-duplex>)
        status: active
lo0: flags=8049<UP,LOOPBACK,RUNNING,MULTICAST> metric 0 mtu 16384
        options=600003<RXCSUM,TXCSUM,RXCSUM_IPV6,TXCSUM_IPV6>
        inet6 ::1 prefixlen 128
        inet6 fe80::1%lo0 prefixlen 64 scopeid 0x2
        inet 127.0.0.1 netmask 0xff000000
        nd6 options=21<PERFORMNUD,AUTO_LINKLOCAL>
```
```
root@freebsd:/home/beam # cat /etc/rc.conf
hostname="freebsd"
ifconfig_em0="DHCP"
# ifconfig_em0_ipv6="inet6 accept_rtadv"
sshd_enable="YES"
dumpdev="NO"
```
```
root@freebsd:/home/beam # cat /etc/sysctl.conf
# $FreeBSD: releng/10.1/etc/sysctl.conf 112200 2003-03-13 18:43:50Z mux $
#
#  This file is read when going to multi-user and its contents piped thru
#  ``sysctl'' to adjust kernel values.  ``man 5 sysctl.conf'' for details.
#

# Uncomment this to prevent users from seeing information about processes that
# are being run under another UID.
#security.bsd.see_other_uids=0
```

Mosh 1.2.5, listen only on IPv6, not IPv4
```
root@freebsd:/home/beam # mosh-server new
setsockopt( IP_RECVTOS ): Invalid argument
MOSH CONNECT 60001 FHl8BUKbtI0JjQEp7nvq+g
mosh-server (mosh 1.2.5) [build mosh 1.2.5]
root@freebsd:/home/beam # sockstat | grep mosh
root     mosh-serve 689   4  udp6   *:60001               *:*
```

Mosh 1.2.5 with -s parametr, listen on IPv4
```
root@freebsd:/home/beam # mosh-server new -s
MOSH CONNECT 60001 a9tKR14O5UorsdgFt9Mceg
mosh-server (mosh 1.2.5) [build mosh 1.2.5]
root@freebsd:/home/beam # sockstat | grep mosh
root     mosh-serve 718   4  udp4   192.168.0.162:60001   *:*
```

Mosh 1.2.4 listen on IPv4
```
root@freebsd:/home/beam # mosh-server new
MOSH CONNECT 60001 y+QmCK1Ngq66JlMYmESUVA
mosh-server (mosh 1.2.4)
root@freebsd:/home/beam # sockstat | grep mosh
root     mosh-serve 700   4  udp4   *:60001               *:*
```

**Comment by cgull** [comment]
Sorry for making you do that, I had some testing errors and went off in the wrong direction.  This actually happens on all FreeBSD systems.  The issue is that unlike most Linux systems, FreeBSD (also NetBSD and OpenBSD, apparently) doesn't enable v4-to-v6 address mapping by default.  So when mosh-server binds its socket to a default IPv6 address, it only receives IPv6 packets.

To fix this, mosh-server needs to listen on two separate sockets, one for IPv4 and IPv6 (this is a solution portable across all systems), and might also want to add some configuration for behavior in this area.  It is an edge case though, because the mosh script avoids this problem by default.

There's several workarounds:
* the `-s` option as you discovered-- but that depends on your SSH session setting the SSH_CONNECTION environment variable.  If you're not connecting to the server with SSH to start the session, you won't have that.
* the `-i addr` option, which lets you specify an address to listen on.
* telling the FreeBSD kernel to do v4-to-v6 address mapping by setting the sysctl variable `net.inet6.ip6.v6only` to 0, or setting the rc.conf variable `ipv6_ipv4mapping` (same thing).

But I also want to back up and ask, what's the complete issue here?  Why are you running mosh-server manually?

**Comment by beam** [comment]
Issue here is JuiceSSH client with mosh connection doesn't work on *BSD after upgrade to 1.2.5 with default settings on both sides.

**Comment by beam** [comment]
And -s or -i isn't usable for me, from my local network i have to connect to my local IP and from internet i connect to public IP. I have local resolver configured to return local IP on query for my public hostname.

**Comment by keithw** [comment]
This seems like a pretty unfortunate regression -- maybe we should push JuiceSSH to push out an update with `-s` as a default argument (like the `mosh` script).

**Comment by cgull** [comment]
I just sent mail to the JuiceSSH maintainers, we'll get something worked out one way or another.

**Comment by cgull** [comment]
@beam, why *isn't* `-s` usable?  I'm missing something there.  Do you not have a single hostname and IP address you can use from both local and public networks?  Does roaming between the two networks work?

**Comment by beam** [comment]
I can't connect from my local network to my public IP, so my public hostname my.server.tld is on my local network DNS resolver resolved as 192.168.0.1 and in the Internet is resolved as my public IP as usualy.

When i connect at home to my.server.tld with `-s`, mosh-server is listen on 192.168.0.1:60001 and when i go outside connection is lost because i need mosh-server on another interface accessable from internet (but not so well accessable from local network).

Roaming worked great when mosh-server listen on all interfaces (*:60001) which is problem on FreeBSD without ipv6_ipv4mapping for now.

**Comment by andersk** [comment]
@beam, I’m not seeing how that could have ever worked. When you connect at home, the client starts sending packets to 192.168.0.1. When you roam to outside, the client continues sending packets to 192.168.0.1. (Mosh has not implemented re-resolution of the DNS name to get a new IP address on the fly. There are open issues discussing that.) It doesn’t matter which interfaces the server is listening on if the client doesn’t know where to send packets.

**Comment by beam** [comment]
I tried it on 1.2.4 and it really doesn't work. Sorry than.
Param -s resolv my init problem on FreeBSD.

**Comment by eminence** [comment]
Does anyone know the status of this issue on the latest version of mosh (1.3.2)?  Looks like the above PR fixed this issue, but a confirmation that no one is seeing this issue anymore would be nice to have.

**Comment by achernya** [comment]
We are assuming that this has been fixed. Please reopen if that is not the case.
