### ISSUE TITLE
Fix ECN receipt on FreeBSD

### ISSUE THREAD

**Issue by keithw** [mobile-shell/mosh#658]
Right now mosh only checks for the `IP_TOS` cmsg type to get the ECN bits (https://github.com/mobile-shell/mosh/blob/master/src/network/network.cc#L496).

On FreeBSD, the type is actually `IP_RECVTOS` (Linux uses `IP_TOS`).

So mosh should check for both cmsg types in order to make ECN receipt work properly on FreeBSD.

(Per 2014 email from Michael Tuexen)

**Comment by cgull** [comment]
Fixed by dfdfa5d9b0fa7a8f80df6367ff3cb8c1c9d68459.
