### ISSUE TITLE
vte based terminals & mosh

### ISSUE THREAD

**Issue by glensc** [mobile-shell/mosh#660]
vte based terminals (mate-terminal, lxterminal, gnome-terminal, ...) have problem with refreshing.
(it's probably already known issue. but i was unable to find any issues or PR when searching `vte`)

to reproduce (i believe):
- `mosh somehost`
- look some long pages of text (`less somefile`), press space for next page

you will notice that some parts of the screens are not painted with updates. to force paint one can `C-a` `C-a` (screen switch window), but also helps with desktop alt-tab to other window that covers terminal, and then alt-tab again to switch back, so that terminal itself needs to repaint.

it's probably more vte bug than mosh bug, but would like to track and follow progress of it.

**Comment by glensc** [comment]
oh, sorry, i searched only open issues

but [closed issues](https://github.com/mobile-shell/mosh/issues?q=is:issue+vte+is:closed) gives bunch of similar problems. suggesting to select with mouse, etc

perhaps still keep one issue open (so one could subscribe there in hope tracking fix progress), or have it in [faq](https://mosh.mit.edu/#faq)?

**Comment by glensc** [comment]
[looks like](https://github.com/mobile-shell/mosh/issues/325#issuecomment-43454119), [there was](https://github.com/mobile-shell/moshweb/pull/26/files) a faq entry, but it is no more. and seems vte3 fixes it, but not older ones.

**Comment by glensc** [comment]
found some patch for gtk2, will be testing it for a while

**Comment by andersk** [comment]
The FAQ entry was [commented](https://github.com/mobile-shell/moshweb/commit/709e7c4b7721bb77a24b379104f91ae50f0aa169#diff-eacf331f0ffc35d4b482f1d15a887d3bR753) with the 1.2.5 release. This bug has been fixed in VTE upstream, so the only thing left to do is tell you to update your software; there’s nothing left for Mosh to do here. Please do let us know if you still see problems in vte 0.35 or higher, though.

**Comment by glensc** [comment]
yes, i backported fix for 0.28.2, as seen in related commits
