### ISSUE TITLE
Mosh depends on SSH ProxyCommand which depends on $SHELL having 'exec', which xonsh doesn't have

### ISSUE THREAD

**Issue by scopatz** [mobile-shell/mosh#663]
Hello, I am one of the developers of [xonsh](http://xonsh.org).  Mosh fails to start up with xonsh as the shell, complaining about exec, see this comment https://github.com/scopatz/xonsh/issues/84#issuecomment-128830865. Or on my machine.

```console
scopatz@athenaie ~ $ $SHELL = '/home/scopatz/.local/bin/xonsh'
scopatz@athenaie ~ $ mosh localhost
xonsh: subprocess mode: command not found: exec
Did you mean one of the following?
    ex:     Command (/usr/bin/ex)
    xev:    Command (/usr/bin/xev)
    xexec:  Alias
    etex:   Command (/usr/bin/etex)
    jexec:  Command (/usr/bin/jexec)

No command 'exec' found, did you mean:
 Command 'jexec' from package 'openjdk-7-jre-headless' (main)
 Command 'jexec' from package 'openjdk-6-jre-headless' (universe)
 Command 'jexec' from package 'default-jre' (main)
 Command 'jexec' from package 'openjdk-8-jre-headless' (universe)
 Command 'pexec' from package 'pexec' (universe)
 Command 'gexec' from package 'gexec' (universe)
 Command 'hexec' from package 'hexec' (universe)
 Command 'kexec' from package 'kexec-tools' (main)
ssh_exchange_identification: Connection closed by remote host
/usr/bin/mosh: Did not find remote IP address (is SSH ProxyCommand disabled?).
```

I can't tell if this issue is mosh's or xonsh's. Not understanding mosh deeply, it doesn't even seem like xonsh has fully started up (no reading of the xonshrc file) by the time this error is issued.  Furthermore, there are [only two places in mosh where exec is even mentioned](https://github.com/mobile-shell/mosh/blob/ebecb9bd3a4cdab43c2847ab35ceeb49618ea5ae/scripts/mosh.pl#L282).  The error message issues is not the error message associate with those lines of code, as far as I can tell.  

Any idea about where to look or what is going on?  Advice is most appreciated!

**Comment by keithw** [comment]
Can you try running something much simpler? What does this do?

`ssh localhost hostname`

**Comment by kseistrup** [comment]
That gives the local machine's hostname.

**Comment by keithw** [comment]
Ok, how about this?

`ssh -t localhost mosh-server new`

**Comment by kseistrup** [comment]
I don't know much Perl, but I assume the `exec` somehow comes from the line

```perl
my $pid = open(my $pipe, "-|");
```

(must be an equivalent to `subprocess.Popen`).

**Comment by keithw** [comment]
Ok, try running this too then please:

`perl -wle 'print open( my $pipe, "-|" )'`

**Comment by kseistrup** [comment]
```sh
$ ssh -t localhost mosh-server new
kas@localhost's password: 
mosh-server needs a UTF-8 native locale to run.

Unfortunately, the local environment ([no charset variables]) specifies
the character set "US-ASCII",

The client-supplied environment ([no charset variables]) specifies
the character set "US-ASCII".

LANG=
LC_CTYPE="POSIX"
LC_NUMERIC="POSIX"
LC_TIME="POSIX"
LC_COLLATE="POSIX"
LC_MONETARY="POSIX"
LC_MESSAGES="POSIX"
LC_PAPER="POSIX"
LC_NAME="POSIX"
LC_ADDRESS="POSIX"
LC_TELEPHONE="POSIX"
LC_MEASUREMENT="POSIX"
LC_IDENTIFICATION="POSIX"
LC_ALL=
Connection to localhost closed.
```

**Comment by kseistrup** [comment]
```sh
$ $ perl -wle 'print open( my $pipe, "-|" )'
31805
```

**Comment by kseistrup** [comment]
So it's the [missing] `LC_*` variables that is the culprit.

**Comment by keithw** [comment]
Not following you, sorry. Can you hop on the #mosh IRC channel and we can sort this out?

**Comment by kseistrup** [comment]
I'm already there.

**Comment by keithw** [comment]
You don't seem to be responding. Are you on Freenode #mosh? There's a link at http://mosh.mit.edu

**Comment by kseistrup** [comment]
Nope, #mosh @ OFTC.

**Comment by keithw** [comment]
The channel's on Freenode -- please head over there.

**Comment by kseistrup** [comment]
I'm sorry, but the channel is on OFTC:

https://github.com/scopatz/xonsh/pull/325/files

**Comment by cgull** [comment]
Well, I see two problems here:

1) xonsh doesn't implement the exec command.  That's kind of an important one.

2) Mosh, by passing a single string (with metacharacters?) for the SSH command to Perl's exec(), causes Perl to use $SHELL to interpret the string and exec that command, and $SHELL gets the two args:
`-c` `exec '/usr/local/bin/mosh' '--family=inet' --fake-proxy -- localhost 22`

That's unnecessary, and fertile ground for security issues.

**Comment by andersk** [comment]
This isn’t quite accurate. Perl uses `/bin/sh` to interpret the string, not `$SHELL`. If you’ve pointed `/bin/sh` to a non-POSIX-compliant shell, then you will have problems with many applications.

I tend to agree that it’s unnecessary, since I don’t expect users to pass (e.g.) multiple semicolon-separated commands to `--ssh`. I have therefore opened #664. However, I have been wrong about users before.

**Comment by andersk** [comment]
Oh. I figured out where the `exec` is really coming from, and we can’t really do anything about it: it’s `ssh` calling back to `$SHELL -c 'exec mosh --fake-proxy'`.

**Comment by keithw** [comment]
Yes, this demonstrates the problem in xonsh without Mosh or Perl:

`ssh localhost -o ProxyCommand="nc localhost 22"`

**Comment by keithw** [comment]
I think the xonsh guys will have to fix this one if they want to work with systems (like OpenSSH) that expect that $SHELL is a POSIX-conforming shell. (`exec` is required by POSIX.) This doesn't seem to actually affect Perl, and (I think) iit only affects Mosh because Mosh runs SSH with a ProxyCommand.

**Comment by cgull** [comment]
We *can* do something about that:  set SHELL=/bin/sh before invoking SSH.  I think that's reasonable since we're invoking ssh programmatically, not as an interactive session.  Except, as @andersk notes, users.  They can be clever.

**Comment by scopatz** [comment]
Ahh great! Thanks @keithw @andersk @cgull and @kseistrup for hunting this down in record time (sorry I was async after the cafe closed).  I can confirm that `ssh localhost -o ProxyCommand="nc localhost 22"`  on its own also triggers this issue.  I'll tackle this from that angle then.

**Comment by keithw** [comment]
Closing this as a Mosh issue, but please let us know if we can be helpful!

**Comment by scopatz** [comment]
Thanks @keithw!

**Comment by cgull** [comment]
Commit 09bdc7caaee4473b4f1087b1e58058b3ea383655 fixes this from the Mosh side.

**Comment by scopatz** [comment]
Thanks @cgull!
