### ISSUE TITLE
mosh v1.2.5 still producing issues #473 #472

### ISSUE THREAD

**Issue by jessup** [mobile-shell/mosh#666]
both client and server are mosh v 1.2.5.  I try to connect to server from within Emacs shell:

Server started without pseudo-terminal. Opening 80x24 terminal.

Assertion failed: (s_height > 0), function Framebuffer, file terminalframebuffer.cc, line 74.
abort trap: 6

**Comment by andersk** [comment]
M-x shell doesn't implement enough of a terminal to usefully run Mosh. Try M-x term or M-x ansi-term instead.

**Comment by jessup** [comment]
that does it--thanks
