### ISSUE TITLE
bind-server option rejects IPv6 addresses

### ISSUE THREAD

**Issue by robbat2** [mobile-shell/mosh#669]
--bind-server=IP does not support IPv6 addresses.

/usr/bin/mosh: Unknown server binding option: (ipv6 address)

**Comment by doomrobo** [comment]
[This](https://github.com/mobile-shell/mosh/blob/master/scripts/mosh.pl#L165) regex may be the only thing that's preventing this from working.

**Comment by robbat2** [comment]
https://github.com/mobile-shell/mosh/pull/670

**Comment by cgull** [comment]
#670 has been pulled.
