### ISSUE TITLE
Mosh drops connection when command has dash - symbol

### ISSUE THREAD

**Issue by a-b** [mobile-shell/mosh#672]
Running mosh on OS X installed with `brew install mosh`

`mosh server_alias screen` - works
`mosh server_alias 'screen -dR session_name'` - [mosh is exiting.]

`mosh server_alias` and `screen -dR session_name'` - works

any hint's how to debug that?

**Comment by keithw** [comment]
Mosh follows the convention of using `--` as a separator between options and arguments.

Try this: `mosh server_alias -- screen -dR session_name`

**Comment by a-b** [comment]
Ok, probably I brough wrong example I have a

`mosh server_alias -- 'tmux a -t pairing || tmux new -s pairing'`

**Comment by a-b** [comment]
with ssh i run that as `ssh server_alias -t 'tmux a -t pairing || tmux new -s pairing' `

**Comment by keithw** [comment]
ssh's command-line parsing is buggy and we chose not to emulate it. The arguments to mosh are exactly the same as a normal shell. If you run `'tmux a -t pairing || tmux new -s pairing'` at the shell, you'll get "command not found," and the same happens with mosh. (Run mosh with `--no-init` to see the error message.) But you can run this to do what you're trying to do:

`mosh --no-init localhost -- sh -c 'tmux a -t pairing || tmux new -s pairing'`

**Comment by keithw** [comment]
To elaborate a bit on how mosh works the same as sh (and unlike ssh):

```
$ echo "Hell's kitchen"
Hell's kitchen
$ mosh --no-init localhost -- echo "Hell's kitchen"
Hell's kitchen
 
[mosh is exiting.]
$ ssh localhost -- echo "Hell's kitchen"
bash: -c: line 0: unexpected EOF while looking for matching `''
bash: -c: line 1: syntax error: unexpected end of file
```

**Comment by a-b** [comment]
Awesome! Thanks for detailed explanation.
Created https://github.com/mobile-shell/mosh/wiki/Usage where we can move this beautiful example.
