### ISSUE TITLE
Can I see where the client is connected from in current session?

### ISSUE THREAD

**Issue by ddofborg** [mobile-shell/mosh#674]
I'm using GNU Screen in combination with MOSH. In the screen statusbar I have a ping status/speed from the host to the client. Just to see how fast the connection is.

Somehow when I'm connected via MOSH I don't always see on the ip where the client is connected form. Sometimes `who -a -l` shows the IP, sometimes it doesn't. And because screen is started earlier SSH_CLIENT env. variable has the IP of the first client and not the current client.

`who -a -l` shows:

```
user + pts/6        2015-08-31 18:29   .         23848 (141:S.11)
```

My IP stats with `141` and `S.11` is the screen number 11, but I cannot see the full address.

Any ideas how to solve this?

**Comment by achernya** [comment]
From reading screen.git:src/utmp.c I think this is probably a bug in screen, since it does re-write utmp entries. If you can reproduce with tmux please let us know.
