### ISSUE TITLE
bash completion on OS X and homebrew not working 

### ISSUE THREAD

**Issue by georgexsh** [mobile-shell/mosh#675]
bash tab completion in OS X not working, error message is
```
-bash: _init_completion: command not found
```
it looks like bash-completion 1.3 which homebrew installed, doesn't include `_init_completion`
ref: https://github.com/kubernetes/kubernetes/pull/13570/files#diff-930870013bd67170378f456609d58168R10

**Comment by iurii-polishchuk** [comment]
Works like a charm! Thanks!

**Comment by koma85** [comment]
So, what's the best way to fix this?

**Comment by iurii-polishchuk** [comment]
Update your /usr/local/etc/bash_completion.d/mosh with following content:

```
_init_completion()
{
    COMPREPLY=()
    _get_comp_words_by_ref cur prev words cword
}
 
_mosh () {
    local cur prev
    _init_completion || return
    _known_hosts_real -a "$cur"
}
complete -F _mosh mosh
```

**Comment by cgull** [comment]
bash-completion 1.3 is ancient, but I think it's used because OS X uses bash 3.2 (and now it's also `/bin/sh` as well).  Newer versions of bash-completion only support bash 4.1 and later, and are of course found on recent Linux distributions.
If we can write a completion that works with both versions, that'd be great.

**Comment by georgexsh** [comment]
@cgull thanks very much!

**Comment by petitchevalroux** [comment]
Am I the only one having this issue with mosh 1.2.5.95rc1 ?
I did a "fresh" reinstall using :
brew uninstall mosh
brew install --HEAD mosh
mosh --version
mosh 1.2.5.95rc1 [build mosh-1.2.5.95rc1-1-g274b5a4-dirty]
Copyright 2012 Keith Winstein <mosh-devel@mit.edu>
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>.
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.

OSX El Capitan 10.11.5

bash --version
GNU bash, version 3.2.57(1)-release (x86_64-apple-darwin15)
Copyright (C) 2007 Free Software Foundation, Inc.

**Comment by georgexsh** [comment]
@petitchevalroux I didn't upgrade mosh to dev version, but copied https://raw.githubusercontent.com/y-higuchi/mosh/c35b4de3a2439a6722d6afc35cbbf332ad6c1088/conf/bash-completion/completions/mosh to `/usr/local/Cellar/mobile-shell/1.2.5/etc/bash_completion.d/mosh` ...

**Comment by petitchevalroux** [comment]
@georgexsh just did your tips (and reinstalling 1.2.5 from brew) ... and it's ok. TY  ;-)

**Comment by cgull** [comment]
@petitchevalroux, what problem were you having with completion?  It works for me after `brew install --HEAD mosh` with both OS X bash 3.2.57 and brew bash 4.3.42.

**Comment by petitchevalroux** [comment]
@cgull I fixed it using @georgexsh tricks. The problem occured with stock macosx bash, it's why you didn't have the problem imho ;)
