### ISSUE TITLE
Locale setup issue

### ISSUE THREAD

**Issue by Kwpolska** [mobile-shell/mosh#678]
Server: Fedora 22  
Client: Arch Linux

```
The locale requested by LC_CTYPE=en_GB.UTF-8 isn't available here.
Running `locale-gen en_GB.UTF-8' may be necessary.

mosh-server needs a UTF-8 native locale to run.

Unfortunately, the local environment ([no charset variables]) specifies
the character set "US-ASCII",

The client-supplied environment (LC_CTYPE=en_GB.UTF-8) specifies
the character set "US-ASCII".

locale: Cannot set LC_ALL to default locale: No such file or directory
LANG=en_GB.UTF-8
LC_CTYPE=en_GB.UTF-8
LC_NUMERIC=en_GB.UTF-8
LC_TIME=en_GB.UTF-8
LC_COLLATE=pl_PL.UTF-8
LC_MONETARY=pl_PL.UTF-8
LC_MESSAGES="en_GB.UTF-8"
LC_PAPER="en_GB.UTF-8"
LC_NAME="en_GB.UTF-8"
LC_ADDRESS="en_GB.UTF-8"
LC_TELEPHONE="en_GB.UTF-8"
LC_MEASUREMENT=pl_PL.UTF-8
LC_IDENTIFICATION="en_GB.UTF-8"
LC_ALL=
Connection to arya.chriswarrick.com closed.
/usr/bin/mosh: Did not find mosh server startup message.
```

* I do not have any locale-specific SSH settings
* the `UTF-8` spelling seems to be mandated by Arch, and it looks like Mosh does not like it?

(this is not #102)

**Comment by keithw** [comment]
This looks like it is probably not a Mosh-specific problem. Your client's locale (and `LC_CTYPE` environment variable in particular) is British English (`en_GB.UTF_8`). It appears that the server does not have a locale built for British English.

Do you see an error message if you run: `ssh USER@SERVER perl` ?

Your options are basically:
(1) Build a British-English locale on the server (using locale-gen or `dpkg-reconfigure locales` as recommended)
(2) Change the client's locale to something that the server already has (perhaps `en_US.UTF-8` or `C.UTF-8`).

**Comment by Kwpolska** [comment]
1. I do not get any errors from Perl.
2. Mosh works correctly with `export LC_ALL='en_GB.UTF-8'` before, which is really weird (and you can’t set LC_ALL in shell startup files)

**Comment by keithw** [comment]
How about from running this?

`ssh USER@SERVER 'LC_MEASUREMENT=pl_PL.UTF-8 LC_CTYPE=en_GB.UTF-8 perl'`

**Comment by Kwpolska** [comment]
Wait, I actually didn’t have a pl_PL locale around on the server.

Sorry for bothering.
