### ISSUE TITLE
Xcode 7/El Capitan break mosh build

### ISSUE THREAD

**Issue by cgull** [mobile-shell/mosh#680]
- The existing mosh-1.2.5 packages still install fine.
- `pkgutil --unlink <pkg>` no longer does anything.  We don't use this in the OS X build or package, because it's been undocumented for a long time, but it was convenient for development.  Actually, this functionality seems to have disappeared on my Xcode 6.3/OS X 10.10 machine as well.
- OpenSSL includes are gone from Xcode 7, causing the build to break.  This is true even when setting `MACOSX_DEPLOYMENT_TARGET` to older OS X releases.  Homebrew resolves this by properly referring to its own (Cellar-only) OpenSSL.  The workaround for devel build with Homebrew is `PKG_CONFIG_PATH=/usr/local/opt/openssl/lib/pkgconfig:/usr/local/opt/protobuf/lib/pkgconfig`.  This doesn't work for `macosx/build.sh`, which explicitly sets `OPENSSL_CFLAGS` and `OPENSSL_LIBS` to point at the system OpenSSL and not link in a Homebrew/Fink/MacPorts OpenSSL dylib.  That needs some thought.

**Comment by Kriechi** [comment]
Can you do something like this:
```
# configure.ac

AC_MSG_CHECKING([openssl via homebrew])
openssl_prefix=`$BREW --prefix openssl`
if test -n "$openssl_prefix"; then
    export PKG_CONFIG_PATH="$PKG_CONFIG_PATH:$openssl_prefix/lib/pkgconfig"
    AC_MSG_RESULT([$openssl_prefix])
else
    AC_MSG_RESULT([no])
fi
```

**Comment by cgull** [comment]
I've already committed code that eliminates the problem by using Apple's Common Crypto libraries.

**Comment by cgull** [comment]
But I should update the Homebrew formula, for HEAD at least. I'll do that soon.

**Comment by cgull** [comment]
Our Homebrew contact already updated the formula. Try `brew install --HEAD` if you like.
