### ISSUE TITLE
Support platforme request

### ISSUE THREAD

**Issue by bimawa** [mobile-shell/mosh#681]
Very very much support blackberry 10 OS. Community pls made it! :dancer:  Blackberry 10 os have all for this BB Passport like pocketPC it must have mosh app!
releation post: http://forums.crackberry.com/opensourcebb-f402/request-app-mosh-mobile-shell-ssh-mobile-high-latency-connections-826463/#post8784160

**Comment by cgull** [comment]
BBOS 10 is a now-dead platform with small market share that none of Mosh's developers seem interested in.  So it's unlikely to be done by Mosh's core team.  We'll happily accept code contributions, though.  If these BlackBerry phones support installing/running console apps, a QNX/BB OS 10 port might not be very hard.
