### ISSUE TITLE
Mosh constantly disconnects

### ISSUE THREAD

**Issue by Oliver84** [mobile-shell/mosh#683]
I'm able to connect to my mosh server just fine but every 60 seconds or so, it disconnects and I have to wait 30+ seconds for it to reconnect again so I can keep working. This obviously makes mosh unusable for me. What could be causing this? 

I have a mosh session going with a computer at home that is sleeping and I just started another session here at work. Would that be the issue?

Mosh-server is running on a mac and I'm using the Chrome App as the client at work.

**Comment by keithw** [comment]
When you say that "it disconnects" -- what message do you actually see on the screen? Can you please take a screenshot?

Does the problem happen from other locations (not at your work)? Does it happen with other clients (i.e. not the Chrome app)?

**Comment by Oliver84** [comment]
I've attached a screenshot. I didn't have this issue at home so it may be related to our network? I don't have any other network issues here though and our connection is really fast so I don't know what it could be. 

![capture](https://cloud.githubusercontent.com/assets/5189557/10401360/7d7c3fb2-6e8c-11e5-9e72-a6fb7bd27089.PNG)

**Comment by cgull** [comment]
It sounds like you're running a server at home and trying to reach it from work. When you're connecting to it at home, you're on the same local network, which eliminates a lot of issues. Can you try from a remote location that's not work?  That'll help determine whether the issue is at the home or work end.

If you understand tcpdump well enough, using it can be very helpful for these issues.

**Comment by cgull** [comment]
No response, closing.

**Comment by vipasu** [comment]
Hi,

I'm having a similar, possibly related issue. The scenario for me is that I can usually initiate a mosh session just fine, but usually within a minute, I get the "mosh: last contact xx:xx ago". 

The "fix" that I usually do involves opening a separate terminal and ssh'ing in. Somehow this seems to remind the mosh-server that it's still running. I'm running mosh-server on OSX 10.14, installed via homebrew. I'm not familiar with tcpdump, but I'm happy to run commands and share output.

Thanks,
Vincent
