### ISSUE TITLE
Mosh doesn't finish connecting?

### ISSUE THREAD

**Issue by dondiego87** [mobile-shell/mosh#684]
I found out about Mosh this morning and was super excited to try it — I'm sick of the wi-fi in my office going down for a second and disconnecting me from all my sessions. I installed via brew and then tried doing `mosh server1nickname`, where `server1nickname` is a name I have defined in .ssh/config. It went through the normal process, with the server asking me to authenticate, and then accepting my credentials and showing me the usual intro message. ("Authorized users can ssh to their destination host," "Special commands available.") But it didn't do the last bit, which is actually showing me a live terminal prompt like `[usr@ssh ~]$ `. It's just blank, and typing in the window doesn't do anything.

To clarify what the deal is with this… The way this system works is, I ssh into server1, minimize that window, then ssh into whatever machine I want to work on. Not sure if that's relevant.

Sorry if this is a dumb question, but hopefully that means it's an easy fix? I'm running Mac OS X 10.10.5 in case that matters.

**Comment by eminence** [comment]
I'm a little confused about the workflow.  Ignoring mosh for the moment, is this what you do to get a ssh session?

1.  From OSX, you run:  `ssh server1nickname`
2.  From OSX, you run:  `ssh server2`

And you are only able to connect to `server` if you have an active ssh connection to `server1` ?

If so, does the definition for `server1nickname1 in your .ssh/config do anything fancy (perhaps with a ProxyCommand?)

**Comment by dondiego87** [comment]
Yep, that's how it works. Or for more details and consistency with what is below:

1. Open Terminal window; `ssh server1nickname`
2. Authenticate, wait for success, then minimize window.
3. Open Terminal window; `ssh machine1`
4. Authenticate, wait for success, then I'm good to go.
5. I can now open new Terminal windows and do `ssh machine1` without needing to re-authenticate.

The definition is a bit fancy:

    Host server1nickname
      HostName                ssh.organization.com
      User                    My.Name
      # tunnels to various machines
      LocalForward            3123 machine1.organization.com:22
      LocalForward            3124 machine2.organization.com:22
    Host machine1
      Hostname                localhost
      Port                    3123
      User                    My.Name
    Host machine2
      HostName                localhost
      Port                    3124
      User                    My.Name

**Comment by eminence** [comment]
thank you, this clears things up a lot.  What if you do this:

From OSX, run `ssh server1nickname`
From OSX, run `mosh machine1`

Since mosh doesn't have any port forwarding, you'll need to use ssh to server1nickname.  But once that is set up, you might be able to mosh to the other machines:  mosh will use ssh (over port 3123) to spawn mosh-server on machine1.  If your OSX machine and machine1 have UDP connectivity, mosh should work in this scenario.

but I'm wondering if perhaps machine1 is behind a very restrictive firewall which might not allow any UDP traffic.  in this case, you will be out of luck with mosh

**Comment by andersk** [comment]
Right. Mosh only uses SSH for the initial connection. The rest of the data goes over UDP port 60001. Using Mosh behind a restrictive firewall is generally not possible unless you have something like a VPN to get through it.

**Comment by dondiego87** [comment]
Yup, looks like the firewall is just too restrictive. Thanks though!
