### ISSUE TITLE
Mosh loses track of wrap state when control characters are injected between printing characters

### ISSUE THREAD

**Issue by cgull** [mobile-shell/mosh#687]
This is a repro:

`perl -we 'for my $h (1..13000) { print "a"; for my $i (1..15) { print "\000\000" }}; print "\n"; sleep 2'`

Only a single line of output is produced, instead of wrapping and filling the window.

**Comment by cgull** [comment]
This issue doesn't happen with Unicode continuation characters, though, which is the thing I'm actually gnawing on now.

**Comment by keithw** [comment]
Mosh takes the view that all terminal functions (escape sequences, control sequences, and control characters) clear the wrap state, except those explicitly marked with clears_wrap_state=false in the Function constructor in `src/terminal/terminalfunctions.cc`. (These were basically the ones necessary to pass the tests in `vttest`.)

We could try for bug-compatibility with xterm here, but we'd have to figure out exactly which functions do and don't clear the wrap state. E.g. xterm clears it on `CSI 0 X` (delete zero characters) but leaves it in place for `CSI m` (reset renditions).

If the current behavior passes vttest, I'm not sure we need to change it.
