### ISSUE TITLE
Ubuntu Wily PPA depends on outdated `libprotobuf9`

### ISSUE THREAD

**Issue by neopostmodern** [mobile-shell/mosh#691]
Can't install mosh from Ubuntu Wily (15.10) PPA because it depends on `libprotobuf9`:
```
~ $ sudo apt-get install mosh
Reading package lists... Done
Building dependency tree       
Reading state information... Done
Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
The following information may help to resolve the situation:

The following packages have unmet dependencies:
 mosh : Depends: libprotobuf9 but it is not installable
E: Unable to correct problems, you have held broken packages.
```
Current version seems to be `libprotobuf9v5`
```
~ $ apt-cache -n search libprotobuf
libprotobuf-dev - protocol buffers C++ library (development files)
libprotobuf-lite9v5 - protocol buffers C++ library (lite version)
libprotobuf9v5 - protocol buffers C++ library
libprotobuf-c-dev - Protocol Buffers C static library and headers (protobuf-c)
libprotobuf-c1 - Protocol Buffers C shared library (protobuf-c)
libprotobuf-c1-dbg - Protocol Buffers C shared library debug symbols (protobuf-c)
libprotobuf-java - Java bindings for protocol buffers
libprotobuf7 - protocol buffers C++ library

```

**Comment by arch1mede** [comment]
I ran into this exact same issue, sad that its unresolved after all of these months.

**Comment by keithw** [comment]
Which PPA are you referring to? (mosh-dev?) Can you post a link?

Mosh is already in Ubuntu Wily. Most users do not need to add a PPA at all.

**Comment by arch1mede** [comment]
arch1mede@Ubuntu-Server:~$ mosh
The program 'mosh' is currently not installed. You can install it by typing:
sudo apt-get install mosh
arch1mede@Ubuntu-Server:~$ sudo apt-get install mosh
[sudo] password for arch1mede:
Reading package lists... Done
Building dependency tree
Reading state information... Done
Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
The following information may help to resolve the situation:

The following packages have unmet dependencies:
 mosh : Depends: libprotobuf9 but it is not installable
E: Unable to correct problems, you have held broken packages.

**Comment by keithw** [comment]
Can you "apt-get show mosh"? The version in Ubuntu Wily is 1.2.5-1build1.

**Comment by arch1mede** [comment]
Invalid command

dpkg-query --list >> installed_packages
arch1mede@Ubuntu-Server:~$ more installed_packages | grep mosh
arch1mede@Ubuntu-Server:~$

**Comment by keithw** [comment]
Sorry, I meant `apt-cache show mosh`.

**Comment by arch1mede** [comment]
Did you want me to paste this large output?

**Comment by keithw** [comment]
Yes.

**Comment by arch1mede** [comment]
arch1mede@Ubuntu-Server:~$ apt-cache show mosh
Package: mosh
Priority: optional
Section: net
Installed-Size: 861
Maintainer: Keith Winstein <keithw@mit.edu>
Architecture: amd64
Version: 1.2.5+1038-0ppa~ubuntu15.10.1
Recommends: libio-socket-ip-perl
Depends: libc6 (>= 2.17), libgcc1 (>= 1:4.1.1), libprotobuf9, libssl1.0.0 (>= 1.0.0), libstdc++6 (>= 4.9), libtinfo5, libutempter0 (>= 1.1.5), zlib1g (>= 1:1.1.4), openssh-client
Pre-Depends: dpkg (>= 1.15.7.2)
Filename: pool/main/m/mosh/mosh_1.2.5+1038-0ppa~ubuntu15.10.1_amd64.deb
Size: 205764
MD5sum: b76d694ef60f8cec93a39a58619bbf09
SHA1: cdbe2ac8897dbe01ac50966886dac95515f28b6d
SHA256: 4bddcd7b20b10e88241a217863d942798ae004ea18fce1bcbffd5d949c979ee7
Description-en: Mobile shell that supports roaming and intelligent local echo
 Mosh is a remote terminal application that supports:
 - intermittent network connectivity,
 - roaming to different IP address without dropping the connection, and
 - intelligent local echo and line editing to reduce the effects
 of "network lag" on high-latency connections.
Description-md5: 157ed72d855f8b433961721e47151644

Package: mosh
Priority: optional
Section: universe/net
Installed-Size: 815
Maintainer: Ubuntu Developers <ubuntu-devel-discuss@lists.ubuntu.com>
Original-Maintainer: Keith Winstein <keithw@mit.edu>
Architecture: amd64
Version: 1.2.5-1build1
Depends: libc6 (>= 2.17), libgcc1 (>= 1:4.1.1), libprotobuf9v5, libssl1.0.0 (>= 1.0.0), libstdc++6 (>= 5.2), libtinfo5, libutempter0 (>= 1.1.5), zlib1g (>= 1:1.1.4), openssh-client
Pre-Depends: dpkg (>= 1.15.7.2)
Recommends: libio-socket-ip-perl
Filename: pool/universe/m/mosh/mosh_1.2.5-1build1_amd64.deb
Size: 202250
MD5sum: b64309ba33d1d97aa7a5da7a7c61e502
SHA1: 054e7467350b01b39a5d919696aa7020262f9524
SHA256: b972468be7d871d62d3e44c29f7598fdcd942a91c1ac375e07aa7e0a5b9aab8d
Description-en: Mobile shell that supports roaming and intelligent local echo
 Mosh is a remote terminal application that supports:
   - intermittent network connectivity,
   - roaming to different IP address without dropping the connection, and
   - intelligent local echo and line editing to reduce the effects
     of "network lag" on high-latency connections.
Description-md5: 4eb9a4712a90a06683cd9f2c223953b4
Homepage: http://mosh.mit.edu
Bugs: https://bugs.launchpad.net/ubuntu/+filebug
Origin: Ubuntu

**Comment by keithw** [comment]
Yeah, you don't want that. You probably just want to remove the "mosh" PPA and apt-get update and install Mosh normally from Ubuntu. You don't need a PPA to install Mosh.

Alternately, you can add the mosh-dev PPA (as described at http://mosh.mit.edu) to get a bleeding-edge version of Mosh. Your choice.

**Comment by arch1mede** [comment]
Ahh ok, thanks for the super fast responses...hopefully someone else will benefit from this interaction

**Comment by keithw** [comment]
(Also rebuilt the package in the "mosh" PPA.)
