### ISSUE TITLE
Poor failure mode when gid=5 is missing from /dev/pts mount options

### ISSUE THREAD

**Issue by bretth** [mobile-shell/mosh#700]
As a new Mosh user, I've been tearing my hair out over this, so it probably would be nice to be a standard installation instruction or at worst to be in the FAQ. I'm using a base CentOS 7 as the server but it appears to be an issue on ArchLinux as well since that's where I found the answer via google..

Trying to diagnose why mosh can't connect when the port has been confirmed open.
`mosh-server` silently fails
`mosh-server new -v -i 0.0.0.0`
outputs `forkpty: Operation not permitted`

The solution was to add the user to the tty group `sudo gpasswd -a $USER tty`.

**Comment by andersk** [comment]
I cannot reproduce this on a CentOS 7 server. What is the output of these commands?
```sh
echo "$SSH_TTY"
ls -l /dev/pts
mount | grep /dev/pts
```

**Comment by bretth** [comment]
A user before adding to tty group
![screen shot 2015-12-10 at 11 49 03 am](https://cloud.githubusercontent.com/assets/57012/11703524/0ea592a4-9f34-11e5-87cf-e0e1bb8e2f5a.png)

A user (myself) after adding to tty group
![screen shot 2015-12-10 at 11 48 36 am](https://cloud.githubusercontent.com/assets/57012/11703539/278cb108-9f34-11e5-9599-86629c2ffee6.png)

**Comment by andersk** [comment]
What about `ls -l /dev/ptmx`?

**Comment by bretth** [comment]
crw-rw-rw- 1 root tty 5, 2 Dec 10 12:01 /dev/ptmx

**Comment by andersk** [comment]
Do you have SELinux enabled (`getenforce`)? If so, is there anything relevant in `/var/log/audit/audit.log` or `/var/log/messages`? ([Details](https://access.redhat.com/documentation/en-US/Red_Hat_Enterprise_Linux/7/html/SELinux_Users_and_Administrators_Guide/chap-Security-Enhanced_Linux-Troubleshooting.html))

**Comment by bretth** [comment]
No SELinux is disabled.

**Comment by bretth** [comment]
Sorry I lied - I must have been mistaken. /dev/ptmx shows root tty on the base image

![screen shot 2015-12-10 at 12 39 48 pm](https://cloud.githubusercontent.com/assets/57012/11704357/4517d692-9f3b-11e5-8fda-b80c76609e6b.png)

**Comment by andersk** [comment]
It looks like this is in some kind of VM or container? Do you think it would be easy for us to reproduce the problem with the same base image? That might be faster than this back and forth debugging.

**Comment by bretth** [comment]
Ok so I can't replicate the issue in my local vm (it works fine) only on a hosted vm with a non root user which is otherwise the same headline version of Centos7 - but is the default template image provided (not my image). 

I created a tmp vm, then `yum install epel-release` then `yum install mosh` then `adduser bretth` and then confirmed that `mosh-server new -v -i 0.0.0.0` fails to forkpty if I run it as bretth

I added your public github key so you should be able to login as I can without password to
ssh root@43.229.63.73

**Comment by andersk** [comment]
Your VM has an incorrect line in `/etc/fstab`.

```
none            /dev/pts        devpts  mode=0620       0       0
```

I fixed your problem as follows:

```console
# mount | grep /dev/pts
devpts on /dev/pts type devpts (rw,relatime,mode=620,ptmxmode=000)
# getent group tty
tty:x:5:
# mount /dev/pts -o remount,gid=5
# mount | grep /dev/pts
devpts on /dev/pts type devpts (rw,relatime,gid=5,mode=620,ptmxmode=000)
```

You can make this change permanent by adding `gid=5` to that `/etc/fstab` line. Actually, I’m not sure that `/etc/fstab` line should be present at all. A stock CentOS 7 machine only has one line in `/etc/fstab` (for `/`).

**Comment by andersk** [comment]
By the way, before making that fix, I observed that the `script` command also failed (in case this helps you convince your hosting provider that the problem is not specific to Mosh).

**Comment by bretth** [comment]
@andersk thanks for taking the time to look at it for me. Note that I never expect but always appreciate greatly when someone on an OS project gives a minor issue prompt attention.
