### ISSUE TITLE
Disappearing umlaut character regression

### ISSUE THREAD

**Issue by The-Compiler** [mobile-shell/mosh#702]
Since the last update (i.e. probably due to https://github.com/mobile-shell/mosh/pull/531), when trying to type `Glück ` with my [compose key](https://en.wikipedia.org/wiki/Compose_key) and the completion kicks in, sometimes I end up with having `Gück  ` after the completion in urxvt.

When trying the same with xterm, I see a "unknown char" sign (the `?`-like thing) when predicting, which then gets replaced by the proper char.

[See the log](https://github.com/mobile-shell/mosh/files/68237/mosh-compose.txt) made with [stm-data](https://github.com/keithw/stm-data) like requested by @cgull. The first few lines, it works correctly - then a few times at the end I could constantly reproduce it. Sorry for a few typos from my side :laughing: 

It's definitely easier to reproduce if there's more prediction (like when the train I'm in is in a tunnel), and I haven't seen it show up with `--predict=never`.

I also couldn't reproduce it by middle-click pasting the `ü` so far.

**Comment by cgull** [comment]
When you type `ü`, your terminal program is properly sending it as the two-byte UTF-8 sequence `\303\274`.  But in the failing cases, mosh is sending it back as the equivalent ISO 8859-1 character `\374`, which is an illegal UTF-8 sequence.  urxvt simply ignores this, and XTerm (more correctly) draws the replacement character.  This nicely explains the corruption you're seeing.

In #531 I converted the storage for graphemes from UTF-32 to UTF-8.  I needed to add conversions between them in a few places, and I completely missed the prediction code.  I'll have a fix soon.

**Comment by cgull** [comment]
This is rather hard to reproduce.  There's some interplay between predicted vs. actual packet latency involved here, and packet loss may also play into it too.  There may be some interaction between client-side and server-side prediction code as well.  The only way I can semi-reliably reproduce it is by typing `echo ü` immediately on starting a mosh session, and even then only between two hosts, not on loopback on a single machine.  Typing `faĩl` seems more reliable (it will print `)` then replace with `ĩ`), but its reliability almost makes me thinks there's another bug involved.

I'm about to try trains and tunnels next, but that's no good for regression testing.  If anyone has a good reliable reproduction of this, it'd be extremely helpful.

**Comment by cgull** [comment]
@The-Compiler: there's your Mosh Christmas present.  :gift:
(The fix was the easy part; the harder part was finding a good repro and then getting the test past Travis.)
