### ISSUE TITLE
Mosh fails to install on arch if protoc3 is installed

### ISSUE THREAD

**Issue by jkbbwr** [mobile-shell/mosh#703]
I have protobuf version 3 in my system, the package manager things that the dependency is ok but mosh fails to launch with the following error 
```
jakob@devbox~/t/mosh-1.2.5> mosh root@212.47.245.59
mosh-client: error while loading shared libraries: libprotobuf.so.9: cannot open shared object file: No such file or directory
Died at /usr/bin/mosh line 248.
```

**Comment by egorf** [comment]
Same issue here. Is it possible that usage of libprotobuf.so.9 hardcoded? If yes, how to install previous version to the system?

**Comment by andersk** [comment]
Like any binary that depends on any shared library, the Mosh binaries require a libprotobuf with the same soname that they were compiled against. On Debian and Fedora, the automatically generated package dependencies reflect this requirement, but I don’t know how this works on Arch. There is nothing unusual about Mosh in this respect. You’ll need to take this up with the Arch package maintainer. As a workaround, if you recompile it yourself against the protobuf version you have installed, it should work fine.
