### ISSUE TITLE
mosh-client is no longer usable with Cygwin running on a Windows console

### ISSUE THREAD

**Issue by cgull** [mobile-shell/mosh#707]
In #531 I changed the terminal output code quite a bit.  Turns out that this breaks Mosh when run under Cygwin on a Windows console with its lame "ANSI" emulation.  Mosh now requires the terminal to not immediately wrap to the next line when a character is written in the last column, which is a basic feature of any VT100/XTerm emulator.  So the display can get badly corrupted when using Windows console, where 1.2.5 is usable.

The best fix for this is to run Mosh under some better terminal emulator (`mintty`, `xterm`, `Putty`-- there are many available), because while Mosh did sort of work on Windows console, it's an unfriendly, primitive console, and there are other issues such as mouse support and probably foreground/background color.  Also see #705.  So I'm calling this WONTFIX for now.  But on the off chance that anyone has a workflow where they actually _use_ Mosh on Windows console, or otherwise cares, please speak up.

**Comment by deadalnix** [comment]
I can confirm the same problem exist in other terminals such as cmder/conemu . Is there some config I should look for in there to fix this problem ?

**Comment by deadalnix** [comment]
Screenshot of what's happening:

![conemu bad render](https://user-images.githubusercontent.com/854121/42126960-b6d461e4-7c90-11e8-8c3b-c4e90cd7f153.png)

**Comment by SPDurkee** [comment]
There are now 2 terminals in the Windows Store that support Mosh natively:
https://www.microsoft.com/store/productId/9P2KRLMFXF9T
https://www.microsoft.com/store/productId/9NK1GDVPX09V

**Comment by achernya** [comment]
Windows Terminal and WSL exist and support mosh well.
