### ISSUE TITLE
Kerberos ticket cache file deleted during login

### ISSUE THREAD

**Issue by mmehnert** [mobile-shell/mosh#711]
After a mosh login my kerberos ticket cache file gets deleted. Not sure if this is a mosh issue or related to pam or ssh. Since it's only appearing when using mosh, I'm starting to report it here.

    Jan  9 12:44:16 my-cluster sshd[11003]: pam_krb5(sshd:auth): pam_sm_authenticate: entry (nonull)
    Jan  9 12:44:16 my-cluster sshd[11003]: pam_krb5(sshd:auth): (user my-user) attempting authentication as my-user@KERBEROS.REALM
    Jan  9 12:44:16 my-cluster sshd[11003]: pam_krb5(sshd:auth): user my-user authenticated as my-user@KERBEROS.REALM
    Jan  9 12:44:16 my-cluster sshd[11003]: pam_krb5(sshd:auth): (user my-user) temporarily storing credentials in /tmp/krb5cc_pam_BNIqqr
    Jan  9 12:44:16 my-cluster sshd[11003]: pam_krb5(sshd:auth): pam_sm_authenticate: exit (success)
    Jan  9 12:44:16 my-cluster sshd[11003]: Accepted password for my-user from 95.119.59.xx port 46046 ssh2
    Jan  9 12:44:16 my-cluster sshd[11003]: pam_krb5(sshd:setcred): pam_sm_setcred: entry (establish)
    Jan  9 12:44:16 my-cluster sshd[11003]: pam_krb5(sshd:setcred): (user my-user) initializing ticket cache FILE:/tmp/krb5cc_1001273_Hh6K6J
    Jan  9 12:44:16 my-cluster sshd[11003]: pam_krb5(sshd:setcred): pam_sm_setcred: exit (success)
    Jan  9 12:44:16 my-cluster sshd[11003]: pam_unix(sshd:session): session opened for user my-user by (uid=0)
    Jan  9 12:44:16 my-cluster sshd[11024]: pam_krb5(sshd:setcred): pam_sm_setcred: entry (establish)
    Jan  9 12:44:16 my-cluster sshd[11024]: pam_krb5(sshd:setcred): pam_sm_setcred: exit (success)
    Jan  9 12:44:16 my-cluster sshd[11024]: Received disconnect from 95.119.59.xx: 11: disconnected by user
    Jan  9 12:44:16 my-cluster sshd[11003]: pam_unix(sshd:session): session closed for user my-user
    Jan  9 12:44:16 my-cluster sshd[11003]: pam_krb5(sshd:setcred): pam_sm_setcred: entry (delete)
    Jan  9 12:44:16 my-cluster sshd[11003]: pam_krb5(sshd:setcred): pam_sm_setcred: exit (success)

This is the /var/log/auth.log from a mosh login to a machine that currently runs the latest debian jessie. The user is still logged in via mosh, but as can be seen, the ssh session is terminated after mosh has been started. I guess that "pam_krb5(sshd:setcred): pam_sm_setcred: entry (delete)" is where my problem starts...

At the moment I have

    auth    [success=3 default=ignore]      pam_krb5.so minimum_uid=1000 debug
    auth    [success=2 default=ignore]      pam_unix.so nullok_secure try_first_pass
    auth    [success=1 default=ignore]      pam_winbind.so krb5_auth krb5_ccache_type=FILE cached_login use_first_pass debug debug_state

in /etc/pam.d/common-auth

and I tried 

    KerberosTicketCleanup no
    GSSAPICleanupCredentials no

for sshd as well as 

    session optional                        pam_krb5.so minimum_uid=1000 retain_after_close

for pam.

I did not find any way to retain the /tmp/krb5cc_1001273_Hh6K6J that gets created during the login.
This all used to work but I recently did some updates and the problem described above unfolded...

Any ideas how to solve this problem? :-(

**Comment by mmehnert** [comment]
The solution was:

    auth    [success=3 default=ignore]      pam_krb5.so minimum_uid=1000 debug retain_after_close

in /etc/pam.d/common-auth .

**Comment by andersk** [comment]
FWIW, the wrapper script we use at MIT to work around this issue is linked from #25.

It’s hard to do anything about this from Mosh itself, because PAM sessions really expect to be started as root—see #529.
