### ISSUE TITLE
multipath mosh

### ISSUE THREAD

**Issue by TimCook1** [mobile-shell/mosh#712]
Out of curiosity, have boutier's changes/features been integrated into the mainline repo?  If not, are there any plans to?

**Comment by cgull** [comment]
We'd like to take them, but the multipath code adds a few fields to the packet headers, making them incompatible with mainline Mosh.  Nobody has yet figured out a good way to make this code interoperate with older versions of Mosh.

**Comment by TimCook1** [comment]
Perhaps I'm being naive, but for the short term, couldn't you just put a field in to check server/client version on initial connect and default to the old behavior if you find it's an incompatible version?  Then just deprecate the checking in a few versions?

Or, quite frankly, just keep the 1.x branch as a maintenance train only, move to a 2.x version number and tell people there's no backwards compatibility?  I think the feature is compelling enough to make a break.  And it wouldn't be the first time it's happened.

**Comment by pavlix** [comment]
> Or, quite frankly, just keep the 1.x branch as a maintenance train only, move to a 2.x version number and tell people there's no backwards compatibility?

If that happens, it might be useful to add some feature discovery mechanism or protocol versioning mechanism to the protocol to avoid breaking compatibility again.

**Comment by cgull** [comment]
I think more in terms of making the protocol easily and efficiently expandable via option fields or demultiplexing, but yes, better forward compatibility would be a high priority for a v2.

**Comment by achernya** [comment]
https://github.com/boutier/mosh has substantially diverged from mainline mosh, and there's no PR. It's hard to tell which commits are important, and also it looks like it's incompatible with the existing mosh, which means we're not going to be able to consider it any time soon. Separately, we haven't evaluated if there's any benefits for multipath, so there's also that whole investigation.
