### ISSUE TITLE
mosh closing zsh when using autocomplete inside --ssh option

### ISSUE THREAD

**Issue by alexduros** [mobile-shell/mosh#714]
I'm trying mosh client on OS X (Darwin irving 15.2.0 Darwin Kernel Version 15.2.0: Fri Nov 13 19:56:56 PST 2015; root:xnu-3248.20.55~2/RELEASE_X86_64 x86_64 i386 MacBookPro10,2 Darwin).

I'm using oh-my-zsh inside iterm2. 

Using mosh over ssh, I tried to load my private key within --ssh option. So, I started typing `mosh --ssh="/usr/bin/ssh ... `. Then, I automatically used tab for completion and face a crash of my zsh session. 

If I do not use autocompletion, it works fine.

**Comment by cgull** [comment]
This isn't a Mosh issue, it's a zsh or oh-my-zsh issue.  My `/usr/local/bin/mosh` is never executed/read when reproducing this, and the Mosh project doesn't maintain any zsh completions.  Please report the bug with the appropriate project.

**Comment by tkaria** [comment]
@alexduros Did you find a solution for this? I have exactly the same setup and issue.
