### ISSUE TITLE
Mosh leaves traces of background color for prompt_toolkit.

### ISSUE THREAD

**Issue by jonathanslenders** [mobile-shell/mosh#717]
For prompt_toolkit based applications, (ptpython, pgcli, mycli, ...). Mosh leaves traces of the background of the completion menu.
(I don't have time to investigate this right now. But many users will be hapy. ;) )

https://github.com/jonathanslenders/python-prompt-toolkit/issues/16

**Comment by cgull** [comment]
The linked issue has been closed with a suggestion that mosh-1.2.5 fixed it, and information/repro was generally lacking to begin with; closing this too.
