### ISSUE TITLE
Mosh protobufs create code who indentation causes a warning on GCC 6

### ISSUE THREAD

**Issue by keithw** [mobile-shell/mosh#719]
Flagged by Debian: https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=811579

The new warning seems to be in `-Wall`. Our package builds with `-Werror`, so this breaks the package build on GCC 6.

Our options seem to be: (1) give up on -Wall for building the protobufs, (2) give up on -Werror for building the protobufs, (3) get protobuf-compiler to produce better code, and get that new protobuf-compiler released and included in the Debian stretch release.

**Comment by andersk** [comment]
Or we could replace `-Werror` by a more specific list of `-Werror=foo` options. (Here are the [lists of warnings enabled by `-Wall` and `-Wextra`](https://gcc.gnu.org/onlinedocs/gcc-5.3.0/gcc/Warning-Options.html#index-Wall-292).)

**Comment by cgull** [comment]
Also,
* `-Wall -Werror -Wno-error=misleading-indentation` should work.
* Since that particular issue is in a protobuf compile, not an include from elsewhere in Mosh, we could dial down warnings/errors in `src/protobufs/Makefile.am` and, er, trust that generated code.
