### ISSUE TITLE
Improper LOCALE detection

### ISSUE THREAD

**Issue by notorand-it** [mobile-shell/mosh#721]
mosh v1.2.5 is improperly detecting the LOCALE.
```
[Richard@Feynman ~] mosh somewhere

mosh-client needs a UTF-8 native locale to run.

Unfortunately, the client's environment (LC_CTYPE=C) specifies
the character set "US-ASCII".

LANG=en_US.UTF-8
LANGUAGE=en_US
LC_CTYPE=C
LC_NUMERIC=it_IT.UTF-8
LC_TIME=it_IT.UTF-8
LC_COLLATE=C
LC_MONETARY=it_IT.UTF-8
LC_MESSAGES=en_US.UTF-8
LC_PAPER=it_IT.UTF-8
LC_NAME=it_IT.UTF-8
LC_ADDRESS=it_IT.UTF-8
LC_TELEPHONE=it_IT.UTF-8
LC_MEASUREMENT=it_IT.UTF-8
LC_IDENTIFICATION=it_IT.UTF-8
LC_ALL=
```

Which is wrong. My LOCALE is UTF-8 indeed.

**Comment by keithw** [comment]
You appear to have your LC_CTYPE environment variable set to "C". (That is what the error message is saying.) This specifies a character set of US-ASCII. If you unset this environment variable, does it get further along?

**Comment by notorand-it** [comment]
Of course it works.
The point is that LC_CTYPE and LC_COLLATE don't define the character set in use, but rather the character classes and sorting order. LANG does.

**Comment by keithw** [comment]
You'll have to take that up with your operating system. Mosh is just using `nl_langinfo( CODESET )` and reporting the results. See http://man7.org/linux/man-pages/man3/nl_langinfo.3.html
