### ISSUE TITLE
zsh: No such file and diretory

### ISSUE THREAD

**Issue by acgtyrant** [mobile-shell/mosh#722]
I execute `mosh DO` when there is the current environment variable `SHELL=zsh`, it complains:

	zsh: No such file or directory
	ssh_exchange_identification: Connection closed by remote host
	/usr/bin/mosh: Did not find remote IP address (is SSH ProxyCommand disabled?).

However, when I execute `SHELL=/bin/zsh`, the error disappeared.

I hope mosh can support `SHELL=zsh`, thank you!

**Comment by cgull** [comment]
Traditionally, `SHELL` has been a full pathname to your shell.  See [the POSIX standard language on environment variables](http://pubs.opengroup.org/onlinepubs/7908799/xbd/envvar.html).  Even if your system happens to support a command name without path in `SHELL`, it is best to use an explicit absolute path for performance and security.  I don't see a good reason to change Mosh's behavior in this area.

**Comment by cgull** [comment]
Also, this is probably the same issue as #663 and #568, which I didn't quite pick up on at first glance.

**Comment by acgtyrant** [comment]
@cgull You are right, I will set `SHELL` to a full pathname by myself later.

**Comment by cgull** [comment]
Commit 09bdc7caaee4473b4f1087b1e58058b3ea383655 fixes this from the Mosh side.
