### ISSUE TITLE
installing without admin priviledge (and without internet connection)

### ISSUE THREAD

**Issue by Siddhant** [mobile-shell/mosh#735]
I want to install mosh on a server on which i don't have admin privileges, nor is the server connected to the Internet. (It's on an internal network, so I can of course transfer any files needed to it.)

The mosh homepage says "No privileged code. No daemon. You don't need to be the superuser to install or run Mosh." but when I scroll down to the installation section (https://mosh.mit.edu/#getting), the installation instruction for different distributions are all littered with 'sudo'. Bummer.

Suggestion: Provide documentation on how to install mosh/mosh-server without admin privileges.

**Comment by keithw** [comment]
Please see the directions under "building from source."
