### ISSUE TITLE
clarify mosh -p option

### ISSUE THREAD

**Issue by cgull** [mobile-shell/mosh#737]
The `mosh.1` man page correctly describes `-p` as affecting the UDP port, but doesn't make clear that this has no effect on the port used for `ssh`.  lich-li on #mosh had some confusion on this point today.  Adding a sentence or two explaining the difference would be good, and perhaps in `usage()` as well.

**Comment by ashmew2** [comment]
Hi, 
I opened a pull request[1], Please review it.
Thanks.

[1] https://github.com/mobile-shell/mosh/pull/746

**Comment by cgull** [comment]
Pulled.
