### ISSUE TITLE
Metered connections

### ISSUE THREAD

**Issue by Baughn** [mobile-shell/mosh#739]
Here's a scenario:

I'm using mosh on a laptop, through tethering to a cellphone. I close the laptop, but the cellphone retains its own connection. In this case, what happens to mosh?

If the answer is, "It keeps sending UDP packets to the phone, in hopes of sometime getting a reply", then I'd like to add a feature request for it _not_ to do that. Surprisingly, it seems that mosh can add up to megabytes of traffic in a fairly small number of days.

The client should be able to resume the connection from its side, once it awakens from sleep nigh-eternal.

**Comment by eminence** [comment]
What does "close the laptop" mean?   If it means that the laptop enters a suspend state, then mosh is not doing anything, as the machine is suspended.

**Comment by Baughn** [comment]
That's true for the mosh instance on the laptop. Not so much the one on the server.

**Comment by eminence** [comment]
Ah, good point.  Yes, the server will continue to send packages to the last known address of the client, at least for a little while.  The exact timeout is specified by `SERVER_ASSOCIATION_TIMEOUT` here in [network.h#L137](https://github.com/mobile-shell/mosh/blob/81f21fc7acff783732417bfcf8b88d012431f51c/src/network/network.h#L137)

(or 40 seconds)

**Comment by Baughn** [comment]
If there's already such a timeout, then I have nothing to worry about. It's been a little difficult to tell.

40 seconds? The only thing I might as for then is documentation. :)

**Comment by keithw** [comment]
You might also be interested in the `lowbandwidth` branch of mosh (https://github.com/mobile-shell/mosh/tree/lowbandwidth), for extreme low consumption. It is compatible with normal mosh, but if you want the benefits, you'll need to compile the `mosh-client` and `mosh-server` from this branch.
