### ISSUE TITLE
Graphical glitches in irssi + tmux [terminals: st, xterm, urxvt]

### ISSUE THREAD

**Issue by ghost** [mobile-shell/mosh#740]
I see random graphical glitches like corruption of tmux splitter, and sometimes random chars showing up like on screenshot below where both problems happened at one place.
This problem does not happen in ssh.
![scrnshot](https://cloud.githubusercontent.com/assets/9962001/14155710/26188004-f6c3-11e5-8e5d-b1022601f9cf.png)

**Comment by eminence** [comment]
What versions (mosh, tmux, irssi etc)?

**Comment by lich** [comment]
mosh - 1.2.5 both server and client
tmux - 2.1
irssi - 0.8.17

**Comment by cgull** [comment]
Evidently your server is FreeBSD, at least.  What version of FreeBSD are you using?  What OS is your client machine using?

I can't reproduce this on a FreeBSD desktop machine, but it looks like you're also running a number of irssi customization scripts, and my default irssi install looks very different from your screenshot (in particular, I don't know how to reproduce your userlist).

**Comment by lich** [comment]
`uname -a : FreeBSD freebsd-512mb-fra1-01 10.2-RELEASE FreeBSD 10.2-RELEASE #0 r286666: Wed Aug 12 15:26:37 UTC 2015     root@releng1.nyi.freebsd.org:/usr/obj/usr/src/sys/GENERIC  amd64`  
For nicklist, I use nicklist.pl (uses fifo). Theme is the xchat one.

**Comment by achernya** [comment]
It seems that this was not able to be reproduced. Please reopen if you're still seeing this issue.
