### ISSUE TITLE
Connection refused from Raspberry Pi

### ISSUE THREAD

**Issue by SmartSouth** [mobile-shell/mosh#743]
Firstly, the documentation of MOSH is very poor so I have no clue how to make it work. I've tried with Android (Juice SSH) to Mac, Mac to Pi, Pi to Mac and failed. Mosh is installed on both my Mac and my Raspberry Pi. When I try to connect from my mac with 'mosh username@ip_address', the connection is refused. I get a splash screen for a fraction of a second that says something about port 60002 (it's an error message but appears for such short time that it's impossible to read and comprehend). What am I doing wrong? I've also tried running 'mosh-server' and 'mosh-client' at both machines and it did not help.

**Comment by tedder** [comment]
can you ssh to pi? if so, what (*exact*) command do you use?

where is that splash screen coming up- in a terminal?

mosh is usually good at printing error messages. Here are examples, "piwall" is an actual pi host on my network.

```
$ mosh foo@badhost
/usr/local/bin/mosh: Could not resolve hostname badhost
ssh_exchange_identification: Connection closed by remote host
/usr/local/bin/mosh: Did not find remote IP address (is SSH ProxyCommand disabled?).

$ mosh baduser@piwall
baduser@10.11.12.13's password: 
```

**Comment by cgull** [comment]
The best reference for Mosh is the man page.  `man mosh

"Connection refused" is from ssh, which Mosh uses to start its terminal session.  Does ssh by itself work?

Screenshots or transcripts of your commands and their results will help us debug this...

You can also use `script` to capture transient text like your splash screen to a log file.

**Comment by cgull** [comment]
No response in a month, closing.
