### ISSUE TITLE
Build failure with libc++ 3.8.0

### ISSUE THREAD

**Issue by zi0r** [mobile-shell/mosh#745]
During the exp-run in bug 208158, it was found that net/mosh gives errors with libc++ 3.8.0 [1]:

ocb.cc:111:26: error: expected ')'
         static inline uint64_t bswap64(uint64_t x) {
                                ^
/usr/include/sys/endian.h:61:20: note: expanded from macro 'bswap64'
#define bswap64(x)      __bswap64(x)
                        ^
/usr/include/x86/endian.h:80:27: note: expanded from macro '__bswap64'
        (__builtin_constant_p(x) ?      \

From FreeBSD.org bugs repo: https://bugs.freebsd.org/bugzilla/show_bug.cgi?id=209019

**Comment by zi0r** [comment]
Sounds like this is still a problem: https://bugs.freebsd.org/bugzilla/show_bug.cgi?id=209019

> Ok, so the problem is that in ocb.cc, config.h was *still* not included, so while HAVE_DECL_BSWAP64 was properly detected by configure, the define didn't arrive in the right place...
> 
> Here's a revised upstream patch, adding #include "config.h" at the top of the file.

**Comment by andersk** [comment]
It’s there. `#include "config.h"` had already been added in 0eb614809a7ea1fc955d4c5e9d8777c324954d88 (mosh-1.2.5.95rc1~92).
