### ISSUE TITLE
bash: mosh-server: command not found OSX 10.11.3

### ISSUE THREAD

**Issue by thornycrackers** [mobile-shell/mosh#748]
On my mac I installed mosh through brew with 'brew install mobile-shell' and got version 1.2.5. but when I try to execute 'mosh user@server' I get this error.

```
bash: mosh-server: command not found
Connection to server closed.
/usr/local/bin/mosh: Did not find mosh server startup message.
```

This may sound like a dumb question but do I need to install mosh server on the remote machine? All the tutorials read like mosh was supposed to be a drop in replacement for ssh and I was under the impression that I should just be able to install and run with it?

**Comment by eminence** [comment]
Yes, mosh must be installed on both the server and the client.  (Just like ssh must be installed on both the server and the client)

The "drop -in replacement" part just means that if normally you run `ssh user@server.com` then you should be able to run `mosh user@server.com`
(though there are several advanced ssh options that mosh doesn't support, so this is not strictly true)

**Comment by thornycrackers** [comment]
ahhh sorry for the silly question then. It all works now with the server installed.

**Comment by eminence** [comment]
BTW, this is listed on the mosh website under the "Getting Started" section:

https://mosh.mit.edu/#getting

"The Mosh package should be installed on both the client and server. Please find your platform below for installation instructions."

I assume you didn't see this.  If you have any suggestions on how to make this more noticeable, let us know.
