### ISSUE TITLE
Installing mosh 1.2.5 on Jessie ?

### ISSUE THREAD

**Issue by LaP0573** [mobile-shell/mosh#749]
I'm having issues with mouse reporting and noticed it wasn't really supposed to work in 1.2.4, the version that is installed on my VPS running Debian (while my client is in 1.2.5, on my Mac). I decided to upgrade the mosh server, but am having issues. I tried compiling and installing from source but ./configure always stops on :

`
checking pkg-config is at least version 0.9.0... yes
checking for TINFO... no
checking for TINFO... no
checking curses.h usability... no
checking curses.h presence... no
checking for curses.h... no
checking for NcursesW wide-character library... no
checking for Ncurses library... no
checking for Curses library... no
configure: error: requires either tinfo, NcursesW or Ncurses library
`

While all these libraries are installed (via apt-get install). I've tried installing libncurses5-dev but am having this issue :

`
The following packages have unmet dependencies:

 deb http://mirrors.online.net/debian jessie main
 libncurses5-dev : Depends: libtinfo5 (= 5.9+20140913-1+b1) but 6.0+20160319-1 is to be installed
                   Depends: libncurses5 (= 5.9+20140913-1+b1) but 6.0+20160319-1 is to be installed
                   Depends: libtinfo-dev (= 5.9+20140913-1+b1) but it is not going to be installed
E: Unable to correct problems, you have held broken packages.
`

And didn't manage to fix it either. So two questions :

* Any idea why I'm having this last issue, and how to solve it ? From my understanding installing libncurses5-dev should fix my ./configure, but I tried everything and it doesn't work.
* Is there any repository I can use to get the latest mosh version for Debian ?

**Comment by eminence** [comment]
is `libtinfo5` or `libtinfo-dev` held at version 5.9?

**Comment by LaP0573** [comment]
Nope :

libtinfo5:
  Installed: 6.0+20160319-1
  Candidate: 6.0+20160319-1
  Version table:
 *** 6.0+20160319-1 0
        100 /var/lib/dpkg/status
     5.9+20140913-1+b1 0
        500 http://mirrors.online.net/debian/ jessie/main amd64 Packages

However if I remove it, I get a massive warning (I guess it'll remove a shitload of other packages that are depending on it).

**Comment by eminence** [comment]
Does `libncurses6-dev` exist ?

**Comment by andersk** [comment]
@eminence There’s no such thing as libncurses6-dev (only libncurses5-dev version 6).

@LaP0573 It looks like you have packages from stretch installed on your jessie system, but you do not have stretch in your sources.list. This makes apt unhappy. You should either fully upgrade to stretch, or downgrade all packages to jessie.

(Closing because this is not a Mosh issue.)
