### ISSUE TITLE
haproxy and mosh conflict over use of ssh ProxyCommand

### ISSUE THREAD

**Issue by diepes** [mobile-shell/mosh#756]
I setup haproxy on a server to handle SSL and SSH traffic on the same IP.

From ssh v2 the client is quiet and haproxy can't detect it without the following line in .ssh/config

Host my.host.com
  HostName my.host.com
  Port 443
  ProxyCommand openssl s_client -connect my.host.com:443 -quiet

Now ssh works fine, but mosh is broken, as it is picked up as SSL connection, ignoring my .ssh/config

If i force mosh with 
$ mosh --ssh="ssh -p 443 -o ProxyCommand='openssl s_client -connect my.host.com:443 -quiet'" --bind-server=all -p 60661:60669  root@my.host.com

I get the error.

**/usr/bin/mosh: Did not find remote IP address (is SSH ProxyCommand disabled?).**

Any suggestions as to what else i can try ?

**Comment by andersk** [comment]
See #285; the new `--experimental-remote-ip=remote` option in Git might work for you.

Alternatively, if you replace your haproxy-based multiplexer with [sslh](http://www.rutschle.net/tech/sslh.shtml), then the client side can just be plain SSH without a ProxyCommand, so Mosh will just work out of the box.
