### ISSUE TITLE
Use RFC compliant NAT traversal

### ISSUE THREAD

**Issue by tysonclugg** [mobile-shell/mosh#760]
As per https://github.com/mobile-shell/mosh/issues/285#issuecomment-221430173, Mosh should not be inventing new NAT traversal techniques in order to establish connectivity between hosts.  Add support for ICE/STUN/... so Mosh can make connections in a reliable manner without having to rely on hacks to determine the IP of both the remote and local ends of a connection.

**Comment by cgull** [comment]
I think you misunderstand.  Mosh uses bog-standard TCP/UDP session forwarding for client side NAT, and doesn't support server side NAT-- it's only ever supported directly reachable servers, and `--experimental-remote-ip` does not change that.

**Comment by andersk** [comment]
Server side NAT busting is #48.
