### ISSUE TITLE
ProxyCommand: Connection closed by remote host

### ISSUE THREAD

**Issue by flgr** [mobile-shell/mosh#761]
Hey there!

I'm really not quite sure what's going on here. I'm trying to use Mosh to connect to a remote server:

```
acbc329d35e1:mode-rollups fggross$ mosh server
ssh_exchange_identification: Connection closed by remote host
/usr/local/bin/mosh: Did not find remote IP address (is SSH ProxyCommand disabled?).
```

Though:

```
acbc329d35e1:mode-rollups fggross$ ssh server
Welcome to Ubuntu 14.04.3 LTS (GNU/Linux 3.13.0-74-generic x86_64)
```

I then ran this command as told by the debugging article in the wiki:

```
acbc329d35e1:mode-rollups fggross$ ssh -i ~/.ssh/id_rsa -v -v -v -S none -o ProxyCommand='mosh --fake-proxy -- %h %p' -n -tt server -- 'mosh-server new'
OpenSSH_6.2p2, OSSLShim 0.9.8r 8 Dec 2011
debug1: Reading configuration data /Users/fggross/.ssh/config
debug1: /Users/fggross/.ssh/config line 33: Applying options for server
debug1: /Users/fggross/.ssh/config line 38: Applying options for *
debug1: Reading configuration data /etc/ssh_config
debug1: /etc/ssh_config line 20: Applying options for *
debug2: ssh_connect: needpriv 0
debug1: Executing proxy command: exec mosh --fake-proxy -- ec2-xxx.us-west-2.compute.amazonaws.com 22
debug1: permanently_drop_suid: 1940555403
debug3: Incorrect RSA1 identifier
debug3: Could not load "/Users/fggross/.ssh/id_rsa" as a RSA1 public key
debug1: identity file /Users/fggross/.ssh/id_rsa type 1
debug1: identity file /Users/fggross/.ssh/id_rsa-cert type -1
debug3: Incorrect RSA1 identifier
debug3: Could not load "/Users/fggross/.ssh/id_rsa" as a RSA1 public key
debug1: identity file /Users/fggross/.ssh/id_rsa type 1
debug1: identity file /Users/fggross/.ssh/id_rsa-cert type -1
debug1: Enabling compatibility mode for protocol 2.0
debug1: Local version string SSH-2.0-OpenSSH_6.2
ssh_exchange_identification: Connection closed by remote host
```

sshing into the remote server and manualy starting mosh-server there, then manually starting mosh-client locally work just fine.

Seems like whenever I specify `-o ProxyCommand=` with whatever value the remote end will just hang up and close the connection.

Could this be a problem with my local ssh binary or the remote sshd? I already tried googling for this, but couldn't find anything appropriate.

Thanks a lot!
— Florian

**Comment by andersk** [comment]
What version of Mosh do you have, and what is your local `$SHELL`? If you run, say,

`echo 1; $SHELL -c "echo 2"; echo 3`

Do you see anything other than the numbers `1`, `2`, `3`?

**Comment by flgr** [comment]
Thanks a lot. That resolves it. I'm on a weird corporate machine and it seems they horribly misconfigured it:

```
acbc329d35e1:~ fggross$ echo $SHELL
/bin/false
```

Which seems really insane to me.

Setting it to bash solves this. Thanks for your help!

**Comment by andersk** [comment]
Cool. (Mosh 1.2.5.95rc1 has a workaround already—see #663.)
