### ISSUE TITLE
Address jumps from subdomain to domain and can't connect

### ISSUE THREAD

**Issue by lahwran** [mobile-shell/mosh#762]
Hey, so, I'm trying to use mosh to connect to home.lahwran.net. it connects through ssh fine, but then it tries to connect to lahwran.net via udp! I'm really not sure what's going on.

**Comment by andersk** [comment]
Do you have a `~/.ssh/config` entry for home.lahwran.net?

**Comment by lahwran** [comment]
yes, and lahwran.net.

**Comment by andersk** [comment]
And what are they? (Mosh is very careful to respect any aliases defined in the SSH configuration, even for its separate UDP connection. It may just be doing what you asked it to do.)

**Comment by lahwran** [comment]
Sorry for my sparse replies, busy day :/

```

# ... other stuff...

Host lahwran.net
    Hostname 209.236.121.166
    Hostname 204.44.116.80
    Port <redacted>
    IdentityFile <redacted>
    User lahwran

# ... more other stuff ...

Host home.lahwran.net
    hostname lahwran.net
```
... err, I'll just cut the paste off there. sometimes, after reading it three times, I had still managed to miss that that hostname entry was there. not sure how. busy day...
