### ISSUE TITLE
Mosh connections to older servers with both A and AAAA records fail with "mosh-server: Bad IP address" on newer client (1.2.5.95rc1)

### ISSUE THREAD

**Issue by bockmabe** [mobile-shell/mosh#764]
Looks like the newer mosh clients (1.2.5.95rc1) fail connecting to older servers that are running on a dual-stack system with both A and AAAA records.  The failure looks as follows (with names and addresses changes):

```
bb@bb-mac:~$ mosh b@example.org
b@example.org's password:
mosh-server: Bad IP address (2001:DB8::)
Usage: mosh-server new [-s] [-v] [-i LOCALADDR] [-p PORT[:PORT2]] [-c COLORS] [-l NAME=VALUE] [-- COMMAND...]
Connection to example.org closed.
/usr/local/bin/mosh: Did not find mosh server startup message.
bb@bb-mac:~$
```

Note that example.org is available via both A and AAAA records, and a mosh directly to the IPv4 address works with no problems.

The mosh client install I'm using is on OS X 10.11.4 from the prebuilt package at  https://github.com/mobile-shell/mosh/releases/download/mosh-1.2.5.95rc1/mosh-1.2.5.95rc1.pkg.

I've repro'd the issue against mosh-server version 1.2.4a, on Ubuntu 14.04 LTS.

**Comment by cgull** [comment]
Thanks for the report.  I found a red herring labeled "mDNS" in your original email and ran with it (and found another bug, see #765) but this remains a more important issue.

Finding the right balance between v4-only backward compatibility and dual-stack connectivity is non-trivial.  Some options for solving this:
* Set the default `--family` option more conservatively for backward compatibility
* Add something like `--family=prefer-inet` which will still attempt connects to all addresses, but will sort IPv4 addresses to be first
* An uglier idea just popped into my head: actually re-run the connection over v4 if a v6 attempt fails.  I don't think I like this.
