### ISSUE TITLE
tabs, modelines, style guides

### ISSUE THREAD

**Issue by cgull** [mobile-shell/mosh#767]
The Mosh project is sloppy about its style usage and formatting of source code.

I think we should do:
- Add vi/vim and emacs (and any other suggested) modelines to source code files
- Convert tabs to spaces
- Write a style guide more substantial than "Follow KeithW's coding style"

This looks like a bike shed, doesn't it?  Bring your paint.

**Comment by glensc** [comment]
[.editorconfig](http://editorconfig.org/) perhaps?

**Comment by juhakivekas** [comment]
Some code style attributes mentioned in discussion:
 - no literal tabs in any of the source files, excepting imported code
 - use whitespace around the outermost parens of a function or arithmetic group
 - use whitespace after if and while
 - no whitespace in template arguments (at least currently).
 - Mosh is currently strictly C++O3 but compatible with later versions

**Comment by The-Compiler** [comment]
I second the suggestion about using editorconfig to have something unified.

Maybe you also want to use something like [clang-format](http://clang.llvm.org/docs/ClangFormat.html) or [astyle](http://astyle.sourceforge.net/) to automate the cleanup to some degree?

**Comment by juhakivekas** [comment]
I tried astyle and a few misalignments with the current style came up:
 - typecasts will have space padding inside parenthesis
 - indented `#defines` inside conditional preprocessor statements will become flat, the defined code will be indented however
There are also some details that are not consistent over the codebase:
 - `sizeof(foo)` and `sizeof( foo )`, same applies for some macros like `uint64_t(-1)`, using the spacious version would be easier to check automatically
 - `type * foo` and `type *foo`, same applies for `type & foo`

**Comment by sysadmiral** [comment]
Not sure if this helps but Google publish a C++ style guide with mostly sane looking decisions:

https://google.github.io/styleguide/cppguide.html

**Comment by juhakivekas** [comment]
This is an astyle configutarion that outluts the mostly-correct syled code:

    -A4
    --indent=spaces=2
    #reset all parenthesis padding
    --unpad-paren
    #add padding before if, while, for, etc.
    --pad-header
    #add a padding space on the inside of parenthesis
    --pad-paren-in
    #pad operators
    --pad-oper
    --align-pointer=name
    --align-reference=name
    --add-brackets
    --keep-one-line-blocks
    --convert-tabs
    --break-after-logical
