### ISSUE TITLE
Emoji don't display in terminal in mosh

### ISSUE THREAD

**Issue by sedm0784** [mobile-shell/mosh#771]
I'm guessing this is some kind of user configuration error, but mosh seems to be stripping emoji from my terminal output.

Steps to reproduce:

1. Copy the following file onto the server: [mosh-emoji-test.txt](https://github.com/mobile-shell/mosh/files/338035/mosh-emoji-test.txt)
2. Connect via `ssh server`
3. Run `cat mosh-emoji-test.txt` and verify that the emoji displays correctly.
4. Disconnect and reconnect with `mosh server`.
5. Run `cat mosh-emoji-test.txt` again.

Expected behaviour: The terminal should display: "Moon: 🌗"
Observed behaviour: The terminal displays: "Moon:"

**Comment by andersk** [comment]
This is usually means that your libc doesn’t recognize the character in question. U+1F317 LAST QUARTER MOON SYMBOL was added in Unicode 6.0.0, which is [supported by glibc ≥ 2.22](https://sourceware.org/bugzilla/show_bug.cgi?id=14094), and indeed it works fine with Mosh on my system with glibc 2.23.

We’re still considering what to do about this problem in general; maybe it makes sense not to rely on libc so much. See #234 for that discussion.

**Comment by sedm0784** [comment]
Thanks for the info.
