### ISSUE TITLE
tcgetattr: Inappropriate ioctl for device

### ISSUE THREAD

**Issue by li7nux** [mobile-shell/mosh#772]
I installed mosh on my Ubuntu 16.04LTS, and I installed mosh on my windows desktop with cygwin. It works will yesterday, but today I use `mosh root@my_server_ip`, it meats some problems as title:

```
tcgetattr: Inappropriate ioctl for device
```

how can i fix it ?

**Comment by cgull** [comment]
I'm guessing this might be a Cygwin problem.  But I can't reproduce this with Cygwin 2.5.2-1 and its Mosh package 1.2.5-1, either with mintty ("Cygwin64 Terminal") or a console window.  If possible, could you give us a step-by-step procedure for reproducing the problem, and a screenshot?

**Comment by li7nux** [comment]
I reinstall Cygwin on my windows, and destroy my vps server and create a new server, then the problem disappear ...
