### ISSUE TITLE
scroll wheel on mouse does not scroll the terminal window, shows command history instead

### ISSUE THREAD

**Issue by jamorales-bsft** [mobile-shell/mosh#774]
on mac osx el capitan when I use the scroll wheel in a mosh terminal it goes through previous command as if I was pressing the up and down arrow keys. It does not actually scroll the terminal window at all.

**Comment by andersk** [comment]
This is expected. See #2 and #122.

**Comment by hpcnpatel** [comment]
one could disable the secure keyboard entry in MAC terminal and scrolling should work fine. Happened to me.
