### ISSUE TITLE
mosh-server "-s" option causes "Invalid (low) port number (new)"

### ISSUE THREAD

**Issue by flat235** [mobile-shell/mosh#780]
full command: "mosh-server -s new" causes said error message. Not sure if this is the cause, but I run the ssh server on another port than default (higher than 1024). 
Problem occurs on ipv4 and ipv6.
mosh version: 1.2.5
Let me know if you need any additional information.

**Comment by keithw** [comment]
(1) Why are you running `mosh-server` separately? Are you debugging something? Generally you just want to run `mosh` on the client (see the mosh manpage or the mosh.mit.edu website).

(2) The syntax is `mosh-server new [arguments]`. Please see the mosh-server manpage.

**Comment by flat235** [comment]
(1) Yes, I am debugging; damn, I thought, I found the problem. (Any idea why mosh-server would be exiting immediatly after forking? It's not waiting around for a minute.)
(2) Woops, my bad. However an error telling you, that you used the wrong syntax would be *nive to have* (I know there are probably a 100 things more important).
Thank you!

**Comment by keithw** [comment]
You may be running into a glibc 2.22 bug; we have fixed this in the Debian/Ubuntu package (1.2.5-2) and in the current Git master, soon to be released as 1.2.6.

**Comment by keithw** [comment]
https://github.com/mobile-shell/mosh/issues/727

**Comment by flat235** [comment]
Alright, I'm assuming that's it, I can confirm running glibc 2.22.
Thank you very much for your help :)
