### ISSUE TITLE
[patch] Fails to build under FreeBSD 11.x

### ISSUE THREAD

**Issue by zi0r** [mobile-shell/mosh#783]
Details/fix available in the FreeBSD PR: https://bugs.freebsd.org/bugzilla/show_bug.cgi?id=211437

**Comment by zi0r** [comment]
Fix committed to FreeBSD port.

**Comment by cgull** [comment]
This is already fixed in mosh master, see https://github.com/mobile-shell/mosh/commit/0eb614809a7ea1fc955d4c5e9d8777c324954d88.
