### ISSUE TITLE
rsub: connect: Connection refused

### ISSUE THREAD

**Issue by timotheecour** [mobile-shell/mosh#787]
rsub doesn't seem to work through mosh
[rsub:https://github.com/henrikpersson/rsub]

This works:

```
ssh $myserver
rsub file.txt
```

This doesn't:

```
mosh $myserver
rsub file.txt
```

rsub: connect: Connection refused

What would you recommend?

[besides this workaround: in a terminal keep a tunnel open via ssh -N -R 52698:localhost:52698 $myserver]

NOTE: I have:
~/.ssh/config:
Host *
  RemoteForward 52698 localhost:52698

**Comment by eminence** [comment]
It looks like `rsub` relies on SSH portforwarding, which mosh doesn't support.   There are several github issues for this, for example #337, so this would be a feature request

**Comment by Catbodi** [comment]
@eminence 

Is this still not possible? Will it ever be possible with mosh?

**Comment by eminence** [comment]
No.  Mosh still does not support port forwarding.  It's impossible to say if or when mosh will support this.
