### ISSUE TITLE
server side port or range(29926") is not valid

### ISSUE THREAD

**Issue by livc** [mobile-shell/mosh#795]
```bash
#!/usr/bin/expect -f
set user xxx
set host xxx
set password xxx
set port 29926
set timeout -1
 
spawn /usr/local/bin/mosh $user@$host --ssh="ssh -p $port"
expect "*assword:*"
send "$password\r"
interact
expect eof
```

I get :

![shell 152 25 2016-08-20 16-15-45](https://cloud.githubusercontent.com/assets/11692045/17829952/6c9a5c70-66f1-11e6-9f4d-efb450a8def7.png)

**Comment by andersk** [comment]
http://stackoverflow.com/questions/12518354/use-expect-to-spawn-command-with-arguments-containing-spaces

**Comment by livc** [comment]
@andersk I read that but I still don't know how to modify my script.
I don't have experience in shell script language....
Could u help me ?

**Comment by keithw** [comment]
If you really are new to this, are you sure you want to write an expect script to type your password for you? That is probably a bad idea. You're much better off using a public key to authenticate yourself to the server and skipping the password entirely. See https://help.ubuntu.com/community/SSH/OpenSSH/Keys or https://www.digitalocean.com/community/tutorials/how-to-configure-ssh-key-based-authentication-on-a-linux-server

**Comment by livc** [comment]
@keithw I will try that, thank you.
I used to using the expect script to login SSH… But for MOSH, it doesn't work so I'm confused.
