### ISSUE TITLE
"g++-4.9.real: error: @OPENSSL_CFLAGS@: No such file or directory"

### ISSUE THREAD

**Issue by T-X** [mobile-shell/mosh#796]
Trying to build the current mosh master branch (ddb5fd9d7a350b911e29b6a6713b819fdde1744e) on a Debian Jessie fails for me with the following error:

<pre>
checking for a BSD-compatible install... /usr/bin/install -c
checking whether build environment is sane... yes
checking for a thread-safe mkdir -p... /bin/mkdir -p
checking for gawk... gawk
checking whether make sets $(MAKE)... yes
checking whether make supports nested variables... yes
checking for cc... cc
checking whether the C compiler works... yes
checking for C compiler default output file name... a.out
checking for suffix of executables...
checking whether we are cross compiling... no
checking for suffix of object files... o
checking whether we are using the GNU C compiler... yes
checking whether cc accepts -g... yes
checking for cc option to accept ISO C89... none needed
checking for style of include used by make... GNU
checking dependency style of cc... gcc3
checking for c++... c++
checking whether we are using the GNU C++ compiler... yes
checking whether c++ accepts -g... yes
checking dependency style of c++... gcc3
checking for ranlib... ranlib
checking for protoc... /usr/bin/protoc
checking for ar... ar
checking the archiver (ar) interface... ar
checking whether C compiler accepts -fno-strict-overflow... yes
checking whether C++ compiler accepts -fno-strict-overflow... yes
checking whether C compiler accepts -D_FORTIFY_SOURCE=2... yes
checking whether C++ compiler accepts -D_FORTIFY_SOURCE=2... yes
checking whether the linker accepts -fstack-protector-all... yes
checking whether C compiler accepts -Wstack-protector... yes
checking whether C++ compiler accepts -Wstack-protector... yes
checking whether C compiler accepts --param ssp-buffer-size=1... yes
checking whether C++ compiler accepts --param ssp-buffer-size=1... yes
checking whether C compiler accepts -fPIE... yes
checking whether C++ compiler accepts -fPIE... yes
checking whether the linker accepts -fPIE -pie... yes
checking whether the linker accepts -Wl,-z,relro... yes
checking whether the linker accepts -Wl,-z,now... yes
checking whether C++ compiler accepts -fno-default-inline... yes
checking whether C++ compiler accepts -pipe... yes
checking for library containing utempter_remove_record... -lutempter
checking for library containing compress... -lz
checking for library containing socket... none required
checking for library containing inet_addr... none required
checking how to run the C preprocessor... cc -E
checking for grep that handles long lines and -e... ^[OP/bin/grep
checking for egrep... /bin/grep -E
checking for ANSI C header files... yes
checking for sys/types.h... yes
checking for sys/stat.h... yes
checking for stdlib.h... yes
checking for string.h... yes
checking for memory.h... yes
checking for strings.h... yes
checking for inttypes.h... yes
checking for stdint.h... yes
checking for unistd.h... yes
checking fcntl.h usability... yes
checking fcntl.h presence... yes
checking for fcntl.h... yes
checking langinfo.h usability... yes
checking langinfo.h presence... yes
checking for langinfo.h... yes
checking limits.h usability... yes
checking limits.h presence... yes
checking for limits.h... yes
checking locale.h usability... yes
checking locale.h presence... yes
checking for locale.h... yes
checking netdb.h usability... yes
checking netdb.h presence... yes
checking for netdb.h... yes
checking netinet/in.h usability... yes
checking netinet/in.h presence... yes
checking for netinet/in.h... yes
checking stddef.h usability... yes
checking stddef.h presence... yes
checking for stddef.h... yes
checking for stdint.h... (cached) yes
checking for inttypes.h... (cached) yes
checking for stdlib.h... (cached) yes
checking for string.h... (cached) yes
checking sys/ioctl.h usability... yes
checking sys/ioctl.h presence... yes
checking for sys/ioctl.h... yes
checking sys/resource.h usability... yes
checking sys/resource.h presence... yes
checking for sys/resource.h... yes
checking sys/socket.h usability... yes
checking sys/socket.h presence... yes
checking for sys/socket.h... yes
checking for sys/stat.h... (cached) yes
checking sys/time.h usability... yes
checking sys/time.h presence... yes
checking for sys/time.h... yes
checking termios.h usability... yes
checking termios.h presence... yes
checking for termios.h... yes
checking for unistd.h... (cached) yes
checking wchar.h usability... yes
checking wchar.h presence... yes
checking for wchar.h... yes
checking wctype.h usability... yes
checking wctype.h presence... yes
checking for wctype.h... yes
checking pty.h usability... yes
checking pty.h presence... yes
checking for pty.h... yes
checking util.h usability... no
checking util.h presence... no
checking for util.h... no
checking libutil.h usability... no
checking libutil.h presence... no
checking for libutil.h... no
checking paths.h usability... yes
checking paths.h presence... yes
checking for paths.h... yes
checking endian.h usability... yes
checking endian.h presence... yes
checking for endian.h... yes
checking sys/endian.h usability... no
checking sys/endian.h presence... no
checking for sys/endian.h... no
checking utmpx.h usability... yes
checking utmpx.h presence... yes
checking for utmpx.h... yes
checking termio.h usability... yes
checking termio.h presence... yes
checking for termio.h... yes
checking sys/uio.h usability... yes
checking sys/uio.h presence... yes
checking for sys/uio.h... yes
checking how to run the C++ preprocessor... c++ -E
checking memory usability... yes
checking memory presence... yes
checking for memory... yes
checking tr1/memory usability... yes
checking tr1/memory presence... yes
checking for tr1/memory... yes
checking for stdbool.h that conforms to C99... yes
checking for _Bool... yes
checking for inline... inline
checking for int64_t... yes
checking for pid_t... yes
checking for C/C++ restrict keyword... __restrict
checking for size_t... yes
checking for ssize_t... yes
checking for uint16_t... yes
checking for uint32_t... yes
checking for uint64_t... yes
checking for uint8_t... yes
checking for uintptr_t... yes
checking vfork.h usability... no
checking vfork.h presence... no
checking for vfork.h... no
checking for fork... yes
checking for vfork... yes
checking for working fork... yes
checking for working vfork... (cached) yes
checking whether mbrtowc and mbstate_t are properly declared... yes
checking for gettimeofday... yes
checking for setrlimit... yes
checking for iswprint... yes
checking for memchr... yes
checking for memset... yes
checking for nl_langinfo... yes
checking for posix_memalign... yes
checking for setenv... yes
checking for setlocale... yes
checking for sigaction... yes
checking for socket... yes
checking for strchr... yes
checking for strdup... yes
checking for strncasecmp... yes
checking for strtok... yes
checking for strerror... yes
checking for strtol... yes
checking for wcwidth... yes
checking for cfmakeraw... yes
checking for pselect... yes
checking for getaddrinfo... yes
checking for getnameinfo... yes
checking for library containing clock_gettime... none required
checking for pkg-config... /usr/bin/pkg-config
checking pkg-config is at least version 0.9.0... yes
checking for TINFO... yes
checking CommonCrypto/CommonCrypto.h usability... no
checking CommonCrypto/CommonCrypto.h presence... no
checking for CommonCrypto/CommonCrypto.h... no
checking for CRYPTO... yes
checking whether forkpty is declared... no
checking for forkpty in -lutil... yes
checking whether pipe2(..., O_CLOEXEC) is supported... yes
checking whether FD_ISSET() argument is const... yes
checking whether std::shared_ptr is available... no
checking whether std::tr1::shared_ptr is available... yes
checking whether mach_absolute_time is declared... no
checking whether __builtin_ctz is declared... yes
checking whether ffs is declared... yes
checking whether be64toh is declared... yes
checking whether betoh64 is declared... no
checking whether bswap64 is declared... no
checking whether __builtin_bswap64 is declared... yes
checking whether IP_MTU_DISCOVER is declared... yes
checking whether IP_RECVTOS is declared... yes
checking whether __STDC_ISO_10646__ is declared... yes
checking whether IUTF8 is declared... yes
checking for protobuf... yes
configure: creating ./config.status
config.status: creating Makefile
config.status: creating src/Makefile
config.status: creating src/crypto/Makefile
config.status: creating src/frontend/Makefile
config.status: creating src/network/Makefile
config.status: creating src/protobufs/Makefile
config.status: creating src/statesync/Makefile
config.status: creating src/terminal/Makefile
config.status: creating src/util/Makefile
config.status: creating scripts/Makefile
config.status: creating src/examples/Makefile
config.status: creating src/tests/Makefile
config.status: creating man/Makefile
config.status: creating conf/Makefile
config.status: creating config.h
config.status: config.h is unchanged
config.status: executing depfiles commands
configure:  === Configuration results ===
configure: Version:             1.2.6
configure: c++ compiler:        c++
configure: Warning CXXFLAGS:    -Wall
configure: Picky CXXFLAGS:
configure: Harden CFLAGS:        -fno-strict-overflow -D_FORTIFY_SOURCE=2 -fstack-protector-all -Wstack-protector --param ssp-buffer-size=1 -fPIE
configure:  =============================
./configure  4,83s user 1,20s system 27% cpu 22,037 total
make  all-recursive
make[1]: Entering directory '/home/tux/dev/mosh'
Making all in src
make[2]: Entering directory '/home/tux/dev/mosh/src'
Making all in protobufs
make[3]: Entering directory '/home/tux/dev/mosh/src/protobufs'
  GEN    userinput.pb.cc
  GEN    hostinput.pb.cc
  GEN    transportinstruction.pb.cc
make  all-am
make[4]: Entering directory '/home/tux/dev/mosh/src/protobufs'
  CXX    userinput.pb.o
  CXX    hostinput.pb.o
  CXX    transportinstruction.pb.o
  AR     libmoshprotos.a
make[4]: Leaving directory '/home/tux/dev/mosh/src/protobufs'
make[3]: Leaving directory '/home/tux/dev/mosh/src/protobufs'
Making all in util
make[3]: Entering directory '/home/tux/dev/mosh/src/util'
  CXX    locale_utils.o
  CXX    swrite.o
  CXX    select.o
  CXX    timestamp.o  
  CXX    pty_compat.o 
  AR     libmoshutil.a
make[3]: Leaving directory '/home/tux/dev/mosh/src/util'
Making all in crypto  
make[3]: Entering directory '/home/tux/dev/mosh/src/crypto'
  CXX    ocb.o
g++-4.9.real: error: @OPENSSL_CFLAGS@: No such file or directory
Makefile:300: recipe for target 'ocb.o' failed
make[3]: *** [ocb.o] Error 1
make[3]: Leaving directory '/home/tux/dev/mosh/src/crypto'
Makefile:274: recipe for target 'all-recursive' failed
make[2]: *** [all-recursive] Error 1
make[2]: Leaving directory '/home/tux/dev/mosh/src'
Makefile:315: recipe for target 'all-recursive' failed
make[1]: *** [all-recursive] Error 1
make[1]: Leaving directory '/home/tux/dev/mosh'
Makefile:255: recipe for target 'all' failed
make: *** [all] Error 2
make  0,16s user 0,03s system 36% cpu 0,541 total
</pre>

./configure runs fine but make fails. Dependencies were installed via "apt-get build-deb mosh".

**Comment by keithw** [comment]
That's an unexpected error message, given that the string "OPENSSL_CFLAGS" doesn't appear anywhere in our repository.

Can you please blow away your mosh repository, clone from GitHub, and try again?

It did build on the Debian build servers.

**Comment by keithw** [comment]
(You may also just need to run `./autogen.sh` again. Or you can build the actual mosh-1.2.6.tar.gz release instead of from Git.)

**Comment by markybob** [comment]
just tried master on jessie and it works fine here. 
[log.txt](https://github.com/mobile-shell/mosh/files/429111/log.txt)

**Comment by T-X** [comment]
Urgh, had typed "autoconf" and "automake", but forgot about "./autogen.sh". That did the trick, thanks for the amazingly quick help and sorry for the noise! :-)
