### ISSUE TITLE
On Ubuntu, how can I see the normal "Welcome Screen"

### ISSUE THREAD

**Issue by computersarecool** [mobile-shell/mosh#799]
I started This is an [this issue](https://github.com/rpwoodbu/mosh-chrome/issues/128) because I wanted to see the welcome screen that Ubuntu normally shows.

I was encouraged to post the issue here and also try to try `mosh user@localhost`, however trying that gives me this error:

```bash
/usr/bin/mosh: Could not connect to /bin/sh: Name or service not known
ssh_exchange_identification: Connection closed by remote host
/usr/bin/mosh: Did not find remote IP address (is SSH ProxyCommand disabled?)
```

Mainly, I am interested in my first issue but now that this has popped up, I would like to know what SSH ProxyCommand even is (if I need to know that to help with the login issue).

**Comment by eminence** [comment]
Do you have anything in your `~/.ssh/config` file about "localhost" ?   The `Could not connect to /bin/sh: Name or service not known` is quite surprising and unexpected.

**Comment by computersarecool** [comment]
Hi,
There are no entries for local host at all.

**Comment by eminence** [comment]
What version of mosh do you have installed?

And at the risk of asking you to repeat yourself -- is the exact command you ran `mosh user@localhost` ? (if you replaced your username with `user` that's totally fine, but just wondering if there were any other arguments).  And the only output from mosh was those 3 lines?

**Comment by computersarecool** [comment]
The version I have is `mosh 1.2.5 [build mosh 1.2.5] `. Yes, that is the exact command (although I replaced `user` with my actual username.  I am not sure if this matters to anything but I have changed my default ssh port to 50505, but adding `mosh user@localhost --ssh="ssh -p 50505"` makes no difference.

**Comment by andersk** [comment]
In the [linked issue](https://github.com/rpwoodbu/mosh-chrome/issues/128), you mentioned “To complicate this question, my `.bashrc` file opens an instance of TMUX”. This kind of configuration is suspicious because it will usually break noninteractive sessions, such as the one `mosh` uses to start the remote `mosh-server`. To test whether this is your problem, check whether

```
ssh user@localhost 'echo hi'
```

produces _any_ output or interaction other than the normal SSH authentication interaction (if any) and the output line `hi`.

If your goal is to always log in to the server and run tmux, then rather than trying to configure the remote side to launch `tmux` from every `bash`, I would recommend creating a local alias to `ssh user@localhost 'tmux new -AD'` or `mosh user@localhost -- tmux new -AD`. (Or in Mosh for Chrome you can set the “remote command” to `tmux new -AD`.)

**Comment by computersarecool** [comment]
Good point - I think but am not completely sure I understand you.  My `.bashrc` checks to see if it is an interactive session (by checking `$PS1`) before creating / attaching to `TMUX` - I am sure an alias could also work.

Using `ssh user@localhost 'echo hi'` just outputs `hi`.

**Comment by andersk** [comment]
Hmm. Here is the full command that `mosh` 1.2.5 uses to launch the remote `mosh-server`, with the `mosh-server` arguments replaced by `--help`. What does this output?

```
ssh -S none -o 'ProxyCommand=mosh --fake-proxy -- %h %p' -n -tt user@localhost -- mosh-server --help
```

(Expected output is `MOSH IP 127.0.0.1` and a usage message from `mosh-server`, or perhaps some nonsense about `Bad IP address (--help)`, which is fine.)

Also see what happens if you launch just the proxy part:

```
bash -c 'mosh --fake-proxy -- 127.0.0.1 50505'
```

(Expected output is `MOSH IP 127.0.0.1` and an SSH banner like `SSH-2.0-OpenSSH_6.6.1p1 Ubuntu-2ubuntu2.8`; hit Ctrl-C to close.)

**Comment by computersarecool** [comment]
The first command here outputs:
````
/usr/bin/mosh: Could not connect to localhost: Connection refused
ssh_exchange_identification: Connection closed by remote host
```

The second outputs:
````
MOSH IP 127.0.0.1
SSH-2.0-OpenSSH_7.2p2 Ubuntu-4ubuntu1
```

**Comment by andersk** [comment]
Sorry, replace `ssh` with `ssh -p 50505` in the first command.

**Comment by computersarecool** [comment]
No it outputs:
```
MOSH IP 127.0.0.1
Error binding to IP --help: Bad IP address (--help): Name or service not known: Success
MOSH CONNECT 60002 /wxXftHQ/NDDsnA2Ojf7RA
Connection to localhost closed.
```

**Comment by andersk** [comment]
That is as expected.

To check that this is really the command `mosh` is trying to launch, what does this output?

```
mosh --ssh='printf %s\\n' user@localhost
```

**Comment by computersarecool** [comment]
(Thanks for your time). That puts out:
```
-S
none
-o
ProxyCommand='/usr/bin/mosh' '--family=inet' --fake-proxy -- %h %p
-n
-tt
user@localhost
--
mosh-server 'new' '-c' '256' '-s' '-l' 'LANG=en_US.UTF-8'
/usr/bin/mosh: Did not find remote IP address (is SSH ProxyCommand disabled?).
```

**Comment by andersk** [comment]
I cannot figure out where your extra `/bin/sh` is coming from.

Perhaps you can try debugging this from a different angle. Can you reproduce using a freshly-created account with no customizations, using this new account for the local side, for the remote side, or both?

If the problem disappears that way, perhaps try copying over any relevant customizations (such as `.bashrc`) one-by-one to see which one triggers the problem?

**Comment by andersk** [comment]
Or perhaps there might be enough information in an strace log? Can you run

```
strace -s9999 -o /tmp/strace-mosh.log -f -e trace=process mosh --ssh='ssh -p 50505' user@localhost
```

and post the contents of `/tmp/strace-mosh.log`?

**Comment by computersarecool** [comment]
The contents of that file are:
```
5586  execve("/usr/bin/mosh", ["mosh", "--ssh=ssh -p 50505", "optonox@localhost"], [/* 23 vars */]) = 0
5586  arch_prctl(ARCH_SET_FS, 0x7f7027aa9700) = 0
5586  execve("/usr/local/sbin/perl", ["perl", "/usr/bin/mosh", "--ssh=ssh -p 50505", "optonox@localhost"], [/* 23 vars */]) = -1 ENOENT (No such file or directory)
5586  execve("/usr/local/bin/perl", ["perl", "/usr/bin/mosh", "--ssh=ssh -p 50505", "optonox@localhost"], [/* 23 vars */]) = -1 ENOENT (No such file or directory)
5586  execve("/usr/sbin/perl", ["perl", "/usr/bin/mosh", "--ssh=ssh -p 50505", "optonox@localhost"], [/* 23 vars */]) = -1 ENOENT (No such file or directory)
5586  execve("/usr/bin/perl", ["perl", "/usr/bin/mosh", "--ssh=ssh -p 50505", "optonox@localhost"], [/* 23 vars */]) = 0
5586  arch_prctl(ARCH_SET_FS, 0x7fbc373c1700) = 0
5586  clone(child_stack=0, flags=CLONE_CHILD_CLEARTID|CLONE_CHILD_SETTID|SIGCHLD, child_tidptr=0x7fbc373c19d0) = 5587
5587  execve("/usr/local/sbin/mosh-client", ["mosh-client", "-c"], [/* 23 vars */]) = -1 ENOENT (No such file or directory)
5587  execve("/usr/local/bin/mosh-client", ["mosh-client", "-c"], [/* 23 vars */]) = -1 ENOENT (No such file or directory)
5587  execve("/usr/sbin/mosh-client", ["mosh-client", "-c"], [/* 23 vars */]) = -1 ENOENT (No such file or directory)
5587  execve("/usr/bin/mosh-client", ["mosh-client", "-c"], [/* 23 vars */]) = 0
5587  arch_prctl(ARCH_SET_FS, 0x7fa3a60cf740) = 0
5587  exit_group(0)                     = ?
5586  wait4(5587,  <unfinished ...>
5587  +++ exited with 0 +++
5586  <... wait4 resumed> [{WIFEXITED(s) && WEXITSTATUS(s) == 0}], 0, NULL) = 5587
5586  --- SIGCHLD {si_signo=SIGCHLD, si_code=CLD_EXITED, si_pid=5587, si_uid=1001, si_status=0, si_utime=0, si_stime=0} ---
5586  clone(child_stack=0, flags=CLONE_CHILD_CLEARTID|CLONE_CHILD_SETTID|SIGCHLD, child_tidptr=0x7fbc373c19d0) = 5588
5588  execve("/bin/sh", ["sh", "-c", "ssh -p 50505 '-S' 'none' '-o' 'ProxyCommand='\\''/usr/bin/mosh'\\'' '\\''--family=inet'\\'' --fake-proxy -- %h %p' '-n' '-tt' 'optonox@localhost' '--' 'mosh-server '\\''new'\\'' '\\''-c'\\'' '\\''256'\\'' '\\''-s'\\'' '\\''-l'\\'' '\\''LANG=en_US.UTF-8'\\'''"], [/* 23 vars */]) = 0
5588  arch_prctl(ARCH_SET_FS, 0x7f7cd9dea700) = 0
5588  clone(child_stack=0, flags=CLONE_CHILD_CLEARTID|CLONE_CHILD_SETTID|SIGCHLD, child_tidptr=0x7f7cd9dea9d0) = 5589
5588  wait4(-1,  <unfinished ...>
5589  execve("/usr/bin/ssh", ["ssh", "-p", "50505", "-S", "none", "-o", "ProxyCommand='/usr/bin/mosh' '--family=inet' --fake-proxy -- %h %p", "-n", "-tt", "optonox@localhost", "--", "mosh-server 'new' '-c' '256' '-s' '-l' 'LANG=en_US.UTF-8'"], [/* 23 vars */]) = 0
5589  arch_prctl(ARCH_SET_FS, 0x7f6cd2c47800) = 0
5589  clone(child_stack=0, flags=CLONE_CHILD_CLEARTID|CLONE_CHILD_SETTID|SIGCHLD, child_tidptr=0x7f6cd2c47ad0) = 5590
5590  execve("/bin/bash", ["/bin/bash", "-c", "exec '/usr/bin/mosh' '--family=inet' --fake-proxy -- localhost 50505"], [/* 23 vars */]) = 0
5590  arch_prctl(ARCH_SET_FS, 0x7fb5b6e00700) = 0
5590  execve("/usr/bin/mosh", ["/usr/bin/mosh", "--family=inet", "--fake-proxy", "--", "localhost", "50505"], [/* 22 vars */]) = 0
5590  arch_prctl(ARCH_SET_FS, 0x7f4530449700) = 0
5590  execve("/usr/local/sbin/perl", ["perl", "/usr/bin/mosh", "--family=inet", "--fake-proxy", "--", "localhost", "50505"], [/* 22 vars */]) = -1 ENOENT (No such file or directory)
5590  execve("/usr/local/bin/perl", ["perl", "/usr/bin/mosh", "--family=inet", "--fake-proxy", "--", "localhost", "50505"], [/* 22 vars */]) = -1 ENOENT (No such file or directory)
5590  execve("/usr/sbin/perl", ["perl", "/usr/bin/mosh", "--family=inet", "--fake-proxy", "--", "localhost", "50505"], [/* 22 vars */]) = -1 ENOENT (No such file or directory)
5590  execve("/usr/bin/perl", ["perl", "/usr/bin/mosh", "--family=inet", "--fake-proxy", "--", "localhost", "50505"], [/* 22 vars */]) = 0
5590  arch_prctl(ARCH_SET_FS, 0x7f62f4572700) = 0
5590  clone(child_stack=0, flags=CLONE_CHILD_CLEARTID|CLONE_CHILD_SETTID|SIGCHLD, child_tidptr=0x7f62f45729d0) = 5592
5586  wait4(5588,  <unfinished ...>
5589  exit_group(0)                     = ?
5590  --- SIGHUP {si_signo=SIGHUP, si_code=SI_USER, si_pid=5589, si_uid=1001} ---
5590  wait4(5592,  <unfinished ...>
5589  +++ exited with 0 +++
5588  <... wait4 resumed> [{WIFEXITED(s) && WEXITSTATUS(s) == 0}], 0, NULL) = 5589
5588  --- SIGCHLD {si_signo=SIGCHLD, si_code=CLD_EXITED, si_pid=5589, si_uid=1001, si_status=0, si_utime=2, si_stime=0} ---
5588  exit_group(0)                     = ?
5588  +++ exited with 0 +++
5586  <... wait4 resumed> [{WIFEXITED(s) && WEXITSTATUS(s) == 0}], 0, NULL) = 5588
5586  --- SIGCHLD {si_signo=SIGCHLD, si_code=CLD_EXITED, si_pid=5588, si_uid=1001, si_status=0, si_utime=0, si_stime=0} ---
5586  wait4(5588, 0x7fff794b64c4, 0, NULL) = -1 ECHILD (No child processes)
5586  execve("/usr/local/sbin/mosh-client", ["mosh-client --ssh=ssh -p 50505 optonox@localhost |", "127.0.0.1", "60001"], [/* 25 vars */]) = -1 ENOENT (No such file or directory)
5586  execve("/usr/local/bin/mosh-client", ["mosh-client --ssh=ssh -p 50505 optonox@localhost |", "127.0.0.1", "60001"], [/* 25 vars */]) = -1 ENOENT (No such file or directory)
5586  execve("/usr/sbin/mosh-client", ["mosh-client --ssh=ssh -p 50505 optonox@localhost |", "127.0.0.1", "60001"], [/* 25 vars */]) = -1 ENOENT (No such file or directory)
5586  execve("/usr/bin/mosh-client", ["mosh-client --ssh=ssh -p 50505 optonox@localhost |", "127.0.0.1", "60001"], [/* 25 vars */]) = 0
5592  exit_group(0)                     = ?
5592  +++ exited with 0 +++
5590  <... wait4 resumed> [{WIFEXITED(s) && WEXITSTATUS(s) == 0}], 0, NULL) = 5592
5590  --- SIGCHLD {si_signo=SIGCHLD, si_code=CLD_EXITED, si_pid=5592, si_uid=1001, si_status=0, si_utime=0, si_stime=0} ---
5586  arch_prctl(ARCH_SET_FS, 0x7f0c7b9b6740 <unfinished ...>
5590  exit_group(0)                     = ?
5586  <... arch_prctl resumed> )        = 0
5590  +++ exited with 0 +++
```

**Comment by andersk** [comment]
Um, that log does not show any problems at all. Does

```
mosh --ssh='ssh -p 50505' user@localhost
```

still show the error from your original report?

**Comment by cgull** [comment]
I tried to answer this last night, but was too sleepy...

Anders is helping you debug the second problem, but I think your first problem is https://github.com/mobile-shell/mosh/issues/741, aka "we don't support that, nobody's written code for it yet."  It would be platform-specific code for one (very popular) Linux variant, and we have not done a whole lot of that.

**Comment by computersarecool** [comment]
Ah yes @cgull - this is the issue, sorry I didn't see it.  I felt a bit foolish for asking for this in the first place - thanks for your help.  I will monitor that issue from here on out.
