### ISSUE TITLE
Poop emoji rendered as space

### ISSUE THREAD

**Issue by llwu** [mobile-shell/mosh#801]
Hi, this is similar to #612 and #234 , but I'm not sure if it's the caused by the same thing, since I have glibc 2.23 which supports Unicode 8. The following code prints out "1 💩" as desired:

```
#define _XOPEN_SOURCE
#include <wchar.h>
#include <locale.h>
#include <stdio.h>

int main() {
    setlocale(LC_ALL, "");
    const wchar_t poop = 0x1F4A9;
    printf("%d %lc\n", wcwidth(poop), poop);
    return 0;
}
```

But if I paste a bunch of poop emojis into a tmux session over mosh, I see spaces instead. I can reattach to the session over ssh and see the poop emojis, and then reattach over mosh and see spaces again.

**Comment by keithw** [comment]
Do you have glibc 2.23 on the client *and* the server? (What platforms/architectures are the client and server, and what version of Mosh?) This does work for me (using Ubuntu 16.04 LTS on the client and server), both with and without tmux.

**Comment by llwu** [comment]
Ah, you got me, the server is running glibc 2.19. Closing this
