### ISSUE TITLE
Mouse events only work in the top-left corner of mosh window

### ISSUE THREAD

**Issue by colemickens** [mobile-shell/mosh#803]
If I open vim in mosh and click around, I notice the following:

1. Everything works fine in the top-left corner of the window.

2. Click and scroll events elsewhere are translated into key presses.

I've noticed this in both Dev/Stable in both Windows and ChromeOS.

I can supply a video of this behavior as well, if it would help.

**Comment by colemickens** [comment]
And in OS X. Here's a video: https://www.youtube.com/watch?v=BypvSmJOQCc

**Comment by keithw** [comment]
The outer terminal probably matters a lot here. On OS X, is this in Terminal.app or something else?

**Comment by colemickens** [comment]
Oh drat, I filed this on the wrong project. This is an issue with the ChromeOS app. My apologies.
