### ISSUE TITLE
Building mosh 1.2.6 from source doesn't provide an error message for missing pkg-config

### ISSUE THREAD

**Issue by meisme** [mobile-shell/mosh#805]
Attempting to build mosh 1.2.6 on Ubuntu or Debian without having pkg-config installed will fail in ./configure saying there's no crypto library installed, even when the library is installed.

Steps to reproduce:
1) Make sure all dependencies are installed
2) Uninstall pkg-config
3) Clone git repository and check out mosh-1.2.6
4) `./autogen && ./configure --with-crypto-library=openssl`
5) Build fails

**Comment by eminence** [comment]
Yes, I've seen this too.  Installing `pkg-config` should fix this.

I *think* the easiest thing to list `pkg-config` as a build dependency.

**Comment by meisme** [comment]
In mosh 1.2.5 it correctly reports that pkg-config is missing when you try the above steps, so it might be worth looking at what changed.

But listing `pkg-config` as a dependency should probably be done regardless.

**Comment by cgull** [comment]
`debian/control` already lists pkg-config in its dependencies, and `apt-get build-deps` will easily fetch those dependencies.  So I think of this as an incorrect build, though the need for pkg-config on some systems is definitely not well documented.  I'm a little reluctant to require pkg-config in configure.ac given the variety of systems Mosh builds on.  @eminence and @meisme, what are you thinking of when you say "listing `pkg-config` as a build dependency?"  A change to the Mosh web page, or something else?

**Comment by eminence** [comment]
@cgull Yeah, just a change to mosh-web.  Perhaps a new "Build Dependencies" table under the current "Dependencies" table, where we can move `protobuf-compiler` and add `pkg-config`

**Comment by meisme** [comment]
I agree with eminence, that seems like a good solution to me.

**Comment by cgull** [comment]
Updated in https://github.com/mobile-shell/moshweb/commit/c8fa8f2641c40e33ef8955a33624bc717751134b
