### ISSUE TITLE
FreeBSD 11.0 - did not find mosh server startup message

### ISSUE THREAD

**Issue by TimCook1** [mobile-shell/mosh#809]
I know you're aware of the issue.  Not sure if there's anything tracking a fix, or if this has been deemed a FreeBSD issue.  I just upgraded one of my servers to FreeBSD 11.0-RELEASE today and after installing the 1.2.6 package from FreeBSD packages repo, I run into what I believe is the issue mentioned below.  Client is OSX 10.12 (brew) , servers is FreeBSD 11.0-RELEASE-p0 (pkg) | both running 1.2.6.

https://lists.freebsd.org/pipermail/freebsd-current/2016-August/062918.html

**Comment by andersk** [comment]
It was fixed by 4ad131a55d5a82a044a0c62428d6a488a97b46bf.
