### ISSUE TITLE
Missing IPv6-support

### ISSUE THREAD

**Issue by skibbi** [mobile-shell/mosh#81]
Mosh does not seem to support IPv6. When specifying a hostname with both IPv4 and IPv6, an IPv4-connection is used. Specifying an IPv6-address results in:

/usr/bin/mosh: Could not resolve hostname 2a01:238:42a0:a200:e709:8d1c:581d:6e5a
ssh_exchange_identification: Connection closed by remote host
/usr/bin/mosh: Did not find remote IP address (is SSH ProxyCommand disabled?).

**Comment by dtaht** [comment]
will mosh multipath be merged?

**Comment by cgull** [comment]
Not for mosh-1.2.5, which is just a rollup of bugfixes and cleanup PRs that were in the queue-- no more new features.  I haven't even looked at https://github.com/boutier/mosh yet, though I'm definitely interested.

**Comment by nomadium** [comment]
@cgull is there an ETA for mosh-1.2.5?

**Comment by cgull** [comment]
I should have the two remaining issues wrapped up this weekend-- OS X build and Debian bash completion.  Release will come soon after that, depending on how much bake time it gets and if we find anything else.

**Comment by nomadium** [comment]
Good to know, thanks for taking care of the release.

**Comment by kurtkraut** [comment]
With the mosh -6 parameter I'm able to connect to my server using IPv6 but without mentioning this parameter, mosh (version 1.2.5 tested) will always prefer to connect using IPv4 instead of IPv6 if a AAAA DNS entry is available for the FQDN.

I strongly suggest as browsers, OpenSSH and other client/daemon softwares behave, AAAA is prefered over A addresses.

**Comment by Mikaela** [comment]
> I strongly suggest as browsers, OpenSSH and other client/daemon softwares behave, AAAA is prefered over A addresses.

They follow [RFC 6555](https://tools.ietf.org/html/rfc6555) aka [Happy Eyeballs](https://en.wikipedia.org/wiki/Happy_Eyeballs) which everything should support nowadays.

**Comment by graingert** [comment]
@Mikaela but mosh doesn't need to support Happy Eyeballs, it can make multiple connections simultaneously

**Comment by dtaht** [comment]
I really would like to see mosh multipath merged. It's even happier than happy eyeballs.

**Comment by pavlix** [comment]
I hope you don't mind that I created an issue just for the roaming, see #855 . This is an old issue for lack of IPv6 support. I have tried using mosh 1.2.6 on IPv6 with success and therefore I believe this issue should just be closed.

**Comment by achernya** [comment]
We've since merged IPv6 support, and discussion on this issue has diverged. It's no longer clear to me what's being requested. Please file new issues for any missing functionality if you don't see an open one in the issue tracker already.

**Comment by dtaht** [comment]
Thank you for so long ago making ipv6 just work. I use it all the time!
