### ISSUE TITLE
Unable to build mosh on bash on windows

### ISSUE THREAD

**Issue by kyldvs** [mobile-shell/mosh#813]
I'm trying to work around #781 by building the workaround branch: https://github.com/cgull/mosh/tree/wsl-workarounds-14361

However I'm unable to build mosh from source no matter what I try. I've searched extensively for how to meet these dependencies but `./configure` keeps failing, this is the end of the output which has the failure:

```
checking CommonCrypto/CommonCrypto.h usability... no
checking CommonCrypto/CommonCrypto.h presence... no
checking for CommonCrypto/CommonCrypto.h... no
checking for CRYPTO... no
configure: error: OpenSSL crypto library not found
```

From what I understand I need to install, `libssl-dev` which I have:

```
$ sudo apt-get install libssl-dev                                                                                                                                           
Reading package lists... Done
Building dependency tree
Reading state information... Done
libssl-dev is already the newest version.
0 upgraded, 0 newly installed, 0 to remove and 24 not upgraded.
```

I've even tried to configure after installing nettle instead of using openssl, but that didn't work either. It failed at the exact same spot.

Any ideas how I might resolve this?

**Comment by cgull** [comment]
I would guess you don't have `pkg-config` installed. Since you're really almost sort of using Ubuntu, `apt-get build-dep mosh` should get you a good build environment (technically this gets deps to rebuild the Ubuntu package, but they haven't gone stale yet).

**Comment by kyldvs** [comment]
Perfect, installing `pkg-config` got me through configure.

Seems like after building it though the branch doesn't support IPv6, in particular I get this error:

```
$ mosh -6 dev # my ssh alias
/usr/local/bin/mosh: IPv6 sockets not available in this Perl install
```

If you can give me one more quick pointer I'd appreciate it. Is this an issue with how I build mosh or will the windows workarounds not work with -6?

If the later I can just wait for #781

**Comment by cgull** [comment]
IPv6 is supported in that branch. And Ubuntu 14.04's Perl install should have the necessary module in Perl base. I don't remember whether IPv6 on Bash on Windows works, it's possible that the emulation isn't good enough for Perl to think it can use IPv6.

**Comment by kyldvs** [comment]
Thanks for the reply, I'll poke around and see if I can upgrade Perl such that I can use IPv6.

**Comment by kyldvs** [comment]
Got it working, posting back here in case someone else comes along searching for this error too.

I just needed to install the `IO::Socket::IP` package for Perl. 

```
sudo apt-get install libio-socket-ip-perl
```
