### ISSUE TITLE
Color doesnt work with Powerline

### ISSUE THREAD

**Issue by drewcassidy** [mobile-shell/mosh#827]
Whenever I try to use mosh with my VPS that has power line installed, I don't get any colors. Colors still work in ssh, however. Im using zsh on both devices and iTerm. Color still works with some other programs like `ls`

ssh:
<img width="158" alt="screen shot 2016-11-12 at 7 18 52 pm" src="https://cloud.githubusercontent.com/assets/3837797/20243459/e7ef0f26-a90c-11e6-903c-d2e437839062.png">

mosh: 
<img width="196" alt="screen shot 2016-11-12 at 7 19 10 pm" src="https://cloud.githubusercontent.com/assets/3837797/20243460/ef5d2b62-a90c-11e6-9269-2274a77e0380.png">

Update:
Both my laptop and the VPS are running version 1.2.6 of mosh
laptop is running macOS 10.12.1
VPS is a basic droplet from Digitalocean running Debian, testing stream
$TERM = `xterm-256color`
the example of using multiple color codes at once from #507 works fine, so this is definitely a different issue

**Comment by cgull** [comment]
My guess is that you have a powerline theme that uses 24-bit color-- that's not yet supported in Mosh.  Can you capture the terminal output to verify this, with `script` or similar?

**Comment by drewcassidy** [comment]
That fixed it. thanks
