### ISSUE TITLE
Garbled output of toilet output when using figlet fonts

### ISSUE THREAD

**Issue by silverhook** [mobile-shell/mosh#835]
I use `toilet` to generate a nice logo on log-in.

When I log in using `mosh`, I the logo gets garbled. Here is a simplified example:

`toilet --font wideterm "Nice text here"`

    ________  ________  ________

`toilet --font smmono9 "Nice text here"`
                                                        
    __ _ _               _           _      _               
    __ ___   __  __     ___  __ _ _ ___     ___  __  __  __ 
    ____ _  ___ ___      _  ___  __  _      ___ ___  _ ____ 
    _ __ _  _   ___      _  ___  __  _      _ _ ___  _  ___ 
    _ _____ ___ ___      __ ___ ___  __     _ _ ___  _  ___ 
    
For comparison when I log in via `ssh` it works fine.

`toilet --font wideterm "Nice text here"`

    Ｎｉｃｅ  ｔｅｘｔ  ｈｅｒｅ

`toilet --font smmono9 "Nice text here"`

    ▗▖ ▖ ▝               ▗           ▗      ▐               
    ▐▚ ▌▗▄   ▄▖  ▄▖     ▗▟▄  ▄▖ ▗ ▗ ▗▟▄     ▐▗▖  ▄▖  ▖▄  ▄▖ 
    ▐▐▖▌ ▐  ▐▘▝ ▐▘▐      ▐  ▐▘▐  ▙▌  ▐      ▐▘▐ ▐▘▐  ▛ ▘▐▘▐ 
    ▐ ▌▌ ▐  ▐   ▐▀▀      ▐  ▐▀▀  ▟▖  ▐      ▐ ▐ ▐▀▀  ▌  ▐▀▀ 
    ▐ ▐▌▗▟▄ ▝▙▞ ▝▙▞      ▝▄ ▝▙▞ ▗▘▚  ▝▄     ▐ ▐ ▝▙▞  ▌  ▝▙▞ 

I noticed that this seems to be due to the `--font` flag, that sets a custom figlet font. If I simply use the standard console font, the bug is not triggered.

**Comment by carloscabanero** [comment]
I used toilet to take screenshots and videos with Blink, and didn't find
any issues. Have you tried a different terminal?

**Comment by silverhook** [comment]
@carloscabanero, just tried as you said and came to an odd conclusion:

- on `xterm`, it works fine
- on `konsole`, it works fine
- on `yakuake`, it does that odd thing that I reported …which is odd, because it simply uses konsole as a kpart.

Still odd that in `yakuake` it works via SSH. Any ideas why that is?

**Comment by silverhook** [comment]
Even odder still, it suddenly works now even in Yakuake. No idea what I did.

I’m closing this issue and filing it into the X-files drawer.
