### ISSUE TITLE
juicessh not compatible with current mosh-server

### ISSUE THREAD

**Issue by cgull** [mobile-shell/mosh#846]
JuiceSSH shows screen corruption when connecting to a mosh-server from master on OS X, running tmux 2.3 and WeeChat 1.5 (the original reporter saw this on Linux, I believe).  A 1.2.4 server works correctly in the same environment.  The original reporter's screenshot is here:  
http://imgur.com/JxV0Gn3

In my testing, it appears that when the screen is scrolled, graphic characters from previous lines are not erased, and the text of the newly-scrolled line overwrites the old text.  This appears to be a bad interaction between the new screen-update code in mosh-1.2.6 and JuiceSSH's proprietary code, but since JuiceSSH is closed source I can't address this further, and I've reported this to support@sonelli.com, and this is a tracking issue.

**Comment by eminence** [comment]
FWIW, I don't see any issues with juicessh, tmux 2.1, weechat 1.4, mosh 1.2.6, on linux

**Comment by cgull** [comment]
I should say this is *currently* a tracking issue, the problem could well turn out to be on our side.

I tried ssh to mosh-to-localhost in my same test environment, and that seems to work OK-- no display corruption.  So the issue seems to be specific to Mosh implementation, not generically about JuiceSSH's terminal emulation.

I also see the corruption when scrolling up in OS X's vi, but not when scrolling down.

**Comment by featheredtoast** [comment]
I've got the same issue - Arch Linux server, juicessh, tmux.
mosh 1.2.6
irssi 0.8.21
tmux 2.3

Juicessh has worked without character corruption up until a mosh update a few weeks(?) ago. Further, across OSX and Linux (Ubuntu) clients (running v1.2.5 mosh clients), I haven't seen any character corruption so far.
