### ISSUE TITLE
mosh can't handle server IP changing?

### ISSUE THREAD

**Issue by DarwinAwardWinner** [mobile-shell/mosh#847]
I have a server in my closet at home. When I'm on my home LAN, my router resolves mneme.dedyn.io to the internal IP address of the server. When I'm not on my LAN, I use a dynamic DNS service to resolve mneme.dedyn.io to the external IP of the router, which forwards all ports to the server. Therefore I can always type `ssh mneme.dedyn.io` from anywhere and end up at my server, whether I am on the LAN or not. However, if I do `mosh mneme.dedyn.io` on my LAN and then later leave and connect to another network, mosh is unable to reconnect, presumably because it is still using the old internal IP address. If this is the problem, can an option be added to look up the hostname via DNS each time before reconnecting a session?

**Comment by eminence** [comment]
> mosh is unable to reconnect, presumably because it is still using the old internal IP address

That's correct.  

When you are at home, inside your local network, is there any reason you can't connect to your external IP?  This way would be able to seamlessly roam between your internal and external networks.

**Comment by DarwinAwardWinner** [comment]
Hmm. Last time I tried it, my ISP was just dropping all packets sent from my LAN to my external IP. Hence, I set up my router to resolve the external domain name to the internal IP. But trying it now, it seems to be working fine. I guess I'll switch to doing that, then.

**Comment by jungle-boogie** [comment]
mosh + zerotier would be an excellent way to connect to machines inside a LAN from outside your LAN.
https://www.zerotier.com/
