### ISSUE TITLE
record entire mosh session for security audit purposes?

### ISSUE THREAD

**Issue by cypa** [mobile-shell/mosh#849]
Would it be difficult?
How to replay recorded session?

**Comment by cypa** [comment]
this https://github.com/open-ch/log-user-session works nicely, but is it better to record entire traffic on mosh side?

**Comment by andersk** [comment]
In the interest of preferring simple solutions, consider having the user run [`script`](http://manpages.ubuntu.com/manpages/xenial/en/man1/script.1.html) inside Mosh. If that doesn’t satisfy your requirements, what exactly are they?

**Comment by cypa** [comment]
@andersk script is even better then log-user-session

**Comment by andersk** [comment]
Great, I’ll assume this is solved then.

**Comment by cypa** [comment]
Yes, almost ... but as I found script, asciinema or log-user-session is not enough for security audit puposes since user typed input is not recorded until it is echoed by shell.
Thus if one issue command 'stty -echo' then all executed command became hidden so user escape security logging!

Then we need total recording of entire input/output by mosh.

**Comment by cypa** [comment]
I guess one have to use conspy tool for pty device to record session
