### ISSUE TITLE
Mosh ssh option to support process substitution

### ISSUE THREAD

**Issue by CMCDragonkai** [mobile-shell/mosh#850]
I separated my ssh config and host files, which means I alias my ssh commands to take these 2 files 

```
alias ssh='ssh -F <(cat ~/.ssh/config ~/.ssh/hosts)'
```

However, I tried running mosh while overriding the default `ssh` command, I get this:

```
> alias mosh='\mosh --ssh="ssh -F <(cat ~/.ssh/config ~/.ssh/hosts)"'
> mosh snapsearch
sh: -c: line 0: syntax error near unexpected token `('
sh: -c: line 0: `ssh -F <(cat ~/.ssh/config ~/.ssh/hosts) '-S' 'none' '-o' 'ProxyCommand='\''/usr/bin/mosh'\'' '\''--family=inet'\'' --fake-proxy -- %h %p' '-n' '-tt' 'snapsearch' '--' 'mosh-server '\''new'\'' '\''-c'\'' '\''256'\'' '\''-s'\'' '\''-l'\'' '\''LANG=en_US.UTF-8'\'' '\''-l'\'' '\''LANGUAGE=en_US.UTF-8'\'' '\''-l'\'' '\''LC_ALL=en_US.UTF-8'\''''
/usr/bin/mosh: Did not find remote IP address (is SSH ProxyCommand disabled?).
```

Alternatively I tried this:

```
> alias mosh='\mosh --ssh="ssh -F "<(cat ~/.ssh/config ~/.ssh/hosts)'
zsh: No such file or directory
write: Broken pipe
/usr/bin/mosh: Did not find remote IP address (is SSH ProxyCommand disabled?).
```

In the end, even if I set the the hostname into a single config file, I still get the above error. Something's broken with mosh on Cygwin.

**Comment by CMCDragonkai** [comment]
Just wanted to point out that in newer versions of Cygwin, `/etc/passwd` and `/etc/group` no longer exist by default as they are not required. Could this be what is causing the error? https://cygwin.com/cygwin-ug-net/ntsec.html#ntsec-mapping

Also see the docs here: https://www.cygwin.com/cygwin-ug-net/mkpasswd.html

> Don't use this command to generate a local /etc/passwd file, unless you really need one. See the Cygwin User's Guide for more information.

**Comment by andersk** [comment]
You need to insert a call to the shell to get shell expansions, either inline for a cryptic one-liner:

`mosh --ssh='bash -c "ssh -F <(cat ~/.ssh/config ~/.ssh/hosts) \"$@\"" -'`

or by writing a separate `my-ssh` script to be used with `mosh --ssh=my-ssh`:

```bash
#!/bin/bash
ssh -F <(cat ~/.ssh/config ~/.ssh/hosts) "$@"
```

**Comment by CMCDragonkai** [comment]
I can see that solving problem 1. But I tried it without aliasing with a complete config file and met problem 2. Something about file not found and write pipe broken.

**Comment by CMCDragonkai** [comment]
I'm still getting this:

```
> mosh --ssh='bash -c "ssh -F <(cat ~/.ssh/config ~/.ssh/hosts) \"$@\"" -' snapsearch
Can't open user config file /dev/fd/63: No such file or directory
/usr/bin/mosh: Did not find remote IP address (is SSH ProxyCommand disabled?).
```

**Comment by andersk** [comment]
```
> mosh --ssh='bash -c "ssh -F <(cat ~/.ssh/config ~/.ssh/hosts) \"$@\"" -' snapsearch
Can't open user config file /dev/fd/63: No such file or directory
```

That is also what happens for me when I try to run `ssh -F <(cat ~/.ssh/config ~/.ssh/hosts) HOSTNAME` outside Mosh. It seems `ssh` simply doesn’t support that mode of operation, because it closes FDs 3 and higher very early in `main()`. You need a more complicated `ssh` wrapper script that makes a temporary config file.

```
zsh: No such file or directory
write: Broken pipe
/usr/bin/mosh: Did not find remote IP address (is SSH ProxyCommand disabled?).
```

What happens when you run `ssh -tt snapsearch echo hello`? Perhaps your remote dotfiles are trying to automatically launch `zsh` from your default shell without accounting for the noninteractive case. (If so, you should run `chsh` on the remote side rather than trying to launch one shell from another.)

**Comment by CMCDragonkai** [comment]
Using `alias ssh='\ssh -F <(cat ~/.ssh/config ~/.ssh/hosts)'; ssh hostname` really does work. My ssh version is: `OpenSSH_7.4p1, OpenSSL 1.0.2k  26 Jan 2017`.

I don't understand why that would fail for mosh, and apparently for you.

Running `ssh -tt snapsearch echo hello` gives back:

```
hello
Connection to snapsearch.io closed.
```

**Comment by CMCDragonkai** [comment]
Ok I got mosh working. I had to compile from source. The cygwin package is broken in some way.

Had to install a bunch of dependencies from Cygwin packages:

```
libncursesw10
libncurses-devel
libprotobuf8
libprotobuf-devel
make
libboost
libboost-devel
pkg-config
perl
perl-IO-Tty
```

Then just follow the source compilation instructions, and it works.

**Comment by CMCDragonkai** [comment]
Unfortunately the process substitution trick still doesn't work. But at least mosh with a single config file still works.

I think this issue should still be open since the process substitution doesn't work with Mosh.

**Comment by CMCDragonkai** [comment]
@andersk 

I'm trying to do this, but it still doesn't work:

```
mosh () {

    if mosh_ssh_config="$(mktemp /tmp/mosh-ssh-config.XXXXXX)"; then 

        cat ~/.ssh/config ~/.ssh/hosts >"$mosh_ssh_config" \
        && chmod 600 "$mosh_ssh_config" \
        && mosh --ssh="ssh -F '$mosh_ssh_config'" $@

        rm -f "$mosh_ssh_config"

    fi
    
}
```

It results in creating an infinite amount of `/tmp/mosh-ssh-config.sdfdsf`.
