### ISSUE TITLE
Locale issue with LC_TIME having to be supported on the server

### ISSUE THREAD

**Issue by tuxayo** [mobile-shell/mosh#853]
From the error message it seems that only LC_TYPE should matter, can someone confirm that?

```
The locale requested by LC_CTYPE=fr_FR.UTF-8 isn't available here.
Running `locale-gen fr_FR.UTF-8' may be necessary.

mosh-server needs a UTF-8 native locale to run.

Unfortunately, the local environment ([no charset variables]) specifies
the character set "US-ASCII",

The client-supplied environment (LC_CTYPE=fr_FR.UTF-8) specifies
the character set "US-ASCII".

locale: Cannot set LC_ALL to default locale: No such file or directory
```

Server locale seems okay
```
user@server ~ % locale
LANG=fr_FR.UTF-8
LC_CTYPE="fr_FR.UTF-8"
LC_NUMERIC="fr_FR.UTF-8"
LC_TIME="fr_FR.UTF-8"
LC_COLLATE=C
LC_MONETARY="fr_FR.UTF-8"
LC_MESSAGES="fr_FR.UTF-8"
LC_PAPER="fr_FR.UTF-8"
LC_NAME="fr_FR.UTF-8"
LC_ADDRESS="fr_FR.UTF-8"
LC_TELEPHONE="fr_FR.UTF-8"
LC_MEASUREMENT="fr_FR.UTF-8"
LC_IDENTIFICATION="fr_FR.UTF-8"
LC_ALL=
```

```
user@server ~ % locale -a
C
POSIX
en_US.utf8
fr_FR.utf8
ru_RU.utf8
```

Client locale seems okay
```
~ » locale
LANG=fr_FR.utf8
LC_CTYPE=fr_FR.UTF-8
LC_NUMERIC=fr_FR.UTF-8
LC_TIME=en_DK.UTF-8
LC_COLLATE=fr_FR.UTF-8
LC_MONETARY=fr_FR.UTF-8
LC_MESSAGES=en_US.UTF-8
LC_PAPER=fr_FR.UTF-8
LC_NAME=fr_FR.UTF-8
LC_ADDRESS=fr_FR.UTF-8
LC_TELEPHONE=fr_FR.UTF-8
LC_MEASUREMENT=fr_FR.UTF-8
LC_IDENTIFICATION=fr_FR.UTF-8
LC_ALL=
```

```
~ » locale -a
C
en_DK.utf8
en_US.utf8
fr_FR.utf8
POSIX
```

## Work around.
`export LC_TIME="fr_FR.utf8"`

**Comment by keithw** [comment]
Thanks for the report. We don't think this is really related to Mosh -- if your locale-related environment variables specify a locale that (for whatever reason) `setlocale` can't load, you're going to have a bad time. (E.g. Perl will also print an error message every time it starts up.)

SSH lets this happen (and lets you wait to see the errors when you run other programs); try something like `ssh SERVER perl`. Mosh is a bit more rigid because we don't want to let people go ahead with flaky locale setups.

**Comment by tuxayo** [comment]
Thanks for the hints.

> Perl will also print an error message every time it starts up

It seems that Perl is okay and therefore `setlocale` too ?

```
~ » ssh user@example.org "perl -e 'print \"hi \n\"'"
hi
~ »
```

**Comment by tuxayo** [comment]
@keithw As perl seems to have not issue, is there something else that I can check?

**Comment by keithw** [comment]
What do you get if you run: `ssh -tt SERVERNAME 'locale -c charmap'`?

And, what do you get if you log in to the server, set *all* of the client's locale-related environment variables on the server (including LC_TIME=en_DK.UTF-8 and LC_MESSAGES=en_US.UTF-8) and then run `locale -c charmap`?

**Comment by tuxayo** [comment]
> What do you get if you run: ssh -tt SERVERNAME 'locale -c charmap'?

```
~ » ssh -tt user@example.org 'locale -c charmap'
LC_CTYPE
ANSI_X3.4-1968
Connection to example.org closed.
```

> if you log in to the server, set all of the client's locale-related environment variables on the server

set them to which value?

Here is what I guessed:

```
user@server ~ % locale
LANG=fr_FR.UTF-8
LC_CTYPE="fr_FR.UTF-8"
LC_NUMERIC="fr_FR.UTF-8"
LC_TIME="fr_FR.UTF-8"
LC_COLLATE=C
LC_MONETARY="fr_FR.UTF-8"
LC_MESSAGES="fr_FR.UTF-8"
LC_PAPER="fr_FR.UTF-8"
LC_NAME="fr_FR.UTF-8"
LC_ADDRESS="fr_FR.UTF-8"
LC_TELEPHONE="fr_FR.UTF-8"
LC_MEASUREMENT="fr_FR.UTF-8"
LC_IDENTIFICATION="fr_FR.UTF-8"
LC_ALL=
user@server ~ % locale -c charmap
LC_CTYPE
UTF-8
user@server ~ % export LC_ALL="fr_FR.UTF-8"
user@server ~ % export LC_TIME="en_DK.UTF-8"
user@server ~ % locale                      
LANG=fr_FR.UTF-8
LC_CTYPE="fr_FR.UTF-8"
LC_NUMERIC="fr_FR.UTF-8"
LC_TIME="fr_FR.UTF-8"
LC_COLLATE="fr_FR.UTF-8"
LC_MONETARY="fr_FR.UTF-8"
LC_MESSAGES="fr_FR.UTF-8"
LC_PAPER="fr_FR.UTF-8"
LC_NAME="fr_FR.UTF-8"
LC_ADDRESS="fr_FR.UTF-8"
LC_TELEPHONE="fr_FR.UTF-8"
LC_MEASUREMENT="fr_FR.UTF-8"
LC_IDENTIFICATION="fr_FR.UTF-8"
LC_ALL=fr_FR.UTF-8
user@server ~ % locale -c charmap
LC_CTYPE
UTF-8
```
Did I make the right checks?

The server doesn't have the en_DK.UTF-8 locale, that might be the reason `export LC_TIME="en_DK.UTF-8"` doesn't seem to work.

But should it have it? I'm using this locale for LC_TIME on my machine just to get ISO 8601 dates...

**Comment by keithw** [comment]
Hello,

Your first execution indicates that the server is (by default) getting executed in a locale whose charset is US-ASCII ("ANSI_X3.4-1968"). Mosh needs it to be UTF-8.

As a fail-safe to try to rescue the situation, Mosh then tries to take your client's locale-related environment variables to the server. (You asked "set them to which value" -- I meant, set them to the values they have on the client. This is what Mosh does.) If the server does not have the corresponding locale, or if that locale also doesn't specify a charset of UTF-8, Mosh won't be able to run.

You will need to make sure that either:

1. the locale that sshd executes programs with on the server specifies a charset of UTF-8, or
2. the locale-related environment variables on the client, when those values are set on the server, can summon a locale that specifies a charset of UTF-8.

The commands you ran indicated neither of these is true right now.

In your latest post, you gave an example where you set "LC_ALL" to "fr_FR.UTF-8". This is different from the locale-related environment variables you specified in your initial post -- those did not have "LC_ALL" set. If setting "LC_ALL" to "fr_FR.UTF-8" on the client is acceptable to you, and if that causes the server to come up with UTF-8 as the charset, then you might want to do that.

**Comment by piotr-dobrogost** [comment]
@tuxayo 

> The server doesn't have the en_DK.UTF-8 locale, that might be the reason export `LC_TIME="en_DK.UTF-8"` doesn't seem to work.

How do you know that it *doesn't seem to work*? Because afterwards `locale` shows `LC_TIME="fr_FR.UTF-8"`? Setting value of any environment variable is not guarded by any checks so availability of locale has nothing to do with the value you see. You run these commands:
```
user@server ~ % export LC_ALL="fr_FR.UTF-8"
user@server ~ % export LC_TIME="en_DK.UTF-8"

```
As LC_ALL takes precedence over any other LC_* env variable (see http://unix.stackexchange.com/q/87745/5355) by setting it above you made subsequent setting of LC_TIME irrelevant.

@keithw

> Mosh then tries to take your client's locale-related environment variables to the server

What if one of them (like LC_TIME) is set to locale with the charset which is supported by the server and valid from the point of view of mosh (like UTF-8) but locale itself (like en_DK) is not supported on the server? Does mosh in that case bails out and if so then why?

**Comment by tuxayo** [comment]
@keithw thanks for pointing what's wrong in my server config.

> In your latest post, you gave an example where you set "LC_ALL" to "fr_FR.UTF-8".

That's how I understood «if you log in to the server, set all of the client's locale-related environment variables on the server»

(I'm not a native speaker so most confusion comes from that)

> You asked "set them to which value" -- I meant, set them to the values they have on the client. This is what Mosh does.)

I see, then I shouldn't have set LC_ALL

> This is different from the locale-related environment variables you specified in your initial post

The initial state is the same but then I set LC_ALL (for the wrong reasons mentioned above)

@piotr-dobrogost
> How do you know that it doesn't seem to work? Because afterwards locale shows LC_TIME="fr_FR.UTF-8"?

Yes, I'm pretty new about how localization work so my deductions might be wrong.

> As LC_ALL takes precedence over any other LC_* env variable (see http://unix.stackexchange.com/q/87745/5355) by setting it above you made subsequent setting of LC_TIME irrelevant.

I see, thanks for the explanation.

Wait, is this normal that I don't get the same results depending of how I execute the command on the server?

```
~ » ssh -tt user@server.example.org 'locale -c charmap'
LC_CTYPE
ANSI_X3.4-1968
Connection to server.example.org closed.
~ » 
```

```
~ » ssh user@server.example.org
server@server ~ % locale -c charmap
LC_CTYPE
UTF-8
```

**Comment by piotr-dobrogost** [comment]
> Wait, is this normal that I don't get the same results depending of how I execute the command on the server?

Yes. In the first case ssh runs the command using `$SHELL -c <command>` which is **non-interactive** shell and in the second case you run it in *normal* shell which almost always is **interactive** shell. These two kinds of shells very often have different settings and environments and that's why you might see the difference.

Btw, the following part of error message doesn't seem to make sense. How come having encoding specified as `UTF-8` in `LC_CTYPE` *specifies the character set "US-ASCII"*?

```
The client-supplied environment (LC_CTYPE=fr_FR.UTF-8) specifies
the character set "US-ASCII".
```
