### ISSUE TITLE
Incorrect report of detached Mosh sessions

### ISSUE THREAD

**Issue by francesquini** [mobile-shell/mosh#859]
mosh-server (mosh 1.2.4a)

Upon connection, Mosh reports detached sessions when none exists:

```
Mosh: You have 2 detached Mosh sessions on this server, with PIDs:
        - mosh [23862]
        - mosh [6859]

~$ kill -9 23862
-bash: kill: (23862) - No such process
~$kill -9 6859
-bash: kill: (6859) - No such process
~$ pidof mosh-server
30609
~$
```

In fact the reported connections existed someday, but since the process id no longer exists does the message make any sense?

**Comment by keithw** [comment]
We believe this bug was fixed long ago; could you please try with Mosh 1.2.6 or the master branch (on the server)?

**Comment by francesquini** [comment]
Indeed that solves the problem. Tks.
