### ISSUE TITLE
Cannot connect to AWS EC2 instance

### ISSUE THREAD

**Issue by andrewrech** [mobile-shell/mosh#863]
Possibly related to #558 or #489, I cannot connect to an AWS EC2 instance with a fully-permissive security group. The instance is reachable over ssh.

When I `mosh user@<ec2 public ip>` I get

> Nothing received from server on UDP port 60001.

On the server, I see:

`netstat -nulp | grep mosh`

> udp        0      0 <AWS private IP>:60001      0.0.0.0:*                           12472/mosh-server

Is this public/private mismatch the issue?

Thinking perhaps this is related to #374, I tried `--bind-server=any` with no success.

I can pass text using `nc` on 60001, so UDP traffic is working. So I am not sure what to try next. Mosh was working several days ago and even when I restore from a known-good AMI, I still cannot connect, adding to my perplexity.

Thanks!

Local: mosh 1.2.6 [build mosh 1.2.6]
Server: mosh 1.3.0 [build mosh 1.3.0]

**Comment by andrewrech** [comment]
This issue resolved using the following steps:

1. Disassociate elastic IP
2. Remove any attached network interfaces
3. Stop, start instance (not restart)
4. Re-attach elastic IP
5. Stop, start instance (not restart)

The cause is still unclear to me, but certainly this seems to be an AWS-specific issue.

**Comment by EmbeddedLinuxGuy** [comment]
Seeing the same issue on AWS. For me the "dissociate elastic IP" option is grayed-out. I did stop the instance, change the IP address, and restart - but no improvement.

**Comment by tkaria** [comment]
@andrewrech Thank you - I didn't have to remove attached network interfaces and it worked just FYI. Though strangely `nc` tests from server to client don't show traffic but mosh still works.

**Comment by InnovativeInventor** [comment]
@andrewtech Thanks for the tip!

I have been able to replicate this on a fresh AWS EC2 instance running `Ubuntu 18.04.2 LTS (GNU/Linux 4.15.0-1044-aws x86_64)`. Associating the EC2 instance with an elastic IP fixed the issue. This shouldn't happen on AWS! No clue why this problem would occur.
