### ISSUE TITLE
Scrollback still not working in 1.3

### ISSUE THREAD

**Issue by vvug** [mobile-shell/mosh#865]
Hello,

https://mosh.org/ says that mosh-1.3 should support a full scrollback buffer. This is not working for me. If I try to scrollback with `Ctrl+PageUp` or `Shift+PageUp` I get the `[5;2~` control sequence printed in the terminal, and nothing happens. I tried to look at the manpage but the word "scroll" is not mentioned, this is a bit confusing.

I'm running mosh-1.3 from Debian sid at both the server and client side.
My terminal is a libvte based terminal, but it doesn't work even with xterm.
Works fine with plan ssh.

Let me know if you need further feedback.
Thanks for this great tool anyway.

Edit: scrolling with the mouse wheel doesn't work either: the command history is scrolled instead.

**Comment by keithw** [comment]
Hello,

We recently switched to versioning using semver, where every functionality update involves an increment of the minor version number. Our upcoming release of "mosh 1.3.0" does not have have scrollback support and does not have the same milestones as what we used to call "mosh 1.3." You can track this issue at https://github.com/mobile-shell/mosh/issues/2 or, if you like, submit code to implement scrollback support.
