### ISSUE TITLE
Trouble getting mosh to work on server with 2 SSH servers

### ISSUE THREAD

**Issue by dmerrick** [mobile-shell/mosh#870]
I am trying to use mosh to connect to a server running two SSH processes. The second SSH process is running inside a Docker container on the server, and mosh is installed on both the host machine and the container.

If I run `mosh servername`, I get into the SSH server running on port 22, and mosh works as expected.

If I run `mosh --ssh="ssh -p2222" servername`, I get a timeout and a message saying:

```
mosh did not make a successful connection to <server-ip>:60001.
Please verify that UDP port 60001 is not firewalled and can reach the server.
```

**Comment by eminence** [comment]
When you started the docker container, did you configure it to allow incoming UDP data?

**Comment by cgull** [comment]
To be clear:
* Do you have an `sshd` listening on port 2222?  Is that running in the container?
* Is the container only using the host's IP address, or does it have its own IP address?
* What do you get if you try `ssh -t -p 2222 servername mosh-server new`?

**Comment by eminence** [comment]
(I'm assuming there is an sshd on port 2222, else the error message from mosh would have been different.  But this is a good thing to confirm)

**Comment by dmerrick** [comment]
> When you started the docker container, did you configure it to allow incoming UDP data?

Let me look into this. We're using AWS Elastic Beanstalk so we don't get access to the docker commands directly

> Do you have an sshd listening on port 2222? Is that running in the container?

Yep, we can SSH in via that port as expected

> Is the container only using the host's IP address, or does it have its own IP address?

Host's IP

> What do you get if you try `ssh -t -p 2222 servername mosh-server new`?

```
➔ ssh -t -p 2222 <servername> mosh-server new

MOSH CONNECT 60001 rflCglfQW8ic84hKB+iEYg
Connection to <servername> closed.
```

**Comment by dmerrick** [comment]
Figured it out, I needed to expose the UDP ports on the container to the host machine.

Elastic Beanstalk doesn't support port ranges, so my config ends up looking like this:

```
➔ cat docker/Dockerrun.aws.json
{
  "AWSEBDockerrunVersion": 2,
  "containerDefinitions": [
    {
      ...,
      "portMappings": [
        {
          "containerPort": 2222,
          "hostPort": 2222
        },
        {
          "containerPort": 60000,
          "hostPort": 60000,
          "protocol": "udp"
        },
        {
          "containerPort": 60001,
          "hostPort": 60001,
          "protocol": "udp"
        },
        {
          "containerPort": 60002,
          "hostPort": 60002,
          "protocol": "udp"
        },
        {
          "containerPort": 60003,
          "hostPort": 60003,
          "protocol": "udp"
        },
        {
          "containerPort": 60004,
          "hostPort": 60004,
          "protocol": "udp"
        },
        ...
      ]
    }
  ]
}
```
