### ISSUE TITLE
mosh shows motd twice on illumos

### ISSUE THREAD

**Issue by pyhalov** [mobile-shell/mosh#872]
After fix for #190 was integrated mosh prints /etc/motd on illumos twice, as this is done by default /etc/profile. We use the following patch to fix it - https://github.com/pyhalov/oi-userland/blob/d6b8c501e991b96ae28b9d98672bcf92fe328ff3/components/shell/mosh/patches/01-do-not-print-motd.patch

**Comment by cgull** [comment]
@pyhalov, could you test #875?

**Comment by pyhalov** [comment]
Tested. Builds, runs, don't show motd twice.

**Comment by timofonic** [comment]
@cgull @pyhalov Why is this still open then?

**Comment by pyhalov** [comment]
Don't know. Closing.
