### ISSUE TITLE
/src/terminal/parseraction.h: PVS-Studio: Potentially incorrect virtual functions override

### ISSUE THREAD

**Issue by khandeliants** [mobile-shell/mosh#876]
Hello,
I have found a bug using PVS-Studio tool. PVS-Studio is a static code analyzer for C, C++ and C#: https://www.viva64.com/en/pvs-studio/

Analyzer warnings:
* [V762](https://www.viva64.com/en/w/V762/) It is possible a virtual function was overridden incorrectly. See first argument of function '==' in derived class 'UserByte' and base class 'Action'. /src/terminal/parseraction.h 139.
* [V762](https://www.viva64.com/en/w/V762/) It is possible a virtual function was overridden incorrectly. See first argument of function '==' in derived class 'Resize' and base class 'Action'. /src/terminal/parseraction.h 158.

A links to [declaration](https://github.com/mobile-shell/mosh/blob/master/src/terminal/parseraction.h#L59) and [implementation](https://github.com/mobile-shell/mosh/blob/master/src/terminal/parseraction.cc#L102) of the 'Action::operator==' function.
A links to implementations of the '[UserByte::operator==](https://github.com/mobile-shell/mosh/blob/master/src/terminal/parseraction.h#L139)' and '[Resize::operator==](https://github.com/mobile-shell/mosh/blob/master/src/terminal/parseraction.h#L158)' functions.

In addition, I suggest having a look at the emails, sent from @pvs-studio.com.

Best regards,
Phillip Khandeliants

**Comment by andersk** [comment]
A linter warning is not the same thing as a bug. In this case, `Action::operator==` is never used—the code could be removed, but it is not causing a problem. Even if it were used, whether that would be problematic would depend on the particular usage.

**Comment by cgull** [comment]
All three `operator==` are used-- try taking them out :)

@khandeliants: I don't see any emails.  Can you link to a report?  Also, could you add commands to `Makefile.am` to run PVS Studio for Mosh?

**Comment by andersk** [comment]
Only the non-virtual `UserByte::operator==` and `Resize::operator==` are used, and yes, I’d tested this claim before making it. Here, I’ll prove it: #877.

**Comment by khandeliants** [comment]
We have spoken about this project with [Keith Winstein](https://github.com/keithw), but recently he hasn’t been answering the e-mails. We can add for you commands in `Makefile.am` for a more comfortable run of PVS-Studio and provide a temporary license key for a week. For more details please contact us at em@pvs-studio.com.

**Comment by keithw** [comment]
@khandeliants Mosh is an open-source project, and we try to do everything in the open. If you find a bug in Mosh, please file a bug here, or if you believe your bug is security-sensitive and requires a confidential disclosure, please use the security contact address on our website (https://mosh.org). If you wish to email the Mosh developers to start a discussion, please use the mosh-devel contact address in our man pages or website.

**Comment by cgull** [comment]
@andersk:  Sorry-- I came to an, erm, low-quality conclusion when editing and testing that code.

**Comment by timofonic** [comment]
@andersk @cgull @keithw What happened to this?

**Comment by cgull** [comment]
I did commit @andersk's change recently.
