### ISSUE TITLE
local buffer for avoiding latency

### ISSUE THREAD

**Issue by shibumi** [mobile-shell/mosh#878]
Hello,
I tried mosh today and I was a little bit disappointed. I have currently a really slow internet connection just between 5-64kbit/s and I thought mosh would have a local buffer or something but seems like it can only do prediction.

Therefore I want to suggest a local buffer for the shell. When I type something I should get instantly feedback without latency and only when I press enter I would wait for the server output or for the command sending to the server.

**Comment by keithw** [comment]
Try `mosh --predict=experimental` -- it does what you propose.

**Comment by keithw** [comment]
(By default, Mosh is pretty cautious about showing predictions if it's not confident that the prediction will eventually be confirmed by the server. But if you're willing to have occasional transient glitches and just want to see *everything* you type, use `--predict=experimental`. Any misprediction will eventually be corrected.)

**Comment by shibumi** [comment]
@keithw 

When I press `CTRL+u` it has still lag about 2-3 seconds...any idea why?

is the `--` part of the command? it's `--predict=experimental` not `--predict=experimental --` right?

**Comment by eminence** [comment]
Right.  `mosh --predict=experimental user@server.com`

**Comment by keithw** [comment]
Mosh doesn't have a local prediction for Ctrl-U to clear the input line, but it will predict for the delete key.
