### ISSUE TITLE
unicode-later-combining.test breaks with tmux 2.4

### ISSUE THREAD

**Issue by ilovezfs** [mobile-shell/mosh#879]
I just noticed that the tmux 2.4 upgrade in Homebrew has broken the mosh build because we run `make check` and the unicode-later-combining test no longer passes:
```
bash-3.2$ cat ./src/tests/unicode-later-combining.log
Running server test baseline.
Post test failed with exitstatus 1
travis_fold:start:unicode-later-combining.test-baseline.tmux.log
%begin 1493450426 228 0
%end 1493450426 228 0
%window-add @0
%sessions-changed
%session-changed $0 0
%layout-change @0 b25d,80x24,0,0,0 b25d,80x24,0,0,0 *
%output %0 \015\015\012\015\012
%window-renamed @0 perl5.18
%output %0 \033[?1049h\033[?1h
%output %0 \033[?5l\033[r\033[0m\033[H\033[2J\033[?25l\033[K\012\033[K\012\033[K\012\033[K\012\033[K\012\033[K\012\033[K\012\033[K\012\033[K\012\033[K\012\033[K\012\033[K\012\033[K\012\033[K\012\033[K\012\033[K\012\033[K\012\033[K\012\033[K\012\033[K\012\033[K\012\033[K\012\033[K\012\033[K\033[1;1H\033[?25h\033[0m\033[?2004l\033[?1003l\033[?1002l\033[?1001l\033[?1000l\033[?1004l\033[?1015l\033[?1006l\033[?1005l
%output %0 \033[?25l\012abc\015\012 ̂\015\012def\015\012\033[?25h
%output %0 @@@ server complete @@@
%output %0 @@@ runtime   0:00.01 @@@\015\012
%output %0 \033[?1l\033[0m\033[?25h\033[?1003l\033[?1002l\033[?1001l\033[?1000l\033[?1015l\033[?1006l\033[?1005l\033[?1049l
%output %0 [mosh is exiting.]\015\012
%output %0 @@@ exitstatus: 0 @@@\015\012
%sessions-changed
travis_fold:end:unicode-later-combining.test-baseline.tmux.log
FAIL unicode-later-combining.test (exit status: 1)
bash-3.2$ 
```

Running the build with tmux 2.3.3 all is well:
```
bash-3.2$ cat ./src/tests/unicode-later-combining.log
Running server test baseline.
PASS unicode-later-combining.test (exit status: 0)
bash-3.2$ 
```

@cgull As a result, I'll need to disable `make check`, at least for the time being until this is sorted out, in the `mosh` formula.

**Comment by keithw** [comment]
We've disabled this test in Git as a workaround. Can you please file the bug against tmux 2.4 and link it here?

**Comment by ilovezfs** [comment]
@keithw done: https://github.com/tmux/tmux/issues/898

**Comment by keithw** [comment]
tmux fixed this bug with https://github.com/tmux/tmux/commit/a2dd7daf4e583ebb9ddc9d7cf09105c43df51399

**Comment by cgull** [comment]
@ilovezfs:  I merged a fix to mosh master that disables the failing test, but only for tmux-2.4.  You should be able to revert Homebrew/homebrew-core@e060fab63b3da59d6f104002b23db040021935ca (which is curiously mis-commented, BTW).

**Comment by ilovezfs** [comment]
Mis-commented?

**Comment by cgull** [comment]
Maybe I've misunderstood the comment.  Was a protobuf version bump (after the tmux version bump to 2.4) the thing that exposed this problem in the first place?

**Comment by cgull** [comment]
And a revert makes no sense, either, the build spec is fine as it is.  I didn't need to make any comment to you in the first place.

**Comment by ilovezfs** [comment]
Yep, this only came to my attention while working on https://github.com/Homebrew/homebrew-core/pull/13021 and we generally do one commit per formula per PR though there can be occasional exceptions.

>And a revert makes no sense, either, the build spec is fine as it is. I didn't need to make any comment to you in the first place.

No problem.
