### ISSUE TITLE
Error while connecting to remote server in ubuntu 16.04

### ISSUE THREAD

**Issue by preejackie** [mobile-shell/mosh#890]
I'm trying to connect to remote server using the command:
mosh -p 8000 username@host_name -i /path/to/ssh/key from root.
But it tells:
/usr/bin/mosh: Could not connect to rostam.cct.lsu.edu: No route to host
ssh_exchange_identification: Connection closed by remote host
/usr/bin/mosh: Did not find remote IP address (is SSH ProxyCommand disabled?)
I'm new to mosh I don't know how to correct it.
Please help me!
Thanks
Praveen v

**Comment by kevinkjt2000** [comment]
Please check any firewall settings to ensure that you have access to port 8000 on rostam.cct.lsu.edu.  And before that make sure that you can at least ping rostam.cct.lsu.edu.

**Comment by Praveenv98** [comment]
Thank you for your reply. I will ask them

**Comment by apps25** [comment]
I am facing same problem and there is no firewall issue.

**Comment by kevinkjt2000** [comment]
Also have the UDP ports open that mosh expects.   I believe mosh-server will start off at 60001.
There is the initial ssh connection, followed by the mosh-client to mosh-server connection.  Both ports need to be open.

**Comment by cgull** [comment]
@apps25, do you need to change the TCP port for the initial SSH connection, or the UDP port for your interactive Mosh session?  The `-p` option sets the UDP port.  To change the SSH port, do something like `--ssh="ssh -p 8000"`.  This is all documented in the `mosh` man page.

@pree-jackie's server in the original comment needs the TCP port changed.

**Comment by apps25** [comment]
@cgull  Hi Thanks for reply, actually I am trying to connect to a server through terminal and getting same error And it is working fine for other. I am new to this and tried all internet suggestion but still the problem is same.

**Comment by kevinkjt2000** [comment]
@apps25 You are saying that you also get a no route to host error?  Can you ping the host?

**Comment by eminence** [comment]
(This is a very old issue, which appears to be not a mosh issue.  Closing)
