### ISSUE TITLE
Consider requiring two-factor authentication for mobile-shell GitHub organization membership

### ISSUE THREAD

**Issue by andersk** [mobile-shell/mosh#892]
GitHub supports [two-factor authentication](https://help.github.com/articles/securing-your-account-with-two-factor-authentication-2fa/) via SMS, TOTP mobile app, or FIDO U2F, and organizations can be [configured to require this](https://help.github.com/articles/requiring-two-factor-authentication-in-your-organization/) of its members. We should consider enabling this in @mobile-shell.

**Comment by eminence** [comment]
To capture a recent discussion in #mosh IRC (paraphrased, not verbatim):

> \<andersk> keithw, what do you think about turning on the 2FA requirement for the mobile-shell organization?
> \<KeithW>  the challenge is what to do about the Travis-CI user (mosh-ci).
> \<KeithW>  I guess I could just add 2FA to mosh-ci as well...  
> \<andersk>   Yeah, there are plenty of TOTP command line clients if you don’t have a better option. 
> \<KeithW>   cgull, are you okay if I enable 2FA on the mosh-ci user and send you the TOTP credentials in encrypted email?   
> \<KeithW>   (Otherwise I'd put it on my personal Yubikeys with U2F, but hard to share the credentials once you do that...) 
> \<cgull>   KeithW: Yes, that'll work just fine.

**Comment by keithw** [comment]
Done.
