### ISSUE TITLE
Odd Unicode replacement characters

### ISSUE THREAD

**Issue by vercas** [mobile-shell/mosh#896]
```
 ⥁  🖩 4.52 📕 80%/1,984MiB  💡 69d 22h  📅 2017-06-14 Wed 🕔 17:09:19

 ⥁  �� 0170 �� 79%/1,984MiB  �� 69d 23h  �� 2017-06-14 Wed �� 12548:13
```
(As mentioned on IRC) This is part of my tmux statusline, and this is rendered [as such](https://s.vercas.com/7q3yc) with Mosh. It should look [like this](https://s.vercas.com/x19k6) instead.  
The last 4 broken characters are emoji, but the first one is not (*AFAIK*).  

Everything else assumes these characters are 1 unit wide, and somehow Mosh sends two invalid/missing characters instead.
This throws off the layout of the whole terminal.

**Comment by javabrett** [comment]
Are you able to share:

* `mosh-server` version
* `most-client` version
* `tmux` version
* `.tmux.conf` in-use
* Any other relevant info - term, locale etc.

**Comment by trysten** [comment]
This issue seems stale. I think it can be closed.
