### ISSUE TITLE
macOS Firewall

### ISSUE THREAD

**Issue by adamyonk** [mobile-shell/mosh#898]
I'm having to completely disable the macOS firewall to allow the UDP connections to connect to it as a mosh-server. I tried to add `mosh-server` / `mosh` to the "Allow incoming connections" list, but it didn't work. Is there some other way to punch a hole in the macOS firewall for the required ports?

**Comment by eminence** [comment]
What version of macOS?

**Comment by cgull** [comment]
As a Mosh developer, it's been a while since I had to do this, but I think a good way to handle this is to do `mosh localhost` on the Mac involved, while you're at the console.  Then you can click on the macOS firewall dialog to approve `mosh-server` permanently.

We should test and document that, maybe.

**Comment by cgull** [comment]
Oh, please forget I said any of that.  It's all wrong.  Sorry.

Just after I finished the last comment, I remembered I do have a Mac here.  No, it doesn't work that way, and yes, I had the firewall turned off.

**Comment by cap10morgan** [comment]
Yeah, this is an insurmountable problem for me too. Every once in awhile I can get it to work, but it never works for long. I have to disable the firewall for reliable mosh connections. I'm using Little Snitch instead now, but I'm not 100% confident that that's a good replacement for the built-in firewall (and even it's developer says it's intended more as a complement to it).

**Comment by Hipomenes** [comment]
Any solution?

**Comment by robinkim28** [comment]
Bump on this - would really like to use mosh without turning off the entire firewall.

**Comment by Hipomenes** [comment]
Mee to.

**Comment by jeremy-w** [comment]
Does the process outlined here not work for you? http://www.chriskrycho.com/2017/set-up-mosh-on-macos.html

**Comment by Hipomenes** [comment]
Did everything in that guide, including tampering with my router to forward the ports. It didn't work for me.

**Comment by cap10morgan** [comment]
@jeremy-w No, it does not. It will sometimes work for a short time, but very quickly stops working again. I was consistently unable to mosh into my Mac after doing this and several other variations of it. The only permanent fix is to disable the macOS firewall altogether.

**Comment by cap10morgan** [comment]
@eminence For me: macOS 10.13.3, but every version I've tried prior to this one exhibited the same behavior.

**Comment by Harwood** [comment]
I'm seeing the same issues, also on macOS 10.13.3. 

> Does the process outlined here not work for you? http://www.chriskrycho.com/2017/set-up-mosh-on-macos.html

I got this to work for a few minutes but unclear why and repeating the same steps has not allowed me to connect.

**Comment by jschwrtz** [comment]
I was having the same problem adding mosh-server through the firewall GUI, but adding mosh-server through the CLI worked for me.

```bash
# i recommend setting up the following alias first
alias firepower='sudo /usr/libexec/ApplicationFirewall/socketfilterfw'

# temporarily shut firewall off
firepower --setglobalstate off`

# add symlinked location to firewall
firepower --add $(which mosh-server)
firepower --unblockapp $(which mosh-server)

# add homebrew location to firewall
firepower --add $(brew --prefix)/Cellar/mosh/1.3.2_2/bin/mosh-server
firepower --unblockapp $(brew --prefix)/Cellar/mosh/1.3.2_2/bin/mosh-server

# re-enable firewall
firepower --setglobalstate on
```

Worked like a charm for me.

**Comment by carloscabanero** [comment]
Just a heads up in case it helps. In this Knowledge Base for Blink seems like people has been successful with mosh-server configuration for OSX. 

https://github.com/blinksh/blink/issues/11

**Comment by adamyonk** [comment]
@jschwrtz you're awesome.

**Comment by adamyonk** [comment]
Since it seems that the FW wants the un-aliased path to mosh-server, I guess that means you'll have to fix this after every upgrade. 😕 Here's a little bash function for that:

```bash
fix_mosh_server() {
  local fw='/usr/libexec/ApplicationFirewall/socketfilterfw'
  local mosh_sym="$(which mosh-server)"
  local mosh_abs="$(greadlink -f $mosh_sym)"

  sudo "$fw" --setglobalstate off
  sudo "$fw" --add "$mosh_sym"
  sudo "$fw" --unblockapp "$mosh_sym"
  sudo "$fw" --add "$mosh_abs"
  sudo "$fw" --unblockapp "$mosh_abs"
  sudo "$fw" --setglobalstate on
}
```

**Comment by jeremy-w** [comment]
What does the off/on fix? (Disabling the firewall for a bit is something I’d prefer to avoid if possible.)
--
Jeremy W. Sherman
http://jeremywsherman.com/

**Comment by adamyonk** [comment]
@jeremy-w I think it's necessary to reload the config. The whole thing takes less than 500 ms.

**Comment by jeremy-w** [comment]
Thanks. I wonder if it does the common daemon trick of treating a signal as a reload poke, like SIGUSR1?
--
Jeremy W. Sherman
http://jeremywsherman.com/

**Comment by jschwrtz** [comment]
I added a [gist](https://gist.github.com/jschwrtz/017b5a13c5cea6f0b6562c162bf67f17) with @adamyonk's `fix_mosh_server` function in a script, a `LaunchDaemon` plist to load it on startup, and an `install.sh` to put it all in the right places. 

it does the trick for me.

**Comment by chadwickboggs** [comment]
adamyonk's function worked for me on ```# uname -a
Darwin Chadwicks-MBP.hsd1.co.comcast.net 17.4.0 Darwin Kernel Version 17.4.0: Sun Dec 17 09:19:54 PST 2017; root:xnu-4570.41.2~1/RELEASE_X86_64 x86_64 i386 MacBookPro14,3 Darwin```

**Comment by yury** [comment]
One more note.
If you want you imac never go to sleep
```
sudo systemsetup -setcomputersleep Never
```

**Comment by wogong** [comment]
@JayTheMarketer This [gist](https://gist.github.com/jschwrtz/017b5a13c5cea6f0b6562c162bf67f17) is dead now. Can you update it? (I can't find it in your gist page)
Many thanks.

**Comment by tjuerges** [comment]
I found the gist [here](https://gist.github.com/sriramkswamy/9cd9887eafb6d4d27a754dcc8d9bd4b1).

**Comment by imyelmo** [comment]
> I found the gist [here](https://gist.github.com/sriramkswamy/9cd9887eafb6d4d27a754dcc8d9bd4b1).

I also used the mentioned gist but I have this issue in system.log:
com.apple.xpc.launchd[1] (com.mosh): Service only ran for 0 seconds. Pushing respawn out by 10 seconds.

Dp you know what is happening?

**Comment by tjuerges** [comment]
> > I found the gist [here](https://gist.github.com/sriramkswamy/9cd9887eafb6d4d27a754dcc8d9bd4b1).
> 
> I also used the mentioned gist but I have this issue in system.log:
> com.apple.xpc.launchd[1] (com.mosh): Service only ran for 0 seconds. Pushing respawn out by 10 seconds.
> 
> Do you know what is happening?

No, sorry.  I do not know.

**Comment by shusso** [comment]
On Mojave this worked for me:
https://github.com/blinksh/blink/issues/11#issuecomment-258649402

note that as I had installed `mosh` with brew so I had to run:
```
sudo /usr/libexec/ApplicationFirewall/socketfilterfw --add /usr/local/bin/mosh-server
sudo /usr/libexec/ApplicationFirewall/socketfilterfw --unblockapp /usr/local/Cellar/mosh/1.3.2_10/bin/mosh-server
```

You can see the full path after issuing the `--add` command by
```
sudo /usr/libexec/ApplicationFirewall/socketfilterfw --listapps
```

**Comment by sajoku** [comment]
> On Mojave this worked for me:
> [blinksh/blink#11 (comment)](https://github.com/blinksh/blink/issues/11#issuecomment-258649402)
> 
> note that as I had installed `mosh` with brew so I had to run:
> 
> ```
> sudo /usr/libexec/ApplicationFirewall/socketfilterfw --add /usr/local/bin/mosh-server
> sudo /usr/libexec/ApplicationFirewall/socketfilterfw --unblockapp /usr/local/Cellar/mosh/1.3.2_10/bin/mosh-server
> ```
> 
> You can see the full path after issuing the `--add` command by
> 
> ```
> sudo /usr/libexec/ApplicationFirewall/socketfilterfw --listapps
> ```

Ah the --listapps helped me a lot. I was running these commands a few times in a row and somehow macOS just inserted them in the firewall configuration. I removed (`--remove /path/to/app`) all the instances  and re-added with the script. Now seems to work.

**Comment by NightMachinary** [comment]
There is a macOS bug that makes this no longer work:
https://developer.apple.com/forums/thread/666222

It seems it has been solved in the beta builds. Just putting it here for future reference.

**Comment by nreilly** [comment]
I've made a short shell script that can be run to re-add it to the firewall as necessary. Thanks to all the previous comments for how to interact with the firewall.


``` sh
#!/bin/sh
## Setup
COMMAND="sudo /usr/libexec/ApplicationFirewall/socketfilterfw"
MOSH=`which mosh-server`
REALMOSH=`readlink -f $MOSH`
FWSTATE=`$COMMAND --getglobalstate`
MOSHCHECK="$COMMAND --listapps"

## Is it in the firewall?
if $MOSHCHECK | grep -q $REALMOSH; then
	echo "$REALMOSH is present."
else
	echo "$REALMOSH is not present. Adding."
        $COMMAND --add $MOSH
fi

## Unblock it
$COMMAND --unblockapp $REALMOSH

## Toggle firewall if it's enabled
case "$FWSTATE"
in
  *enabled*)  echo "Firewall Enabled. Toggling state." 
        $COMMAND --setglobalstate off
        $COMMAND --setglobalstate on
     ;;
  *disabled*)       echo "Firewall Disabled. Not enabling."
     ;;
   *) echo "Unknown response for firewall state."
esac
```

**Comment by corneliusroemer** [comment]
What about adding such a script as a post-link step in the homebrew recipe - maybe specifically gated as `mosh-server` so that it only runs for those who really want to run a mac server.

**Comment by corneliusroemer** [comment]
I created a Stackexchange (Ask Different) Q&A for this problem to increase findability with google: https://apple.stackexchange.com/q/474802/330523
