### ISSUE TITLE
Cannot connect to mosh-server from client

### ISSUE THREAD

**Issue by js1972** [mobile-shell/mosh#901]
I have just installed mosh on my Mac. when I try to connect to it from the Blink client on ipad it fails with the following error:

```
blink> mosh jason@<local ip address address>
Password: <entered>
bash: mosh-server: command not found
Did not find remote IP address
```
However mosh seems to have installed correctly into /usr/local/bin which is on the path and I can manually enter mosh-server on the mac and it starts.

From my ipad I can also connect to that IP via other means.

Any ideas..?

**Comment by js1972** [comment]
Closing as I've found it its a path issue. Even though I can see mosh-server is on *my* path. When the iOS Blink client connects it doesnt seem to get the same path?!? So if I connect and specify the path to the mosh-server - it all works beautilfully...  ;-)

**Comment by andersk** [comment]
Depending on how your dotfiles are set up, it may be the case that a command run directly on the `ssh` command line:

```
ssh HOSTNAME 'echo "$PATH"'
```

gets a different path than a command run within the shell launched by `ssh` with no command line:

```
ssh HOSTNAME
echo "$PATH"
```
