### ISSUE TITLE
mosh 1.3.0 fails to build under FreeBSD/PowerPC

### ISSUE THREAD

**Issue by zi0r** [mobile-shell/mosh#902]
`fails to compile: metadata_lite.h: class 'google::protobuf::internal::InternalMetadataWithArenaLite' does not have any field named 'InternalMetadataWithArenaBase'`

**Comment by cgull** [comment]
What version of FreeBSD?  gcc or clang?

**Comment by cgull** [comment]
Also, can you give the complete chain of error messages?  I'd like to know which file the compile error originates from.

**Comment by zi0r** [comment]
These are fantastic questions.  I'll have to reach out to the original submitter and see if I can grab this information.  I don't actually have any ppc boxes. :)

**Comment by cgull** [comment]
Oh, where are you discussing this?  One of the mailing lists, bugzilla, #freebsd?  I don't see it.

**Comment by zi0r** [comment]
Was caught in a bulk run--see latest commit:
https://www.freshports.org/net/mosh

**Comment by cgull** [comment]
Who might I contact to get a useful build log?  There was no useful info there, unfortunately.

**Comment by achernya** [comment]
I believe this is very obsolete, as there have been multiple releases of mosh since this was filed.
