### ISSUE TITLE
chrome app does not work with ecdsa private key

### ISSUE THREAD

**Issue by auyongcheemeng** [mobile-shell/mosh#903]
Tried with a pem key converted with PuTTY keygen from .ppk to openssh format on a ecdsa key.

Works with a rsa keypair converted with PuTTY using the same method.

version info in chrome app:
v0.4.5
mosh 1.2.6

**Comment by cgull** [comment]
SSH key issues are generally unrelated to core Mosh, which uses an external SSH client.  But you're using the Chrome Mosh client.  That application *does* include an SSH client.  That project is at https://github.com/rpwoodbu/mosh-chrome and you may want to report this issue there.
