### ISSUE TITLE
Mosh + tmux + zsh prompt issues

### ISSUE THREAD

**Issue by basepi** [mobile-shell/mosh#904]
When I connect to my tmux session via mosh, I find that when I hit return until the window needs to scroll, mosh will start outputting my prompt twice, which obfuscates the output of my last command.

Here's a screenshot:

![mc-gdxqelsxoha_bnzo7ou6i7x1e7qesmhsoy9yfxpfqgtunmie78h6y2s8ic6m463z4fxk341nifibdlnbf-n0iq-_zmiwljnqsu6s4bo0f1kr3dmujedqc16ubuu85](https://user-images.githubusercontent.com/702318/28541588-cbd91f66-7076-11e7-9cbf-b88d6df2fe87.png)

Notice the output of the `ls` command before the graphical bug, and the output after.

This does not happen when I attach to my tmux session with ssh.

A `clear` or `reset` fixes it, until it starts scrolling again.

Here is my prompt, if useful: https://github.com/basepi/dotfiles/blob/master/zsh/zsh/includes/prompt

Terminal emulator: iTerm2 3.0.15
Mosh version: 1.3.0
Zsh version 5.1.1

**Comment by cgull** [comment]
What version of tmux are you using?

tmux 2.5 tickled a bug in mosh, which is now fixed in mosh-1.3.2.  This looks like that bug.

**Comment by basepi** [comment]
tmux==2.5, sounds like that's it. I'll look at upgrading mosh and report back.

**Comment by cgull** [comment]
I forgot to mention, you need to upgrade mosh-server on your server.  The client shouldn't matter.

**Comment by basepi** [comment]
Aha! Was a little bit of a trial getting it upgraded on my ubuntu server (the official repo still only has 1.2.5) but got subscribed to the nightlies and it seems to have resolved my issue! Thanks very much.
