### ISSUE TITLE
cut'n'paste from mosh sessions occassionaly produces joined lines

### ISSUE THREAD

**Issue by pasky** [mobile-shell/mosh#911]
Cut'n'pasting from mosh sessions, especially (but not exclusively) with combination with e.g. window switching in screen, causes a situation that some of the pasted lines are not separated by newlines, but whitespaces equivalent to the terminal width. This happens across a wide spectrum of terminals (from iterm2 to xterm). I assume some rendering optimization causes this.

**Comment by cgull** [comment]
I fixed that bug in 1.3.0.  Are you using that version or later on both
client and server?

**Comment by pasky** [comment]
Oh! Sorry for the duplicate then, thanks - I actually didn't use that on either.
