### ISSUE TITLE
"make check" hangs indefinitely in local.test

### ISSUE THREAD

**Issue by sfzhi** [mobile-shell/mosh#914]
Mosh version: 1.3.2.
The test hangs consistently when executing `tmux -C new-session true`, which appears to have been introduced in commit 9f54cc76d2c60d5735a27f2a7973481944a0237a. The same command also seems to hang when run in an interactive shell, but it is actually waiting for user input (exits upon pressing Ctrl-D). This happens with tmux-2.3, tmux-2.5 doesn't seem to have this issue. If the command in question is replaced with `tmux -C new-session true </dev/null`, the tests run successfully.

By the way, I am surprised to see tmux invoked without -S specifying a test socket. This way It will connect to the regular tmux server instance that happens to be already running and is unrelated to mosh tests. What is the point of doing that?

**Comment by cgull** [comment]
Thanks for the bug report.  What OS are you working on?

As for the lack of `-S`... there's no point in doing it that way, I didn't think of the problem.  I'll fix that too.

**Comment by sfzhi** [comment]
The OS is Linux.

**Comment by cgull** [comment]
Ah, but what distribution?  There are so many.

**Comment by sfzhi** [comment]
Home-grown one, based on Linux From Scratch, if that can be called a distribution.

**Comment by sfzhi** [comment]
Apparently, my initial conclusion about the issue depending on the tmux version was incorrect. The same issue occurs with tmux-2.5 as well. What seems to make difference is whether a tmux server (listening on the corresponding socket) is already running. If it isn't, then the command exits immediately. Strangely, I don't observe the same effect on OS X with tmux-2.5 from MacPorts.

**Comment by cgull** [comment]
I can't reproduce this issue on OS X, Raspbian, or FreeBSD.

Does your `.tmux.conf` do something unusual?  That's another issue that's not guarded against.

**Comment by sfzhi** [comment]
You are right. I have one line in tmux configuration that turns out to cause the issue:
`set -g detach-on-destroy off`
I have experimented a bit, trying to revert that setting to the default value ('on') when invoking tmux:
`tmux -C set -g detach-on-destroy on \; new-session true`
It helps to avoid the issue, but it is only safe to use in a dedicated tmux instance, because `-g` changes the option for all sessions, and without `-g` setting the option to 'on' doesn't help to avoid indefinite waiting.

**Comment by cgull** [comment]
I just pushed a commit that should fix your problem (by using `-f /dev/null` to avoid any user config file), and also does `-S`.  Please try it.

**Comment by sfzhi** [comment]
Works fine. Thanks you.
