### ISSUE TITLE
missing or wrong locale

### ISSUE THREAD

**Issue by blub4747** [mobile-shell/mosh#916]
HI guys,

When trying to connect fromL Linux to another via MOSH on specific port
I get the following error message and the connection get's closed

> The locale requested by LANG=en_GB.UTF-8 isn't available here.
> Running `locale-gen en_GB.UTF-8' may be necessary.

> The locale requested by LANG=en_US.UTF-8 isn't available here.
> Running `locale-gen en_US.UTF-8' may be necessary.

> mosh-server needs a UTF-8 native locale to run.

> Unfortunately, the local environment (LANG=en_GB.UTF-8) specifies
> the character set "US-ASCII",

> The client-supplied environment (LANG=en_US.UTF-8) specifies
> the character set "US-ASCII".

> locale: Cannot set LC_CTYPE to default locale: No such file or directory
> locale: Cannot set LC_MESSAGES to default locale: No such file or directory
> locale: Cannot set LC_ALL to default locale: No such file or directory
> LANG=en_US.UTF-8
> LANGUAGE=en_US.UTF-8
> LC_CTYPE="en_US.UTF-8"
> LC_NUMERIC="en_US.UTF-8"
> LC_TIME="en_US.UTF-8"
> LC_COLLATE="en_US.UTF-8"
> LC_MONETARY="en_US.UTF-8"
> LC_MESSAGES=en_US.UTF-8
> LC_PAPER="en_US.UTF-8"
> LC_NAME="en_US.UTF-8"
> LC_ADDRESS="en_US.UTF-8"
> LC_TELEPHONE="en_US.UTF-8"
> LC_MEASUREMENT="en_US.UTF-8"
> LC_IDENTIFICATION="en_US.UTF-8"
> LC_ALL=
> Connection to duck-feet.webhop.me closed.
> /usr/bin/mosh: Did not find mosh server startup message.

I did run both locale commands on both sides eg client and server.
however I still do get the same error message.

Does anybody know how to resolve this problem ?
Thx, blub4747

**Comment by cgull** [comment]
Mosh needs POSIX locale configuration to be installed on the server for the language that you are using.  https://www.mosh.org and #98 have some debug tips.  It appears that neither `en_US.UTF-8` specified by your client machine's configuration, nor `en_GB.UTF-8` specified by your server/login configuration are available. What do you get if you do `ssh duck-feet.webhop.me locale`?

**Comment by blub4747** [comment]
When I run 

> ssh user@duck-feet.webhop.me locale 
I got the following output
locale: Cannot set LC_MESSAGES to default locale: No such file or directory
locale: Cannot set LC_ALL to default locale: No such file or directory
>LANG=en_GB.UTF-8
>LANGUAGE=
>LC_CTYPE="en_GB.UTF-8"
>LC_NUMERIC="en_GB.UTF-8"
>LC_TIME="en_GB.UTF-8"
>LC_COLLATE="en_GB.UTF-8"
>LC_MONETARY="en_GB.UTF-8"
>LC_MESSAGES=en_US.UTF-8
>LC_PAPER="en_GB.UTF-8"
>LC_NAME="en_GB.UTF-8"
>LC_ADDRESS="en_GB.UTF-8"
>LC_TELEPHONE="en_GB.UTF-8"
>LC_MEASUREMENT="en_GB.UTF-8"
>LC_IDENTIFICATION="en_GB.UTF-8"
>LC_ALL=

after that I ran a locale commcand to view the locales on the box

>LANG=en_GB.UTF-8
>LANGUAGE=
>LC_CTYPE="en_GB.UTF-8"
>LC_NUMERIC="en_GB.UTF-8"
>LC_TIME="en_GB.UTF-8"
>LC_COLLATE="en_GB.UTF-8"
>LC_MONETARY="en_GB.UTF-8"
>LC_MESSAGES="en_GB.UTF-8"
>LC_PAPER="en_GB.UTF-8"
>LC_NAME="en_GB.UTF-8"
>LC_ADDRESS="en_GB.UTF-8"
>LC_TELEPHONE="en_GB.UTF-8"
>LC_MEASUREMENT="en_GB.UTF-8"
>LC_IDENTIFICATION="en_GB.UTF-8"
>LC_ALL=

I than ran 'dpkg-reconfigure locales'
to generate the locales set for  'en_US.UTF-8'
and got this message
>de_DE.UTF-8... done
>en_GB.UTF-8... done
>en_US.UTF-8... done

and I error message stop closing my connection.
Thx guys!
