### ISSUE TITLE
Mosh Server Suddenly Exits when Starting Fish Shell

### ISSUE THREAD

**Issue by violetbaddley** [mobile-shell/mosh#918]
I'm experiencing an issue that appears similar to #667, but without any intentionally malicious output. To debug, I'm ssh'ing in and doing

    mosh-server new -v

then, from my Mac,

    MOSH_KEY=<the key> mosh-client <server ip> 60001

I get to bash inside the mosh session, everything works great. Then I go to launch fish (just `fish`), and the debug output instantly logs

    mosh-server: terminalframebuffer.cc:500: void Terminal::Renditions::set_rendition(Terminal::color_type): Assertion `false' failed.

I have the full mosh-server output, as well as a capture of what fish prints, [here][1]. I read out the capture from `less`, so escape characters are expanded and visible (as `ESC`, `^M`, and `^G`). I don't have the technical understanding to debug those control sequences.

I'd really appreciate any guidance you could provide.

---

## Miscellaneous Info

* Mosh-server is mosh-1.3.2-32-g6f9de49 on Arch.
* Mosh-client is mosh 1.3.2 on Mac.
* Fish on the server is version 2.6.0.
* Before each try, I deleted `.config/fish` and `.local/share/fish` to reset the shell to stock configuration.
* Terminal emulator doesn't appear to be relevant (Tested iTerm Build 3.1.beta.6, and macOS Sierra Terminal)

[1]: https://gist.github.com/violetbaddley/bc8b3ee544dd046510d86566f77c64f9

**Comment by keithw** [comment]
Nice catch, thanks! This is also triggered by running `src/examples/termemu` and then `fish` -- a little easier to iterate than `mosh-server`/`mosh-client`.

git bisect points to the first bad commit being 4835dcf5eed93f8dee44e5d1932c38b1cd243d41.

**Comment by keithw** [comment]
Thanks again! Please let us know if this doesn't fix it for you.

**Comment by violetbaddley** [comment]
Works perfectly. To my surprise, all it took was `pacaur -Syy mosh-git`, and that did it!

Thanks, Keith, you're the best!

**Comment by rapha8l** [comment]
Hi,

I'm experimenting the same problem on Void linux version 1.3.2
- if I mosh from 1.3.2 to 1.3.2 and start fish 3.0.2 (Void on both), it disconnects
- if I do it from OpenBSD version 1.3.2 or Debian version 1.2.6, and starts fish 3.0.2, it disconnects
- if  I connect from any of mosh version to an host and run fish version 2.*, then no problem

I don't know if it's a Mosh of a Fish problem (maybe I can open it on fish repo too)

Thanks

**Comment by cgull** [comment]
@rapha8l, this is fixed in Mosh source, but not in an official release yet.  If you can, build Mosh from Github source on your server, that should cure your problem.

**Comment by rapha8l** [comment]
Thanks !
