### ISSUE TITLE
errors during compiling

### ISSUE THREAD

**Issue by blub4747** [mobile-shell/mosh#920]
HI guys,

Iam trying to compile the latest version of mosh on my Debian 9 box.
I first keept getting a error message, like below

> cannot find protoc
on the this link I found a solution for this first issue
http://www.bluebert.info/?p=224

Unable to Compile Protocol Buffers For MOSH

However when I now try to run 'make'
I get a new error message 

> make: *** No targets specified and no makefile found.  Stop.
Thx for any help in advance,
blub4747

**Comment by cgull** [comment]
On Debian/Ubuntu, the simplest thing to do is `apt install build-essential && apt build-dep mosh` (you may need to configure some source repositories for the second command to work.)

**Comment by blub4747** [comment]
Thank you guys for the help!
This time it did compile without any problems!
