### ISSUE TITLE
The issue tracker is too crowded. Why?

### ISSUE THREAD

**Issue by timofonic** [mobile-shell/mosh#922]
Why are there 155 opened issues opened? What's the problem?

**Comment by glensc** [comment]
@timofonic +1 for adding another one!

**Comment by xtaran** [comment]
Send pix—eh—patches! (SCNR)

**Comment by krader1961** [comment]
FWIW, this person opened a similar [fish issue](https://github.com/fish-shell/fish-shell/issues/4348).

**Comment by timofonic** [comment]
@glensc @xtaran Sorry for my dumb and ignorance, you at least not insulted me! 😆 
- I already got replied by two developers of [fish project (click to see the "issue")](/fish-shell/fish-shell/issues/4348), they were both very polite and made me learnt a lot. I recommend you and everyone reading this "issue" to to their "issue" and read it.

**Comment by glensc** [comment]
@timofonic hit the close button in this issue web form (reporter and maintainers can close issues).

**Comment by xtaran** [comment]
@timofonic: Indeed. I read it already and @zanchey definitely reacted better than I did.

I clearly didn't notice that lack of knowledge about how open source projects often work might be the reason why your bug report sounded like a troll to me. Kudos to @zanchey for having found the right way to handle such a bug report.
