### ISSUE TITLE
Exit immediately when mosh with a command of grep

### ISSUE THREAD

**Issue by SeraphRoy** [mobile-shell/mosh#931]
When I run:
`mosh host -- "ls | grep text"`
mosh exists immediately.

When I try
`mosh --no-init host -- "ls | grep text"`
it shows
`execvp: No such file or directory`

But if I do it step by step, namely first `mosh` into the host, then run `ls | grep text`, it doesn't complain.

**Comment by keithw** [comment]
Please try `mosh --no-init host -- sh -c "ls | grep text"` if you really want the output from this short-lived command.

**Comment by eminence** [comment]
See also this issue: [929](https://github.com/mobile-shell/mosh/issues/929)
