### ISSUE TITLE
Compiled and installed sucessfully, but failed to execute mosh

### ISSUE THREAD

**Issue by c02y** [mobile-shell/mosh#935]
- CentOS6.5-32bit

I downloaded mosh-1.3.2.tar.gz file from page https://mosh.org/#getting and followed the instructions to compile and install mosh from the source code. The compilation and installation works smoothly, but when I tried to execute the mosh binary file like `mosh --help` or `mosh`, error messages occurred to me:

    Bareword "AI_NUMERICHOST" not allowed while "strict subs" in use at /usr/bin/mosh line 489.
    Bareword "AI_CANONNAME" not allowed while "strict subs" in use at /usr/bin/mosh line 498.
    Bareword "NI_NUMERICHOST" not allowed while "strict subs" in use at /usr/bin/mosh line 336.
    Bareword "NI_NUMERICHOST" not allowed while "strict subs" in use at /usr/bin/mosh line 261.
    Execution of /usr/bin/mosh aborted due to compilation errors.

**Comment by eminence** [comment]
What version of perl do you have?

**Comment by cgull** [comment]
According to 5ee542c we should now support all the way back to RHEL5, so this is surprising.  Are you using the distribution‘s Perl?

**Comment by c02y** [comment]
@eminence 
> What version of perl do you have?

v5.10.1 (*) built for i386-linux-thread-multi

@cgull 
> Are you using the distribution‘s Perl?

Yes.

**Comment by cgull** [comment]
When building from source, you'll need to supply all the dependencies before Mosh will build and work.  See `fedora/mosh.spec`.   On Centos 6.5, the `protobuf-compiler`, `protobuf-devel`, and `perl-IO-Socket-IP` packages aren't available from standard repos (but you've evidently gotten the protobuf dependencies from somewhere, or you wouldn't have gotten this far).

It seems that the `mosh` script is mistakenly thinking it's imported useful getaddrinfo support and then failing on the subsequent Perl compile step, that's a (minor) Mosh bug.

**Comment by cgull** [comment]
@andersk: on CentOS 6.5, the `eval { Socket::GetAddrInfo->import( '0.22', @gai_reqs ); 1` succeeds but getaddrinfo isn't actually available-- got any insights?

**Comment by andersk** [comment]
You are missing `Socket::GetAddrInfo`. The error message that was intended to clarify this was broken, and I’ve fixed it in #940.

**Comment by cgull** [comment]
@c02y, we think this is an issue with your build environment, and we've fixed things to catch that with a better error at build time.  Please comment/reopen, if that doesn't match your understanding of your problem.

**Comment by c02y** [comment]
@cgull Now, it failed when executing `make` and displayed error message:

    Uncaught exception from user code:
        ./mosh.pl error: requires Perl 5.14 or Socket::GetAddrInfo.

which is expected.

And I realized that I can just install mosh (v1.3.0) using `sudo yum install mosh`.
