### ISSUE TITLE
protobuf: no value named "LITE_RUNTIME"

### ISSUE THREAD

**Issue by ickc** [mobile-shell/mosh#941]
- Compiler: GNU 6.0.4
- protobuf: 3.0.0
- OS: SUSE Linux Enterprise Server 12 (x86_64)
- System: NERSC (Cori)

```bash
make[3]: Entering directory '~/.mosh/mosh-1.3.2/src/protobufs'
  GEN      userinput.pb.cc
userinput.proto:3:23: Enum type "google.protobuf.FileOptions.OptimizeMode" has no value named "LITE_RUNTIME" for option "google.protobuf.FileOptions.optimize_for".
Makefile:590: recipe for target 'userinput.pb.cc' failed
```

I also tried using the Intel compiler but it resulted in a different error.

- [full output of the error](https://github.com/mobile-shell/mosh/files/1448167/log.txt)
- [script used for installation](https://github.com/mobile-shell/mosh/files/1448173/mosh.txt)

**Comment by cgull** [comment]
Mosh on a Cray supercomputer?  That's a new platform for us!

That's surprising-- I've seen issues with `LITE_RUNTIME` but only on very old protobuf versions.  The install script you give us indicates that you're using some site-local scheme for application dependencies.  I would guess that you're somehow getting a bad protobuf configuration.  Mosh's configure script should be able to use `pkgconfig` to find protobuf-- try removing the `protobuf_CFLAGS` and `protobuf_LIBS` defines from your install script.

**Comment by cgull** [comment]
Also, Mosh is availalble as a package on my OpenSUSE install.  If that's truly a standard OpenSUSE distribution install (it might well not be on your hardware platform), you might try simply installing the package with `zypper` or `aptitude`, if you can do that in your environment, or requesting it from the site administrators.

**Comment by ickc** [comment]
> Mosh's configure script should be able to use pkgconfig to find protobuf-- try removing the protobuf_CFLAGS and protobuf_LIBS defines from your install script.

When I don't specify the 2 flags, it complains that it cannot find protobuf. So that's why I added them.

I later tried installing using protobuf 2.6.1 instead, and now protobuf compiles. But I hit with a different error instead:

```bash
make[3]: Entering directory '~/.mosh/mosh-1.3.2/src/frontend'
  CXX      mosh-client.o
  CXX      stmclient.o
  CXX      terminaloverlay.o
  CXXLD    mosh-client
/usr/bin/ld: cannot find -lssl
/usr/bin/ld: cannot find -lcrypto
collect2: error: ld returned 1 exit status
Makefile:416: recipe for target 'mosh-client' failed
```

I suppose since I only need it to be the server but not the client, I can skip compiling the client? What make command should I use to compile the mosh-server only?

P.S. I did request it from the sys. admin., but somewhat predictably they didn't want to do it. I'm trying to convince them to do so though. Do you aware of any HPC facility using mosh? I think since almost by definition HPC users live their life through ssh, mosh could improve the user experience and get things done faster.

**Comment by cgull** [comment]
Do you have the `libopenssl-devel` package installed?  You'll need that installed for the build to succeed.

`configure --disable-client` will get you a server-only build, but I don't think that will help you much for your build issues-- the build requirements are pretty much the same for client and server, I think.

Since NERSC is using the `module` system for software development, and that's not something we can download and install on a test VM, it's a little hard for me to tell exactly what the problem is.  But your problems all seem to be issues with configuration of dependencies, or availability of dependencies, for the Mosh build.

**Comment by cgull** [comment]
One thing that may help is a more complete build log: `make V=1`

**Comment by eminence** [comment]
In the past, I've had problems with setting `protobuf_CFLAGS`, but found that setting `PKG_CONFIG_PATH` or `PKG_CONFIG_LIBDIR` sometimes works better in cases when .pc files seem to be in non-standard locations.  

That situation doesn't necessarily appear to be the situation here, but it may be something to try.

**Comment by cgull** [comment]
Ah, it looks like you may not have pkg-config available.  I'm also guessing that OpenSSL may also be a module, and so not in the standard system locations.  You may want to use pkg-config (though it doesn't seem to be in the modules listing for cori); if you can't use it, you can set the `CRYPTO_CFLAGS` and `CRYPTO_LIBS` flags as documented by `configure --help`.

This really is an unusual system configuration; you might want to get some help from someone with experience building software on NERSC machines.

**Comment by ickc** [comment]
I just check,

```bash
# pkg-config --version
0.28
```

I'll dig more into `libopenssl-devel` and `make V=1` soon. Thanks.

**Comment by cgull** [comment]
@ickc: were you ever able to resolve this, and if so, how?

**Comment by ickc** [comment]
I tried again with `--disable-cilent`, `V=1`, and it failed. (I tried combinations of different compilers and protobuf.) And the verbose output shows that the failing of `mosh-server` is also related to protobuf. Some typical stderr is like `/usr/common/software/protobuf/3.0.0/hsw/intel/include/google/protobuf/repeated_field.h:1407: undefined reference to `google::protobuf::internal::LogMessage::~LogMessage()'`.

GitHub don't allow me to upload a file again, so I put the [stderr in an external link](https://www.dropbox.com/s/3imdkwjpx3g0xxh/log.txt?dl=0).

After contacting with NERSC admin., they said,

> regarding the state of SSH at NERSC, what is installed on the Crays may look like "traditional" SSH to the user, but in fact it is a highly modified version of SSH instrumented with features to improve both security and performance. The following page provides more information:
>  
> http://www.nersc.gov/users/accounts/user-accounts/computer-security/instrumented-ssh/

I guess there's nothing more can be done, may be we should just close this issue?

**Comment by cgull** [comment]
Sorry to not answer earlier, I was a bit busy this week.

It's still hard for me to guess what might be going on, but I have one last idea-- perhaps your original problem is something to do with the `LITE_RUNTIME` option, after all.  I think our Configure script may be a bit sloppy in selecting the right libraries here.  Try deleting all lines of the form
`option optimize_for = LITE_RUNTIME;` in src/proto/*.proto, then clean and rebuild with the NERSC module-build script.

**Comment by jlehtira** [comment]
Hi hi! Another cray user here, I found this thread by googling for the error. I compiled protobuf 3.5.1 myself to my own location ($HOME/opt), and tried to install mosh 1.3.2 from there (by doing export PKG_CONFIG_PATH=$HOME/opt/lib/pkgconfig:$PKG_CONFIG_PATH). I hit the same error in the same location.

I tried removing all optimize_for lines in src/protobufs/*.proto, make clean, make, then I hit 

"make[4]: Entering directory '/cray_home/altix/jlehtira/opt/INSTALL/mosh-1.3.2/src/protobufs'
  CXX      userinput.pb.o
In file included from userinput.pb.cc:3:0:
userinput.pb.h:16:2: error: #error This file was generated by an older version of protoc which is
 #error This file was generated by an older version of protoc which is
  ^
userinput.pb.h:17:2: error: #error incompatible with your Protocol Buffer headers. Please
 #error incompatible with your Protocol Buffer headers.  Please
  ^
userinput.pb.h:18:2: error: #error regenerate this file with a newer version of protoc.
 #error regenerate this file with a newer version of protoc.
  ^
userinput.pb.cc:7:45: fatal error: google/protobuf/wire_format_inl.h: No such file or directory
 #include <google/protobuf/wire_format_inl.h>"

**Comment by andersk** [comment]
@jlehtira The `protoc` binary in your `PATH` must match the protobuf library found through `PKG_CONFIG_PATH`. Make sure that `$HOME/opt/bin` is early enough in your `PATH` such that `which protoc` returns `$HOME/opt/bin/protoc` rather than some other `protoc`.

**Comment by ickc** [comment]
Hi, just to follow up. I now can install mosh on NERSC. (But I'm hitting another problem about UDP ports. Asking NERSC staffs now.)

In short, I can finally compile mosh by first installing [linuxbrew](http://linuxbrew.sh), and then run `brew install mosh`. I think I have tried it last time but it didn't work. Now it does.

Background: linuxbrew is a fork of homebrew for macOS, for installing libraries entirely without sudo. So it is very suitable for installing stuffs on servers that you don't have sudo rights.

**Comment by ickc** [comment]
I now can run mosh on NERSC with a special permission to by pass the load balancer. We are studying the security implications of using mosh instead of ssh, so for now it's not for every users yet.

**Comment by mkhorton** [comment]
@ickc let us know if it becomes available for more users, trying to ssh in from a plane, would be useful :)

**Comment by ickc** [comment]
Can you try `ssh USERNAME@cori01-224.nersc.gov` and see if you can get in? If so I can provide you more instructions.

**Comment by mkhorton** [comment]
@ickc, nope that doesn't work, it doesn't accept my password+OTP. Thank you though!

**Comment by ickc** [comment]
Have you used `sshproxy`? If so, how about `ssh -i ~/.ssh/nersc $USER@cori01-224.nersc.gov`?

If these doesn't work, it probably because it requires a special permission. You may try to open a NERSC ticket specifically mention the use of mosh. Currently using mosh on NERSC by passes the load-balancer (on the 12 log in nodes.) The connections probably will be specifically monitored to study its security implications.

Ask me again if you managed to get approval from them. I think it could help towards an official support of mosh on NERSC if more people tests it.

Since you might not have time to get all these set up in time before your flight, you might also try to have an intermediate server somewhere and use that to "step into" NERSC. I sometimes do this when using blink on iOS when I don't want the trouble of entering password+OTP. mosh into a computer with sshproxy then generates the key then ssh into NERSC and start a tmux session (or even nested tmux.) This is sometimes useful as the intermediate server and tmux keeping the session alive and you can jump right back after reconnect. (zerotier can be helpful to set up a private network between your non-public facing computers.)
