### ISSUE TITLE
mosh-server incorrectly reports detached session in utmp/wtmp

### ISSUE THREAD

**Issue by cgull** [mobile-shell/mosh#942]
In #559, @mojoTX reports that mosh-server reports sessions as detached when they aren't really.  I've verified this.  This is almost certainly fallout from the recent changes to add syslog.

**Comment by mojoTX** [comment]
If I get some free time soon, I will take a look at your recent changes to `src/frontend/mosh-server.cc`, to see if I can identify the problem.

**Comment by mojoTX** [comment]
@cgull and @amishHammer: It appears to have been a simple typo in commit `ab31b0f`.

**Comment by mojoTX** [comment]
This is definitely fixed in pull request #944.

**Comment by eminence** [comment]
@cgull  in #944 reported successful testing, so I think this issue can now be closed.
