### ISSUE TITLE
--local can't be used with --server if it contains spaces

### ISSUE THREAD

**Issue by TomiBelan** [mobile-shell/mosh#946]
As of mosh 1.3.2, this works:

```
$ mosh --server='env foo=bar mosh-server' 127.0.0.1
```

But this doesn't:

```
$ mosh --local --server='env foo=bar mosh-server' 127.0.0.1
Can't exec "env foo=bar mosh-server": No such file or directory at /usr/bin/mosh line 390.
Cannot exec env foo=bar mosh-server: No such file or directory
/usr/bin/mosh: Did not find mosh server startup message. (Have you installed mosh on your server?)
```

The error message points to line 390: `exec( $server, @server );`

In the nonlocal case, `$server` is not used as the program filename, but as part of the shell command that runs on the remote side: `my @exec_argv = ( `(...)`, $ssh_connection . "$server " . shell_quote( @server ) );`

I don't know Perl, but would something like this work? `exec( "$server " . shell_quote( @server ) );`

**Comment by andersk** [comment]
That seems reasonable. Are you interested in testing it and submitting it as a PR?

**Comment by TomiBelan** [comment]
Sorry, but could I ask you to test and submit it? I don't have the dependencies for that set up here and I don't have enough time right now.

**Comment by cgull** [comment]
@TomiBelan:  I'm curious, what is your use case for this?  Are you just experimenting with Mosh locally, or do you have some particular reason for using `--local`?  I don't have any objection to fixing it, I'm just wondering what we're fixing it for.

I originally added `--local` for testing and development, and it's a bit of a hack.

I'll also mention that this problem (and other similar ones) can also be solved with a wrapper script

**Comment by TomiBelan** [comment]
Good question - my use case is really weird. I'm not using `--local` right now, and I don't know if I'll use it after this is fixed. I found this bug when I was looking into ways to simplify my strange hacky custom tunnel.

I have a strange host which I can ssh to, but which I can't directly UDP to. Instead I have a tunnel which port forwards a range of UDP ports between localhost and that host. So `mosh` must ssh to that host, but `mosh-server` must listen on 127.0.0.1 and `mosh-client` must connect to 127.0.0.1.

This would be trivial if mosh supported `--experimental-remote-ip=127.0.0.1`. Do you think I should submit a feature request for that (or a PR when I have more time)? Honestly, I'm not sure anyone other than me needs it - it might just be feature bloat. At least this issue is a bug with a one line fix.

Right now that option doesn't exist, but you can hack around that in various ways by setting `--ssh` and/or `--server` to various wrapper scripts - I'm sure you can imagine. I found this bug when I tried to do `mosh --local --server='ssh -n -tt myhost mosh-server' 127.0.0.1`. But again, even with this bug fixed that might not be the best hack to use.

**Comment by cgull** [comment]
Yes, this is a pretty odd use case, where you have a non-UDP tunnel running with endpoints on localhost at both client and server.  You might consider writing a replacement for the `mosh` script that does what you need-- for a single fixed host like yours, it's not too difficult.  Essentially your script would ssh to your remote host to start `mosh-server -b 127.0.0.1`, capture the `MOSH IP <addr> <port>` if needed, start your UDP proxy if needed, then start mosh-client with the IP address and port of your proxy.  In any case, we'll fix the original issue here, there's no reason not to, so you'll have that available too.
