### ISSUE TITLE
FreeBSD pasting freezes/locks mosh

### ISSUE THREAD

**Issue by krismach** [mobile-shell/mosh#953]
I've tried mosh on latest FreeBSD 11.1 from ports and also compiled it from git, and when I paste large amount of text (like a page or two) it will accept about 40 characters and freeze and lose connection. It will display "mosh: Commands: Ctrl-Z suspends, "." quits, "^" gives literal Ctrl-^ (1:25 without contact.)"

SSH on same server doesn't have this issue.

I also tried mosh on latest Debian and didn't have an issue either, was able to paste as much as I wanted.

**Comment by eminence** [comment]
What version of mosh precisely?  (On both client and server)

Is FreeBSD your client or server?  Is Debian your client or server?

**Comment by krismach** [comment]
FreeBSD ports mosh:
mosh-server (mosh 1.3.2) [build mosh 1.3.2]

FreeBSD git compiled:
mosh-server (mosh 1.3.2) [build mosh-1.3.2-58-gd4ce0d4]

Debian from apt:
mosh-server (mosh 1.2.6) [build mosh 1.2.6]

And I tried on client side Windows MobaXterm 10.5:
mosh-client (mosh 1.2.4)

And Windows Chrome latest mosh extension:
seems to be mosh 1.2.6

**Comment by cgull** [comment]
We've had problems with FreeBSD ptys in the past, but this looks more like an MTU issue.  Is this session over VPN or some other kind of path with less than 1500 byte MTU?

If you can, please try this with a tmux session on your server, with an ssh session and a Mosh session connected to it.  Then paste your text into the Mosh session.  If the ssh session shows the paste succeeding as you'd expect, but the Mosh session does not, then this is almost certainly an MTU issue on your server->client path.  If the ssh session shows an incomplete paste happening, then it's probably an MTU issue on your client->server path, but that is less certain.

Also, it's possible `mosh-server` is crashing.  Can you check and see if the login session and/or mosh-server process is still around after one of these failed pastes?

**Comment by krismach** [comment]
No, it's a regular connection, Windows reports 1500 MTU.

Yes I tried through tmux and with ssh it works and with mosh it doesn't. I also tried a fresh default freebsd11.1 and installed mosh from pkg, same result. I then spun up a freebsd instance on google cloud and installed mosh from pkg, same result.

And yes, mosh-server and the login session process stay around after the client is disconnected.

I also tried to connect from two different ISPs and also from phone using juicessh which has mosh client. Same results.

I don't think the issue is with network, because connecting to debian server works fine on the same network, while freebsd doesn't. So I think it's a freebsd issue.

**Comment by cgull** [comment]
I use Mosh on FreeBSD servers every day.  I tried to reproduce the issue on about 4 different FreeBSD installs on a variety of networks and couldn't.  Your symptoms do match up with MTU issues fairly well.

Two more things to try:
* Connect to the FreeBSD server with Mosh.  Start tmux.  Create two shell sessions in mosh.  In the first one, paste a large text that makes Mosh hang.  Then type the key sequence to switch to the other shell session.  If your Mosh session comes to life on the empty window, and it freezes again when you switch back to the first session, then it's an MTU issue, or something else like it causing packet loss.
* If you can, do a packet capture (`tcpdump`, `Wireshark` or similar) on your client machine while you paste into Mosh and make it hang, and report its output here.

If it does turn out to be an MTU issue, then the question becomes "Why FreeBSD and not Debian?"  Mosh doesn't get much direct control over that and should behave quite similarly on FreeBSD and Linux.  We would then have to look at your machines' local network configuration and general connectivity to figure out why one works and the other doesn't.  I do notice you are using an older version of Mosh on the Debian machine, but I would expect the older version to behave badly, not the newer one.

**Comment by cgull** [comment]
@krismach, were you able to resolve this?

**Comment by krismach** [comment]
Yes you were right, it was an MTU issue. It was caused by being behind double nat on a pppoe connection. Getting rid of the double nat, and being on just nat on pppoe solved the problem.
