### ISSUE TITLE
Mosh release with 24-bit color support

### ISSUE THREAD

**Issue by bchallenor** [mobile-shell/mosh#961]
It looks like 24-bit color support was [added last October](https://github.com/mobile-shell/mosh/commit/6cfa4aef598146cfbde7f7a4a83438c3769a2835), but as far as I can tell, there is no release that includes this commit.

Would it be possible to make such a release?

**Comment by nanzhong** [comment]
Curious, is there a process or plan that mosh follows for cutting releases?

**Comment by sbromberger** [comment]
It'd be great to have a formal release with this capability. Thanks.

**Comment by wookayin** [comment]
Bring another attention! Looking forward to mosh release that contains this feature.

**Comment by ergusto** [comment]
Just spent the past hour tearing my hair out over this, rebuilding vim manually a few times. Highly anticipated feature.

**Comment by oblitum** [comment]
Any update on this? It has been some years since the last release.

**Comment by sbromberger** [comment]
Folks - 24-bit color works. You need a recent source build of mosh-server.

**Comment by benley** [comment]
I hate to "me too" things, but this is becoming an increasingly important feature for me as well.  I would really appreciate a new release with 24-bit color support, as would many others.

**Comment by sbromberger** [comment]
If you build master from source, it'll give you 24-bit color. I agree that a release would be nice, but there are ways to get it now if you're impatient (as I was).

**Comment by dmitryzykov** [comment]
+1 for a new release with 24-bit color included.

Meanwhile I have to build mosh-server from sources on my ubuntu 19.10 servers.
Even [PPA from Keith Winstein](https://launchpad.net/~keithw/+archive/ubuntu/mosh-dev) doesn’t provide builds for latest ubuntu release.

my commands how i built ( maybe will be helpful for someone ) 
```bash
apt install debhelper  autotools-dev protobuf-compiler libprotobuf-dev dh-autoreconf pkg-config libutempter-dev zlib1g-dev libncurses5-dev libssl-dev bash-completion locales
git clone https://github.com/mobile-shell/mosh
cd mosh
./autogen.sh
./configure
make
make install
```

**Comment by jpincas** [comment]
Repeating the above steps doesnt work for me:
```checking whether protoc matches protobuf... no
In file included from conftest.cpp:73:
conftest.pb.h:10:10: fatal error: google/protobuf/port_def.inc: No such file or directory
   10 | #include <google/protobuf/port_def.inc>
      |          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
compilation terminated.
configure: error: in `/home/jon/src/github.com/mobile-shell/mosh':
configure: error: Could not build output generated by protoc (/usr/local/bin/protoc).
Check that protoc matches the installed protobuf headers and libraries.
See `config.log' for more details```

**Comment by broander** [comment]
For anyone coming here now, dmitryzykov directions work.  I rebuilt mosh on my local system and a remote server using his directions and now I have true-color support!   Very helpful, now I can run solarized in vim everywhere and not have it be very ugly.

**Comment by hozza** [comment]
Thanks for the 24bit color confirmation @broander - compiling is certainly an option, but a published version would be preferable for most people, as they could install straight form a repo.

Looking into this a little more It looks like there's not been a new mosh version since July 2017!

I had a look at the main contributors to mosh, @keithw was most active in 2012/2013 and published the last version in 2017, @cgull has been active in 2016/2017/2018 and @andersk most recently.

Could any of you maintainers consider publishing a new version? It's been quite some time and all the extra work you guys have done since 2017 would be greatly appreciated in a new version which could be added to Linux repos too!

**Comment by broander** [comment]
@hozza completely agree that revving to a new version would be great, so new features like true color can end up win the Linux repos.  Maintainers, there's probably several of us that would be happy to help you with the work it'll take to rev to a new version.

**Comment by HackAttack** [comment]
If you’re using Homebrew, `brew install --HEAD mosh` works.

**Comment by wookayin** [comment]
@eminence @keithw Can you please make a release anytime soon? Mosh hasn't had any release since 2017.

**Comment by eminence** [comment]
Closing in favor of #1115
