### ISSUE TITLE
Licencing

### ISSUE THREAD

**Issue by henri** [mobile-shell/mosh#963]
The GNU GPL is excellent. However, I am curious to know if you would allow the people at Panic who offer a non-free software package called Prompt to use your code. Perhaps, they could licence it via an alternative licence? I understand if this is not a path your team is not willing to go down. Just wanted to put it on your radar. Otherwise an open source project like blink will be the way to go on iOS devices. If you do consider offering a seperate licence to Panic you can reach out to them at : http://panic.com

Feel free to close this issue without a reply. I just wanted to make sure it is on the radar.

Thanks.
H

**Comment by keithw** [comment]
Thanks for your interest! We have heard from Panic about this as recently as last August -- it's not like they don't know how to reach us. I'm not sure we could relicense Mosh even if we wanted to (we have had a lot of contributors over the years), but I also haven't heard a great argument for giving one company special treatment. If we had, I doubt there would now be FOSS ports of Mosh for essentially every platform of interest.
