### ISSUE TITLE
Clips?

### ISSUE THREAD

**Issue by dwest100** [mobile-shell/mosh#968]
Hi,
Just purchased the app. I have several iPads in different locations. Is there some means to save frequently used command strings? If so, do they sync through iCloud? I can’t seem to find this functionality.
Thanks!

**Comment by eminence** [comment]
Hi.  There is no official mosh app, so I'm not sure what exactly you purchased.  But any questions about the iOS app you're using should be directed at their help system, as we can't support apps that we don't control

**Comment by carloscabanero** [comment]
Hi @dwest100, if you refer to Blink, the proper issue tracker is on https://github.com/blinksh/blink/issues. We can help you out there.

**Comment by dwest100** [comment]
Geeez! Sorry! I followed a link (I thought) to the blink shell app. My apologies!
