### ISSUE TITLE
Does someone have a docker image for mosh?

### ISSUE THREAD

**Issue by itfanr** [mobile-shell/mosh#972]
My OS is Centos7.2 and  I donot like to download the dependencies to install mosh.

**Comment by keithw** [comment]
You might just install the RPM package from EPEL. (https://fedoraproject.org/wiki/EPEL)

**Comment by itfanr** [comment]
@keithw  Do you mean http://dl.fedoraproject.org/pub/epel/7/x86_64/Packages/m/ ?

But it's hard for my PC to access the Internet to install the EPEL .

**Comment by eminence** [comment]
Here is a very basic Dockerfile that will build the latest version of mosh from git sources:

```dockerfile
FROM centos:7
RUN yum -y install git perl openssl-devel ncurses-devel protobuf-compiler protobuf-devel libutempter-devel zlib-devel && yum -y groupinstall 'Development Tools'
RUN git clone --depth=1 https://github.com/mobile-shell/mosh
WORKDIR /mosh
RUN sh autogen.sh && ./configure && make && make install
RUN mosh-server --version
```

**Comment by itfanr** [comment]
@eminence  Thank you very much !
