### ISSUE TITLE
Docker-Machine Support

### ISSUE THREAD

**Issue by brandontamm** [mobile-shell/mosh#975]
I am searching for a solution to connect to docker-machine's from a mobile iOS device.

The persistent connections would be necessary.

There is also one other thing that I am wondering.

To keep the SSH keys in sync for my docker-machines across two different desktops, I have to sync the ~/.docker folders. The configurations and ssh keys are there by default for desktop. Does the mosh application have a way to manage these on an iOS device? I understand if this would have to be a manual copy and may take some fileshare applications. I am able to sync that folder via the iCloud Drive if somehow this mosh application would be able to select the keys from iCloud folder?

Any ideas for current and/or future functionality if current is not adequate to meet these requirements?

**Comment by achernya** [comment]
It's not clear what is being suggested/asked-for here. mosh does not have any facilities for synchronizing files, nor does mosh have any special iOS or iCloud support.
