### ISSUE TITLE
m4 Directory not found when running autogen

### ISSUE THREAD

**Issue by brandonmanley** [mobile-shell/mosh#976]
So I'm trying to download the mosh git on a remote server. I started to build protobuf but it seems as though when I run autogen.sh it says that the directory "m4" is not found. However when I check the directory is clearly there. Any ideas?

**Comment by eminence** [comment]
Can you show us the full commands you ran, and their output?   And also tell us what type of machine you are on?  (Linux, OSX, Windows, etc)

**Comment by andersk** [comment]
Closing since we can’t help without the requested information. We can reopen if you provide it.
