### ISSUE TITLE
conflict work mosh and editor ConEmu

### ISSUE THREAD

**Issue by rdbox** [mobile-shell/mosh#977]
## INFO
**mosh 1.2.5 [build mosh 1.2.5]**
**Ubuntu 16.04.4 LTS**

I put the perfect mosh shell, but I got a problem with scrolling when I edit the file in the vim editor.
here are examples of gif

![gugxo](https://user-images.githubusercontent.com/18515862/40281938-fcb20836-5c99-11e8-995b-6c90efbac461.gif)

as seen for example, everything is very terrible, when you try to edit a file in the vim editor. all the text on each other goes. And it's not possible to use your mosh

through ssh this of course I do not have.
You probably thought I tried using screen. Yes I tried the problem exactly the same.

I need your help!!!
please

**Comment by eminence** [comment]
It looks like vim isn't correctly entering alternate screen mode or something.

A few questions:
* Is mosh 1.2.5 running on both the client and server?  
* What is your local terminal?
* What is the value of $TERM within your mosh session?
* Do you see any problems with other full-screen apps (like emacs or elinks)?

**Comment by rdbox** [comment]
- yes mosh works for me both on the server and on the client the same version
- I do not know exactly but I think it's xterm
- On the server, the variable $ TERM shows xterm. And on the client shows cygwin
- now checked in the emacs editor is also a similar problem

**Comment by achernya** [comment]
ConEmu is not a very good terminal emulator. Try using Windows Terminal
