### ISSUE TITLE
Cannot connect (MacOSX client, Debian server)

### ISSUE THREAD

**Issue by ErikDeBruijn** [mobile-shell/mosh#98]
Hi,

I just wanted to say that this is a long awaited feature... a client that is robust to roaming around, as many of us do.

I compiled the recent version from git for the server (a Debian Squeeze/sid machine) and am using the MacPorts version of mosh.

When running It I get the following error:
 # mosh root@server4
 mosh requires a UTF-8 locale.
 Connection to server4 closed.
/opt/local/bin/mosh: Did not find mosh server startup message.

I fiddled around with my client's /etc/ssh_config but this didn't help. What can I do to resolve this and start using mosh?

**Comment by tclh123** [comment]
just make `LANG` same between server and client.

**Comment by deiu** [comment]
Here is a fix in case your Debian-based server complains about locales:
```
bash: warning: setlocale: LC_ALL: cannot change locale (en_US.UTF-8)
```

You need to generate the UTF-8 locales with these two commands:
```
sudo locale-gen en_US.UTF-8
sudo dpkg-reconfigure locales
```

**Comment by ovizii** [comment]
Slightly despairing here: 

I have 2 servers I connect to regularly from my Macbook and only one works with mosh. 
I invoke both with an alias like this: 
alias mike='mosh --ssh="ssh -p xxxx" --server="LANG=$LANG mosh-server" root@162.xxx.xxx.xxx'
The non-working one gives: 
Connection to 162.xxx.xxx.xxx closed.
/usr/bin/mosh: Did not find mosh server startup message.

a) working server
(3:564)# locale
LANG=en_GB.utf8
LANGUAGE=en_GB.utf8
LC_CTYPE="en_GB.utf8"
LC_NUMERIC="en_GB.utf8"
LC_TIME="en_GB.utf8"
LC_COLLATE="en_GB.utf8"
LC_MONETARY="en_GB.utf8"
LC_MESSAGES="en_GB.utf8"
LC_PAPER="en_GB.utf8"
LC_NAME="en_GB.utf8"
LC_ADDRESS="en_GB.utf8"
LC_TELEPHONE="en_GB.utf8"
LC_MEASUREMENT="en_GB.utf8"
LC_IDENTIFICATION="en_GB.utf8"
LC_ALL=en_GB.utf8

b) non-working server
root@server:~# locale
LANG=en_GB.UTF-8
LANGUAGE=
LC_CTYPE="en_GB.UTF-8"
LC_NUMERIC="en_GB.UTF-8"
LC_TIME="en_GB.UTF-8"
LC_COLLATE="en_GB.UTF-8"
LC_MONETARY="en_GB.UTF-8"
LC_MESSAGES="en_GB.UTF-8"
LC_PAPER="en_GB.UTF-8"
LC_NAME="en_GB.UTF-8"
LC_ADDRESS="en_GB.UTF-8"
LC_TELEPHONE="en_GB.UTF-8"
LC_MEASUREMENT="en_GB.UTF-8"
LC_IDENTIFICATION="en_GB.UTF-8"
LC_ALL=

LOCAL MACBOOK:
shiny:~ ovi$ locale
LANG="en_US.UTF-8"
LC_COLLATE="en_US.UTF-8"
LC_CTYPE="UTF-8"
LC_MESSAGES="en_US.UTF-8"
LC_MONETARY="en_US.UTF-8"
LC_NUMERIC="en_US.UTF-8"
LC_TIME="en_US.UTF-8"
LC_ALL=

Any ideas?

**Comment by keithw** [comment]
What version of mosh-client is on the client, and what versions of mosh-server are on the servers?

If you are running mosh 1.2 or later everywhere, we don't think you should override server to try to set LANG -- especially if you're not getting our verbose locale-related diagnostic and error message.

**Comment by ovizii** [comment]
Local MACBook: mosh-server (mosh 1.2.4)
a) working server: mosh-server (mosh 1.2.3)
b: non-working server: mosh-server (mosh 1.2.3)

So what does your reply exactly mean? My local config seems to work for server a) but not b)

**Comment by keithw** [comment]
I don't think your problem has anything to do with locales, and I don't think you should use the "--server=" argument that you're using.

What happens if you just run `ssh -t -p xxxx root@SERVER mosh-server` for the broken server?

**Comment by ovizii** [comment]
sshpass -p 'xxx' ssh -p2222 root@162.xxx.xxx.xxx mosh-server
LANG=
LANGUAGE=
LC_CTYPE="POSIX"
LC_NUMERIC="POSIX"
LC_TIME="POSIX"
LC_COLLATE="POSIX"
LC_MONETARY="POSIX"
LC_MESSAGES="POSIX"
LC_PAPER="POSIX"
LC_NAME="POSIX"
LC_ADDRESS="POSIX"
LC_TELEPHONE="POSIX"
LC_MEASUREMENT="POSIX"
LC_IDENTIFICATION="POSIX"
LC_ALL=
mosh-server needs a UTF-8 native locale to run.

Unfortunately, the local environment ([no charset variables]) specifies
the character set "US-ASCII",

The client-supplied environment ([no charset variables]) specifies
the character set "US-ASCII".

**Comment by keithw** [comment]
Ok, now we're getting somewhere. I'm confused why you didn't see a locale-related error message originally. Did you really **only** get the two lines you printed? "Connection to 162.xxx.xxx.xxx closed.
/usr/bin/mosh: Did not find mosh server startup message."?

How about running?

`ssh -t -p xxxx root@SERVER mosh-server -l LANG=en_GB.UTF-8`

**Comment by keithw** [comment]
Also please try running:

`ssh -p xxxx root@SERVER perl -e 1`

and let us know the output (if any).

**Comment by ovizii** [comment]
yes, only those 2 lines:

shiny:~ ovi$ mosh --ssh="ssh -p xxxx" --server="LANG=$LANG mosh-server" root@162.xxx.xxx.xxx
Connection to 162.xxx.xxx.xxx closed.
/usr/bin/mosh: Did not find mosh server startup message.
shiny:~ ovi$

The next suggestion resulted in weird results:
shiny:~ ovi$ ssh -t -p xxx root@162.xxx.xxx.xxx -l LANG=en_GB.UTF-8
LANG=en_GB.UTF-8@162.xxx.xxx.xxx's password:
Permission denied, please try again.
LANG=en_GB.UTF-8@162.xxx.xxx.xxx's password:
Permission denied, please try again.
LANG=en_GB.UTF-8@162.xxx.xxx.xxx's password:
Permission denied (publickey,password).
shiny:~ ovi$

Why is it not using root as user name?

shiny:~ ovi$ ssh -p xxx root@162.xxx.xxx.xxx perl -e 1
shiny:~ ovi$

no output.

**Comment by keithw** [comment]
Please double-check the command you're running. It looks like you omitted the "mosh-server".

**Comment by ovizii** [comment]
sorry, my bad, I was typing not copy/pasting and missed it.

shiny:~ ovi$ ssh -t -p xxxx root@162.xxx.xxx.xxx mosh-server -l LANG=en_GB.UTF-8

The programs included with the Debian GNU/Linux system are free software;
the exact distribution terms for each program are described in the
individual files in /usr/share/doc/*/copyright.

Debian GNU/Linux comes with ABSOLUTELY NO WARRANTY, to the extent
permitted by applicable law.
mosh-server: Bad IP address (-l)
Usage: mosh-server new [-s] [-v] [-i LOCALADDR] [-p PORT] [-c COLORS] [-l NAME=VALUE] [-- COMMAND...]
Connection to 162.xxx.xxx.xxx closed.
shiny:~ ovi$

**Comment by keithw** [comment]
Sorry, now it is my fault! Please make it "mosh-server new -l LANG=en_GB.UTF-8" and try again. (Just insert the "new" into what you have now.)

**Comment by ovizii** [comment]
hmmmm

shiny:~ ovi$ ssh -t -p xxx root@162.xxx.xxx.xxx mosh-server new -l  LANG=en_GB.UTF-8

The programs included with the Debian GNU/Linux system are free software;
the exact distribution terms for each program are described in the
individual files in /usr/share/doc/*/copyright.

Debian GNU/Linux comes with ABSOLUTELY NO WARRANTY, to the extent
permitted by applicable law.

MOSH CONNECT 60001 VQ22h6LvhnEuRNmV0Fb+Zg
Connection to 162.xxx.xxx.xxx closed.
shiny:~ ovi$

**Comment by keithw** [comment]
Ok, the problem is that your client wants to speak American, and the server with the problem only speaks British. (The other server apparently has an American locale available.) This is a basic weakness in the way POSIX does locales (not particular to Mosh, but Mosh is aggressive with detecting it).

Please try setting your LANG to en_GB.UTF-8 on the client before running mosh or ssh.

LANG=en_GB.UTF-8 mosh --ssh='ssh -p xxxx' user@host

You should not need a --server argument.

**Comment by ovizii** [comment]
Both servers have the American locale available, I double checked and reconfigured locales on the problematic machine, still no-go. 

Your command yields this:

    shiny:~ ovi$ LANG=en_GB.UTF-8 mosh --ssh='ssh -p xxxx' root@162.xxx.xxx.xxx
    Connection to 162.xxx.xxx.xxx closed.
    /usr/bin/mosh: Did not find mosh server startup message.
    shiny:~ ovi$

**Comment by keithw** [comment]
Aha, looking closer, why do you have LC_CTYPE="UTF-8" on the client machine? Are you setting this manually? Generally LC_CTYPE needs to be the name of a locale, e.g. en_US.UTF-8.

Can you please try unsetting LC_CTYPE and rerunning the mosh commands?

**Comment by ovizii** [comment]
No idea where that came from and I couldn'T figure out how to unset it even after googling so I edited my .bash_profile and inserted
export LC_CTYPE="en_US.UTF-8" 

And now everything works perfect, with both servers!!!

Thank you so much!

**Comment by keithw** [comment]
You're welcome, and I'm glad we fixed it, but I don't understand is why you weren't seeing mosh's (very verbose) error message that would have identified this as the problem straight out.

**Comment by ovizii** [comment]
No idea, I copy/pasted all errors straight in here :-(

**Comment by proteusvacuum** [comment]
For me, this error was happening because my remote locale wasn't being properly generated when calling `locale-gen` on arch, even though it was listed properly when calling `locale`
To fix it, I had to uncomment the locale I was trying to use (en_CA.UTF8) in `/etc/locale.gen`, then running `locale-gen` again.

**Comment by prodeveloper** [comment]
For me, what worked was adding the lines
export LC_ALL=en_US.UTF-8  
export LANG=en_US.UTF-8

to my .zshrc file

**Comment by larryhu** [comment]
@prodeveloper  THX!  Your code  worked for me

**Comment by ts95** [comment]
Thanks @prodeveloper That did it for me

**Comment by amedee** [comment]
@cbbrowne' s https://github.com/mobile-shell/mosh/issues/98#issuecomment-5090714 was the only thing that worked for me, and I agree that it's ugly as hack. All the other things, exporting languages, localegens etc didn't work.

**Comment by Huang-Libo** [comment]
This works for me
sh -c "export LANG=\"en_US.UTF-8\"; /usr/local/bin/mosh user@example.com"

**Comment by junaid-ali** [comment]
This worked for me:
set LC_ALL="en_US.UTF-8"

**Comment by WeirdCircumstances** [comment]
I still don't get it to work. I tried serval things posted here, connecting MacOS 10.13 to a Debian server. The connection was working for years. Lastly I changed my desktop language to english and installed the last version of mosh via brew. Now I'm also getting those errors and nothing posted here helped me yet.  

```
mosh mc3
The locale requested by LC_CTYPE=UTF-8 isn't available here.
Running `locale-gen UTF-8' may be necessary.

mosh-server needs a UTF-8 native locale to run.

Unfortunately, the local environment ([no charset variables]) specifies
the character set "US-ASCII",

The client-supplied environment (LC_CTYPE=UTF-8) specifies
the character set "US-ASCII".

locale: Cannot set LC_CTYPE to default locale: No such file or directory
locale: Cannot set LC_ALL to default locale: No such file or directory
LANG=
LANGUAGE=
LC_CTYPE=UTF-8
LC_NUMERIC="POSIX"
LC_TIME="POSIX"
LC_COLLATE="POSIX"
LC_MONETARY="POSIX"
LC_MESSAGES="POSIX"
LC_PAPER="POSIX"
LC_NAME="POSIX"
LC_ADDRESS="POSIX"
LC_TELEPHONE="POSIX"
LC_MEASUREMENT="POSIX"
LC_IDENTIFICATION="POSIX"
LC_ALL=
Connection to (server) closed.
/usr/local/bin/mosh: Did not find mosh server startup message. (Have you installed mosh on your server?)
```
But it is working by using 
```mosh mc3 --server="LANG=en_US.UTF-8 mosh-server"```

My server (Debian) says:
```locale 
LANG=en_US.UTF-8
LANGUAGE=
LC_CTYPE="en_US.UTF-8"
LC_NUMERIC="en_US.UTF-8"
LC_TIME="en_US.UTF-8"
LC_COLLATE="en_US.UTF-8"
LC_MONETARY="en_US.UTF-8"
LC_MESSAGES="en_US.UTF-8"
LC_PAPER="en_US.UTF-8"
LC_NAME="en_US.UTF-8"
LC_ADDRESS="en_US.UTF-8"
LC_TELEPHONE="en_US.UTF-8"
LC_MEASUREMENT="en_US.UTF-8"
LC_IDENTIFICATION="en_US.UTF-8"
`LC_ALL=en_US.UTF-8`

Any hints?

**Comment by keithw** [comment]
Your client-side environment has LC_CTYPE of `UTF-8`, which is not a valid locale/language on your Debian server. You will have the same problem with SSH, except it will be more annoying because SSH will just let programs randomly fail instead of flagging the mismatch and bombing out.

Please try setting the local `LC_CTYPE` (or `LANG`) environment variables to something that the server understands (e.g. `en_US.UTF-8`), and that ought to fix the problem. You do not need to modify the command-line to mosh if your system is set up properly and in a way that's compatible with the server. You may need to navigate the system preferences on your macOS machine to do this.

**Comment by hagabla** [comment]
2017, fresh macOS, vanilla Debian Jessie, with all locales generated on the server.
Does not work out of the box, neither with Terminal.app nor with iTerm

**Comment by kevinwaddle** [comment]
I have a 2016 Macbook Pro 13" that I was using to mosh to an Ubuntu 14.04 server over VPN. Always worked fine.

I just 'downgraded' to a 2015 Macbook Pro 15" and after I having gotten it set back up, as close to the same as MBP13, I am getting this same/similar error message when i try to mosh to the same Ubuntu 14.04 server.

The 13" is running Sierra, the 15" came with High Sierra.

I can still mosh into the server from the MBP13 with no problems.

```
The locale requested by LC_CTYPE=UTF-8 isn't available here.
Running `locale-gen UTF-8' may be necessary.

mosh-server needs a UTF-8 native locale to run.

Unfortunately, the local environment (LC_CTYPE=UTF-8) specifies
the character set "US-ASCII",

The client-supplied environment (LC_CTYPE=UTF-8) specifies
the character set "US-ASCII".

locale: Cannot set LC_CTYPE to default locale: No such file or directory
locale: Cannot set LC_ALL to default locale: No such file or directory
LANG=
LANGUAGE=
LC_CTYPE=UTF-8
LC_NUMERIC="POSIX"
LC_TIME="POSIX"
LC_COLLATE="POSIX"
LC_MONETARY="POSIX"
LC_MESSAGES="POSIX"
LC_PAPER="POSIX"
LC_NAME="POSIX"
LC_ADDRESS="POSIX"
LC_TELEPHONE="POSIX"
LC_MEASUREMENT="POSIX"
LC_IDENTIFICATION="POSIX"
LC_ALL=
Connection to ubuntuserver closed.
/usr/local/bin/mosh: Did not find mosh server startup message. (Have you installed mosh on your server?)```

**Comment by andersk** [comment]
It seems that macOS sets `LC_CTYPE=UTF-8` as a fallback when the combination of the system language/region settings aren’t recognized. (For example, English/United States is okay, German/Germany is okay, English/Germany is not.) This nonstandard setting of `LC_CTYPE` is recognized by macOS but not by Linux.

https://bugs.python.org/issue18378#msg215215
https://gitlab.com/gnachman/iterm2/issues/5478

Workarounds: either change the language/region settings to a recognized combination, or manually set `LC_CTYPE` to something like `en_US.UTF-8`. (Run `locale -a` for a list of accepted values.)

**Comment by kevinwaddle** [comment]
What I can't figure out is why my MBP13 has no problems connecting with mosh, but this new MBP15 does. 

They are *almost* identical in the Language & Region settings. The only difference I can see in the Region & Language screens is that in Date & Time > [Advanced] > Times the Timezone on the working MBP13 shows GMT+1 and on the non-working MBP15 it shows CEST

And `locale` definitely shows the same for both when run from the Terminal.

```
--MBP15--

LANG=
LC_COLLATE="C"
LC_CTYPE="UTF-8"
LC_MESSAGES="C"
LC_MONETARY="C"
LC_NUMERIC="C"
LC_TIME="C"
LC_ALL=
```

```
--MBP13--

LANG=
LC_COLLATE="C"
LC_CTYPE="UTF-8"
LC_MESSAGES="C"
LC_MONETARY="C"
LC_NUMERIC="C"
LC_TIME="C"
LC_ALL=
```
The other difference between the two machines is that I bought the MBP13 in the US, but changed it to Region Denmark when I moved here.

This new MBP15 I set to Denmark for the Region during the initial setup.

If I switch the Region on the MBP15, that has the problem connection with mosh, to United State, then mosh works!

```
--MBP15 (Region set to United States)--

LANG="en_US.UTF-8"
LC_COLLATE="en_US.UTF-8"
LC_CTYPE="en_US.UTF-8"
LC_MESSAGES="en_US.UTF-8"
LC_MONETARY="en_US.UTF-8"
LC_NUMERIC="en_US.UTF-8"
LC_TIME="en_US.UTF-8"
LC_ALL=
```

**Comment by rthouvenin** [comment]
I think I am facing a similar problem as @kevinwaddle: unusual mix of language and region.

I regularly connect to a handful of Ubuntu 16.04 servers, this was working fine with my previous system which was set with French language in region France.
I recently switched to a new system, and this time set the language to US English and the region still to France. Locale output:
```
LANG=en_US.UTF-8
LANGUAGE=en_US
LC_CTYPE="en_US.UTF-8"
LC_NUMERIC=fr_FR.UTF-8
LC_TIME="en_US.UTF-8"
LC_COLLATE="en_US.UTF-8"
LC_MONETARY=fr_FR.UTF-8
LC_MESSAGES="en_US.UTF-8"
LC_PAPER=fr_FR.UTF-8
LC_NAME=fr_FR.UTF-8
LC_ADDRESS=fr_FR.UTF-8
LC_TELEPHONE=fr_FR.UTF-8
LC_MEASUREMENT=fr_FR.UTF-8
LC_IDENTIFICATION=fr_FR.UTF-8
LC_ALL=
```

Since then, mosh accepts to connect to only *some* of the servers. All servers have the same locale (en_US.UTF-8), and the same `AcceptEnv LANG LC_*` directive in sshd config. The only difference I can see is that those that work are servers that were directly installed with Ubuntu 16.04 while those that don't are Ubuntu 14.04 migrated to 16.04.

I worked around the problem by changing the ssd config to `AcceptEnv LANG`.

Note: Even if SSH does not handle character sets as well as MOSH, SSH handles this problem in a superior way I think: it does let me connect. I do get a warning that something's wrong with locales, but at least I can work.

**Comment by junchih** [comment]
that's very interesting. every time I retired my old MacBook, I need to google about this issue and read through this thread.

can't understand that, why an issue occurred on every fresh Mac OS will not be refused to fix.

**Comment by andypiper** [comment]
In my case, I have Raspbian running in the en_GB locale but was seeing this connecting from macOS Catalina. I needed to run `locale-gen` on Raspbian with en_US.UTF-8 uncommented in `/etc/locale.gen` to get the connection to work.

**Comment by Vivraan** [comment]
Similar issue: https://github.com/mobile-shell/mosh/issues/1112
