### ISSUE TITLE
mosh server doesn't work with libprotobuf10?

### ISSUE THREAD

**Issue by charlieporth1** [mobile-shell/mosh#982]
mosh server doesn't work with libprotobuf10? And I cannot install libprotobuf9 on ubuntu18.04

**Comment by andersk** [comment]
Mosh works fine with libprotobuf10. If you’re having a problem, please paste in the exact commands you ran along with their output, including any error messages.

I’m going to take a wild guess that maybe you tried to upgrade a system from Ubuntu 16.04 to Ubuntu 18.04 while a Mosh compiled for Ubuntu 16.04 was still installed. You need to recompile Mosh on Ubuntu 18.04, or save yourself the trouble and get the binary package from Ubuntu’s repository (`apt install mosh`) or from the [PPA](https://launchpad.net/~keithw/+archive/ubuntu/mosh).

As a rule, it is always the case that a program compiled for libfoo.so.X needs to be recompiled for libfoo.so.Y if Y ≠ X.
