### ISSUE TITLE
Use Mosh but tmux doesn't support mouse move. 

### ISSUE THREAD

**Issue by HelloFy** [mobile-shell/mosh#987]
when i use ssh connect the dev-env and create the tmux session , and i can use the mouse move the  tmux panel and so on . but if i use mosh , it can't. why?  how can i solve this problem?
tmux 2.1
mosh 1.2.4a

**Comment by rwuwon** [comment]
@HelloFy, are you able to update to or build a new version of mosh?

CentOS 7.5 with mosh 1.3.0 and tmux 1.8 gives me no issues with mouse-resize-pane and mouse-select-pane.

While you're at it, I also recommend updating to tmux 2.7 as I believe it resolves some memory leaks as well as improves the :set mouse commands to simply :set mouse.

But I reckon updating to mosh 1.3.0+ alone should fix this issue for you.

**Comment by HelloFy** [comment]
@rwuwon Thanks。
