### ISSUE TITLE
either library or proxy-command

### ISSUE THREAD

**Issue by aep** [mobile-shell/mosh#997]
is is either
1. possible to use mosh as library so i can supply the IO
2. possible to specify a proxy command that does opens a local udp socket and gets killed properly when mosh exits?

currently 2 is semi possibly by using mosh --ssh "something", but something isnt cleaned up when mosh exits

background: i'm integrating mosh into https://github.com/aep/devguard/ which does the udp wiring through double-nat, so i have a command that does establish a udp wire to the other side, but that currently isnt cleaned up properly.

I can implement option 2 if you would accept a PR.
probably something like:
```
mosh --proxy "proxycommand" 
```

where proxycommand connect prints the obvious:
```
MOSH CONNECT 127.0.0.1 53974 foobarkey
```

but stdin of the proxycommand is held open until the mosh-client dies, so that the proxycommand can cleanup

**Comment by andersk** [comment]
`mosh` is just a [Perl script](https://github.com/mobile-shell/mosh/blob/mosh-1.3.2/scripts/mosh.pl) that launches `mosh-server` remotely via `ssh`, parses out the connection information, and launches `mosh-client`. If you already have the connection information, it sounds like you want to skip the Perl script and launch `mosh-client` directly. You can do whatever cleanup you need when `mosh-client` exits (no need for stdin trickery, just use plain old `waitpid`).

**Comment by aep** [comment]
hmmm not sure how i would launch the proxy **from** mosh-client tho.
or would you recommend wrapping mosh-client inside the proxy instead? I'm not sure if that covers all cleanup cases.

**Comment by andersk** [comment]
Right, you can launch `mosh-client` as a child of the proxy. What do you mean? What cleanup case other than `mosh-client` exiting are you worried about?

**Comment by aep** [comment]
works fine, not sure why i thought i need to do it the other way round. thanks!
